### PR TITLE
Support for sai-thrift calls in ixia ecn scripts.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Post-merge conflict resolved after #6040.
Adding support for PTF based sai-thrift calls in ixia scripts, due to the need to query the DUT for SAI counter values. Support only for cisco-8000 platforms.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@kevinskwang : Can you pls advice what to do about the azp failures ? Thanks.

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
