### PR TITLE
Skip test cases on x86_64-mlnx_msn2700a1-r0 platform

### PR DESCRIPTION
**Pull request by bingwang-ms**
### Description of PR

Summary:
There are some test cases being skipped or running on `x86_64-mlnx_msn2700-r0` platform. This PR is to update the `tests_mark_conditions.yaml` to apply the same operation to new platform `x86_64-mlnx_msn2700a1-r0`.

Skipped test cases:
- ecmp/inner_hashing/test_inner_hashing.py
- ecmp/inner_hashing/test_inner_hashing_lag.py
- ecmp/inner_hashing/test_wr_inner_hashing.py
- ecmp/inner_hashing/test_wr_inner_hashing_lag.py
- ecmp/inner_hashing/test_fgnhg_inner_hashing_internal.py
- ecmp/test_fgnhg.py

Test cases run on the new platform:
- vxlan/test_vxlan_ecmp.py
- vxlan/test_vxlan_crm.py
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305

#### What is the motivation for this PR?
This PR is to update `tests_mark_conditions.yaml`  to apply the same operations to the new platform `x86_64-mlnx_msn2700a1-r0`.

#### How did you do it?
Update [tests_mark_conditions.yaml](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:skip_test_cases_2700_a1?expand=1#diff-ab3274ff0521b1296970af58aea75edf72472ce5a2b29506f54c9ef0534fe1f2)

#### How did you verify/test it?
The change is verified by syntax checking.

#### Any platform specific information?
`x86_64-mlnx_msn2700a1-r0` specified.

#### Supported testbed topology if it's a new test case?
Not a new test case.

### CODE REVIEW

**Review by siqbal1986 — COMMENTED** [review]
Please add the test names in the description. Are these tests passing ,if yes please paste the output for reference

**Comment by bingwang-ms** [comment]
> Please add the test names in the description. Are these tests passing ,if yes please paste the output for reference

Updated. Thanks!

**Comment by bingwang-ms** [comment]
@AntonHryshchuk Can you help double confirm the skip is expected?

**Review by siqbal1986 — APPROVED** [review]

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
PR filed for 202305 branch. https://github.com/sonic-net/sonic-mgmt/pull/11171

**Pull request merged**
