### PR TITLE
[doc]: Update README.md

### PR DESCRIPTION
**Pull request by mdanish-kh**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Documentation
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
- Add LGTM label like other sonic repos
- Update instructions in README.md

### CODE REVIEW

**Comment by mdanish-kh** [comment]
@Blueve Could you please review this PR and #6359 (minor URL fix) ?

**Review by Blueve — APPROVED** [review]

**Comment by mdanish-kh** [comment]
Closing and re-opening PR to run pipelines.

**Comment by Blueve** [comment]
> Closing and re-opening PR to run pipelines.

@mdanish-kh Some tests were failed due to vs image issue. I will re-run the test once the image issue solved.

**Pull request merged**
