### PR TITLE
Cisco-8000: multi-asic: qos-sai: Modifications to BufferPoolWatermark for cisco-8000 multi-asic.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
For cisco-8000 the fabric card between the source and dest asic brings in uncertainities regarding the number of packets in flight. So we focus on dest asic for BufferPoolWatermark test.

Modifications include:
1. Read the watermark only from dest asic during the test for cisco-8000.
2. At the end of the test, when we want to overflow the shared-pool, we use the watermark before the tx is enabled - because once the tx is enabled on dst port, the packets that were held up in the fabric make it through and the watermark jumps way above the limit we expect.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
Run result:
--------------------------------------------------------- generated xml file: /run_logs/qos-rerun/qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark.xml ---------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
--------------------------------------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------------------------------------
06:38:10 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
================================================================================================ 6 passed in 2474.12 seconds =================================================================================================
sonic@e70a4c3cc9f8:/masic/tests$

**Comment by rraghav-cisco** [comment]
[bpwm.tar.gz](https://github.com/sonic-net/sonic-mgmt/files/11689953/bpwm.tar.gz)

**Review by abdosi — APPROVED** [review]

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@wangxin can you please help with merge of this.

**Comment by wangxin** [comment]
@rraghav-cisco Got conflicts after some other PRs are merged. Can you help resolve the new conflicts?

**Comment by rraghav-cisco** [comment]
@wangxin Resolved the current conflicts. Thanks.

**Comment by wangxin** [comment]
@rraghav-cisco Unfortunately, there are conflicts again. Can you help resolve?

**Comment by rraghav-cisco** [comment]
Resolved the conflicts.

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Pull request merged**
