### PR TITLE
Add memory usage checker for the stress route test

### PR DESCRIPTION
**Pull request by nhe-NV**
### Description of PR

Summary: Add memory usage checker in the stress route test
Fixes # (issue) 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### CODE REVIEW

**Comment by lipxu** [comment]
Is this memory check only for this test_stress_routes.py? Is it possible to add it into the new utilization fixture? thanks, https://github.com/sonic-net/sonic-mgmt/pull/13698

**Comment by bingwang-ms** [comment]
@yutongzhang-microsoft Can you help review? Thanks!

**Review by yutongzhang-microsoft — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
