### PR TITLE
Added new testcase for checking console connections from supervisor t…

### PR DESCRIPTION
**Pull request by YatishSVC**
Added new test case to check console connections from sup to linecards for T2 Chassis for arista and cisco devices

### Description of PR

Summary:
Fixes # (issue)
#5084
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x ] 202405

#### What is the motivation for this PR?
Testgap - https://github.com/sonic-net/sonic-mgmt/issues/5084
#### How did you verify/test it?
By running on Cisco and Arista T2 chassis
#### Any platform specific information?
Arista and Cisco
#### Supported testbed topology if it's a new test case?
T2

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@abdosi for viz..

**Comment by abdosi** [comment]
does this test case validate parallel conection to multiple LC's at same time ? if not we should add that,

**Comment by YatishSVC** [comment]
Hi @abdosi, 
Yes, this test case works with arista and cisco chassis, and will pull out the information of all the online line cards that are connected with the supervisor card and then try to connect them through serial console ports and will through an exception if it is unable to connect to any online linecard

**Comment by abdosi** [comment]
> Hi @abdosi, Yes, this test case works with arista and cisco chassis, and will pull out the information of all the online line cards that are connected with the supervisor card and then try to connect them through serial console ports and will through an exception if it is unable to connect to any online linecard

are we doning one by one (connect/disconnect) or we connect to all LC's in parallel ?

**Comment by YatishSVC** [comment]
Hi @abdosi 
Yes, we are doing it one by one (connect/disconnect)

**Comment by abdosi** [comment]
> Hi @abdosi Yes, we are doing it one by one (connect/disconnect)

can we enahnce to do parallel . that might be more real use-case

**Comment by abdosi** [comment]
@yatishkoul : please enhance to include reboot and verify same scenario again.

**Comment by YatishSVC** [comment]
@abdosi Sure, will test and update the changes.

**Comment by rlhui** [comment]
@YatishSVC as this PR is already merged, you'd raise separate PR for new suggestion right? Thanks.

**Comment by rlhui** [comment]
@bingwang-ms reminder to approve the back-port.

**Pull request merged**
