### PR TITLE
[reboot] Improved advanced-reboot PTF test case

### PR DESCRIPTION
**Pull request by ppikh**
Signed-off-by: Petro Pikh <petrop@nvidia.com>

### Description of PR
[reboot] Improved advanced-reboot PTF test case

- Added logic which store controlplane downtime into test logs in case of fast-reboot test
Added logic which store controlplane downtime into test logs in case of fast-reboot test  Previously we did not store controlpnale downtime into PTF logs TEST-NAME-report.json in case of fast-reboot(we did store only in case of warm-reboot) Now we store controlplane downtime into PTF logs also for fast-reboot test case

- Added validation that fast-reboot test always must have dataplane loss
- Added validation that dataplane loss checked correctly
Fix the misleading print of zero traffic loss and test pass when the traffic is not restoring
In the warm/fast-boot test, a certain amount of packet is sent(about 50k), the date plane loss is derived by the number of consecutive packets lost during the reboot. However, if the traffic won't restore, the loss time will be calculated as 0, and the test will pass(not expected). This change is fixing the case, so if the traffic won't restore, the test will fail and a meaningful message will be printed to the user.

Summary: [reboot] Improved advanced-reboot PTF test case
Fixes # (issue)

### Type of change
- [x] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205

#### What is the motivation for this PR?
[fast/warm-boot test] Fix the misleading print of zero traffic loss and test pass when the traffic is not restoring
In the warm/fast-boot test, a certain amount of packet is sent(about 50k), the date plane loss is derived by the number of consecutive packets lost during the reboot. However, if the traffic won't restore, the loss time will be calculated as 0, and the test will pass(not expected). This change is fixing the case, so if the traffic won't restore, the test will fail and a meaningful message will be printed to the user.

#### How did you do it?
See code(added few extra validations)

#### How did you verify/test it?
Executed fast/warm reboot tests

### CODE REVIEW

**Review by roysr-nv — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca could you help to review or assign someone?

**Comment by liat-grozovik** [comment]
@yxieca kindly reminder to review or assign someone

**Comment by liat-grozovik** [comment]
@vaibhavhd @kellyyeh kindly reminder to review

**Comment by ppikh** [comment]
Temporary moved to Draft - some improvements will be added.

**Comment by ppikh** [comment]
Another PR created with more changes. This is not relevant anymore.

**Pull request closed without merging**
