### PR TITLE
skip bgp/test_bgp_slb::test_bgp_slb_neighbor_persistence_across_advanced_reboot on SN4700

### PR DESCRIPTION
**Pull request by ryanzhu706**
### Description of PR

Summary:
Fixes # (issue)
Warmboot-finalizer service timeout on DUT, skipping the test case for now.

### Type of change
- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Warm-reboot is not currently meant to be qualified on SN4700.
#### How did you do it?
Skip warm-reboot on SN4700.
#### How did you verify/test it?
```
================================================= short test summary info ==================================================
SKIPPED [2] bgp/test_bgp_slb.py:68: Skip it on dual tor since it got stuck during warm reboot due to known issue on master and internal image; skip warm-reboot on SN4700 since it is not currently meant to be qualified.
```

### CODE REVIEW

**Review by vaibhavhd — APPROVED** [review]
Minor change suggested. Non blocking.

**Comment by wsycqyz** [comment]
The pre-commit check is mandatory. Please help check.

**Comment by yxieca** [comment]
@ryanzhu706 [;ease address the pretest checker failure.

**Comment by ryanzhu706** [comment]
@yxieca Thanks Ying, all checks have passed, this pr will be merged once got approval.

**Comment by vaibhavhd** [comment]
@StormLiangMS can you please help merge this change?

**Pull request merged**
