### PR TITLE
[dhcp_relay] Update error log for dhcp server route incorrect

### PR DESCRIPTION
**Pull request by yaqiangz**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Error log for default route incorrect is ambiguous

#### How did you do it?
Update the log

#### How did you verify/test it?
Run test

### CODE REVIEW

**Review by Gfrom2016 — APPROVED** [review]
LGTM

**Review by lizhijianrd — APPROVED** [review]

**Comment by yaqiangz** [comment]
Hi @wangxin could you please help to merge this PR?

**Review by wangxin — APPROVED** [review]

**Comment by yaqiangz** [comment]
Hi @bingwang-ms could you please help to approve the backport request?

**Comment by yaqiangz** [comment]
Hi @yxieca could you please help to approve this backport request?

**Pull request merged**
