### PR TITLE
Update the pfcwd test cases according to the new implement of the pfcwd.

### PR DESCRIPTION
**Pull request by nhe-NV**
Update the pfcwd test cases according to the new implement of the pfcwd
After the feature is completed, it criteria to trigger the pfcwd is much more strict than previous on Nvidia platform, So adjust the test case to properly trigger the pfcwd. The solution is to send background traffic during the pfc frame is sent from the fanout.

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
To make the pfcwd test case could pass after the new implement of the pfcwd.

#### How did you do it?
Add the logic of sending the background traffic to make the test case could pass after the new implement of the pfcwd

#### How did you verify/test it?
All pfcwd test case could pass

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@nhe-NV please handle the conflicts.
please let me know if we should merge it after the feature is changed, if so lets create dependency.

**Review by stephenxs — APPROVED** [review]

**Comment by nhe-NV** [comment]
> @nhe-NV please handle the conflicts. please let me know if we should merge it after the feature is changed, if so lets create dependency.

HI @liat-grozovik  conflict fixed, and tested

**Review by roy-sror — APPROVED** [review]

**Comment by stephenxs** [comment]
@neethajohn @bingwang-ms would you please review this PR? it is the corresponding test of PFC WD enhancement. thanks.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
