### PR TITLE
Choose ARP scale based on available NH entries for CISCO 8000 platforms

### PR DESCRIPTION
**Pull request by sridhartalari**
### Description of PR

Summary:
ARP stress test is failing for certain CISCO 8000 platforms as the tested scale exceeds the HW availablity

Fixes # (issue)
Choose ARP scale based on available NH entries for CISCO 8000 platforms
### Type of change

- [ x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
Pass all sonic mgmt tests on CISCO 8000  platforms

#### How did you do it?
ARP scale depends on NH Scale. Earlier NH scale is not considered while pushing ARP entries. Now NH scale is also used.

#### How did you verify/test it?
Make sure all learnt ARP's are installed by comparing the neighbor entries installed in HW with ARP requests sent .
Ran it on T0 setup of Cisco-8122-O64 and Cisco-8111-O32 platforms

#### Any platform specific information?
In certain CISCO platforms, Each Neighbor needs one NH entry. As a general fix,  we limit the number of Neighbor entries tested to the available NH entry on the platform

### CODE REVIEW

**Review by bpar9 — DISMISSED** [review]

**Comment by rajendrat** [comment]
@bpar9 , @wsycqyz : Could you please help restart this test... ?

**Review by bpar9 — APPROVED** [review]

**Comment by rajendrat** [comment]
viz @wsycqyz  . please help merge this in 202405

**Pull request merged**
