### PR TITLE
Add watchdog timeout event test

### PR DESCRIPTION
**Pull request by zbud-msft**
### Description of PR

Summary:
Fixes # (issue)26636373

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?

Add event for watchdog timeout

#### How did you do it?

Create mock test service that will sleep and therefore not send watchdog signal. This will generate watchdog timeout event

#### How did you verify/test it?

Manual test/Pipeline

### CODE REVIEW

**Comment by zbud-msft** [comment]
Relies on https://github.com/sonic-net/sonic-buildimage/pull/19383

**Comment by wsycqyz** [comment]
PR test is re-triggered.

**Review by liuh-80 — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by zbud-msft** [comment]
Hi @StormLiangMS, can we have this in 202311?

**Pull request merged**
