### PR TITLE
Fix allure report issue that doesn't display 'Version', 'Platform' and 'HwSKU' values for dualtor setup

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Allure report could not display 'Version', 'Platform' and 'HwSKU' values for dualtor setup. Previuosly we cannot get all dut information by testbed for dualtor setup, currently we get the dut information from ansible_host_pattern.
Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Fix allure report issue

#### How did you do it?
Get the dut information from ansible_host_pattern.

#### How did you verify/test it?
run it on dualtor or non-dualtor setup

#### Any platform specific information?
any

#### Supported testbed topology if it's a new test case?
any

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Review by lolyu — COMMENTED** [review]
Hi @JibinBao, thanks for the fix, could you please give an example of the report with your PR?

**Comment by JibinBao** [comment]
> Hi @JibinBao, thanks for the fix, could you please give an example of the report with your PR?

image

**Review by nhe-NV — APPROVED** [review]

**Review by roy-sror — APPROVED** [review]

**Review by lolyu — APPROVED** [review]
LGTM

**Review by bingwang-ms — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
@JibinBao I added the cherry-pick for 202311 and 202405. The release branch 202305 is not approved as it seems to be a nice-to-have change.

**Pull request merged**
