### PR TITLE
Additional test cases to verify 'startup_tsa_tsb.service' - PR#18496 PR#12238

### PR DESCRIPTION
**Pull request by sanjair-git**
### Description of PR

Summary:
Fixes # (issue)

- This PR has additional new test cases to verify the changes introduced as part of #https://github.com/sonic-net/sonic-buildimage/pull/18496.
- This PR is dependent on PR #12238
- Basically, this PR has new 4 test cases in addition to the 5 test cases added to verify start and stop of the new service 'startup_tsa_tsb.service' introduced by PR #12238 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
To verify code changes introduced as part of the PR #https://github.com/sonic-net/sonic-buildimage/pull/18496

#### How did you do it?
- Added 4 more new test cases as mentioned below to verify the changes.
- Attaching updated test cases' description document with all 9 test cases here for further reference and details.
[BGP-TSA-TSB-Service-TestCases.txt](https://github.com/sonic-net/sonic-mgmt/files/15264571/BGP-TSA-TSB-Service-TestCases.txt)

1. _test_user_init_tsa_while_service_run_on_dut_
2. _test_user_init_tsb_while_service_run_on_dut_
3. _test_user_init_tsb_on_sup_while_service_run_on_dut_
4. _test_tsa_tsb_timer_efficiency_

#### How did you verify/test it?

- Ran all the above mentioned test cases on a T2 chassis and made sure tests passed with expected behavior.

**Commit Id to review as part of this PR:** @tjchadaga 
3b6b38e9e4cb425f34225163dcf1f7f732b1e083  -- ([New testcases for tsa_tsb_service feature](https://github.com/sonic-net/sonic-mgmt/commit/3b6b38e9e4cb425f34225163dcf1f7f732b1e083))

### Documentation

image

### CODE REVIEW

**Comment by sanjair-git** [comment]
@tjchadaga, Thanks for looking into it. I have resolved the comments for the new test cases. Rerun them and please find the results below.

image

**Review by tjchadaga — APPROVED** [review]

**Comment by rlhui** [comment]
@sanjair-git  please resolve conflict

**Comment by sanjair-git** [comment]
> @sanjair-git please resolve conflict

Hi @rlhui, rebased and resolved conflict.

**Comment by sanjair-git** [comment]
> @sanjair-git : Please help resolve conflict.

Hi @abdosi , rebased and resolved conflict.

**Review by rlhui — APPROVED** [review]

**Pull request merged**
