### PR TITLE
Add Cisco Smartswitch hswku to select src/dst ports in qos_sai_base.py

### PR DESCRIPTION
**Pull request by dypet**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
LosslessVoq testcase was failing on smartswitch platform due to source ports having different qos profiles.

#### How did you do it?
Added smartswitch hwsku to the check in qos_sai_base to select src/dst ports similarly to Cisco-8101-O8C48.

#### How did you verify/test it?
Ran test_qos_sai.py with smartswitch DUT in T1 testbed, LosslessVoq test case passing after this fix.

### CODE REVIEW

**Review by bpar9 — DISMISSED** [review]
lgtm

**Review by wsycqyz — APPROVED** [review]
lğtm

**Comment by wsycqyz** [comment]
PR test stuck. Let me close and re-open the PR.

**Comment by wsycqyz** [comment]
@dypet There is pre-commit error. Please help fix it.

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
