### PR TITLE
[Dual-Tor] Improve the stability of dualtor memory leak test

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
The test statistically fails due to a slight violation of the memory threshold. I have investigated the failure and believe there is no real memory leak. 
So, I have made some changes to improve the stability of the test.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
To improve the stability of dualtor memory leak test.
#### How did you do it?
1. Increase the memory threshold buffer from 0.02 to 0.03.
We found that the test occasionally fails on Nvidia 4600C platform due to the memory usage after the test is 103% of the original memory usage, which is 1% more than the buffer defined in the test. I have tried to modify the test and repeat the neighbor leaning action much more times than it is in the test, and no real memory leak was observed.
Since the 0.02 is an experience value, I suggest we increase it a little bit to 0.03.

2. Get the original memory usage after all neighbors are deleted.
The original memory usage was recorded before deleting the neighbors, suggest doing it after the deleting to avoid any unexpected memory change during the process.

3. Add retries in the memory check at the end of the test.
We have observed that sometimes after the last memory check in the test, the memory usage could still fall a little without any actions being taken on the switch.

#### How did you verify/test it?
Run the test 10 times on 4600c platform and all passed.

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@bingwang-ms FYI, please let us know if you have any review feedback.

**Comment by liat-grozovik** [comment]
@congh-nvidia do we need it for 202205 and 202305? if so, need to add the labels.

**Comment by congh-nvidia** [comment]
> @congh-nvidia do we need it for 202205 and 202305? if so, need to add the labels.

Hi Liat, yes we need it for 202205 and 202305, but I expect some merge conflict on 202205, I will manually cherry pick it when this is merged. And for 202305 please help add the label. Thanks.

**Review by roy-sror — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@ZhaohuiS  Please help review. Thanks!

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Pull request merged**
