### PR TITLE
Set inner packet next header as TCP

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Set the inner packet next header as TCP
In order to be compatible with the payload type

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Script enhancement
#### How did you do it?
Set inner packet next header as TCP
#### How did you verify/test it?
Run it in internal regression

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by echuawu** [comment]
Hi @wangxin , please help check the pre-checker failure. The code change should not lead to this failure.

**Review by nhe-NV — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Hi @echuawu, can you help me understand why we have to use TCP instead of UDP?

**Comment by echuawu** [comment]
> Hi @echuawu, can you help me understand why we have to use TCP instead of UDP?

The payload type is TCP but the real payload is UDP in the script. The change here is just to make the payload and payload type compatible.

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@prsunny, @siqbal1986 Can you please help review?

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@bingwang-ms , please merge

**Comment by bingwang-ms** [comment]
@echuawu Can you please raise another PR for 202405 to address conflict?

**Comment by echuawu** [comment]
> @echuawu Can you please raise another PR for 202405 to address conflict?

Hi @bingwang-ms , the https://github.com/sonic-net/sonic-mgmt/pull/12564 had not been merged into 2311 and 2405. It lead the merge conflict issue. Could you merge the #12564 to 2311 and 2405?

**Pull request merged**
