### PR TITLE
[202012][dualtor] fixing test_downstream_ecmp_nexthops

### PR DESCRIPTION
**Pull request by Ndancejic**
What I did:
changed test_downstream_ecmp_nexthops to check if packets being sent are funneled towards a single mux neighbor or portchannel

Why I did it:
test_downstream_ecmp_nexthops fails due to swss change which programs a single active mux nexthop or a single tunnel route for a given route

How to test:
run sonic-mgmt dualtor/test_orchagent_active_tor_downstream.py test on t0 topo.

Summary:
### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

### CODE REVIEW

**Comment by prsunny** [comment]
Please create a PR to master

**Comment by prsunny** [comment]
> Please create a PR to master

@Ndancejic , can you please tag master PR here?

**Comment by wangxin** [comment]
@Ndancejic Is this PR a backport of a master branch PR? Can you mention the master PR number in PR description?

**Comment by Ndancejic** [comment]
cancelled in favor of master PR: https://github.com/sonic-net/sonic-mgmt/pull/8906 will open new 202012 PR if needed

**Pull request closed without merging**
