### PR TITLE
Ignore BGP and SWSS containers during service check due to issue #7151

### PR DESCRIPTION
**Pull request by sanjair-git**
### Description of PR

Summary:
Fixes # (issue)
- Ignore BGP and SWSS containers as part of '_test_service_checker_with_process_exit_' test case in system_health/test_system_health test suite.
- This is because, if '_bgpd_' and '_orchagent_' processes are chosen in random and if those processes are stopped and started again, the DUT configs are not restored as before. "_sonic-mgmt_" issue #7151

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
- Ignore BGP and SWSS containers as part of '_test_service_checker_with_process_exit_' test case. This is done due to the issue #7151, so that '_bgpd_' and '_orchagent_' processes are not chosen in random.

#### How did you do it?
- Added 'bgp' and 'swss' containers to the 'ignore' list while selecting containers.

#### How did you verify/test it?
- Ran the system health tests against a multi-asic line card in a T2 chassis.

### CODE REVIEW

**Comment by rlhui** [comment]
abdosi: this is generic.

**Comment by rlhui** [comment]
@yxieca please check this as well, not a specific chassis change, thanks

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/system_health/test_system_health.py:12:1: F401 'tests.platform_tests.thermal_control_test_helper.disable_thermal_policy' imported but unused<br/>tests/system_health/test_system_health.py:13:1: F401 'device_mocker.device_mocker_factory' imported but unused<br/>tests/system_health/test_system_health.py:108:31: E712 comparison to True should be 'if cond is True:' or 'if cond:'<br/>tests/system_health/test_system_health.py:114:23: E712 comparison to True should be 'if cond is True:' or 'if cond:'<br/>tests/system_health/test_system_health.py:139:31: E712 comparison to True should be 'if cond is True:' or 'if cond:'<br/>tests/system_health/test_system_health.py:146:69: F811 redefinition of unused 'device_mocker_factory' from line 13<br/>tests/system_health/test_system_health.py:146:92: F811 redefinition of unused 'disable_thermal_policy' from line 12<br/>tests/system_health/test_system_health.py:168:121: E501 line too long (135 > 120 characters)<br/>tests/system_health/test_system_health.py:170:121: E501 line too long (147 > 120 characters)<br/>tests/system_health/test_system_health.py:173:121: E501 line too long (122 > 120 characters)<br/>tests/system_health/test_system_health.py:185:121: E501 line too long (131 > 120 characters)<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by yxieca** [comment]
I think the best way to skip, is to parameterize the test, so that we could use the conditional markers to skip BGP/SWSS under the condition that the issue is open. Eventually, we would like to test BGP/SWSS process crash, right?

**Comment by sanmalho-git** [comment]
@yxieca  Do you think the issue https://github.com/sonic-net/sonic-mgmt/issues/7151 would be fixed in SONiC.  The test case currently ignores [syncd and database ](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/system_health/test_system_health.py#L123). We used same mechanism to ignore bgp and swss in this PR

**Review by judyjoseph — APPROVED** [review]

**Comment by yxieca** [comment]
> @yxieca Do you think the issue #7151 would be fixed in SONiC. The test case currently ignores [syncd and database ](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/system_health/test_system_health.py#L123). We used same mechanism to ignore bgp and swss in this PR

@sanmalho-git exiting doesn't mean right :-). I know you didn't start this way. Please help file a test gap to parameterize test_service_checker_with_process_exit and skip with conditional marks.

**Review by yxieca — APPROVED** [review]
Please help file test gap to use the right way to skip.

**Comment by sanjair-git** [comment]
> Please help file test gap to use the right way to skip.

@yxieca Test gap filed #7545 to skip and parametrize the test case. Please take a look.

**Pull request merged**
