### PR TITLE
Fix test_check_show_lpmode case

### PR DESCRIPTION
**Pull request by weiguo-nvidia**
### Description of PR

Summary: Fix test_check_show_lpmode case
Fixes # (issue)
1. Currently the `test_check_show_lpmode` case use `xcvr_skip_list` function to check lpmode for only supported interface, but the code passes all the output of `show interface transceiver lpmode` to `validate_transceiver_lpmode` function, then the function checks each interface lpmode. This is incorrect. Fix it.

For example, if the interface lpmode is like this "`['Ethernet0   N/A', 'Ethernet1  Off']`", Ethernet0 is RJ45 and no lpmode check is needed. Ethernet1 needs to check lpmode
- In the current logic, Ethernet0 does not check lpmode, which is correct.
- Ethernet1 needs to check lpmode, but the code passes all the output `(['Ethernet0 N/A', 'Ethernet1 Off'])` of the command to the function `validate_transceiver_lpmode`. It checks each item and finds that Ethernet0 lpmode is "`N/A`", then the case fails. This is incorrect

2. Move the "`check if header exists`" test from `validate_transceiver_lpmode` to `test_check_show_lpmode`. So the header only check one time.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@prgeor Can you help review?

**Comment by prgeor** [comment]
@mihirpat1 can review?

**Review by mihirpat1 — APPROVED** [review]

**Comment by weiguo-nvidia** [comment]
Hi @bingwang-ms , 

@mihirpat1 had approved the change, could you help merge it, thanks!

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
PR checker got stuck. Just re-triggered it

**Pull request merged**
