### PR TITLE
[snmp] Fix snmpget command to run from duthost

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
https://github.com/sonic-net/sonic-mgmt/pull/9074 modified test_snmp_memory to make it stable.
This change executes commands to get snmp memory and memory from /proc/meminfo sequentially from duthost.
one of the commands is to use snmpget, which fails because snmpget is available only inside snmp docker.

#### How did you do it?
Modify testcase to run docker exec snmp snmpget instead of snmpget
#### How did you verify/test it?
Verificed on testbed.

### CODE REVIEW

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Thanks for fixing the problem!

**Comment by bingwang-ms** [comment]
> Thanks for fixing the problem! I was wondering how it passed when I was doing the manual verification?

Oh, I see. Probably I installed snmpget on the DUT when I was debugging the issue.

**Comment by bingwang-ms** [comment]
@SuvarnaMeenakshi  PR #9074 is not merged to `202205` yet due to conflict. I will include this change when resolving the conflict. So I remove the label. Thanks for the improvement!

**Comment by SuvarnaMeenakshi** [comment]
Removing request for 202205 labels as this PR https://github.com/sonic-net/sonic-mgmt/pull/9240/files includes this change

**Pull request merged**
