### PR TITLE
[T2] Generate pkts_num_egr_mem in runtime

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

Use overflow_egress() to generate pkts_num_egr_mem in runtime if src and dst's asic types are different.
The pkts_num_egr_mem varies too much in different combinations. The qos params are based on ingress (Q100), so the pkts_num_egr_mem is 5915, but in Q100->Q200, pkts_num_egr_mem is 7536, 7536-5915 = 1621. It will cost too much time to send packets one by one for 1621 iterations.

With this, pg watermark case had to be skipped if src and dst asic-type are different. Because with using overflow_egress, it sends some extra packets, and that makes pg watermark increasing which fails the case. The case expects pg watermark to be 0 at the beginning. We can unskip it after thrift rpc api supports watermark clear.

In PFCXon case, overflow_egress() is called for all of 3 flows to get pkts_num_egr_mem1/2/3, this is because pacific counter-A threshold0 is 7MB, xoff threshold will be decreased for the 2nd flow.

Summary:

202205 PR: https://github.com/sonic-net/sonic-mgmt/pull/10277

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305
- [x] 202311

### CODE REVIEW

**Comment by abdosi** [comment]
@zhixzhu  Do we need this ?

**Comment by zhixzhu** [comment]
We will need it when running multi-dut Q100->Q200

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@wangxin : please help with cherry-pick

**Comment by abdosi** [comment]
@zhixzhu please create PR for 202305.

**Comment by zhixzhu** [comment]
202305 PR: https://github.com/sonic-net/sonic-mgmt/pull/11973

**Pull request merged**
