### PR TITLE
[sensors] Add sku sensor data for Wistron sw_to3200K platform

### PR DESCRIPTION
**Pull request by WistronNetwork**
### Description of PR

Summary:
Fixes sensors case errors

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Make sensors case working for x86_64-wistron_sw_to3200k-r0 platform
#### How did you do it?
Update sensors data
#### How did you verify/test it?
Run sensors TC case and get PASS result
#### Any platform specific information?
root@lab-3200k:/home/admin# show version

SONiC Software Version: SONiC.202111.0-dirty-20220727.101343
Distribution: Debian 11.4
Kernel: 5.10.0-8-2-amd64
Build commit: 04cd65ded
Build date: Wed Jul 27 02:30:41 UTC 2022
Built by: roger@ntc-PowerEdge-R740

Platform: x86_64-wistron_sw_to3200k-r0
HwSKU: Wistron_sw_to3200k_32x100
ASIC: innovium
ASIC Count: 1
Serial Number: 681Z0P16000512600006M0SE
Model Number: SW-TO3200K
Hardware Revision: 0
Uptime: 16:48:37 up 9 min,  2 users,  load average: 2.03, 2.1

### CODE REVIEW

**Review by wangxin — CHANGES_REQUESTED** [review]
If this change is only for the `x86_64-wistron_sw_to3200k-r0` platform, why updated sensors data of so many other platforms? Is this change based on the latest master branch?

**Comment by WistronNetwork** [comment]
fix based on latest master branch, thanks for review.

**Comment by WistronNetwork** [comment]
@wangxin would you please help review, thanks.

**Review by wangxin — APPROVED** [review]

**Pull request merged**
