### PR TITLE
Adding dualtor iptable rules for test_cacl_application_dualtor

### PR DESCRIPTION
**Pull request by svelamal**
### Description of PR

The expected rules for dualtor are present in the script as a fixture "ignore_hardcoded_cacl_rule_on_dualtor" but the global variable "ignored_iptable_rules" is not called anywhere. This is causing test_cacl_application_dualtor to fail because the script is not expecting these rules.

Summary:
Fixes # (issue)

### Type of change

- [ x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ x] 202205

#### Any platform specific information?
Checked it on DualToR testbed with Cisco devices

### CODE REVIEW

**Comment by Aravind-Subbaroyan** [comment]
@ZhaohuiS - could you please review this?

**Review by ZhaohuiS — DISMISSED** [review]
LGTM

**Comment by ZhaohuiS** [comment]
> @ZhaohuiS - could you please review this?

@svelamal  Could you please fix the error or pre-commit?

tests/cacl/test_cacl_application.py:426:5: E265 block comment should start with '# '
tests/cacl/test_cacl_application.py:429:9: E122 continuation line missing indentation or outdented
tests/cacl/test_cacl_application.py:430:9: E122 continuation line missing indentation or outdented
tests/cacl/test_cacl_application.py:431:9: E122 continuation line missing indentation or outdented

check conditional mark sort..........................(no files to check)Skipped

**Comment by svelamal** [comment]
@ZhaohuiS could you please check it now? I made the changes suggested above

**Comment by ZhaohuiS** [comment]
> @ZhaohuiS could you please check it now? I made the changes suggested above

@svelamal 

Pre-commit check results:
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

The PR check still failed, could you please run pre-commit to success before your push your changes?

**Comment by svelamal** [comment]
Please refer https://github.com/sonic-net/sonic-mgmt/pull/8994

**Pull request closed without merging**
