### PR TITLE
[Mellanox]Update platform tests for dpu

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Update platform tests for dpu

1. Updated platform test list:

-    platform_tests/test_sensors.py
-    platform_tests/api/test_sfp.py
-    platform_tests/mellanox/test_check_sfp_presence.py
-    platform_tests/mellanox/test_check_sfp_eeprom.py

2. Update platform skip condition for some sfp aip cases in api/test_sfp.py

- tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
Update platform tests for dpu

#### How did you do it?
update platform tests accordingly based on the behavior of dpu

#### How did you verify/test it?
Run platform tests on dpu

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by prgeor** [comment]
@JibinBao please resolve conflict

**Comment by JibinBao** [comment]
> @JibinBao please resolve conflict

will update it

**Comment by JibinBao** [comment]
Hi @prgeor ,
Conflict has been fixed. Can you help review again?

**Review by prgeor — APPROVED** [review]

**Pull request merged**
