### PR TITLE
dualtor test_arp_update_for_failed_standby_neighbor failure on mixed topo_fix

### PR DESCRIPTION
**Pull request by AnantKishorSharma**
Description of PR

Summary: When test_arp_update_for_failed_standby_neighbor is run in mixed topology, while randomly selecting PTF IP to test we sometimes select IP mapped to a port with active-active config.. If we select such PTF IP, we won't see expected behavior. With this PR we have added a check to select a port in A-S when this test is run in mixed topo.

Fixes # (issue)
test_arp_update_for_failed_standby_neighbor

Type of change

[x ] Test case(new/improvement)
Back port request

202205
Approach

Why I did it
To select PTF IP mapped to a port with active-standby mux config

How I did it
Introduced a new fn to select neigh IP randomly with a check for active-standby mux config

How to verify it
Verified that PTF IP mapped to a port with active-standby mux config is selected to test and test case passes.
```
sonic@sonic-ucs-m6-1:/data/tests$ ./run_tests.sh -n m64-dtor-yy41 -l debug -e -s -O -u -c arp/test_arp_dualtor.py::test_arp_update_for_failed_standby_neighbor -f ../ansible/testbed.yaml -p /data/tests/logs/anant_debug_9338
=========================================================== short test summary info ===========================================================
SKIPPED [2] /data/tests/common/dualtor/dual_tor_common.py:48: Skip cable type 'active-active'
==================================================== 2 passed, 2 skipped in 325.06 seconds ====================================================
```
Log excerpts:
```
sonic@sonic-ucs-m6-1:/data/tests/logs/anant_debug_9338$ grep -A1 "Random selected intf" test_2023-09-11-03-37-22.log 
11/09/2023 03:40:02 test_arp_dualtor.neighbor_ip_active_stan L0088 INFO   | Random selected intf: Ethernet128, intf cable_type: None
11/09/2023 03:40:02 test_arp_dualtor.neighbor_ip_active_stan L0093 INFO   | Using 192.168.0.30 as neighbor IP
....
11/09/2023 03:41:23 test_arp_dualtor.neighbor_ip_active_stan L0088 INFO   | Random selected intf: Ethernet184, intf cable_type: None
11/09/2023 03:41:23 test_arp_dualtor.neighbor_ip_active_stan L0093 INFO   | Using fc02:1000::28 as neighbor IP
```
Which release branch to backport (provide reason below if selected)
202205

Any platform specific information?

NA

Supported testbed topology if it's a new test case?

NA

### CODE REVIEW

**Comment by Aravind-Subbaroyan** [comment]
@kevinskwang - could you please review this?

**Comment by AnantKishorSharma** [comment]
@kevinskwang , could you please help re-trigger the checks and review the changes?

**Comment by AnantKishorSharma** [comment]
@kevinskwang  - could you please review this?

**Comment by AnantKishorSharma** [comment]
@kevinskwang , could you please review this?

**Comment by AnantKishorSharma** [comment]
@kevinskwang, could you please review this?

**Review by bpar9 — APPROVED** [review]

**Comment by kevinskwang** [comment]
There is already a fixture cable_type to handle this.

**Pull request closed without merging**
