### PR TITLE
[dualtor_io][active-active] increase `wait_until` timeout for rebooting active-active dualtor DUT

### PR DESCRIPTION
**Pull request by zjswhhh**
### Description of PR

Summary:
Fixes # (issue)

This is to fix test failure: 
`dualtor_io/test_tor_failure.py::test_active_tor_reboot_upstream[active-active]`

Somehow it took slighly longer for STATE_DB entry to populate after active-active dualtor reboots. 

For now, increase the timeout from 30s to 60s for active-active test case. 

sign-off: Jing Zhang zhangjing@microsoft.com 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### How did you verify/test it?
Run on mixed-topology testbeds, both cases active-standby and active-active passed. 
```
- generated xml file: /var/src/sonic-mgmt-int/tests/logs/dualtor_io/test_tor_failure.py::test_active_tor_reboot_upstream.xml -
---------------------------- live log sessionfinish ----------------------------
23:38:54 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
========================== 2 passed in 599.53 seconds ==========================
```

### CODE REVIEW

**Review by yxieca — DISMISSED** [review]

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Failed<br/>- hook id: check-ast<br/>- exit code: 1<br/><br/>tests/dualtor_io/test_tor_failure.py: failed parsing with CPython 3.10.6:<br/><br/>Traceback (most recent call last):<br/>File "/home/vsts/.cache/pre-commit/repo2d87mm3v/py_env-python3/lib/python3.10/site-packages/pre_commit_hooks/check_ast.py", line 21, in main<br/>ast.parse(f.read(), filename=filename)<br/>File "/usr/lib/python3.10/ast.py", line 50, in parse<br/>return compile(source, filename, mode, flags,<br/>File "tests/dualtor_io/test_tor_failure.py", line 81<br/><<<<<<< HEAD<br/>^^<br/>SyntaxError: invalid syntax<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/dualtor/control_plane_utils.py:44:121: E501 line too long (122 > 120 characters)<br/>tests/common/dualtor/control_plane_utils.py:156:121: E501 line too long (147 > 120 characters)<br/>tests/common/dualtor/control_plane_utils.py:162:121: E501 line too long (143 > 120 characters)<br/>tests/dualtor_io/test_tor_failure.py:83:5: E122 continuation line missing indentation or outdented<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/dualtor/control_plane_utils.py:45:5: E125 continuation line with same indent as next logical line<br/>tests/common/dualtor/control_plane_utils.py:45:9: E128 continuation line under-indented for visual indent<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by yxieca** [comment]
@zjswhhh please create separate PR for 202205 branch.

**Pull request merged**
