### PR TITLE
cisco: multi-asic qos-sai: Fix qos/conftest.py to use redis CLI with multiasic context.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
qos/conftest.py is using redis-cli without multi-asic context in function `nearbySourcePorts`. This PR is changing it to call sonic-db-cli with multi-asic context.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@rbpittman , pls review.

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
why we don;t have PR for master directly ?

**Review by rbpittman — APPROVED** [review]
lgtm.

Yeah can this be redirected to master?

**Comment by abdosi** [comment]
please direct to master. validation can be on 202205 branch.

**Review by abdosi — CHANGES_REQUESTED** [review]
as comment.

**Comment by rraghav-cisco** [comment]
@rbpittman , @abdosi : Master PR opened: https://github.com/sonic-net/sonic-mgmt/pull/8329

**Review by abdosi — APPROVED** [review]

**Pull request merged**
