### PR TITLE
Adding Innovium(Marvell) specific changes to run QOS module tests

### PR DESCRIPTION
**Pull request by kbabujp**
### Description of PR
Signed-off-by: kbabujp [kbabujp@marvell.com](mailto:kbabujp@marvell.com)

Adding Innovium(Marvell) specific changes to run QOS buffer tests

Summary:
* Added file to check the chip type
* Changed the buffer item to check in innovium (Marvell) chip
* Added vendor_id check in common/system_utils/docker.py

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [x] 201911
- [x] 202012

#### What is the motivation for this PR?
To pass QOS buffer test on innovium(Marvell) chip

#### How did you do it?
Added conditional check to modify expected buffer item to check in buffer_items_to_check_dict dictionary 

#### How did you verify/test it?
Test test_buffer.py passed with this change

### CODE REVIEW

**Comment by rck-innovium** [comment]
@neethajohn 
Can you please help review and merge this. The changes are Marvell(Innovium) platform specific and tested on Innovium platform

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
@kbabujp The EasyCLA check failed. Can you sign the EasyCLA?

**Pull request merged**
