### PR TITLE
Fix dhcpv6 testcase failures in Dual TOR Setups

### PR DESCRIPTION
**Pull request by santoss3**
### Description of PR

In Dual TOR scenario the "dhcpv6" testcase is failing due to the following reasons - 
1. in AA Setup the packets from server may land into any TOR due to ECMP, whereas the testcase expects it to land on DUT port
- Fix is to toggle non-DUT ports so that the dhcpv6 request will always be received on the DUT
2. The PTF DHCPCounterTest and DHCPTest toggles the interface to get the proper link-local address, this impacts the link health in Dual-Tor scenario due to missing ICMP HB
- Fix is to skip the above step for Dual Tor testcase Scenarios

Summary:
Fixes # Failures in dhcp_relay/test_dhcpv6_relay.py in Dual Tor Setups

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [X] 202305
- [X] 202311

#### What is the motivation for this PR?
Fix Failures in dhcp_relay/test_dhcpv6_relay.py in Dual Tor Setups

#### How did you do it?
Specified in PR Description

#### How did you verify/test it?
Verified that the dhcpv6 testcase passes after the code changes.

### CODE REVIEW

**Review by bpar9 — DISMISSED** [review]

**Comment by XuChen-MSFT** [comment]
after applied this changes, and run local test on 202305 branch, still observe dhcpv6 failure. Please check testlog at Mar/3 and address it

image

**Comment by santoss3** [comment]
Hi Xu,
I apologize, there was some issue with the patch with I addressed it yesterday.
Can you please try again with the latest diff?
Thanks

**Review by bpar9 — APPROVED** [review]
LGTM

**Comment by bpar9** [comment]
@santoss3 , please check/rerun the sonic-mgmt failures in the workflow

**Comment by XuChen-MSFT** [comment]
@santoss3   try latest commit, hit failure and error

=========================== short test summary info ============================
SKIPPED [1] dhcp_relay/test_dhcpv6_relay.py:347: skip the link flap testcase on dual tor testbeds
SKIPPED [1] dhcp_relay/test_dhcpv6_relay.py:394: skip the uplinks down testcase on dual tor testbeds
ERROR dhcp_relay/test_dhcpv6_relay.py::test_dhcpv6_relay_counter - Failed: Pr...
FAILED dhcp_relay/test_dhcpv6_relay.py::test_dhcpv6_relay_counter - Assertion...
FAILED dhcp_relay/test_dhcpv6_relay.py::test_dhcp_relay_default - tests.commo...
==== 2 failed, 1 passed, 2 skipped, 1 warning, 1 error in 299.45s (0:04:59) ====

**Review by lolyu — COMMENTED** [review]
LGTM

**Comment by lolyu** [comment]
Hi @StormLiangMS, please cherry-pick this into 202305, thanks!

**Pull request merged**
