### PR TITLE
Subject: sonic-mgmt: fix tagged-arp test for large topos

### PR DESCRIPTION
**Pull request by ccroy-arista**
### Description of PR

Summary:
For large topos, i.e. those with a large number of interfaces, there exists a likely possibility that `show arp` will not be up to date when the call is made.

Try the `show arp` command again before moving on.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Fix test failure for topos with large number of interfaces. 

#### How did you do it?
Wrapped the arp entry check in a wait_until, which will attempt the `show arp` command a few times on a given interface before failing.

#### How did you verify/test it?
Ran the offending test (tests/arp/test_tagged_arp.py) several times and confirmed that failure was not observed and that the test passed every time.

#### Any platform specific information?
Verified on Arista-7060X6-64PE-256x200G.

### CODE REVIEW

**Comment by ccroy-arista** [comment]
Checking pre-commit...

**Comment by Janetxxx** [comment]
@ccroy-arista I cherry-picked this PR and ran the test, but received an ```AssertionError: Expected 10 entries, but 0 found.``` It seems ARP packets have not been received by the DUT for some reason. I'll ping you to discuss it further. Thanks.

**Comment by StormLiangMS** [comment]
hi @Janetxxx do we still see failure with internal runs?

**Comment by Janetxxx** [comment]
> hi @Janetxxx do we still see failure with internal runs?

Hi @StormLiangMS , It still failed in our internal run, I'll have a look in the next coming days.

**Comment by r12f** [comment]
since the issue on our side is caused by different things from the issue being fixed here, let's get this merged, because eventually we will hit this anyway.

**Review by r12f — APPROVED** [review]

**Comment by StormLiangMS** [comment]
hi @yxieca need cherry pick.

**Pull request merged**
