### PR TITLE
Multi-asic fixes for `lldp/test_lldp_syncd.py`

### PR DESCRIPTION
**Pull request by arista-nwolfe**
### Description of PR
Various multi-asic fixes in `lldp/test_lldp_syncd.py`
* Fix helper functions `db_instance`, `get_lldp_entry_keys`, `get_lldp_entry_content`, `get_lldpctl_output` to query both namespaces

test_lldp_entry_table_after_flap
* Ignore routeCheck log errors as this test flaps ports and churns routes `ignore_expected_loganalyzer_exceptions`
* Don't skip the test if it finds `eth0` port, just continue
* Add namespace to `config interface` commands
* Increase delay from 5s to 10s as `verify_lldp_entry` was seeing the stale `LLDP_ENTRY` from before link flap and returning True

test_lldp_entry_table_after_lldp_restart
* Query the per-namespace `lldp` docker when available

test_lldp_entry_table_after_reboot
* wait until `check_intf_up_ports=True` when rebooting, otherwise the `LLDP_ENTRY` may flap when the ports come up

Summary:
Fixes https://github.com/sonic-net/sonic-mgmt/issues/15256

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

### CODE REVIEW

**Comment by wumiaont** [comment]
Hi, I think your fix is also fine. We are using different approach to fix the same issue which is conflict to each other. I will test with your fix and see if all test could pass. Will update here.

**Comment by wumiaont** [comment]
All lldp syncd test passed using this PR change. I will close my PR 15148. Thx.

**Comment by arista-nwolfe** [comment]
> All lldp syncd test passed using this PR change. I will close my PR 15148. Thx.

Thanks @wumiaont for confirming this, sorry for not realizing you already had a fix for this.

**Comment by abdosi** [comment]
@yejianquan : please cherry-pick to 202405

**Pull request merged**
