### PR TITLE
[QoS]Sai-thrift support for Credit_WD enable disable code changes in sonic-mgmt qos_test

### PR DESCRIPTION
**Pull request by ansrajpu-git**
### Description of PR

To implement & verify the changes added from sai-thrift to enable/disable credit-watchdog voq capability.
PR# https://github.com/opencomputeproject/SAI/pull/2010 

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [ ] 202305
- [ ] 202311

#### How did you verify/test it?
Executed qos test cases and verify the results

### CODE REVIEW

**Comment by wsycqyz** [comment]
@XuChen-MSFT Maybe need your attention.

**Comment by wsycqyz** [comment]
@ansrajpu-git Do we need this PR in 202311 or 202305 branch?

**Comment by saksarav-nokia** [comment]
> @ansrajpu-git Do we need this PR in 202311 or 202305 branch?

@wsycqyz , This is applicable only for master

**Review by wsycqyz — APPROVED** [review]
LGTM

**Review by vmittal-msft — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@yxieca @wangxin please help merge.

**Comment by yxieca** [comment]
@vmittal-msft has this change been tested on a pizza box and observe no regression?

**Comment by vmittal-msft** [comment]
@yxieca this is only applicable for chassis.

**Comment by wenyiz2021** [comment]
@bingwang-ms please help to cherry-pick this PR to 202405, thanks!

**Pull request merged**
