### PR TITLE
cisco: qos-sai: Fix losslessvoq test for multi-asic

### PR DESCRIPTION
**Pull request by rraghav-cisco**
I had modified the lossless voq test to use dst_ports instead of src_ports since the src_port_* were not available. This will fail in case of multiple asic runs. This PR fixes the script to use the correct src_ports only, using the "testPortIps" key that is available from dutConfig fixture.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
Run result:
------------------------------------------------------------------------------------------------------------------ live log sessionfinish ------------------------------------------------------------------------------------------------------------------
21:40:40 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
================================================================================================================= short test summary info ==================================================================================================================
SKIPPED [8] /data/tests/qos/test_qos_sai.py:584: This test needs to be revisited later, for the case where src and dst ASICs are different.
========================================================================================================== 4 passed, 8 skipped in 1543.64 seconds ==========================================================================================================
AzDevOps@dc86aa7b98e5:/data/tests$

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@wangxin Can you please help with merge of this.

**Comment by abdosi** [comment]
@wangxin please help merge this

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Pull request merged**
