### PR TITLE
Update definition of topology t1-32-lag

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Update the soft link for t1-32-lag-tor.j2 and t1-32-lag-spine.j2 
Update the last UP port index in topology t1-32-lag definition

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Update the definition of t1-32-lag to override deployment failure
#### How did you do it?
Update the softlink definition.
Update the last up port definition
#### How did you verify/test it?
Run it in internal regression

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@yanmo96 Can you please comment on this change?

**Comment by bingwang-ms** [comment]
@yanmo96 Please help review and double-check if the definition is compatible with the current testbed deployment.

**Comment by yanmo96** [comment]
@echuawu What's your testbed setup? Thanks

**Comment by nhe-NV** [comment]
> @echuawu What's your testbed setup? Thanks

HI @yanmo96 this is for Mellanox-SN4700-O32, @bingwang-ms  please confirm this is the expected topo.

**Comment by yanmo96** [comment]
@nhe-NV How about the physical connections? Thanks

**Comment by echuawu** [comment]
> @nhe-NV How about the physical connections? Thanks

Hi @yanmo96 , there are 4 portchannels connect with the T2 VMs, all the other 20 portchannels connect with the T0 VMs.

**Review by nhe-NV — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
