### PR TITLE
Deprecate testbed CSV files

### PR DESCRIPTION
**Pull request by wangxin**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
All code have migrated to use YAML for mat testbed definition files. The CSV testbed files are no longer required.

#### How did you do it?
This change deleted the CSV format testbed files to deprecate them.

### CODE REVIEW

**Comment by opcoder0** [comment]
Hi @wangxin,

I've noticed that the code parsing `testbed.csv` is present in the following files. Will the irrelevant code be cleaned up in a separate PR?

- `ansible/testbed-cli.sh`
- `ansible/library/test_facts.py`
- `tests/common/testbed.py`

**Review by StormLiangMS — DISMISSED** [review]
LGTM

**Comment by wangxin** [comment]
> Hi @wangxin,
> 
> I've noticed that the code parsing `testbed.csv` is present in the following files. Will the irrelevant code be cleaned up in a separate PR?
> 
> * `ansible/testbed-cli.sh`
> * `ansible/library/test_facts.py`
> * `tests/common/testbed.py`

Correct. These code will be removed in separate PRs.

**Review by lerry-lee — APPROVED** [review]
Approved and left a comment: there are no code references for `testbed.csv` and `vtestbed.csv`, but there are non-code references. Will update them in this PR or in a separate one?

**Comment by lerry-lee** [comment]
> Approved and left a comment: there are no code references for `testbed.csv` and `vtestbed.csv`, but there are non-code references. Will update them in this PR or in a separate one?

Saw your reply to @opcoder0 , please ignore my comment.

**Review by opcoder0 — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]

**Pull request merged**
