### PR TITLE
Skipping test_memory_exhaustion.py for Cisco Distributed chassis

### PR DESCRIPTION
**Pull request by vperumal**
### Description of PR
Skipping the test temporarily on Cisco Distributed Chassis. Will remove the skip once the internal issue is fixed

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Skipping the test temporarily on Cisco Distributed Chassis. Will remove the skip once the internal issue is fixed

#### How did you do it?
Added the skip to tests_mark_conditions_platform_tests.yaml

#### How did you verify/test it?
Verified on T2 profile for Cisco Distributed chassis

### CODE REVIEW

**Comment by vperumal** [comment]
FYI @abdosi

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Failed<br/>- hook id: end-of-file-fixer<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml<br/><br/>check yaml...............................................................Failed<br/>- hook id: check-yaml<br/>- exit code: 1<br/><br/>while constructing a mapping<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 867, column 3<br/>found duplicate key "skip" with value "{}" (original value: "{}")<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 871, column 3<br/><br/>To suppress this check see:<br/>http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Failed<br/>- hook id: end-of-file-fixer<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml<br/><br/>check yaml...............................................................Failed<br/>- hook id: check-yaml<br/>- exit code: 1<br/><br/>while constructing a mapping<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 867, column 3<br/>found duplicate key "skip" with value "{}" (original value: "{}")<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 871, column 3<br/><br/>To suppress this check see:<br/>http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Failed<br/>- hook id: trailing-whitespace<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml<br/><br/>fix end of files.........................................................Passed<br/>check yaml...............................................................Failed<br/>- hook id: check-yaml<br/>- exit code: 1<br/><br/>while constructing a mapping<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 867, column 3<br/>found duplicate key "skip" with value "{}" (original value: "{}")<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 871, column 3<br/><br/>To suppress this check see:<br/>http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys<br/>...<br/>[truncated extra lines, please run pre-commit locally to view full check results]<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...............................................................Failed<br/>- hook id: check-yaml<br/>- exit code: 1<br/><br/>while constructing a mapping<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 868, column 5<br/>found duplicate key "reason" with value "Skipping the test temporarily on Cisco Distributed Chassis. Will remove the skip once the internal issue is fixed" (original value: "Unsupported release 20191130")<br/>in "tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml", line 871, column 5<br/><br/>To suppress this check see:<br/>http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys<br/><br/>check for added large files..............................................Passed<br/>check python ast.....................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by abdosi** [comment]
We will not need this PR. There will be fix in Software Image

**Pull request closed without merging**
