### PR TITLE
[tests/configlet] Remove -n in apply-patch in add_rack test

### PR DESCRIPTION
**Pull request by wen587**
### Description of PR

Summary: Remove -n in apply-patch of test_add_rack.
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
The -n was added because not all of YANG models are present in SONiC. Now the YANG model is complete. So we can remove the -n option.
#### How did you do it?
Remove -n in apply-patch operation.
#### How did you verify/test it?
E2E test.

### CODE REVIEW

**Comment by wen587** [comment]
I was trying to add back the result check of apply-patch.
https://github.com/sonic-net/sonic-mgmt/blob/babe544009363cd33becdbbd73da73c0846b7b8d/tests/configlet/util/generic_patch.py#L204


Now `generic_patch_add_t0` will succeed but `generic_patch_remove_t0` won't.
By checking the result, it seems there is uppercase to lowercase converting result int the leafref
```
   "stdout_lines":[
====>#####NOTE: Where does it come of below line conversion? I was not able to find it in code.######
      "converted ipv6 address to lowercase fc00::41~1126 with prefix /INTERFACE/Ethernet64| in value: /INTERFACE/Ethernet64|FC00::41~1126",
      "Patch Applier: Patch application starting.",
      "Patch Applier: Patch: [{\"path\": \"/QUEUE/Ethernet64|3\", \"op\": \"remove\"}, {\"path\": \"/QUEUE/Ethernet64|2\", \"op\": \"remove\"}, {\"path\": \"/QUEUE/Ethernet64|1\", \"op\": \"remove\"}, {\"path\": \"/QUEUE/Ethernet64|0\", \"op\": \"remove\"}, {\"path\": \"/QUEUE/Ethernet64|6\", \"op\": \"remove\"}, {\"path\": \"/QUEUE/Ethernet64|5\", \"op\": \"remove\"}, {\"path\": \"/QUEUE/Ethernet64|4\", \"op\": \"remove\"}, {\"path\": \"/PORT/Ethernet64/admin_status\", \"op\": \"remove\"}, {\"path\": \"/PORT/Ethernet64/description\", \"value\": \"fortyGigE0/64\", \"op\": \"replace\"}, {\"path\": \"/BUFFER_PG/Ethernet64|0\", \"op\": \"remove\"}, {\"path\": \"/BGP_NEIGHBOR/10.0.0.33\", \"op\": \"remove\"}, {\"path\": \"/BGP_NEIGHBOR/fc00::42\", \"op\": \"remove\"}, {\"path\": \"/PORT_QOS_MAP/Ethernet64\", \"op\": \"remove\"}, {\"path\": \"/BUFFER_QUEUE/Ethernet64|5-6\", \"op\": \"remove\"}, {\"path\": \"/BUFFER_QUEUE/Ethernet64|0-2\", \"op\": \"remove\"}, {\"path\": \"/BUFFER_QUEUE/Ethernet64|3-4\", \"op\": \"remove\"}, {\"path\": \"/DEVICE_NEIGHBOR_METADATA/ARISTA01T0\", \"op\": \"remove\"}, {\"path\": \"/DEVICE_NEIGHBOR/Ethernet64\", \"op\": \"remove\"}, {\"path\": \"/CABLE_LENGTH/AZURE/Ethernet64\", \"value\": \"0m\", \"op\": \"replace\"}, {\"path\": \"/ACL_TABLE/EVERFLOW/ports/8\", \"op\": \"remove\"}, {\"path\": \"/ACL_TABLE/EVERFLOWV6/ports/8\", \"op\": \"remove\"}, {\"path\": \"/INTERFACE/Ethernet64\", \"op\": \"remove\"}, {\"path\": \"/INTERFACE/Ethernet64|10.0.0.32~131\", \"op\": \"remove\"}, {\"path\": \"/INTERFACE/Ethernet64|fc00::41~1126\", \"op\": \"remove\"}]",
      "Patch Applier: Getting current config db.",
      "Patch Applier: Simulating the target full config after applying the patch."
   ],
====>####NOTE: below error caused that it cannot find lowercase Ethernet ip-prefix. It will succeed if uppercase#####
   "stderr":"Failed to apply patch\nUsage: config apply-patch [OPTIONS] PATCH_FILE_PATH\nTry \"config apply-patch -h\" for help.\n\nError: can't remove a non-existent object 'Ethernet64|fc00::41/126'",
```

**Review by renukamanavalan — DISMISSED** [review]
Go for it, if it passes the test.
Thanks!

**Comment by renukamanavalan** [comment]
> pperca

The patch applier should be enabled to handle this case difference for attributes like IP, which are case insensitive.
Please check with remove patch code author to handle it.

**Comment by wen587** [comment]
> 

Hi @renukamanavalan , 

- From the jsonpatch website (https://extendsclass.com/json-patch.html), it recognizes the difference when we change the ip from lowercase to uppercase.

```
Source JSON:
{
      "INTERFACE": {
        "Ethernet64|FC00::41~1126": {}
    }
}

Target JSON:
{
      "INTERFACE": {
        "Ethernet64|fc00::41~1126": {}
    }
}

JSON Patch
[
 {
  "op": "remove",
  "path": "/LOOPBACK_INTERFACE/Loopback0|FC00:1::32~1128"
 },
 {
  "op": "add",
  "path": "/LOOPBACK_INTERFACE/Loopback0|fc00:1::32~1128",
  "value": {}
 }
]

```

- Another thing is that it was UPPERCASE at first, but it was modified to LOWERCASE by unknown operation. Here is the log

```
  "stdout_lines":[
====>#####NOTE: Where does it come of below line conversion? ######
      "converted ipv6 address to lowercase fc00::41~1126 with prefix /INTERFACE/Ethernet64| in value: /INTERFACE/Ethernet64|FC00::41~1126",
      "Patch Applier: Patch application starting.",
```
I think it is good if we can prevent that operation.
Need to mention in test `generic_patch_add_t0`, it doesn't do the conversion.

**Review by qiluo-msft — APPROVED** [review]

**Comment by wangxin** [comment]
This PR was cherry-picked to 202205 branch before the image change is backported to 202205 branch. Revert it for now and cherry-pick it later after the 202205 image has the related changes.

**Pull request merged**
