### PR TITLE
[chassis] [voq] convert strings to lowercases before comparison in voq_helpers.py

### PR DESCRIPTION
**Pull request by wenyiz2021**
### Description of PR

There are failures in function check_voq_neighbor_on_sup and check_all_neighbors_present_local that on some voq chassis, config facts had entries like: `SYSTEM_NEIGH|xxx-lc3-1|Asic0|Ethernet72|fc00::ca` while we are trying to find asicname that is `ASIC0` in the previous string, which causes lots of failures in voq testing.

in some other cases on the same chassis dut, the uppercase/lowercase is not consistent, so we have to check by ignoring upper/lowercases.
```
79) "SYSTEM_INTERFACE|lc7-1|Asic0|Ethernet80"
80) "SYSTEM_INTERFACE|lc3-1|ASIC0|PortChannel1015"
```

Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/10473

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### How did you verify/test it?
run test_voq_init and test_voq_disrupts on chassis, only failure is because of TB issue(/etc/sonic/chassisdb.conf" not present on dut)

```
ERROR voq/test_voq_init.py::test_voq_neighbor_create[lc5-1-0] - Fai...
ERROR voq/test_voq_init.py::test_voq_neighbor_create[lc5-1-1] - Fai...
FAILED voq/test_voq_init.py::test_voq_interface_create[lc5-1-0] - R...
FAILED voq/test_voq_init.py::test_voq_interface_create[lc5-1-1] - R...
================ 2 failed, 8 passed, 2 error in 344.93 seconds =================
```

### CODE REVIEW

**Comment by wenyiz2021** [comment]
@arlakshm could you please help to review? testing is done

**Comment by judyjoseph** [comment]
@wenyiz2021  can we check if we can fix in minigraph parsing itself ASIC0 --> asic0 for single asic

**Comment by wenyiz2021** [comment]
@judyjoseph the issue no longer persist in latest 202205.54 image
minigraph change was done by Abhishek to fix this

**Comment by judyjoseph** [comment]
closing this PR .. as Wenyi mentioned that the issue no longer persist in latest 202205.54 image

**Pull request closed without merging**
