### PR TITLE
Update nexthop rewrite for flows based on default hash offset for cisco platform

### PR DESCRIPTION
**Pull request by ranepbhagyashree**
### Description of PR
Changes to fix failing testcase: test_nhop_group_member_order_capability for cisco platform
After the default hash offset change, the mac address received for Flows is inconsistent with expected gb_asic_flow_map was changed.
  
Summary:
Fixes # (issue)
Fixed the gb dictionary values and verified on T1-100G and T1-400G.

 
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [X] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### How did you verify/test it?
Verified on T1-100G and T1-400G

#### Any platform specific information?
Gb specific

### CODE REVIEW

**Comment by rajendrat** [comment]
viz @kevinwangsk

**Review by bpar9 — CHANGES_REQUESTED** [review]
please remove internal/vendor bug ID info from PR details

**Review by bpar9 — APPROVED** [review]
lgtm

**Comment by wsycqyz** [comment]
Do we need this PR in 202311 branch?

**Comment by ranepbhagyashree** [comment]
> Do we need this PR in 202311 branch?

No we do not need this change for 202311 branch

**Review by wsycqyz — APPROVED** [review]
lğtm

**Review by kevinskwang — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Closing and reopening PR could trigger semgrep, seems it was blocked for no reason.

**Comment by ranepbhagyashree** [comment]
lgtm

**Pull request merged**
