### PR TITLE
skipping test_vxlan_decap testcase on cisco 8122 platform

### PR DESCRIPTION
**Pull request by CharudattaSChitale**
**What is the motivation for this PR?**
Skipping test_vxlan_decap testcase as vxlan support is not available for cisco 8122 platforms.

**How did you do it?**
Added a skip condition for test vxlan/test_vxlan_decap.py for cisco 8122 platforms in file tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

**Type of change** 
-Test modification

**Back port request** 
-202311
-202405
-202305

**How did you verify/test it?**
Ran vxlan/test_vxlan_decap.py for Cisco 8122 platform. Made sure it was skipped with 'vxlan support not available for cisco-8122 platform'

### CODE REVIEW

**Comment by wsycqyz** [comment]
PR test stuck. Try to close the PR and re-open the PR.

**Comment by wsycqyz** [comment]
@CharudattaSChitale Please comment "/azpw run" in this PR to trigger PR test.

**Comment by CharudattaSChitale** [comment]
Opened another PR which does not have any pre-commit errors
https://github.com/sonic-net/sonic-mgmt/pull/15219

**Pull request closed without merging**
