### PR TITLE
[202205][m0][route] Add support for m0-2vlan in test_route_perf

### PR DESCRIPTION
**Pull request by yaqiangz**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
test_route_perf failed at m0-2vlan topo

#### How did you do it?
Add support for m0-2vlan

#### How did you verify/test it?
Run test

### CODE REVIEW

**Review by Blueve — APPROVED** [review]

**Comment by yaqiangz** [comment]
@wangxin Could you pls help to merge this PR?

**Comment by wangxin** [comment]
@yaqiangz Is this a backport of a master branch PR to 202205 branch?
Can you mention the master branch PR ID in PR description?

**Comment by yaqiangz** [comment]
> @yaqiangz Is this a backport of a master branch PR to 202205 branch? Can you mention the master branch PR ID in PR description?

@wangxin No, it is just for 202205 branch. 
In master branch this PR fixed the issue by the way. [8265-line61](https://github.com/sonic-net/sonic-mgmt/pull/8265/files#diff-6a6fda970f0e67ed27814bb614811ae8e2de10b175418a81a48c6781ee1e2811R61). But this PR would case test failure in Arista 720DT. I have checked with @prabhataravind and found that this PR was done as repair item for 202012 branch issue. So I am still in progress checking with @StormLiangMS whether it should be fixed or backported to 202205.

As for current PR, we want to fix failure in m0-2vlan at first.

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
Confirmed with @yaqiangz, the issue fixed by this PR was also fixed in #8265. However, we have concern with backporting #8265 to 202205 branch. To address the issue for m0-2vlan topo, created this PR to 202205 branch. It's kind of a partial backporting of #8265 to 202205 branch.

**Pull request merged**
