### PR TITLE
[python3] json.dumps() not support bytes string as input

### PR DESCRIPTION
**Pull request by XuChen-MSFT**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

hit below error in nightly test, after upgrade to python3
```
qos/test_qos_sai.py::TestQosSai::testParameter[testbed-None] 
-------------------------------- live log setup --------------------------------
05:50:57 __init__._fixture_generator_decorator    L0088 ERROR  | 
TypeError("Object of type 'bytes' is not JSON serializable",)
Traceback (most recent call last):
  File "sonic-mgmt/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "sonic-mgmt/tests/qos/qos_sai_base.py", line 1294, in ingressLosslessProfile
    pgs
  File "sonic-mgmt/tests/qos/qos_sai_base.py", line 266, in __getBufferProfile
    self.__updateVoidRoidParams(dut_asic, bufferProfile)
  File "sonic-mgmt/tests/qos/qos_sai_base.py", line 197, in __updateVoidRoidParams
    "COUNTERS_BUFFER_POOL_NAME_MAP", bufferPoolName
  File "sonic-mgmt/tests/common/devices/sonic_asic.py", line 413, in run_redis_cmd
    result = self.sonichost.shell(argv=argv)
  File "sonic-mgmt/tests/common/devices/base.py", line 70, in _run
    json.dumps(complex_args)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
ERROR                                                                    [100%]
```

RCA：
In Python 3, json.dumps() expects a string object as input, not a bytes object. To make your code work in Python 3, 

#### How did you do it?

since input is not a simple bytes string, it's a dict  and contain a bytes string. like below:
```
complex_args type <class 'dict'> value {'argv': ['redis-cli', '-n', '2', 'HGET', 'COUNTERS_BUFFER_POOL_NAME_MAP', b'ingress_lossless_pool']}
```

so override default method of json library, to support convert bytes string to normal string.

### CODE REVIEW

**Review by wsycqyz — APPROVED** [review]

**Review by Gfrom2016 — APPROVED** [review]

**Review by wsycqyz — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Comment by arlakshm** [comment]
@wangxin, @XuChen-MSFT do we need this change in 202205?

**Comment by wangxin** [comment]
@arlakshm Not yet. The python3 change has not been added to the 202205 branch yet.

**Comment by arlakshm** [comment]
Thanks @wangxin.
@tjchadaga @vmittal-msft looks like the python3 changes are not there in 202205. What test failures are seen because of python3 changes in T2 qos tests?

**Comment by wangxin** [comment]
@arlakshm Probably it's because of cherry-picking some changes to 202205. For example, a change is not for python3, but it has extra python3 related changes.

**Pull request merged**
