### PR TITLE
fix to validate all db device keys are populated after chassid restart

### PR DESCRIPTION
**Pull request by vperumal**
### Description of PR
test_chassisd.py tests fails intermittently due to early exit of _collect_data function before the db is populated completely

Added code to avoid early exit of _collect_data function

return false until the number of db device keys after restarting chassisd process matches the number of db keys before restart

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
test_chassisd.py tests fails intermittently due to early exit of _collect_data function before the db is populated completely

#### How did you do it?
Added code to avoid early exit of _collect_data function

#### How did you verify/test it?
Verified on cisco-8000 platform with T2 profile

### CODE REVIEW

**Comment by vperumal** [comment]
FYI @gechiang

**Review by gechiang — APPROVED** [review]
LGTM.

**Pull request merged**
