### PR TITLE
Implement Cisco qos parameter autogenerator for 8111

### PR DESCRIPTION
**Pull request by rbpittman**
### Description of PR

Summary:
Implement Cisco qos parameter autogenerator for 8111

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305

#### How did you do it?
Enable new calculations for 8111 to predict qos.yaml tunings for test_qos_sai.py. 

#### How did you verify/test it?
Verified 8111 passes all test_qos_sai.py tests on 202305 branch. Required PR #10725 (not merged at time of writing) to get a cleaner baseline run for better verification. 
Verified no regression on T1 8102.

#### Any platform specific information?
Cisco-specific qos.yaml parameter autogenerator.

### CODE REVIEW

**Comment by Aravind-Subbaroyan** [comment]
@kevinwangsk - Could you please review this?

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me

**Review by kevinskwang — APPROVED** [review]

**Comment by rbpittman** [comment]
I don't think we have plans to support 8111 in 202205. Some of the baseline code isn't there, hence a conflict.

**Comment by XuChen-MSFT** [comment]
> I don't think we have plans to support 8111 in 202205. Some of the baseline code isn't there, hence a conflict.

Thanks @rbpittman  for clarify. will remove cherry pick for 202205.
and I found test stuck on 202305 branch when verify this PR.  Did you observed similar symptom on 202305 branch.

**Comment by rbpittman** [comment]
No such conflict on 202305, the bot was able to cleanly file the PR. 
Looks like it waited for the checks to pass, but saw the failure and decided not to merge. Would be a nice upgrade if it sent a notification on check failure. 
Guessing the failure is just a random infra problem?

**Comment by XuChen-MSFT** [comment]
@rbpittman  I merge this change to private 202305 branch, and then manually run qos sai test on 8111 t1 device, encounter test stuck.
just revert this change, not observe test stuck.
so I stop cherry-pick to 202305 until fix this issue.
can you run and check at your side?
if necessary, I can share the test log for test stuck.

**Comment by rbpittman** [comment]
Yes if you could share the log that'd be great, I'll take a look tomorrow

**Pull request merged**
