### PR TITLE
skip encapsulation protocol when hashing ip_proto as 60

### PR DESCRIPTION
**Pull request by yenlu-keith**
Description
In our lab environment, sonic router will to hit the failure when running "test_hash" of hashing ip_proto as 60 on both ipv4 and ipv6 test cases.

Steps to reproduce the issue:
run the testcase "fib/test_fib.py::test_hash" on T1 testbed.
Describe the results you received:
Traceback (most recent call last):
File "ptf/hash_test.py", line 406, in runTest
self.check_hash(hash_key)
File "ptf/hash_test.py", line 158, in check_hash
(matched_index, _) = self.check_ip_route(hash_key, src_port, dst_ip, exp_port_list, pkt_cnt)
File "ptf/hash_test.py", line 168, in check_ip_route
(matched_index, received) = self.check_ipv4_route(hash_key, src_port, dst_port_list, pkt_cnt)
File "ptf/hash_test.py", line 255, in check_ipv4_route
send_packet(self, src_port, pkt)
File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 2538, in verify_packet_any_port
% (ports, device_number, result.format()))

then,
set ptf_runner.py with debug level on below
set def ptf_runner(...., debug_level="debug"... )

not receiving any packets
dataplane : DEBUG : Poll timeout, no packet from device 0, port None
dataplane : DEBUG : Poll timeout, no packet from device 0, port None

Describe the results you expected:
testcase Pass

Additional information you deem important:
concluded as ptf testscript does form the tcp transport segment content by simple_tcp_packet(), but the ip network content does not have. testscript only locates ip_proto field (in this case: ip_proto is an encapsulation type if randomly selected with ip_proto is 60 as ipv4v6). data payload should have ipv4 and ipv6 network layer content (ex: by simple_ip_packet())

it could be a limitation on PTF when considering tcp/ip content together. Here is the wiki page for listing protocol meaning: **https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers

the snippets base on sonic-mgmt 202012.
https://github.com/Azure/sonic-mgmt/blob/202012/ansible/roles/test/files/ptftests/hash_test.py#L208
Using simple_tcp_packet(), no taking simple_ip_packet()

https://github.com/Azure/sonic-mgmt/blob/202012/ansible/roles/test/files/ptftests/hash_test.py#L226
pkt['IP'].proto=ip_proto without IP content.

We also have 2 observations based on T0 setup with proposed solution as below.
(If u think it is okay, we can file a case on sonic-mgmt 202012 branch first)

solution:
https://github.com/Azure/sonic-mgmt/blob/202012/ansible/roles/test/files/ptftests/hash_test.py#L178
-skip_protos= [2, 4, 41, 253,254]
+skip_protos= [2, 4, 41, 60, 253,254]

other observations:
 the PTF pcap file:
checking on the packet with ip_proto field as 60, the ip raw payload redirected and represented as ip_proto field 4, the ip raw payload represents as IP Error/malformed.

### CODE REVIEW

**Review by kevinskwang — APPROVED** [review]

**Comment by kevinskwang** [comment]
Should it target to master?

**Comment by wangxin** [comment]
> Should it target to master?

I agree with @kevinskwang. The PR should be created to the master branch. Then we can cherry-pick it into other branches like the 202012 branch.

**Comment by yenlu-keith** [comment]
> > Should it target to master?
> 
> I agree with @kevinskwang. The PR should be created to the master branch. Then we can cherry-pick it into other branches like the 202012 branch.

this file does not exist on master branch. it will be better to have this file first on master before doing cherry-pick, correct?

**Comment by wangxin** [comment]
> > > Should it target to master?
> > 
> > 
> > I agree with @kevinskwang. The PR should be created to the master branch. Then we can cherry-pick it into other branches like the 202012 branch.
> 
> this file does not exist on master branch. it will be better to have this file first on master, correct? should we merge this commit first?

On master branch, this file has been moved to `ansible/roles/test/files/ptftests/py3/hash_test.py`
Considering the file is under different folder between master and 202012 branch, there will be merge conflicts if we do cherry-picking. In this case, I think we can keep this PR. Can you create a separate one to the master branch?

**Comment by wangxin** [comment]
BTW, your branch for this PR is out-of-date with the base branch. Can you do a rebase to the 202012 branch and force push to update this branch? Then we can go ahead with merging it.

**Comment by yenlu-keith** [comment]
> BTW, your branch for this PR is out-of-date with the base branch. Can you do a rebase to the 202012 branch and force push to update this branch? Then we can go ahead with merging it.

please kindly merge this; I have filed PR on master branch.

**Pull request merged**
