### PR TITLE
fix TestPfcwdFunc::test_pfcwd_multi_port t2

### PR DESCRIPTION
**Pull request by auspham**
### Description of PR

Summary:
Fixes # (issue) 30115858

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
From the original PR #10198 these changes were left out. After adding it back in it passed all the tests

@rraghav-cisco @abdosi could you please review?

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@auspham , this will affect all other tests in the same file. You may have to run the entire suite to make sure it is good.

**Review by rraghav-cisco — APPROVED** [review]
LGTM.

**Review by abdosi — APPROVED** [review]

**Comment by auspham** [comment]
> @auspham , this will affect all other tests in the same file. You may have to run the entire suite to make sure it is good.

Tested with the whole modules, other functionality passed.

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
@bingwang-ms could you help to approve cherry-pick?

**Comment by bingwang-ms** [comment]
This PR changed the behavior of all non-dualtor platform. Is it expected?

**Comment by auspham** [comment]
> This PR changed the behavior of all non-dualtor platform. Is it expected?

I have reached out to you via teams

**Pull request merged**
