### PR TITLE
[Nvidia] Update too_big_timeout for test_arm_too_big_timeout

### PR DESCRIPTION
**Pull request by JibinBao**
Update too_big_timeout to 66000, because a life timeout for CPLD can be configured between 0 - 65535s instead of 0 -32s

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Update test parameters for test_arm_too_big_timeout

#### How did you do it?
Update too_big_timeout to 66000

#### How did you verify/test it?
Run test_arm_too_big_timeout on the latest cpld version

#### Any platform specific information?
Spc1, Spc2

#### Supported testbed topology if it's a new test case?
Any

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Review by keboliu — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@nhe-NV is it spc1, spc2 only (type 1)? I see timeout was changed for spc3 as well (type 2)

**Comment by JibinBao** [comment]
> @nhe-NV is it spc1, spc2 only (type 1)? I see timeout was changed for spc3 as well (type 2)

Now all spectrums support the timeout 66000

**Comment by JibinBao** [comment]
@liat-grozovik , Could you help merge It?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
