### PR TITLE
[dualtor-aa] Fix test_server_failure errors over dualtor-aa topo 

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
As it requires `active-standby` mux ports to test, skip it if no
`active-standby` mux ports available.

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

#### How did you do it?
As the motivation.

#### How did you verify/test it?
Run over both `dualtor-aa` and `dualtor` testbeds.

### CODE REVIEW

**Comment by yxieca** [comment]
Seems that this is a valid test scenario for active-active as well? Do you plan to add a test for active-active? Or set different expectations according to port type?

**Comment by lolyu** [comment]
> Seems that this is a valid test scenario for active-active as well? Do you plan to add a test for active-active? Or set different expectations according to port type?

The testcase tries to verify that if the server stops replying heartbeats, the tors pair doesn't oscillate. For `active-active`, we don't have such a scenario, if the server stops replying to heartbeats, both ToRs will be standby in this case.

**Comment by yxieca** [comment]
Please add test gap for Libra.

**Review by yxieca — APPROVED** [review]

**Review by zjswhhh — APPROVED** [review]
lgtm

**Comment by lolyu** [comment]
filed a test gap #8233

**Pull request merged**
