### PR TITLE
[auto-techsupport] Improved test_autotechsupport

### PR DESCRIPTION
**Pull request by ppikh**
Signed-off-by: Petro Pikh <petrop@nvidia.com>

### Description of PR
Improved test test_autotechsupport:
- Fixed issue when "self.dockers_list" has duplicated docker(feature) names(caused sometimes issue when techsupport validation was not able to find running process)
- Added logic which doing disable for cron task which doing automatic cleanup for core files(caused sometimes false failure in case when core files cleanup was done by cron job)
- Decreased number of stub files from 5 to 4(previously it caused time to time issue when some .core files not available in dump due to luck of space on DUT)

Added new test case "test_sai_sdk_dump" which validate techsupport generation started in case when SAI call failed and check that saidump available in techsupport dump

Summary: Improved test_autotechsupport
Fixes # (issue) fixed test_autotechsupport stability

### Type of change
- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Improve test stability and add new test case

#### How did you do it?
see code

#### How did you verify/test it?
Executed all test_auto_techsupport test cases

### CODE REVIEW

**Review by AntonHryshchuk — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@vivekrnv  could you please help to review?

**Comment by ppikh** [comment]
@yxieca , @wangxin , @liat-grozovik  could you please merge this PR?

**Review by vivekrnv — APPROVED** [review]

**Comment by ppikh** [comment]
@yxieca - could you please merge it?

**Review by wangxin — APPROVED** [review]

**Pull request merged**
