### PR TITLE
[T2]:Adding GB LCs to qos-sai list.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Porting 9072 to 202205.(https://github.com/sonic-net/sonic-mgmt/pull/9072)

Adding GB LCs to the cisco-8000 list in qos-sai.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : for viz.

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : Any comments?

**Review by abdosi — DISMISSED** [review]

**Comment by abdosi** [comment]
@wangxin please help merge with this

**Comment by rraghav-cisco** [comment]
@abdosi : I resolved conflict, pls review again. Thanks.

**Review by wangxin — APPROVED** [review]

**Pull request merged**
