### PR TITLE
Porting 9780 to 202305, qos_sai_tests.py code.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Porting PR:9780 to 202305. There were no conflicts in this merge.

This is the 3rd part of the porting effort that we are doing - porting cisco-8000/T2 related code changes from 202205 to master. This PR is for the changes in tests/saitests/py3/sai_qos_tests.py. Changes include:
 

- Adding get_multiple_flows function for cisco platforms.
- Using the new function for LosslessVoq, AllPortQWaterMark, PGSharedWaterMark, BufferPoolWatermarkTest and PFCXon.
- Introduce new functions : dynamicall_fill_leakout, fill_egress_plus_one, and overflow_egress. These functions enhance fill_leakout_plus_one for T2 - allowing us to take care of packets needed to fill both dst ASIC memory, backplane memory and then src ASIC memory.
- Minor formatting changes needed by pre-commit.
- Remove hardcoded values for queue numbers in AllPortQWaterMark.

### CODE REVIEW

**Review by XuChen-MSFT — APPROVED** [review]
LGTM
and test pass in 202305 branch

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : Would you be merging this and the other PRs to 202305 ?

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco  Can you just call get_multiple_flows() on cisco platform?

**Comment by rraghav-cisco** [comment]
> @rraghav-cisco Can you just call get_multiple_flows() on cisco platform?

Will raise a new PR to call this function only for cisco. May I see the log for infinite loop in other platforms?

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT , Can you pls let me know why the checks failed above ? Pls let me know if it is related to the PR diffs. Thanks, rraghav

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : Any updates?

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco why did you change so many common code in this QoS PR? even include changes for  ACL.
Actually, before your these latest 4 comments, we just need to limit get_multiple_flows()  for cisco platform to avoid test stuck on other platform.
can you file separate PR for those common functions?

```
@XuChen-MSFT ➜ /workspaces/sonic-mgmt (9780_to_202305) $ git diff HEAD~4 | grep "diff --git"
diff --git a/.azure-pipelines/upgrade_image.py b/.azure-pipelines/upgrade_image.py
diff --git a/ansible/devutil/devices/sonic.py b/ansible/devutil/devices/sonic.py
diff --git a/ansible/library/reduce_and_add_sonic_images.py b/ansible/library/reduce_and_add_sonic_images.py
diff --git a/tests/acl/test_acl_outer_vlan.py b/tests/acl/test_acl_outer_vlan.py
diff --git a/tests/arp/test_tagged_arp.py b/tests/arp/test_tagged_arp.py
diff --git a/tests/common/dualtor/mux_simulator_control.py b/tests/common/dualtor/mux_simulator_control.py
diff --git a/tests/saitests/py3/sai_qos_tests.py b/tests/saitests/py3/sai_qos_tests.py
diff --git a/tests/templates/dual_tor_sniffer.conf.j2 b/tests/templates/dual_tor_sniffer.conf.j2
@XuChen-MSFT ➜ /workspaces/sonic-mgmt (9780_to_202305) $ 
```

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : I don't understand. My diff has only one file. Why does your diff show so many files ? Also, I have moved the get_multiple_flows only to cisco-8000.

**Review by XuChen-MSFT — APPROVED** [review]
LGTM

**Comment by XuChen-MSFT** [comment]
@StormLiangMS  @kevinwangsk 
[Raghav ha](https://github.com/sonic-net/sonic-mgmt/pull/11043) include the fix of test stuck, and already was merged to master branch.
this PR https://github.com/sonic-net/sonic-mgmt/pull/10725 is ready for commit to 202305 branch.
Can you help to merge it?

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
