### PR TITLE
[copp]: Add test cases to verify rate-limiting for the following cases

### LINKED ISSUE #4691: [Test gap] Verify CPU Q and rate limiting for trapped packets
**Description**

In one of the dualtor scenario, observed that packets that were trapped to CPU was on a high priority que on which there was no rate-limiting. This resulted in overloading kernel and device became unresponsive to critical commands like "changing mux state"

Need a test to check on what queues are being used in trapping and ensure rate limiting is applied. 

For e.g in the problem case, ~100k packets/sec got trapped to CPU. Whereas Sonic has rate limiting on Queue 1 and 4 but not on Queue 4. 

```
show c cpu
MC_PERQ_PKT(1).cpu0	    :		263,138,968		 +1,239 	    258/s
MC_PERQ_PKT(4).cpu0	    :		  9,310,202		    +58 	     10/s
MC_PERQ_PKT(7).cpu0	    :		259,029,881	       +440,113 	 84,029/s

show c cpu
TDBGC3_64.cpu0		    :		    254,717		 +9,421
MC_PERQ_PKT(1).cpu0	    :		263,137,729		+79,148 	    259/s
MC_PERQ_PKT(4).cpu0	    :		  9,310,144		 +3,549 	     11/s
MC_PERQ_PKT(7).cpu0	    :		258,589,768	    +28,963,633 	 97,576/s

```

Reference CSP - CS00012218081

**Steps to reproduce the issue:**
Need a test to check on trapped Q and/or the rate limiting for the following cases:

1. IP2ME packets (Regular ICMP)
2. Neighbor Miss (IPv4 and IPv6)
3. IPinIP encapsulated packet (v4inv4 and v6inv4) and neighbor miss after decap

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

```
SONiC.20201231.31
HwSKU: Arista-7050CX3
ASIC: broadcom
 ```

### PR DESCRIPTION
**Pull request by prabhataravind**
### Description of PR
 * Neighbor miss (subnet hit) packets
    - This test case sends IPv4 and IPv6 packet to a vlan subnet IP on a device
    - The expectation is that the packets hit the CPU and are rate-limited at  the default trap group cir/cbs. The test uses a default grap group cir/cbs of 600PPS.

 * Neighbor miss after decap for IPinIP encapsulated packets
     - This test case sends IPinIP packets (v4inv4 and v6inv4) to a vlan subnet IP on a device
     - The expectation is that the packets hit the CPU and are rate-limited at  the default trap group cir/cbs. The test uses a default grap group cir/cbs of 600PPS.
     
 * TTL 1 packets
     - This test case sends a simple TCP packet with TTL 1
     - The expectation is that the packets hit the CPU and are rate-limited at 600PPS

Summary:
Fixes #4691 
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### CODE REVIEW

**Comment by prsunny** [comment]
@prabhataravind , changes lgtm. Can you update the PR description with test case and expection? What is the rate-limiting behavior we can expect.

**Comment by prabhataravind** [comment]
@prsunny, could you approve if everything looks ok?

**Comment by prsunny** [comment]
As discussed, can you add a test for the same cases without explicit trap configs but use image defaults.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
