### PR TITLE
[Mellanox][DualTor] Skip dualtor ecn test cases for inner dscp 2 and 6 on Nvidia platforms.

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
In the dualtor scenario, when dscp remapping is enabled and packet with dscp 2 or 6 is received by the standby tor, the mapping behavior is different between Nvidia and other vendors.
On Nvidia platforms, the downstream packet with dscp 2 or 6 on the standby tor will be encapsulated with the same 2 or 6 outer dscp and bounced back to the tunnel as lossless packet. And this behavior will cause the dualtor ecn test fail.
Actually, this is not considered as a valid use case, the dscp 2 and 6 should be reserved for the remapped tunnel traffic. And this has been discussed and confirmed with the Community.
So, we need to skip the cases for dscp 2 and 6 on Nvidia platforms when dscp remapping is enabled.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### What is the motivation for this PR?
Skip the dualtor ecn test cases for dscp 2 and 6 on Nvidia platforms when dscp remapping is enabled.
#### How did you do it?
Add the skip logic in the test cases.
#### How did you verify/test it?
By running the test on Nvidia 4600c dualtor testbed.

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@stephenxs please review as well
@ayurkiv-nvda FYI

**Comment by liat-grozovik** [comment]
@bingwang-ms FYI

**Review by stephenxs — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
LGTM. @ZhaohuiS Can you please also help review? Thanks

**Review by ZhaohuiS — APPROVED** [review]

**Pull request merged**
