### PR TITLE
Dtor changes

### PR DESCRIPTION
**Pull request by svelamal**
### Description of PR

When using mux simulator instead of hardware mux cables, added delay is suggested for dualtor_io testcases to pass
1.We see hearbeat loss during tests in our environment
2.The test intends to test functionality and not performance and we can achieve same more reliably with these relaxed parameters.
Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ x] 202205

### CODE REVIEW

**Comment by kevinskwang** [comment]
Please indicate the clear reason about the changes for each parameter, what's the detailed error you observed with current configuration.

**Comment by svelamal** [comment]
We see failures in multiple cases under dualtor_io intermittently for e.g:
test_normal_op_downstream_lower_tor[active-active] fails due to 
E       Failed:
E       Traffic to server 192.168.0.15 was disrupted 2 times. Allowed number of disruptions: 1
E       Traffic to server 192.168.0.18 was disrupted 2 times. Allowed number of disruptions: 1

In cases like dualtor_io/test_normal_op.py::test_active_config_reload_downstream_standby where downstream tarffic is expected to be disrupted by one disruption window (of lost packets) when transition of standby ToR to Active ToR takes place, we saw errors like these:
E Failed: 
E Traffic to server 192.168.0.2 was disrupted 29 times. Allowed number of disruptions: 1
E Traffic to server 192.168.0.3 was disrupted 28 times. Allowed number of disruptions: 1
E Traffic to server 192.168.0.4 was disrupted 29 times. Allowed number of disruptions: 1

@theasianpianist from MSFT suggested these changes for us last year which reduced these issues caused by mux simulator in our testing environment.
From: Lawrence Lee <[Lee.Lawrence@microsoft.com](mailto:Lee.Lawrence@microsoft.com)>
Date: Thursday, January 5, 2023 at 5:35 PM
To: Yanzhao Zhang <[yanzhaoz@microsoft.com](mailto:yanzhaoz@microsoft.com)>, Kevin(Shengkai) Wang <[shengkaiwang@microsoft.com](mailto:shengkaiwang@microsoft.com)>, Balajinath Bollini (balajib) <[balajib@cisco.com](mailto:balajib@cisco.com)>, Krithika Srinivas (kritsrin) <[kritsrin@cisco.com](mailto:kritsrin@cisco.com)>, Mani Veerachamy (mveerach) <[mveerach@cisco.com](mailto:mveerach@cisco.com)>, Ross Bennett (rossben) <[rossben@cisco.com](mailto:rossben@cisco.com)>, Devesh Pathak (devpatha) <[devpatha@cisco.com](mailto:devpatha@cisco.com)>
Cc: Ying Xie <[Ying.Xie@microsoft.com](mailto:Ying.Xie@microsoft.com)>, Guohan Lu <[gulv@microsoft.com](mailto:gulv@microsoft.com)>, Prince Sunny <[Prince.Sunny@microsoft.com](mailto:Prince.Sunny@microsoft.com)>, Satish Ananthanarayana (sanantha) <[sanantha@cisco.com](mailto:sanantha@cisco.com)>, Bhavani Parise (bhavani) <[bhavani@cisco.com](mailto:bhavani@cisco.com)>, Soumya Velamala (svelamal) <[svelamal@cisco.com](mailto:svelamal@cisco.com)>, Raghavendran Ramanathan (rraghav) <[rraghav@cisco.com](mailto:rraghav@cisco.com)>, Shivu Vibhuti (svibhuti) <[svibhuti@cisco.com](mailto:svibhuti@cisco.com)>, Aman Singhal (amans) <[amans@cisco.com](mailto:amans@cisco.com)>, Jeremy Moschner (jmoschne) <[jmoschne@cisco.com](mailto:jmoschne@cisco.com)>
Subject: RE: Dual ToR test case sync up

Hi folks, please try the following performance constant changes:
 
tests/common/dualtor/constants.py:15 – set `MUX_SIM_ALLOWED_DISRUPTION_SEC` to 30
tests/common/dualtor/data_plane_utils.py:220 – set `send_interval` default value to 1
tests/common/dualtor/dual_tor_utils.py:1348 – set `probe_interval_ms` to 3000

**Comment by kevinskwang** [comment]
@theasianpianist  could you help to take a review of this PR?

**Comment by theasianpianist** [comment]
@svelamal have you been able to run the tests recently without these changes? There have been a few improvements to the test cases since our discussion, please check if the tests can pass without these changes.

**Comment by CharudattaSChitale** [comment]
I ran dualtor_io folder on recent sonic Images with strict vs relaxed parameters.
I see that some testcases like dualtor_io/test_grpc_server_failure.py, dualtor_io/test_link_failure.py fail because of disruptions in case of strict parameters (without changes mentioned in this PR)

**Review by theasianpianist — APPROVED** [review]

**Comment by jamesan47** [comment]
@bpar9, could you help with review and approve?

**Review by bpar9 — APPROVED** [review]

**Pull request merged**
