### PR TITLE
[Nvidia] Update qos cases for SN5600

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

For Nvidia SN5600 the formula to calculate the shared buffer size for pg and queue differs from other Spectrum. So, update the corresponding code for it.

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Update QoS cases for SN5600

#### How did you do it?
Update the code according to the relevant formula

#### How did you verify/test it?
Run qos tests on the SN5600 device

#### Any platform specific information?
SN5600

#### Supported testbed topology if it's a new test case?
Any

### CODE REVIEW

**Review by stephenxs — APPROVED** [review]

**Comment by JibinBao** [comment]
@bingwang-ms @XuChen-MSFT  Can you help review it?

**Comment by JibinBao** [comment]
@bingwang-ms @XuChen-MSFT Can you help review it?

**Comment by JibinBao** [comment]
@bingwang-ms Can you help review this PR?

**Review by nhe-NV — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
> @bingwang-ms Can you help review this PR?

We don't have SN5600 testbed, so I have no way to verify the change on a physical testbed. The change looks good to me.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
