### PR TITLE
Migrate utility script (sonic.py) to python 3

### PR DESCRIPTION
**Pull request by opcoder0**
### Description of PR

Convert `sonic.py` utility script to Python 3.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?

Considering Python 2 is no longer supported convert all PTF scripts to Python 3 so that current/newer releases can have a PTF image with just Python 3.

#### How did you do it?
Use 2to3.

#### How did you verify/test it?
Test in progress.

#### Any platform specific information?
Not applicable

#### Supported testbed topology if it's a new test case?
Not applicable

### Documentation
Not applicable

### CODE REVIEW

**Comment by wangxin** [comment]
This is a utility script. If its location is changed, could other scripts depend on it not be able to find it?

**Comment by opcoder0** [comment]
> This is a utility script. If its location is changed, could other scripts depend on it not be able to find it?

I have created a soft link like other utility scripts in py3 and kept the main script outside so any other scripts relying on it find it.

**Review by wangxin — APPROVED** [review]

**Comment by saiarcot895** [comment]
@opcoder0  This script was already migrated to Python 3, and was running as a Python 3 script in the PTF container. In fact, if my understanding is correct, all PTF scripts on master branch are running in Python 3.

Were there any failures seen because this script was running under Python 2?

**Comment by opcoder0** [comment]
> @opcoder0 This script was already migrated to Python 3, and was/is running as a Python 3 script in the PTF container. In fact, if my understanding is correct, all PTF scripts on master branch are running in Python 3.
> 
> Were there any failures seen because this script was running under Python 2?

@saiarcot895 from what I understood most of the files/tests in `ptftests` were indeed already in Python 3. I didn't see any errors/failures. I recently noticed `vnet_vxlan` was still in Python 2 and I moved that (in #12540). I also noticed all of the utilities were moved under `py3` with a symlink pointing back one level up. Hence this PR for sonic.py. The change the tool made was trivial and not really Py3 related. Apart from the files in `ptftests` I believe the other tests in `acstests` and a bunch of others (I have a list) may still be in Python 2. I am in the process of checking those in the coming week.

**Pull request merged**
