### PR TITLE
Use asichost mac when DUT is multi-asic system

### PR DESCRIPTION
**Pull request by sridhartalari**
### Description of PR

Summary: Changes to support DUT with  Multi-ASIC 
Fixes # (issue)
Packets send to DUT should have ASIC MAC has DMAC instead of DUT MAC. Fixed the same
### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
pass all sonic mgmt tests on multi-asic systems
#### How did you do it?
Ran scripts with multi-asic system as DUT and recorded the list
#### How did you verify/test it?
Ran the test_stress_arp.py script with fix and test-case passed
#### Any platform specific information?
if all ASIC in platform share the same MAC as DUT MAC this fix is not needed

### CODE REVIEW

**Comment by rajendrat** [comment]
viz @abdosi . Please review/merge the PR.

**Comment by rajendrat** [comment]
viz @abdosi please review/merge this PR.

**Comment by rajendrat** [comment]
viz Please review @bpar9

**Review by bpar9 — APPROVED** [review]
LGTM. Can you remove the line logging msg line from Description as the only change you are making via the PR is changing the DMAC for multi-asic

**Comment by vperumal** [comment]
@abdosi @yejianquan - Kindly help review and merge

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
