### PR TITLE
fixed a duplicated skip declaration for the test_set_fans_speed

### PR DESCRIPTION
**Pull request by antonptashnik**
### Description of PR

Summary: fixed duplicated skip declaration for the test_set_fans_speed
Fixes # (issue)

Combined a duplicated test_set_fans_speed skip declaration under a single section
### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### CODE REVIEW

**Review by OleksandrKozodoi — APPROVED** [review]

**Review by ZhaohuiS — APPROVED** [review]

**Comment by ZhaohuiS** [comment]
@antonptashnik  There is conflicts, could you please resolve them then I will merge it for you. Thanks.

**Comment by antonptashnik** [comment]
> @antonptashnik There are conflicts, could you please resolve them then I will merge it for you. Thanks.

I've resolved the conflict, please merge if you can. Thanks !

**Comment by abdosi** [comment]
there is another PR for this: https://github.com/sonic-net/sonic-mgmt/pull/6813/files

cc @vperumal which one we should take ?

**Comment by vperumal** [comment]
> there is another PR for this: https://github.com/sonic-net/sonic-mgmt/pull/6813/files
> 
> cc @vperumal which one we should take ?

Hi @abdosi, This PR only covers one of the tcs, the one Ram opened takes care of :
platform_tests/api/test_fan_drawer_fans.py::TestFanDrawerFans::test_set_fans_speed:
platform_tests/api/test_chassis_fans.py::TestChassisFans::test_set_fans_speed:
platform_tests/api/test_chassis_fans.py::TestChassisFans::test_set_fans_led:

I would go with Ram's PR: https://github.com/sonic-net/sonic-mgmt/pull/6813

**Comment by antonptashnik** [comment]
closing in favor of https://github.com/sonic-net/sonic-mgmt/pull/6813

**Pull request closed without merging**
