### PR TITLE
Increase the timeout for advanced reboot test

### PR DESCRIPTION
**Pull request by congh-nvidia**
Change-Id: If47adc0a8c2a494ec636bf82d7685ba5a3f1611d

### Description of PR

Summary:
For the advanced reboot test, the timeout was 1800s, but on some platform 1800s it is not enough. From the ptf log we can see, the test was almost done in the handle_post_reboot_test_reports(). So increase the timeout for another 300s. 
```
"advanced-reboot.ReloadTest ... ERROR", "", "======================================================================", 
"ERROR: advanced-reboot.ReloadTest", 
"----------------------------------------------------------------------", 
"Traceback (most recent call last):", 
"  File \"ptftests/advanced-reboot.py\", line 1283, in runTest", "    self.handle_post_reboot_test_reports()", 
"  File \"ptftests/advanced-reboot.py\", line 1131, in handle_post_reboot_test_reports", "    self.sad_revert()", 
"  File \"ptftests/advanced-reboot.py\", line 546, in sad_revert", "    log_info, fails = self.sad_handle.revert()", 
"  File \"ptftests/sad_path.py\", line 44, in revert", "    self.shandle.sad_setup()", 
"  File \"ptftests/sad_path.py\", line 292, in sad_setup", "    time.sleep(120)", 
"  File \"/usr/lib/python2.7/dist-packages/ptf/ptfutils.py\", line 102, in raise_timeout", 
"    raise Timeout.TimeoutError()", "TimeoutError", "",
"----------------------------------------------------------------------", 
"Ran 1 test in 1802.241s", "", "FAILED (errors=1)"]
```

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
The 1800s timeout of the advanced reboot test is not enough on some platforms, need to increase it. 
#### How did you do it?
Increase the timeout from 1800s to 2100s.
#### How did you verify/test it?
By automation test.

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Review by nhe-NV — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by congh-nvidia** [comment]
Hi @liat-grozovik, could you please cherry-pick this to 202205? Thanks.

**Comment by liat-grozovik** [comment]
> Hi @liat-grozovik, could you please cherry-pick this to 202205? Thanks.

added the label. @yxieca to handle the cherry pick

**Comment by yxieca** [comment]
@vaibhavhd for awareness.

@congh-nvidia from the attached log, it appears that 30 minutes expired on a backtrace of setting up the test. In this case, why would adding another 5 minutes help?

**Comment by yxieca** [comment]
Holding off back port until we have understood the change.

**Comment by congh-nvidia** [comment]
> @vaibhavhd for awareness.
> 
> @congh-nvidia from the attached log, it appears that 30 minutes expired on a backtrace of setting up the test. In this case, why would adding another 5 minutes help?

This is not the setup phase of the test but the teardown phase. The sad_setup() is called in revert() to revert the setup to the pre-test state.
The initial caller handle_post_reboot_test_reports() is in the finally block of the test(line 1283):
https://github.com/sonic-net/sonic-mgmt/blob/c2a86d2e9d037d1be3d8c744915a06d9b0ab3547/ansible/roles/test/files/ptftests/advanced-reboot.py#L1227-L1283

**Comment by yxieca** [comment]
Thanks for the clarification! Putting back the cherry-picking flag.

**Pull request merged**
