### PR TITLE
[DPU, CRM] Added testplan for SONiC DASH CRM tests

### PR DESCRIPTION
**Pull request by ppikh**
### Description of PR
Added testplan for SONiC DASH CRM tests
Tests will be implemented in fodler: tests/dash and will re-use logic from original CRM test case - but will use different CRM resources

Summary: Added testplan for SONiC DASH CRM tests
Fixes # (issue)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Added testplan for SONiC DASH CRM tests

#### How did you do it?
Nothing to review, testplan the same as regular CRM test plan for SONiC but with different CRM resources

#### Any platform specific information?
DPU/DASH

#### Supported testbed topology if it's a new test case?
appliance

### CODE REVIEW

**Review by AntonHryshchuk — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@prsunny FYI

**Review by AntonHryshchuk — APPROVED** [review]

**Comment by yxieca** [comment]
@ppikh can you fix the pre-commit-check failures? I think this check should be passing now.

**Comment by liat-grozovik** [comment]
@ppikh can you please check again the pre-check failure?

**Comment by liat-grozovik** [comment]
@prsunny do you wish to assign someone to review?
@oleksandrivantsiv please review

**Review by oleksandrivantsiv — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prsunny kindly reminder to review or assign someone.

**Pull request merged**
