### PR TITLE
Support for sai-thrift calls in ixia ecn scripts.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Adding support for PTF based sai-thrift calls in ixia scripts, due to the need to query the DUT for SAI counter values. Support only for cisco-8000 platforms.

### CODE REVIEW

**Review by alpeshspatel — DISMISSED** [review]

**Comment by kevinskwang** [comment]
Is this PR really needed? I don't see any place invoke get_sai_attribute even in PR6041?

**Comment by rraghav-cisco** [comment]
> Is this PR really needed? I don't see any place invoke get_sai_attribute even in PR6041?

@kevinskwang : Once this PR is merged, the rpc calls will be enabled in the PR:6041. Currently they are commented out.

**Comment by rraghav-cisco** [comment]
I opened a different PR since I had to resolve all the conflicts. Pulling the code from master cleared out my branch.

**Pull request closed without merging**
