### PR TITLE
[202205] Cherry-pick : Improve the stability of dualtor memory leak test (#9198)

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
This is the manual cherry-pick of PR (#9198) to 202205 branch for conflict resolving.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
This is the manual cherry-pick of PR (#9198) to 202205 branch for conflict resolving.
#### How did you do it?
The conflict is caused by the Python2/3 migration change which is not included in 202205 branch. I removed the change to resolve the conflict.
#### How did you verify/test it?
Run the test 5 times on 4600C with 202205 SONiC image, all passed.

### CODE REVIEW

**Comment by congh-nvidia** [comment]
Hi @wangxin @yxieca , could you please help check the CodeQL failure? Looks like some environment issue? Thanks.

**Comment by liat-grozovik** [comment]
@bingwang-ms FYI
@yxieca could can you please help to merge?

**Comment by yxieca** [comment]
@congh-nvidia is this codeql failure related to sonic-swss PR 2845? That PR has been cherry-picked to 202205 branch.

At some point in the future, we should be able to retry this PR and get a pass?

**Comment by congh-nvidia** [comment]
> @congh-nvidia is this codeql failure related to sonic-swss PR 2845? That PR has been cherry-picked to 202205 branch.
> 
> At some point in the future, we should be able to retry this PR and get a pass?

Hi @yxieca, I don't if it's related to sonic-swss PR 2845. Is sonic-mgmt share the same CodeOL flow with sonic-swss?
In my PR, the failure is:
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off [24](https://github.com/sonic-net/sonic-mgmt/actions/runs/6080166034/job/16493707662?pr=9836#step:1:28).472 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/f43a0e5ff2bd294095638e18286ca9a3d1956744'. Error: Response status code does not indicate success: 503 (Service Unavailable).
Warning: Back off 22.095 seconds before retry.
Error: Response status code does not indicate success: 503 (Service Unavailable).

**Review by nhe-NV — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Pull request merged**
