### PR TITLE
Fix test_events flakiness

### PR DESCRIPTION
**Pull request by zbud-msft**
### Description of PR

Summary:
Fixes # (issue)

22732546

### Type of change

Refactored test_events to use gnmi_cli_py client running in docker-ptf to make more stable

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

Current test_events is not stable and fails > 50% of the time, as running gnmi_cli inside container is not reliable.  With new added code in gnxi/gnmi_cli_py, we can use ptf docker gnmi cli for event testing in effort to make more stable.

Also no reason to skip arm test case as we are not worrying about using gnmi_cli binary on dut.

#### How did you do it?

Refactoring (code change)

#### How did you verify/test it?

Pipeline/manual

### CODE REVIEW

**Comment by zbud-msft** [comment]
Hi @lerry-lee can you run 50 rounds of test_events on t0 with testbedv2?

**Comment by lerry-lee** [comment]
> Hi @lerry-lee can you run 50 rounds of test_events on t0 with testbedv2?

Yes, let's validate its stability.

**Comment by lerry-lee** [comment]
@zbud-msft This PR has been validated 50 times on t0, it's stable.

**Review by qiluo-msft — APPROVED** [review]

**Comment by zbud-msft** [comment]
Thanks @lerry-lee

**Pull request merged**
