### PR TITLE
[sai_qualify]Add timeout value for sai_adhoc cmd

### PR DESCRIPTION
**Pull request by richardyu-ms**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [X] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### why
For sai_adhoc command(run ansible command in background), it might get the output/return after file a command, i.e. reboot. The command runs successful remotely, cause no return in that running terminal(reboot happen, reboot-terminal ternimated, ssh reconnect happen after reboot, but reboot command has no return), then cannot finish the command.

Then, we need add some timeout value for the command, and terminate it.

Combine with the ignore_error parameter, we can choice if we need to care about the errors.

#### how
Add timeout value for sai_adhoc command

#### Verify
test in testbed

### CODE REVIEW

**Review by lolyu — APPROVED** [review]

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/sai_qualify/conftest.py:208:9: E265 block comment should start with '# '<br/>tests/sai_qualify/conftest.py:209:9: E265 block comment should start with '# '<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Review by lolyu — DISMISSED** [review]

**Review by lolyu — APPROVED** [review]

**Pull request merged**
