### PR TITLE
Add t0-28 topo

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
This is to add the t0-28 topology for Nvidia platform sn4280.
#### How did you do it?
Update the related files.
#### How did you verify/test it?
Run regression with t0-28 topology on sn4280 testbed.

### CODE REVIEW

**Review by bingwang-ms — DISMISSED** [review]

**Comment by congh-nvidia** [comment]
Hi @bingwang-ms, I have fixed the conflict and rebase to resolve checker failures. Please help approve it again, thanks.

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
