### PR TITLE
[T2] Add case to test lossy fair-voq

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

1, Add a new case to test lossy fair-voq.
2, Add lossy_queue_voq_2 and lossy_queue_voq_3 to qos_param_generator.py. 
Default-voq and fair-voq will pass lossy_queue_voq_2, fair-voq and split-voq will pass lossy_queue_voq_3.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### How did you verify/test it?
Case testQosSaiLossyQueueVoqMultiSrc

vanguard(Q200 longlink, default voq) skipped:
```
-------------------------------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoqMultiSrc.xml --------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------------------------------
01:57:15 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
===================================================================================== short test summary info =====================================================================================
SKIPPED [1] /data/tests/qos/qos_sai_base.py:2125: This test is skipped for egress asic HBM enabled systems.
=================================================================================== 1 skipped in 355.75 seconds ===================================================================================
```
lancer(Q200 shortlink, fair voq) passed:
```
============================================================================================= PASSES ==============================================================================================
_____________________________________________________________________ TestQosSai.testQosSaiLossyQueueVoqMultiSrc[single_asic] _____________________________________________________________________
-------------------------------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoqMultiSrc.xml --------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------------------------------
00:53:24 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
===================================================================================== short test summary info =====================================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoqMultiSrc[single_asic]
=================================================================================== 1 passed in 389.64 seconds ====================================================================================
```
Case testQosSaiLossyQueueVoq

Vanguard skipped lossy_queue_voq_1, passed lossy_queue_voq_2.
```
============================================================================================= PASSES ==============================================================================================
________________________________________________________________ TestQosSai.testQosSaiLossyQueueVoq[single_asic-lossy_queue_voq_2] ________________________________________________________________
------------------------------------------------------ generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoq.xml ------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------------------------------
01:17:13 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
===================================================================================== short test summary info =====================================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoq[single_asic-lossy_queue_voq_2]
SKIPPED [1] /data/tests/qos/test_qos_sai.py:1135: LossyQueueVoq: This test is skipped since cisco-8000 T2 doesn't support split-voq.
============================================================================== 1 passed, 1 skipped in 608.24 seconds ==============================================================================
```

Lancer skipped lossy_queue_voq_1, passed lossy_queue_voq_2.
```
============================================================================================= PASSES ==============================================================================================
________________________________________________________________ TestQosSai.testQosSaiLossyQueueVoq[single_asic-lossy_queue_voq_2] ________________________________________________________________
------------------------------------------------------ generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoq.xml ------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------------------------------
01:32:15 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
===================================================================================== short test summary info =====================================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiLossyQueueVoq[single_asic-lossy_queue_voq_2]
SKIPPED [1] /data/tests/qos/test_qos_sai.py:1135: LossyQueueVoq: This test is skipped since cisco-8000 T2 doesn't support split-voq.
============================================================================== 1 passed, 1 skipped in 615.21 seconds ==============================================================================

```

### CODE REVIEW

**Comment by abdosi** [comment]
Please resolve the conflict.

**Comment by zhixzhu** [comment]
@abdosi conflicts resolved.

**Review by abdosi — APPROVED** [review]

**Comment by XuChen-MSFT** [comment]
have duplicated impl for function "skip_longlink"  in both PR https://github.com/sonic-net/sonic-mgmt/pull/11553 and PR https://github.com/sonic-net/sonic-mgmt/pull/10838,
already fixed in master branch, please remove duplicated code when cherry pick

**Comment by abdosi** [comment]
> have duplicated impl for function "skip_longlink" in both PR #11553 and PR #10838, already fixed in master branch, please remove duplicated code when cherry pick

@zhixzhu to handle this please create PR for 202305 directly.

**Comment by zhixzhu** [comment]
To avoid duplicate function "skip_longlink", here is the PR for 202305: https://github.com/sonic-net/sonic-mgmt/pull/11904
Didn't see function "skip_longlink" in 202311 branch.

**Comment by XuChen-MSFT** [comment]
@kevinskwang can you help to approve cherry-pick to 202311 branch?

**Comment by XuChen-MSFT** [comment]
@zhixzhu 
can you manually create double commit to 202311 branch, since #14447 have pre-commit failure

**Comment by XuChen-MSFT** [comment]
This PR had been included in 202305 and 202405.
For 202311, manually cherry pick by PR https://github.com/sonic-net/sonic-mgmt/pull/14584

**Pull request merged**
