### PR TITLE
enabled VxLAN VNET tests for Barefoot

### PR DESCRIPTION
**Pull request by antonptashnik**
### Description of PR

Summary: enabled VxLAN VNET tests for Barefoot
Fixes # (issue)
- moved skip condition to a dedicated file tests_mark_conditions
- enabled tests for Barefoot

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

### CODE REVIEW

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Comment by antonptashnik** [comment]
@wangxin @ZhaohuiS please merge if the PR looks good

**Comment by ZhaohuiS** [comment]
> @wangxin @ZhaohuiS please merge if the PR looks good

Ye, currently, PR test keeps failing due to image issue. Will merge it when PR test is passed

**Comment by ZhaohuiS** [comment]
@antonptashnik There is conflicts now, could you please resolve it? thanks.

**Review by wangxin — DISMISSED** [review]

**Comment by antonptashnik** [comment]
> @antonptashnik There is conflicts now, could you please resolve it? thanks.

done. Please re-review once you have a chance. Thanks!

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Comment by xwjiang-ms** [comment]
Hi @antonptashnik , do we need to cherry pick this PR to 202205 branch?

**Pull request merged**
