### PR TITLE
update skip conditions for watermark cases

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

Updated skip conditions of watermark cases.

QSharedWatermark: Queue watermark read on egress, since qos params are based on src, keep skipping lossless if src and dst's port_speed_cable_length different, or asic types(Q200, Q100) are different.

PgSharedWatermark: Unskip lossless multi_dut.

BufferPoolWatermark: The watermark is read on egress asic. Unskip lossy for multi_dut. Unskip lossless for multi_dut_shortlink_to_shortlink. Since qos params are based on src, keep skipping lossless if src and dst's port_speed_cable_length different, or asic types(Q200, Q100) are different.

Summary:
Fixes # (issue)
https://migsonic.atlassian.net/browse/MIGSMSFT-695 QoS SAI test gap review

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
update skip conditions for QSharedWatermark and PgSharedWatermark.

#### How did you verify/test it?
Verified it on T2 testbed.

QSharedWatermark:
multi-dut short_to_short is also enabled, since ingress and egress port same config. Verification pending.
```
------------------------------ generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark_2024-11-08-21-50-32.xml ------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------- live log sessionfinish -------------------------------------------------------------------------
22:36:22 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
======================================================================== short test summary info =========================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark[single_asic-wm_q_shared_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark[single_asic-wm_q_shared_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark[single_dut_multi_asic-wm_q_shared_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark[single_dut_multi_asic-wm_q_shared_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark[multi_dut_longlink_to_shortlink-wm_q_shared_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiQSharedWatermark[multi_dut_shortlink_to_longlink-wm_q_shared_lossy]
SKIPPED [2] qos/test_qos_sai.py:1830: Skip queue watermark lossless test since portspeed or cable length is different between src and dst asic
SKIPPED [2] qos/test_qos_sai.py:1800: Don't have 2 shortlink frontend nodes - so can't run multi_dut_shortlink_to_shortlinktests
========================================================== 6 passed, 4 skipped, 1 warning in 2748.05s (0:45:48) ==========================================================
sonic@sonic-ucs-m6-09:/data/tests$ 
```
PgSharedWatermark multi_dut:
```
----------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark_2024-11-08-20-50-54.xml ------------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------- live log sessionfinish -------------------------------------------------------------------------
21:32:17 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
======================================================================== short test summary info =========================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[single_asic-wm_pg_shared_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[single_asic-wm_pg_shared_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[single_dut_multi_asic-wm_pg_shared_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[multi_dut_longlink_to_shortlink-wm_pg_shared_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[multi_dut_shortlink_to_longlink-wm_pg_shared_lossless]
SKIPPED [3] qos/test_qos_sai.py:1642: PGSharedWatermark: Lossy test is not applicable in cisco-8000 multi_asic scenarios.
SKIPPED [2] qos/test_qos_sai.py:1598: Don't have 2 shortlink frontend nodes - so can't run multi_dut_shortlink_to_shortlinktests
========================================================== 5 passed, 5 skipped, 1 warning in 2482.17s (0:41:22) ==========================================================
sonic@sonic-ucs-m6-09:/data/tests$  
```
```
----------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark_2024-11-05-00-51-43.xml ------------------------------
------------------------------------------------------------------------- live log sessionfinish -------------------------------------------------------------------------
01:09:16 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
======================================================================== short test summary info =========================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPgSharedWatermark[multi_dut_shortlink_to_shortlink-wm_pg_shared_lossless]
SKIPPED [1] qos/test_qos_sai.py:1617: The lossy test is not valid for multiAsic configuration.
========================================================== 1 passed, 1 skipped, 1 warning in 1051.75s (0:17:31) ==========================================================
DEBUG:tests.conftest:[log_custom_msg] item: <Function testQosSaiPgSharedWatermark[multi_dut_shortlink_to_shortlink-wm_pg_shared_lossy]>
DEBUG:tests.conftest:append custom_msg: {'dut_check_result': {'config_db_check_pass': False, 'core_dump_check_pass': True}}
INFO:root:Can not get Allure report URL. Please check logs
sonic@sonic-ucs-m6-4:/data/tests$ 
```

BufferPoolWatermark:
```
----------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark_2024-11-05-05-56-41.xml -----------
------------------------------------------------------- live log sessionfinish --------------------------------------------------------
06:23:48 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
======================================================= short test summary info =======================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[multi_dut_shortlink_to_shortlink-wm_buf_pool_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[multi_dut_shortlink_to_shortlink-wm_buf_pool_lossy]
```
```
---------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark_2024-11-08-19-14-59.xml -----------------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------------------- live log sessionfinish -------------------------------------------------------------------------
19:57:05 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
======================================================================== short test summary info =========================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[single_asic-wm_buf_pool_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[single_asic-wm_buf_pool_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[single_dut_multi_asic-wm_buf_pool_lossless]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[single_dut_multi_asic-wm_buf_pool_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[multi_dut_longlink_to_shortlink-wm_buf_pool_lossy]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiBufferPoolWatermark[multi_dut_shortlink_to_longlink-wm_buf_pool_lossy]
SKIPPED [2] qos/test_qos_sai.py:1108: Skip buffer Pool watermark lossless test since portspeed or cable length is different between src and dst asic
SKIPPED [2] qos/test_qos_sai.py:1070: Don't have 2 shortlink frontend nodes - so can't run multi_dut_shortlink_to_shortlinktests
========================================================== 6 passed, 4 skipped, 1 warning in 2524.20s (0:42:04) ==========================================================
sonic@sonic-ucs-m6-09:/data/tests$ 
```

### CODE REVIEW

**Comment by alpeshspatel** [comment]
FYI @kevinwangsk and @wsycqyz

**Comment by auspham** [comment]
@abdosi please help review

**Comment by sdszhang** [comment]
@zhixzhu can you resolve the conflict, and move it out of draft state when ready?

**Comment by zhixzhu** [comment]
Conflict resolved, ready for review.

**Review by abdosi — APPROVED** [review]

**Comment by zhixzhu** [comment]
Double commit to 202405: https://github.com/sonic-net/sonic-mgmt/pull/16056

**Comment by sdszhang** [comment]
conflicts due to #14469 not in 202405.

**Pull request merged**
