### PR TITLE
Add new skips on mellanox platforms to .yml file

### PR DESCRIPTION
**Pull request by mhen1**
### Description of PR

Summary:
Added new skips to tests/common/plugins/conditional_mark/tests_mark_conditions.yaml.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Add new skips to .yaml file.

### CODE REVIEW

**Comment by mhen1** [comment]
@roy-sror

**Review by wangxin — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@wangxin do you know how to restart or Semgrep only? it is holding from the PR to get in

**Comment by wangxin** [comment]
> @wangxin do you know how to restart or Semgrep only? it is holding from the PR to get in

The Semgrep was auto-inserted by Github. I am not sure how to restart it. Currently this PR has merge conflicts. @mhen1 can you resolve the merge conflicts? A new commit will trigger another round of PR tests. Let's see if that can fix the problem.

**Comment by bingwang-ms** [comment]
@yxieca Can you please help cherry-pick this PR? Thanks

**Comment by bingwang-ms** [comment]
Below tests are passing on Mellanox platform
```
test_show_platform_fanstatus_mocked
test_thermal_control_fan_status 
test_thermal_control_load_invalid_format_json
test_thermal_control_load_invalid_value_json
```
Below test is always disabled
```test_buffer_model_test```
Please double check.

**Comment by mhen1** [comment]
> Below tests are passing on Mellanox platform
> 
> ```
> test_show_platform_fanstatus_mocked
> test_thermal_control_fan_status 
> test_thermal_control_load_invalid_format_json
> test_thermal_control_load_invalid_value_json
> ```
> 
> Below test is always disabled `test_buffer_model_test` Please double check.

Added a PR updated with the skip reasons of these tests - https://github.com/sonic-net/sonic-mgmt/pull/12939

**Comment by mhen1** [comment]
Hey,
I’ve added a new PR, updated with the skip reasons - Updated skip reasons on Mellanox platforms by mhen1 · Pull Request #12939 · sonic-net/sonic-mgmt (github.com)<https://github.com/sonic-net/sonic-mgmt/pull/12939>.
Thanks,
Mor Hen

**Comment by mhen1** [comment]
Hey,
Could you please take a look and approve it?
Thanks,
Mor Hen

From: Mor Hen ***@***.***>
Sent: Wednesday, 22 May 2024 11:20
To: sonic-net/sonic-mgmt ***@***.***>; sonic-net/sonic-mgmt ***@***.***>; Xin Wang ***@***.***>
Cc: Mention ***@***.***>; Roy Sror ***@***.***>
Subject: RE: [sonic-net/sonic-mgmt] Add new skips on mellanox platforms to .yml file (PR #12183)

Hey,
I’ve added a new PR, updated with the skip reasons - Updated skip reasons on Mellanox platforms by mhen1 · Pull Request #12939 · sonic-net/sonic-mgmt (github.com)<https://github.com/sonic-net/sonic-mgmt/pull/12939>.
Thanks,
Mor Hen

**Pull request merged**
