### PR TITLE
Fix syslog test failure about fixture tbinfo

### PR DESCRIPTION
**Pull request by wumiaont**
### Description of PR
Syslog test failed for complaining about tbinfo usage as it's a fixture. Solution is to add tbinfo as fixture in the orch_logrotate_setup. Then referencing tbinfo will be the yield of tbinfo which is a dict

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [X] 202405

#### What is the motivation for this PR?
Fix the test failure for syslog test_logrotate.
#### How did you verify/test it?
Tested on OC test bed and see test pass now.

### CODE REVIEW

**Review by cyw233 — APPROVED** [review]
LGTM! Added the request label for 202405

**Comment by rlhui** [comment]
@yejianquan would you be able to help approve/merge this? thanks.

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by yejianquan** [comment]
Hi @wumiaont , please raise a separate PR resolving the conflict to 202405 branch

**Comment by wumiaont** [comment]
> Hi @wumiaont , please raise a separate PR resolving the conflict to 202405 branch

OK

**Pull request merged**
