### PR TITLE
[Test gap] Test dhcp_relay with source port ip enabled

### LINKED ISSUE #3624: Need new test: DHCP Relay supports using src intf ip in relay
**Description**
This is to test the new feature in https://github.com/Azure/sonic-buildimage/pull/7055

### PR DESCRIPTION
**Pull request by yejianquan**
### Description of PR

Summary:
Fixes #3624 
Mitigate the test gap: Test dhcp relay with source port ip in relay enabled.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Fixes #3624 
Mitigate the test gap: Test dhcp relay with source port ip in relay enabled.
#### How did you do it?
1. Enhance dhcp_relay ptf test to verify the src_ip in relay packets
2. Add a fixture which modify deployment_id to 8 and enable source port ip in relay
3. Add a test case exactly same with test_dhcp_relay_default but include fixture enable_source_port_ip_in_relay.
#### How did you verify/test it?
Run on local dev vm, 
dhcp_relay/test_dhcp_relay.py::test_interface_binding PASSED             [ 12%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default PASSED            [ 25%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_with_source_port_ip_in_relay_enabled PASSED [ 37%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_after_link_flap PASSED    [ 50%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_start_with_uplinks_down PASSED [ 62%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_unicast_mac PASSED        [ 75%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_random_sport PASSED       [ 87%]
dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_counter SKIPPED (skip...) [100%]
and PR test will test it again.

### CODE REVIEW

**Comment by yejianquan** [comment]
Hi @Blueve @yaqiangz , could you please help to review this PR?

**Review by yaqiangz — APPROVED** [review]
LGTM

**Comment by yaqiangz** [comment]
Hold on..

**Comment by yaqiangz** [comment]
Hi @lolyu does dualtor need this test? It would affect source IP sent from relay to DHCP server

**Comment by lolyu** [comment]
> Hi @lolyu does dualtor need this test? It would affect source IP sent from relay to DHCP server

If it is a generic feature on T0, dualtor will need it.
I think dhcp-relay will enable source port ip on t0, right?

**Comment by yejianquan** [comment]
> > Hi @lolyu does dualtor need this test? It would affect source IP sent from relay to DHCP server
> 
> If it is a generic feature on T0, dualtor will need it. dhcp-relay will enable source port ip on t0, right?

@lolyu What do you mean by 'dhcp-relay will enable source port ip on t0'?

From my understanding and research, 
when the -si is used, in the relay packets, the source ip will be client_ip from the loopback ip of DUT.

In the buildimage, only when deployment_id==8, we enable source ip in relay.
https://github.com/sonic-net/sonic-buildimage/blob/e0e0c0c1b3c58635bc25fde6a77ca3b0849dfde1/dockers/docker-dhcp-relay/dhcpv4-relay.agents.j2#L16
But not sure when the deployment_id will be 8 in the production ENV.

**Review by yaqiangz — APPROVED** [review]
LGTM, @yejianquan could you please confirm whether it could pass in dualtor topo?

**Review by lolyu — APPROVED** [review]

**Comment by yaqiangz** [comment]
> > Hi @lolyu does dualtor need this test? It would affect source IP sent from relay to DHCP server
> 
> If it is a generic feature on T0, dualtor will need it. dhcp-relay will enable source port ip on t0, right?

@lolyu If -si is not set, kernel would set source IP of relayed packets automatically (What I saw is loopback ip). If -si is set, dhcrelay would force to set source IP of relayed packets to be the egress interface ip (Upstream P2P ip)

**Comment by yejianquan** [comment]
> LGTM, @yejianquan could you please confirm whether it could pass in dualtor topo?
@yaqiangz 
Created a dualtor test plan, and it passed
https://elastictest.org/scheduler/testplan/66f0e1c6741a4a192f8a29b6?leftSideViewMode=detail&testcase=dhcp_relay%2Ftest_dhcp_relay.py&type=console

image

**Comment by w1nda** [comment]
Synced with @yejianquan and @wen587, we can backport this PR to 202311 and 202405.

Hi @yxieca, @bingwang-ms, cloud you help approve the backporting to 202311 and 202405? thanks in advance

**Comment by auspham** [comment]
@yejianquan The automated cherry-pick of this change to the `202405` branch ([action] PR #15825) failed and has been closed. Please raise a PR to `202405` to cherry-pick this change manually.

**Comment by yejianquan** [comment]
> @yejianquan The automated cherry-pick of this change to the `202405` branch ([action] PR #15825) failed and has been closed. Please raise a PR to `202405` to cherry-pick this change manually.

no worries, let's skip on this

**Pull request merged**
