### PR TITLE
Update the skip condition for test_vlan_subnet_decap

### PR DESCRIPTION
**Pull request by nhe-NV**
### Description of PR

Summary: Update the skip based on the skip description 
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### CODE REVIEW

**Comment by nhe-NV** [comment]
@xwjiang-ms  Can you help to review?  it shoud resolve the issue: https://github.com/sonic-net/sonic-mgmt/issues/15912

**Review by xwjiang-ms — APPROVED** [review]
LGTM

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
@nhe-NV Can you update the PR description to elaborate why make this change?

**Comment by kperumalbfn** [comment]
@nhe-NV could you check the conflicts in 202411?

**Comment by nhe-NV** [comment]
> @nhe-NV could you check the conflicts in 202411?
HI @kperumalbfn  I opened the PR for the 202411, Can you help to merge? Thanks!

**Pull request merged**
