### PR TITLE
Fix issue "createEntry: Invalid port interface"

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

Summary:
Fixes # (issue)
https://miggbo.atlassian.net/browse/MIGSOFTWAR-19536
2024 Nov 25 20:11:42.889000 yy39top-lc4 ERR swss0#orchagent: :- createEntry: Invalid port interface Ethernet-BP384
2024 Nov 25 20:11:42.889000 yy39top-lc4 ERR swss0#orchagent: :- doTask: Failed to process PFC watchdog SET task, invalid entry

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
Fix issue of "createEntry: Invalid port interface" when running script snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py.

#### How did you do it?
Fix the sequence of config files when doing config load.

#### How did you verify/test it?
Verified the case on T2 ixia testbed.
```
----------------------- generated xml file: /run_logs/ixia/18470/2024-12-04-00-38-12/tr_2024-12-04-00-38-12.xml -----------------------
INFO:root:Can not get Allure report URL. Please check logs
======================================================= short test summary info =======================================================
PASSED snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py::test_ecn_marking_port_toggle[multidut_port_info0]
============================================== 1 passed, 4 warnings in 698.79s (0:11:38) ==============================================
sonic@snappi-sonic-mgmt-vanilla-202405-t2:/data/tests$ 
```
```
cisco@yy39top-lc4:~$ sudo cat /var/log/syslog | grep "start-LogAnalyzer"
2024 Dec  4 00:35:43.561644 yy39top-lc4 INFO start-LogAnalyzer-test_ecn_marking_port_toggle[multidut_port_info0].2024-12-04-00:39:16
2024 Dec  4 00:40:54.158423 yy39top-lc4 INFO python[176673]: ansible-extract_log Invoked with directory=/var/log file_prefix=syslog start_string=start-LogAnalyzer-test_ecn_marking_port_toggle[multidut_port_info0].2024-12-04-00:39:16 target_filename=/tmp/syslog
cisco@yy39top-lc4:~$ sudo cat /var/log/syslog | grep "Invalid port interface"
cisco@yy39top-lc4:~$ sudo cat /var/log/syslog | grep "_raw_params=config load"
2024 Dec  4 00:40:39.667553 yy39top-lc4 INFO python[175350]: ansible-ansible.legacy.command Invoked with _raw_params=config load 1733273048.975233_pfcwd_None.json,1733273048.975233_pfcwd_asic0.json,1733273048.975233_pfcwd_asic1.json,1733273048.975233_pfcwd_asic2.json -y _uses_shell=True warn=False stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
cisco@yy39top-lc4:~$ 
```

### CODE REVIEW

**Review by sdszhang — APPROVED** [review]
LGTM

**Review by alpeshspatel — APPROVED** [review]

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by alpeshspatel** [comment]
@sdszhang and @yejianquan we need this in 202411 as well.

**Comment by zhixzhu** [comment]
202411 branch contains this change, no need to double commit.

**Pull request merged**
