### PR TITLE
Fixing AttributeError: 'LagPort' object has no attribute 'protocol'

### PR DESCRIPTION
**Pull request by selldinesh**
### Description of PR

Summary: Providing fix for AttributeError: 'LagPort' object has no attribute 'protocol' since snappi-convergence verison has been upgraded
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/12262

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
Providing fix for AttributeError: 'LagPort' object has no attribute 'protocol' since snappi-convergence verison has been upgraded
#### How did you do it?
Modified the protocol attribute to be added to lag config object
#### How did you verify/test it?
Tested on Arista dut

### CODE REVIEW

**Review by developfast — APPROVED** [review]
lgtm

**Comment by rraghav-cisco** [comment]
@selldinesh , @developfast ,

After this, we see a new problem: 
ERROR    root:__init__.py:40 Traceback (most recent call last):
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 1772, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/sonic/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/sonic/.local/lib/python3.8/site-packages/_pytest/python.py", line 195, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/tests/snappi_tests/lacp/test_add_remove_link_from_dut.py", line 52, in test_lacp_add_remove_link_from_dut
    run_lacp_add_remove_link_from_dut(snappi_api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 41, in run_lacp_add_remove_link_from_dut
    tgen_bgp_config = __tgen_bgp_config(api,
  File "/data/tests/snappi_tests/lacp/files/lacp_dut_helper.py", line 152, in __tgen_bgp_config
    lag0.protocol.lacp.actor_system_id = "00:10:00:00:11:11"
AttributeError: 'Lag' object has no attribute 'protocol'

**Comment by developfast** [comment]
@rraghav-cisco you need to update the snappi-ixnetwork version in your test docker environment. @selldinesh please provide the version.

**Comment by dks0692** [comment]
> @rraghav-cisco you need to update the snappi-ixnetwork version in your test docker environment. @selldinesh please provide the version.

@rraghav-cisco please use the following snappi versions
snappi                           0.9.1
snappi-convergence               0.3.4
snappi-ixnetwork                 0.8.2

**Comment by rraghav-cisco** [comment]
@dks0692 : Seeing it with 
sonic@snappi-202305-sonic-mgmt:~$ pip list | grep snappi
snappi                           0.9.1
snappi-convergence               0.4.1
snappi-ixnetwork                 0.9.1
sonic@snappi-202305-sonic-mgmt:~$

**Comment by selldinesh** [comment]
> @dks0692 : Seeing it with
> 
> ```
> sonic@snappi-202305-sonic-mgmt:~$ pip list | grep snappi
> snappi                           0.9.1
> snappi-convergence               0.4.1
> snappi-ixnetwork                 0.9.1
> sonic@snappi-202305-sonic-mgmt:~$ 
> ```

could u please modify the snappi-convergence and snappi-ixnetwork versions as mentioned above and give a try

**Comment by rraghav-cisco** [comment]
@selldinesh , with this also I am seeing the problem. Does it matter if the python2 is still the other package version?

```
FAILED snappi_tests/reboot/test_cold_reboot.py::test_reboot[cold] - AttributeError: 'LagPort' object has no attribute 'protocol'
FAILED snappi_tests/reboot/test_fast_reboot.py::test_reboot[fast] - AttributeError: 'LagPort' object has no attribute 'protocol'
FAILED snappi_tests/reboot/test_soft_reboot.py::test_reboot[soft] - AttributeError: 'LagPort' object has no attribute 'protocol'
FAILED snappi_tests/reboot/test_warm_reboot.py::test_reboot[warm] - AttributeError: 'LagPort' object has no attribute 'protocol'
```

Python3 has the required snappi versions:
```
sonic@snappi-202311-sonic-mgmt:/data/tests$ pip3 list | grep snappi
snappi                           0.9.1
snappi-convergence               0.4.1
snappi-ixnetwork                 0.9.1
WARNING: There was an error checking the latest version of pip.
sonic@snappi-202311-sonic-mgmt:/data/tests$ pip list | grep snappi
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
snappi                             0.7.44
snappi-convergence                 0.2.2
snappi-ixnetwork                   0.7.12
sonic@snappi-202311-sonic-mgmt:/data/tests$ 

```

**Pull request merged**
