### PR TITLE
Add support for Cisco-8000 400G (#7436)

### PR DESCRIPTION
**Pull request by rbpittman**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Double commit to 202205 branch, resolving 2 small conflicts.

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
@rbpittman Can you run a git rebase to resolve the merge conflicts?

**Comment by rbpittman** [comment]
@wangxin Rebased to latest 202205.

**Comment by wangxin** [comment]
@rbpittman, there are still merge conflicts, probably related with recent cherry-pick. Can you rebase again?

**Review by XuChen-MSFT — APPROVED** [review]

**Comment by rbpittman** [comment]
Yeah due to double commit of #7641. 

Resolved conflicts. Also checked that master's "gb:" section of the yaml is identical to this PRs "gb:" section to ensure no mishaps during conflict resolution or other oddities.

**Comment by rbpittman** [comment]
@wangxin This should be good to go. 
And QQ: Do you prefer rebase over merge commits for double commits?

**Pull request merged**
