### PR TITLE
Added missing parameters for qos/test_tunnel_qos_remap.py for TD3

### PR DESCRIPTION
**Pull request by vivekverma-arista**
### Description of PR

Summary: Added missing parameters for qos/test_tunnel_qos_remap.py for TD3
Fixes # (issue): https://github.com/aristanetworks/sonic-qual.msft/issues/72

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
qos/test_tunnel_qos_remap.py::test_xoff_for_pcbb fails with the key error
```
29/02/2024 15:24:22 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/sonic-mgmt-latest/tests/qos/test_tunnel_qos_remap.py", line 787, in test_xoff_for_pcbb
    test_params.update(qos_config[xoff_profile])
KeyError: 'pcbb_xoff_1'
```

This is due to absence of pcbb_xoff parameters for TD3.

#### How did you do it?
Updated the `qos_params.td3.yaml` file directly with the parameters.

### CODE REVIEW

**Comment by StormLiangMS** [comment]
hi @bingwang-ms would you help to review?

**Comment by bingwang-ms** [comment]
Hi @vivekverma-arista, can you please help me understand why we need this change? Because the QoS parameter is per topo, and we already have that parameter defined for topo dualtor.

**Comment by vivekverma-arista** [comment]
> Hi @vivekverma-arista, can you please help me understand why we need this change? Because the QoS parameter is per topo, and we already have that parameter defined for topo dualtor.

Hi @bingwang-ms, the parameters are per topo, the parameters are present for dualtor and dualtor-56, and there should be a separate section for dualtor-aa/dualtor-mixed. In the current state the test defaults to topo-any since there is no section for dualtor-aa: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/qos/tunnel_qos_remap_base.py#L297-L301. And under topo-any these values are not present, therefore it hits the key error.

Also the test is suppose to run in active-standby mode ( even in active-active dualtor ) as it's testing tunnel_qos_remap functionality so the same parameters should be used for dualtor/dualtor-aa/dualtor-mixed for a given cable length and speed. Hence the values in this change are same as: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/qos/files/qos_params.td3.yaml#L173-L202 which are being used for dualtor.

**Comment by StormLiangMS** [comment]
@bingwang-ms  could you help to review?

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
> Hi @vivekverma-arista , may I know what's topo are you running the test on? I got your point, but I think adding the parameter into `topo-any` may not be good enough. Why not add a new section for the new topology?

The change is good for now because we only have one dualtor-aa topo. We need to add sections for different dualtor-aa topos probably in the future,

**Pull request merged**
