### PR TITLE
[BUG FIX] 13449 4 byte asn community

### LINKED ISSUE #13449: [Bug]: bgp/test_4-byte_asn_community.py Multi Asic Support in /data/tests/bgp/templates/bgp_id.template  for extracting the Router Id
### Issue Description

The Template(bgp_id.template) used in the Test Case to extract the router id from the command show ip bgp sum doesn't consider the use case of multi-asic. The regex defined is unable to parse the show ip bgp sum on a multi asic dut 

### Results you see

During the parsing of 
image
 Null value is received

### Results you expected to see

A list of list of the router ids of all asics bgp

### Is it platform specific

generic

### Relevant log output

_No response_

### Output of `show version`

_No response_

### Attach files (if any)

_No response_

### PR DESCRIPTION
**Pull request by Azarack**
### Description of PR

This is to fix the bug described in 13449

Summary:
Fixes #13449

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
To fix identified bug with textfsm parsing

#### How did you do it?
Added a new textfsm template and split logic between single and multi-asic devices

#### How did you verify/test it?
Unable to as I do not have access to multi-asic sonic-mgmt platform

### CODE REVIEW

**Comment by deepak-singhal0408** [comment]
@vikshaw-Nokia please help with reviewing the change..

**Comment by vikshaw-Nokia** [comment]
@Azarack The Cli option uses asic ns and not asic id
https://github.com/sonic-net/sonic-mgmt/issues/13437

**Comment by Azarack** [comment]
> @Azarack The Cli option uses asic ns and not asic id #13437

Ok, I can change that.  But we should only apply one fix to this issue, not two.  Which approach should we take?

**Comment by vikshaw-Nokia** [comment]
@Azarack I have made changes in my commit, if you can check it.
If it works for your case then we can move ahead with that

**Comment by Azarack** [comment]
Fixed with #13689

**Pull request closed without merging**
