### PR TITLE
Add xfail conditions for DualToR

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
Update DualToR skip issues based on github issues or known limitations specific to a vendor. 
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305

#### What is the motivation for this PR?
Add the skip conditions for DualToR

#### How did you verify/test it?
Run regression with the skip conditions.

#### Any platform specific information?
Although some issues may affect all vendors, for now we only skip the tests on Nvidia platforms since we don't know for sure about the test results on other vendors.
It is recommended to take further look and adopt some of the ignore skip due to general issues observed.

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@congh-nvidia  please handle conflict.
@bingwang-ms  please help to review.

**Comment by congh-nvidia** [comment]
Conflict is resolved.

**Comment by liat-grozovik** [comment]
@bingwang-ms FYI

**Comment by congh-nvidia** [comment]
Hi @yxieca , from the weekly meeting you suggest changing the "skip" to "xfail" in this PR. But some skips are also for other reasons which was added before this PR, since duplicate entries are not allowed in the file, should I also change them to xfail?

**Comment by liat-grozovik** [comment]
> @congh-nvidia please handle conflict. @bingwang-ms please help to review.

kindly reminder

**Comment by congh-nvidia** [comment]
Hi @yxieca , I have changed the skips added by me to xfail, but kept the ones which were there originally. Please review.
Thanks.

**Review by yxieca — APPROVED** [review]

**Pull request merged**
