### PR TITLE
fix bgp update timer failure on dual tor

### PR DESCRIPTION
**Pull request by jcaiMR**
### Description of PR
Fix bgp update timer issue on dual tor env. 

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Fix bug update timer issue on dual tor, when set up bgp speaker session with dual tor.
Interface selection on PTF has wrong behavior, config IP addresses within same subnet on different interfaces would case connection error. Refer to analysis of #8487.

#### How did you do it?
Config primary /secondary ip addresses on same physical interface.

#### How did you verify/test it?
re-run test on dual-tor env

### CODE REVIEW

**Review by yejianquan — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM. 

but small question, when we use ip address other than ifconfig?

**Comment by jcaiMR** [comment]
> @jcaiMR LGTM.
> 
> but small question, when we use ip address other than ifconfig?
ifconfig will overwrite previous ip address, it's a kind of operation for primary address. ip address will add primary/secondary ip 
which can make multiple address on same interface.

**Pull request merged**
