### PR TITLE
Fix TypeError in verify_mac_jumping

### PR DESCRIPTION
**Pull request by bratashX**
Signed-off-by: Petro Bratash <petrox.bratash@intel.com>

### Description of PR

**PROBLEM**:
If  run `platform_tests/test_advanced_reboot.py::test_warm_reboot` we have next error:
> root:__init__.py:40 Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
>     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
>   File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
>     return self._hookexec(self, self.get_hookimpls(), kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
>     return self._inner_hookexec(hook, methods, kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
>     return outcome.get_result()
>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
>     _reraise(*ex)  # noqa
>   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
>     res = hook_impl.function(*args)
>   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
>     testfunction(**testargs)
>   File "/var/user/jenkins/sonic-mgmt/tests/platform_tests/test_advanced_reboot.py", line 74, in test_warm_reboot
>     advancedReboot.runRebootTestcase()
>   File "/var/user/jenkins/sonic-mgmt/tests/common/fixtures/advanced_reboot.py", line 575, in runRebootTestcase
>     return self.runRebootTest()
>   File "/var/user/jenkins/sonic-mgmt/tests/common/fixtures/advanced_reboot.py", line 550, in runRebootTest
>     reboot_oper=rebootOper, log_dir=log_dir)
>   File "/var/user/jenkins/sonic-mgmt/tests/platform_tests/conftest.py", line 532, in post_reboot_analysis
>     verify_mac_jumping(test_name, analyze_result, verification_errors)
>   File "/var/user/jenkins/sonic-mgmt/tests/platform_tests/conftest.py", line 336, in verify_mac_jumping
>     if "mac_jump" in test_name:
>   File "/var/user/jenkins/sonic-mgmt/tests/platform_tests/conftest.py", line 32, in _parse_timestamp
>     time = datetime.strptime(timestamp, _FMT)_
> TypeError: strptime() argument 1 must be string, not None

**DESCRIPTION:**

Issue reproduces when we have **_SAI_FDB_EVENT_LEARNED_** before  **_FDB_AGING_DISABLE_START_**.
Test detects event but `timestamp` will be empty:
```
        "FDB_EVENT_OTHER_MAC_EXPIRY": {
            "timestamp": {}, 
            "Start count": 1, 
            "time_taken": "N/A"
        }, 
```

**FIX:**
Verify  `mac_expiry_start` before using

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Fail SONiC TC.
#### How did you do it?
Verify `mac_expiry_start` before using

#### How did you verify/test it?
 Run `platform_tests/test_advanced_reboot.py::test_warm_reboot`

### CODE REVIEW

**Review by msosyak — APPROVED** [review]

**Review by msosyak — APPROVED** [review]

**Comment by bratashX** [comment]
@wangxin @liat-grozovik @gechiang please review and merge

**Comment by bratashX** [comment]
@vcheketx @SavchukRomanLv please rewiew

**Review by OleksandrKozodoi — APPROVED** [review]

**Comment by gechiang** [comment]
@vaibhavhd can you help review this change?
Thanks!

**Review by vcheketx — APPROVED** [review]

**Comment by vaibhavhd** [comment]
This fix prevents the test from breaking (which is a good part), however, it prevents the underlying failure from being exposed., We are now bypassing the check for MAC expiry detection when MAC ageing is disabled.

We should rather find out why the timestamp is not obtained. Does it need regex update which is preventing the loganalyzer from obtaining the correct pattern?


> About this: ```Issue reproduces when we have SAI_FDB_EVENT_LEARNED before FDB_AGING_DISABLE_START.
Test detects event but timestamp will be empty:
        "FDB_EVENT_OTHER_MAC_EXPIRY": {
            "timestamp": {}, 
            "Start count": 1, 
            "time_taken": "N/A"
        }, 


I don't think this is expected, right? FDB learning should not happen when FDB learning is disabled.

**Comment by bratashX** [comment]
> This fix prevents the test from breaking (which is a good part), however, it prevents the underlying failure from being exposed., We are now bypassing the check for MAC expiry detection when MAC ageing is disabled.
> 
> We should rather find out why the timestamp is not obtained. Does it need regex update which is preventing the loganalyzer from obtaining the correct pattern?
> 
> About this:
> 
> > Issue reproduces when we have SAI_FDB_EVENT_LEARNED before FDB_AGING_DISABLE_START.
> > Test detects event but timestamp will be empty:
> > "FDB_EVENT_OTHER_MAC_EXPIRY": {
> > "timestamp": {},
> > "Start count": 1,
> > "time_taken": "N/A"
> > },
> 
> I don't think this is expected, right? FDB learning should not happen when FDB learning is disabled.

Test before saving timestamp for **_SAI_FDB_EVENT_LEARNED_** (`mac_expiry_start`) compere it with **_FDB_AGING_DISABLE_START_** time. 

[Code:](https://github.com/bratashX/sonic-mgmt/blob/fix_mac_jump_verification/tests/platform_tests/conftest.py#L285-L294)
```
                    if "FDB_EVENT_OTHER_MAC_EXPIRY" in state_name or "FDB_EVENT_SCAPY_MAC_EXPIRY" in state_name:
                        fdb_aging_disable_start = result.get("time_span", {}).get("FDB_AGING_DISABLE", {})\
                            .get("timestamp", {}).get("Start")
                        if not fdb_aging_disable_start:
                            break
                        first_after_offset = fdb_aging_disable_start
                    else:
                        first_after_offset = result.get("reboot_time", {}).get("timestamp", {}).get("Start")
                    state_times = get_state_times(timestamp, state, offset_from_kexec,
                                                  first_after_offset=first_after_offset)
```

[Code](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/conftest.py#L102-L105):

```
def get_state_times(timestamp, state, state_times, first_after_offset=None):
. . . . . . . .

# capture the first occurence as the one after offset timestamp and ignore the ones before
# this is useful to find time after a specific instance, for eg. - kexec time or FDB disable time.        
if _parse_timestamp(first_after_offset) < _parse_timestamp(time):
            timestamps[state_status] = time 
```
If **_SAI_FDB_EVENT_LEARNED_** is before **_FDB_AGING_DISABLE_START_** test detects the event but timestamp will be empty (_this behavior designed in the test_).

I agree, my PR is a workaround for fixing test errors, but for complex fix need to change test logic.
Can we merge this PR as a hotfix, and open a new one with test refactoring?

**Comment by bratashX** [comment]
@vaibhavhd could you please check last comment

**Comment by vaibhavhd** [comment]
I am in favor of a more complete fix. This hot fix not just fixes the TypeError, but along with that ignores a key check criterion of the mac jump test.

Alternatively, you could still handle this TypeError (as in this PR) but also fail the testcase when the type is detected as None. That way the test will continue to fail gracefully. A future PR should fix that failure.

**Pull request closed without merging**
