### PR TITLE
Fix qos/test_qos_dscp_mapping.py

### PR DESCRIPTION
**Pull request by vkjammala-arista**
### Description of PR

Summary: Fix qos/test_qos_dscp_mapping.py failures
Fixes # [aristanetworks/sonic-qual.msft#132](https://github.com/aristanetworks/sonic-qual.msft/issues/132)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?

This test is mainly failing due to:
   - Sending 10K packets at once on a ptf interface is sometimes causing nnpy socket to be non-functional for a moment and connection is getting timedout (logic to timeout is introduced by https://github.com/p4lang/ptf/pull/183).
   - Sometimes egress_queue_count on queue 7 is way greater than no of packets being sent and the queue_count is not within the TOLERANCE, this could be due to protocol packets.
   - Test is not enhanced to be run on dualtor topologies (packets are going to unexpected ToR).
   - Fixtures "upstream_links" and "downstream_links" are always referring to upper ToR, thus return values of these fixtures is not really considering the ToR type and causing failures.
   
#### How did you do it?
Fixes involve adding right fixtures to the test methods (to consider dualtor topologies) and minor changes to address above issues.

#### How did you verify/test it?
With the fix test is passing well (earlier it was failing most of the times with one or other reason). Verified the fix on Arista-7260CX3-C64 202311 branch.

### CODE REVIEW

**Comment by wsycqyz** [comment]
The pre-commit check is mandatory. Please check.

**Comment by vkjammala-arista** [comment]
> The pre-commit check is mandatory. Please check.



> The pre-commit check is mandatory. Please check.

Thanks took care of this.

**Comment by wsycqyz** [comment]
@XuChen-MSFT  FYI

**Comment by wsycqyz** [comment]
@vkjammala-arista Do you need to backport to 202311 branch?

**Review by wsycqyz — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @XuChen-MSFT @developfast could you help to review this PR also?

**Comment by vkjammala-arista** [comment]
> @vkjammala-arista Do you need to backport to 202311 branch?

Hi @wsycqyz, we need this fix in 202311 as well (as mentioned in description). Thanks!

**Comment by StormLiangMS** [comment]
hi @vkjammala-arista, could you file separate PR for 202305, it is a conflict.

**Comment by vkjammala-arista** [comment]
> hi @vkjammala-arista, could you file separate PR for 202305, it is a conflict.

Hi @StormLiangMS, this change is NA for 202305 (test doesn't exist there). Thanks!

**Pull request merged**
