### PR TITLE
 Fix the  ptf_test_port_map.json for chassis/multi-asic

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

1. Fix the `ptf_test_port_map_active_active` and `ptf_test_port_map` to get correct ptf_port to asic_idx mapping by using only the Front panel ports (ignoring all backplane and special ports)

How I verify:

Manual run.

### CODE REVIEW

**Comment by abdosi** [comment]
cc @vperumal . wondering why we did not catch this earlier ?

@bingwang-ms i have made `ptf_test_port_map` call `ptf_test_port_map_active_active`. Please see if that is fine

**Comment by bingwang-ms** [comment]
> cc @vperumal . wondering why we did not catch this earlier ?
> 
> @bingwang-ms i have made `ptf_test_port_map` call `ptf_test_port_map_active_active`. Please see if that is fine

Sorry, I don't understand why we call the fixture  `ptf_test_port_map_active_active`  for all topology. The fixture `ptf_test_port_map_active_active` was introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/6006. It's mainly for dualtor active-active mode. If the fixture is updated somehow, I'm afraid there would be a bunch of test failure.
Add @lolyu for comments.

**Comment by abdosi** [comment]
> > cc @vperumal . wondering why we did not catch this earlier ?
> > @bingwang-ms i have made `ptf_test_port_map` call `ptf_test_port_map_active_active`. Please see if that is fine
> 
> Sorry, I don't understand why we call the fixture `ptf_test_port_map_active_active` for all topology. The fixture `ptf_test_port_map_active_active` was introduced by PR #6006. It's mainly for dualtor active-active mode. If the fixture is updated somehow, I'm afraid there would be a bunch of test failure. Add @lolyu for comments.

@bingwang-ms there was code duplication in both of this API. I am calling like this now. will this not work ?

image

**Comment by bingwang-ms** [comment]
> > > cc @vperumal . wondering why we did not catch this earlier ?
> > > @bingwang-ms i have made `ptf_test_port_map` call `ptf_test_port_map_active_active`. Please see if that is fine
> > 
> > 
> > Sorry, I don't understand why we call the fixture `ptf_test_port_map_active_active` for all topology. The fixture `ptf_test_port_map_active_active` was introduced by PR #6006. It's mainly for dualtor active-active mode. If the fixture is updated somehow, I'm afraid there would be a bunch of test failure. Add @lolyu for comments.
> 
> @bingwang-ms there was code duplication in both of this API. I am calling like this now. will this not work ?
> 
> image



> > > cc @vperumal . wondering why we did not catch this earlier ?
> > > @bingwang-ms i have made `ptf_test_port_map` call `ptf_test_port_map_active_active`. Please see if that is fine
> > 
> > 
> > Sorry, I don't understand why we call the fixture `ptf_test_port_map_active_active` for all topology. The fixture `ptf_test_port_map_active_active` was introduced by PR #6006. It's mainly for dualtor active-active mode. If the fixture is updated somehow, I'm afraid there would be a bunch of test failure. Add @lolyu for comments.
> 
> @bingwang-ms there was code duplication in both of this API. I am calling like this now. will this not work ?
> 
> image

It's hard to say. The code of `ptf_test_port_map` and `ptf_test_port_map_active_active` are not exactly the same. The fixture `ptf_test_port_map_active_active` is for dualtor active-active mode. I don't know if it can work on other topology. 
Another concern is, if the fixture `ptf_test_port_map_active_active` is updated to accommodate the dualtor active-active change, we may see regressions in other topology.

**Comment by vperumal** [comment]
Hi @abdosi, to my knowledge we haven't hit any issues because of it. Did you hit any issue ? which script did you see the problem- so that I can cross check on our side.

**Review by SuvarnaMeenakshi — APPROVED** [review]

**Comment by abdosi** [comment]
> Hi @abdosi, to my knowledge we haven't hit any issues because of it. Did you hit any issue ? which script did you see the problem- so that I can cross check on our side.

fib/ip-decap test case is failing because of this.

**Comment by vperumal** [comment]
> > Hi @abdosi, to my knowledge we haven't hit any issues because of it. Did you hit any issue ? which script did you see the problem- so that I can cross check on our side.
> 
> fib/ip-decap test case is failing because of this.

Hi @abdosi , In our case decap passed and even most of fib tcs passed

**Pull request merged**
