### PR TITLE
[chassis] add check on every linecard as well after every reboot on chassis sup

### PR DESCRIPTION
**Pull request by wenyiz2021**
### Description of PR

There are issues seen on pipeline run, where test_continuous_reboot on a linecard after test_continuous_reboot on SUP failed.
While running test_continuous_reboot on any single linecard succeeded.
It is because after SUP reboot, we didn't check linecards' critical services and interfaces, but only check SUP. It could lead to either following reboot tests to fail or have crash, if linecard isn't back and we perform reboot again on it.
Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### How did you verify/test it?
ran this on Arista pipeline
#### Any platform specific information?
test will only be changed for chassis

### CODE REVIEW

**Comment by kenneth-arista** [comment]
Looks good to me. @patrickmacarthur can you also take a look?

**Review by kenneth-arista — APPROVED** [review]

**Comment by kenneth-arista** [comment]
In the community chassis meeting last week, https://github.com/sonic-net/sonic-mgmt/pull/7085 was referenced. @wenyiz2021 how should we proceed? Proceed with your PR or the other one?

**Comment by patrickmacarthur** [comment]
> Looks good to me. @patrickmacarthur can you also take a look?

Also LGTM.

**Comment by abdosi** [comment]
@vperumal please review this. It's similar to your PR https://github.com/sonic-net/sonic-mgmt/pull/7085/files but some more updates.

**Comment by vperumal** [comment]
> @vperumal please review this. It's similar to your PR https://github.com/sonic-net/sonic-mgmt/pull/7085/files but some more updates.

Hi @abdosi, Both PR's are the same but I am fine, if we want to merge this PR, I can close the other PR

**Comment by vperumal** [comment]
@wenyiz2021 - I am going to close #7085 since both PRs are similar to each other. This PR looks good to me.

**Comment by wenyiz2021** [comment]
> @wenyiz2021 - I am going to close #7085 since both PRs are similar to each other. This PR looks good to me.

@vperumal thanks. I think the other PR has a minor issue to be address that added arguments in `reboot_and_check` but did not make them default.

**Comment by vperumal** [comment]
> > @wenyiz2021 - I am going to close #7085 since both PRs are similar to each other. This PR looks good to me.
> 
> @vperumal thanks. I think the other PR has a minor issue to be address that added arguments in `reboot_and_check` but did not make them default.

Yes @wenyiz2021, saw your review comments, I saw that you have taken care of it here, so decided best that we keep your PR.

**Review by abdosi — APPROVED** [review]

**Pull request merged**
