### PR TITLE
Stability of Voq tests (#4951, #4953)

### PR DESCRIPTION
**Pull request by mannytaheri**
### Description of PR
This is the same PR as PR#  https://github.com/sonic-net/sonic-mgmt/pull/8468
Please see PR# 4951 and 4953 for details.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

In VoQ tests against a T2 VoQ chassis we sometimes see 5-6 seconds delay before which the ping to the neighbor works after the port on the DUT is brought up as part of the voq link flap tests.

Currently, when we bring the link up on either the DUT or the fanout, we would only check if the link is up on the DUT.

What we see is that even though the DUT becomes operationally up, the remote peer doesn't become operationally up right away at the same time. It seems to take 2-6 seconds more than the DUT port. If the port is not up on the fanout, then the packets from the DUT is not forwarded to the testbed server, and thus the ping fails.

#### How did you do it?
Fix is to check the link status on the fanout port as well, whenever we bring a port up.

#### How did you verify/test it?
Fix is to check the link status on the fanout port as well, whenever we bring a port up.

### CODE REVIEW

**Comment by mannytaheri** [comment]
@arlakshm @wangxin @mssonicbld   This is the same as PR #8468 which was already merged to master.  Created this new PR due to Cherry Pick Conflict_202205.

**Comment by rlhui** [comment]
@arlakshm  please help review/approve this?  thanks

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
@wangxin please help merge this PR in 202205.

**Comment by yejianquan** [comment]
Hi @arlakshm , this PR still has conflicts, it's may because other PRs are merged, please resolved the conflict, thanks!

**Comment by mannytaheri** [comment]
A new PR will be created for this

**Pull request closed without merging**
