### PR TITLE
Add pkts_num_hysteresis for new rx cgm profile

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

The fix of https://migsonic.atlassian.net/browse/MIGSMSFT-388 introduces xon hysteresis, qos params in xon testcases need to be updated.

Summary:
Fixes # (issue)
Add pkts_num_hysteresis for new rx cgm profile.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
Update qos params used in xon testcases.

#### How did you do it?
Add pkts_num_hysteresis in file qos_param_generator.py, qos_params.gb.yaml and qos_params.pac.yaml.

#### How did you verify/test it?
Run it on testbed.

T1-100G
```
============================================================================ PASSES =============================================================================
______________________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_1] ______________________________________________________
______________________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_2] ______________________________________________________
---------------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit_2024-05-10-00-06-29.xml ----------------------------
INFO:root:Can not get Allure report URL. Please check logs
-------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------
00:23:30 init.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
==================================================================== short test summary info ====================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2]
SKIPPED [2] qos/test_qos_sai.py:600: Additional DSCPs are not supported on non-dual ToR ports
SKIPPED [4] qos/qos_sai_base.py:613: Did not find any frontend node that is multi-asic - so can't run single_dut_multi_asic tests
SKIPPED [4] qos/qos_sai_base.py:620: multi-dut is not supported on T1 topologies
===================================================== 2 passed, 10 skipped, 1 warning in 1019.97s (0:16:59) =====================================================
```
T2 Vanguard:
```
===================================================================== PASSES ======================================================================
_______________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_1] _______________________________________________
_______________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_2] _______________________________________________
--------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit_2024-05-14-05-30-43.xml ---------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------
05:44:19 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
============================================================= short test summary info =============================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2]
SKIPPED [2] qos/test_qos_sai.py:599: Additional DSCPs are not supported on non-dual ToR ports
=============================================== 2 passed, 2 skipped, 1 warning in 815.24s (0:13:35) ===============================================
```

T2 pacific:
```
===================================================================== PASSES ======================================================================
_______________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_1] _______________________________________________
_______________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_2] _______________________________________________
--------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit_2024-05-14-06-12-17.xml ---------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------
06:28:47 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
============================================================= short test summary info =============================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2]
SKIPPED [2] qos/test_qos_sai.py:599: Additional DSCPs are not supported on non-dual ToR ports
=============================================== 2 passed, 2 skipped, 1 warning in 988.42s (0:16:28) ===============================================
```
T2 lancer:
```
===================================================================== PASSES ======================================================================
_______________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_1] _______________________________________________
_______________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_2] _______________________________________________
--------------------- generated xml file: /tmp/qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit_2024-05-14-17-57-03.xml ---------------------
INFO:root:Can not get Allure report URL. Please check logs
------------------------------------------------------------- live log sessionfinish --------------------------------------------------------------
18:10:46 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
============================================================= short test summary info =============================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2]
SKIPPED [2] qos/test_qos_sai.py:599: Additional DSCPs are not supported on non-dual ToR ports
=============================================== 2 passed, 2 skipped, 1 warning in 821.44s (0:13:41) ===============================================
sonic@sonic-ucs-m5-1:/data/tests$ 
```

### CODE REVIEW

**Comment by zhixzhu** [comment]
@abdosi Could you help trigger a rerun? prepare_testbed failed.

**Comment by wsycqyz** [comment]
Trigger rerun failed jobs.

**Review by wsycqyz — APPROVED** [review]

**Comment by wsycqyz** [comment]
I am ok with this PR.

**Review by alpeshspatel — APPROVED** [review]

**Review by kevinskwang — APPROVED** [review]

**Comment by zhixzhu** [comment]
@abdosi Could you add label "Request for 202305 branch" to this PR? Raghav is hitting xon case failure using 202305 branch.

**Comment by wsycqyz** [comment]
@kevinskwang Please help approve for 202305 branch as @zhixzhu requested.

**Comment by XuChen-MSFT** [comment]
@kevinskwang  this dependency of https://github.com/sonic-net/sonic-mgmt/pull/14203  "Cisco-8111: adjust reduced_pause_thr to hardware value"
need to cherry pick this PR first.

**Pull request merged**
