### PR TITLE
nhop_group: Fix expected mac address dictionary for Cisco 8122 

### PR DESCRIPTION
**Pull request by ranepbhagyashree**
### Description of PR
Changes to fix failing testcase: test_nhop_group_member_order_capability for Cisco 8122 platform
Created a new dictionary for gr2 asic with the expected mac addresses for 0-49 flows

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [X] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### How did you verify/test it?
Ran sonic-mgmt test suite on Cisco 8122

#### Any platform specific information?
Specific to Cisco 8122

### CODE REVIEW

**Review by bpar9 — APPROVED** [review]
lgtm

**Comment by bpar9** [comment]
can you remove the internal platform names from the verification section

**Comment by ranepbhagyashree** [comment]
> can you remove the internal platform names from the verification section

done

**Review by bpar9 — APPROVED** [review]

**Comment by vperumal** [comment]
@yejianquan -  can we backport this PR to 202311 branch. We need this PR for our fixed boxes

**Comment by yejianquan** [comment]
> @yejianquan - can we backport this PR to 202311 branch. We need this PR for our fixed boxes

Hi @StormLiangMS (release manager of 202311) could you help to take a look?

**Pull request merged**
