### PR TITLE
[qos/t2] support single ASIC linecards

### PR DESCRIPTION
**Pull request by kenneth-arista**
### Description of PR

https://github.com/sonic-net/sonic-mgmt/pull/11000 only can handle multi-asic linecards. This fixes the limitation foro single ASIC linecards.

Summary:
Fixes #  https://github.com/sonic-net/sonic-mgmt/issues/13676

### Type of change
- [ X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [X] 202405

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@wenyiz2021 @arlakshm @ysmanman for awareness

**Review by arlakshm — APPROVED** [review]

**Review by wenyiz2021 — APPROVED** [review]

**Comment by kenneth-arista** [comment]
@wenyiz2021 can you help merge this fix?

**Comment by kenneth-arista** [comment]
@wenyiz2021 can you help add a label to `Request for 202405 branch`?

**Comment by wenyiz2021** [comment]
@yejianquan can you help port this to 202405? thanks

**Pull request merged**
