### PR TITLE
Fix missing import re in platform_tests

### PR DESCRIPTION
**Pull request by andywongarista**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Fix missing imports

### CODE REVIEW

**Comment by wangxin** [comment]
@andywongarista The change looks good to me. Can you sign the eacyCLA and do a rebase to this branch? Then we can proceed with merging this PR.

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
@andywongarista Another thing, is this a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description?

**Review by wsycqyz — APPROVED** [review]
LGTM

**Comment by andywongarista** [comment]
@wangxin sorry for the late reply. This isn't a backport, but I realized #7360 does something similar. Perhaps we should backport that PR instead?

**Comment by wangxin** [comment]
@andywongarista Backporting #7360 would be too difficult. If the issue fixed by this PR is not in master branch, we can merge this PR to 202205 branch. 
BTW, can you sign the EasyCLA? Otherwise, the failed EasyCLA check blocks merging.

**Comment by andywongarista** [comment]
@wangxin I think the EasyCLA issue is resolved now. Thanks for following up

**Pull request merged**
