### PR TITLE
[sFlow] Fix sFlow TC and improve execution time

### LINKED ISSUE #5938: [sFlow] after move the slow ptf test to run with python3, the test which can finish with 50s, now it will take 5161s
**Description**
After move the ptftests/sflow_test.py to run with python3, the test which will be finished in 1 mins in python2, will take almost 2 hrs.

**Steps to reproduce the issue:**
1. Run the sflow test, and add breakpoint before the ptf test start
2. run the ptf test on the ptf docker with python2, and with python3.
    /root/env-python3/bin/ptf --test-dir ptftests/py3 sflow_test --platform-dir ptftests --platform remote -t "enabled_sflow_interfaces=['Ethernet64', 'Ethernet0', 'Ethernet80', 'Ethernet16'];active_collectors=['collector0'];dst_port=8;testbed_type='t0-64';router_mac='1c:34:da:c9:60:00';sflow_ports_file='/tmp/sflow_ports.json';agent_id='10.1.0.32'" --relax --debug info --log-file /tmp/TestSflowCollector.test_sflow_config.log --socket-recv-size 16384

ptf --test-dir ptftests/py3 sflow_test --platform-dir ptftests --platform remote -t "enabled_sflow_interfaces=['Ethernet64', 'Ethernet0', 'Ethernet80', 'Ethernet16'];active_collectors=['collector0'];dst_port=8;testbed_type='t0-64';router_mac='1c:34:da:c9:60:00';sflow_ports_file='/tmp/sflow_ports.json';agent_id='10.1.0.32'" --relax --debug info --log-file /tmp/TestSflowCollector.test_sflow_config.log --socket-recv-size 16384
 
4.

**Describe the results you received:**
root@f3b7c6559aa7:~# ptf --test-dir ptftests/py3 sflow_test --platform-dir ptftests --platform remote -t "enabled_sflow_interfaces=['Ethernet64', 'Ethernet0', 'Ethernet80', 'Ethernet16'];active_collectors=['collector0'];dst_port=8;testbed_type='t0-64';router_mac='1c:34:da:c9:60:00';sflow_ports_file='/tmp/sflow_ports.json';agent_id='10.1.0.32'" --relax --debug info --log-file /tmp/TestSflowCollector.test_sflow_config.log --socket-recv-size 16384
ptftests/py3/macsec.py:3: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  import cryptography.exceptions
sflow_test.SflowTest ... ok

----------------------------------------------------------------------
**Ran 1 test in 50.084s**

OK

root@f3b7c6559aa7:~# /root/env-python3/bin/ptf --test-dir ptftests/py3 sflow_test --platform-dir ptftests --platform remote -t "enabled_sflow_interfaces=['Ethernet64', 'Ethernet0', 'Ethernet80', 'Ethernet16'];active_collectors=['collector0'];dst_port=8;testbed_type='t0-64';router_mac='1c:34:da:c9:60:00';sflow_ports_file='/tmp/sflow_ports.json';agent_id='10.1.0.32'" --relax --debug info --log-file /tmp/TestSflowCollector.test_sflow_config.log --socket-recv-size 16384
/root/env-python3/bin/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using packet manipulation module: ptf.packet_scapy
/root/env-python3/lib/python3.7/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/root/env-python3/lib/python3.7/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
sflow_test.SflowTest ... ok

----------------------------------------------------------------------
**Ran 1 test in 5161.308s**

OK

**Describe the results you expected:**

The test execution time should not increase after swtiching to python3
**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

### PR DESCRIPTION
**Pull request by AndriiLozovyi**
Signed-off-by: Andrii-Yosafat Lozovyi <andrii-yosafatx.lozovyi@intel.com>

### Description of PR

Summary:  After sFlow ptftests migrated to python3, executing time of a single sFlow ptftest increased from 50-80 seconds to 5000 seconds. As investigation showed, executing time of function that send pkt's increased significantly.

When executed using `python3 `it takes about ~11-18 seconds to send 512 pkt's:
```
12:45:01.563  root      : INFO    : Sending 512 pkts to Ethernet124  time_it_took_to_send 0:00:12.623860
12:45:12.655  root      : INFO    : Sending 512 pkts to Ethernet112  time_it_took_to_send 0:00:11.087558
12:45:28.359  root      : INFO    : Sending 512 pkts to Ethernet120  time_it_took_to_send 0:00:15.700587
12:45:41.719  root      : INFO    : Sending 512 pkts to Ethernet116  time_it_took_to_send 0:00:13.351208
12:45:54.629  root      : INFO    : Sending 512 pkts to Ethernet124  time_it_took_to_send 0:00:12.899076
12:46:07.386  root      : INFO    : Sending 512 pkts to Ethernet112  time_it_took_to_send 0:00:12.748628
12:46:21.228  root      : INFO    : Sending 512 pkts to Ethernet120  time_it_took_to_send 0:00:13.833997 
```

When executed using `python2`:
```
12:25:54.563  root      : INFO    : Sending 512 pkts to Ethernet116  time_it_took_to_send 0:00:00.042150
12:25:54.612  root      : INFO    : Sending 512 pkts to Ethernet124  time_it_took_to_send 0:00:00.046037
12:25:54.738  root      : INFO    : Sending 512 pkts to Ethernet112  time_it_took_to_send 0:00:00.123535
12:25:54.876  root      : INFO    : Sending 512 pkts to Ethernet120  time_it_took_to_send 0:00:00.133869
12:25:55.034  root      : INFO    : Sending 512 pkts to Ethernet116  time_it_took_to_send 0:00:00.153847
12:25:55.165  root      : INFO    : Sending 512 pkts to Ethernet124  time_it_took_to_send 0:00:00.127286
12:25:55.316  root      : INFO    : Sending 512 pkts to Ethernet112  time_it_took_to_send 0:00:00.147911
12:25:55.465  root      : INFO    : Sending 512 pkts to Ethernet120  time_it_took_to_send 0:00:00.144826
```

It looks like the problem was in difference of how threads work in python 2 vs python3, by updating TC logic with using events in threads this issue was fixed. Also removed unused import and fixed some bad indentation.
Fixes #5938 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
As for now 1 sFlow ptftest can run around 5000 seconds, which significantly increase executing time of Sflow suite.
PR decrease execution time of sFlow TC on python3 by updating TC logic.
#### How did you verify/test it?
Run sFlow ptftest with changes on python3 and measure executing's time of send function:

```
11:09:26.212  root      : INFO    : send pkt 512 from Ethernet116 time_it_took_to_send 0:00:00.053198
11:09:26.266  root      : INFO    : send pkt 512 from Ethernet124 time_it_took_to_send 0:00:00.051653
11:09:26.300  root      : INFO    : send pkt 512 from Ethernet112 time_it_took_to_send 0:00:00.032249
11:09:26.333  root      : INFO    : send pkt 512 from Ethernet120 time_it_took_to_send 0:00:00.031033
11:09:26.364  root      : INFO    : send pkt 512 from Ethernet116 time_it_took_to_send 0:00:00.029478
11:09:26.402  root      : INFO    : send pkt 512 from Ethernet124 time_it_took_to_send 0:00:00.035845
11:09:26.458  root      : INFO    : send pkt 512 from Ethernet112 time_it_took_to_send 0:00:00.053826
11:09:26.496  root      : INFO    : send pkt 512 from Ethernet120 time_it_took_to_send 0:00:00.035140
```
#### Any platform specific information?
```
SONiC Software Version: SONiC.master.127871-dirty-20220728.095752
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: 746e05210
Build date: Thu Jul 28 14:13:30 UTC 2022
Built by: AzDevOps@sonic-build-workers-001UGB
Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
```

### CODE REVIEW

**Comment by AndriiLozovyi** [comment]
@ZhaohuiS 
Could you please take a look?

**Comment by ZhaohuiS** [comment]
@AndriiLozovyi could you please solve the LGMT alerts?

**Comment by AndriiLozovyi** [comment]
@ZhaohuiS
LGTM states that this PR fixes 14 alerts

**Comment by AndriiLozovyi** [comment]
@wangxin @yxieca could you please take a look?

**Review by yxieca — APPROVED** [review]

**Comment by AndriiLozovyi** [comment]
Could this be merged ?

**Pull request merged**
