### PR TITLE
Support pfcwd tests on KVM with partial configuration coverage

### PR DESCRIPTION
**Pull request by xwjiang-ms**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
Elastictest performs well in distribute running PR test in multiple KVMs, which support us to add more test scripts to PR checker.
But some traffic test can't be tested on KVM platform, we need to skip traffic test if needed
#### How did you do it?
This PR adds pfcwd tests to the KVM-based PR test framework with the following scope and modifications:
1. Excludes fanout switch-related configurations, which are not applicable in the KVM test environment.
2. Traffic tests have been intentionally skipped due to the limitations of running traffic in the KVM environment.

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by lipxu** [comment]
Thanks for implementing support for these cases on KVM platform, Just curious about the purpose of this PR, since as I remember, most or all of the PFCWD failure cases were related to the PFC generation. if KVM platform does not support PFC generation, It might not be very helpful in identifying the failures in advance. 
If we want to use PR test to identify the PFCWD related issue in advance, such as configuration failures, CLI commands output failures, etc, I suggest introducing a new PFCWD basic test case that does not invlove any HW which could run on KVM platform, thanks.

**Review by lipxu — APPROVED** [review]

**Comment by xwjiang-ms** [comment]
> Thanks for implementing support for these cases on KVM platform, Just curious about the purpose of this PR, since as I remember, most or all of the PFCWD failure cases were related to the PFC generation. if KVM platform does not support PFC generation, It might not be very helpful in identifying the failures in advance. If we want to use PR test to identify the PFCWD related issue in advance, such as configuration failures, CLI commands output failures, etc, I suggest introducing a new PFCWD basic test case that does not invlove any HW which could run on KVM platform, thanks.

I agree to add a new pfcwd basic test to test control plane, current shift left work would detect some config or key error, and prevent from merging into nightly.

**Review by wangxin — APPROVED** [review]

**Comment by kperumalbfn** [comment]
@xwjiang-ms Do we need this in 202411? If so, please fix the conflict.

**Comment by yutongzhang-microsoft** [comment]
Hi, @xwjiang-ms , can you help resolve the conflict

**Pull request merged**
