### PR TITLE
[sdn_tests]: Adding binding infra to pins_ondatra.

### PR DESCRIPTION
**Pull request by VSuryaprasad-HCL**
### Description of PR
- [sdn_tests]: Adding binding infra to pins_ondatra.

Summary:
- Adding binding infra to pins_ondatra.

Build Results:

          INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//pathz:pathz_proto:
          github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import 
          github.com/openconfig/gnsi/version/version.proto is unused.
          github.com/openconfig/gnsi/pathz/pathz.proto:25:1:
          warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
          INFO: Elapsed time: 625.193s, Critical Path: 105.81s
          INFO: 882 processes: 251 internal, 631 linux-sandbox.
          INFO: Build completed successfully, 882 total actions

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [-] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

### CODE REVIEW

**Review by parth-opensrc — APPROVED** [review]

**Comment by kishanps** [comment]
@vamsipunati Can you pls review and merge.

**Review by vamsipunati — APPROVED** [review]

**Comment by VSuryaprasad-HCL** [comment]
Build Results:
vsurya@eonms7vm1:~/APR-30-2024/sonic-mgmt/sdn_tests/pins_ondatra$ bazel build ...

      INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//pathz:pathz_proto:
      github.com/openconfig/gnsi/pathz/authorization.proto:43:1: warning: Import 
      github.com/openconfig/gnsi/version/version.proto is unused.
      github.com/openconfig/gnsi/pathz/pathz.proto:25:1:
      warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
      INFO: Elapsed time: 625.193s, Critical Path: 105.81s
      INFO: 882 processes: 251 internal, 631 linux-sandbox.
      INFO: Build completed successfully, 882 total actions

**Review by rkavitha-hcl — APPROVED** [review]

**Review by vamsipunati — APPROVED** [review]

**Comment by vamsipunati** [comment]
VSuryaprasad-HCL Can you address the following failure?

sdn_tests/pins_ondatra/infrastructure/binding/pins_backend.go
    ❯❱ go.lang.security.audit.crypto.missing-ssl-minversion.missing-ssl-minversion
          `MinVersion` is missing from this TLS configuration.  By default, TLS 1.2 is currently used as the
          minimum when acting as a client, and TLS 1.0 when acting as a server. General purpose web         
          applications should default to TLS 1.3 with all other protocols disabled.  Only where it is known 
          that a web server must support legacy clients with unsupported an insecure browsers (such as      
          Internet Explorer 10), it may be necessary to enable TLS 1.0 to provide support. Add `MinVersion: 
          tls.VersionTLS13' to the TLS configuration to bump the minimum version to TLS 1.3.                
          Details: https://sg.run/oxEN                                                                      
                                                                                                            
           ▶▶┆ Autofix ▶ tls.Config{ Certificates: []tls.Certificate{clientCert},RootCAs:      certPool,ServerName:
              serverName, MinVersion: tls.VersionTLS13 }                                                           
           [54](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:55)┆ b.configs[service] = &tls.Config{
           [55](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:56)┆    Certificates: []tls.Certificate{clientCert},
           [56](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:57)┆    RootCAs:      certPool,
           [57](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:58)┆    ServerName:   serverName,
           [58](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:59)┆ }
                            
  BLOCKING CODE RULES FIRED:
    go.lang.security.audit.crypto.missing-ssl-minversion.missing-ssl-minversion

**Comment by VSuryaprasad-HCL** [comment]
> VSuryaprasad-HCL Can you address the following failure?
> 
> sdn_tests/pins_ondatra/infrastructure/binding/pins_backend.go ❯❱ go.lang.security.audit.crypto.missing-ssl-minversion.missing-ssl-minversion `MinVersion` is missing from this TLS configuration. By default, TLS 1.2 is currently used as the minimum when acting as a client, and TLS 1.0 when acting as a server. General purpose web applications should default to TLS 1.3 with all other protocols disabled. Only where it is known that a web server must support legacy clients with unsupported an insecure browsers (such as Internet Explorer 10), it may be necessary to enable TLS 1.0 to provide support. Add `MinVersion: tls.VersionTLS13' to the TLS configuration to bump the minimum version to TLS 1.3. Details: https://sg.run/oxEN
> 
> ```
>        ▶▶┆ Autofix ▶ tls.Config{ Certificates: []tls.Certificate{clientCert},RootCAs:      certPool,ServerName:
>           serverName, MinVersion: tls.VersionTLS13 }                                                           
>        [54](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:55)┆ b.configs[service] = &tls.Config{
>        [55](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:56)┆    Certificates: []tls.Certificate{clientCert},
>        [56](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:57)┆    RootCAs:      certPool,
>        [57](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:58)┆    ServerName:   serverName,
>        [58](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:59)┆ }
> ```
> 
> BLOCKING CODE RULES FIRED: go.lang.security.audit.crypto.missing-ssl-minversion.missing-ssl-minversion

@vamsipunati I've addressed the failure and tried resloving it by adding MinVersion: tls.VersionTLS13 to the TLS in pins_backend.go, Also attaching the build info here.

        $ bazel build ...

         INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//pathz:pathz_proto:
         github.com/openconfig/gnsi/pathz/authorization.proto:43:1: 
         warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
         github.com/openconfig/gnsi/pathz/pathz.proto:25:1: 
         warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
         INFO: Elapsed time: 392.027s, Critical Path: 82.05s
         INFO: 882 processes: 251 internal, 631 linux-sandbox.
         INFO: Build completed successfully, 882 total actions

**Comment by kishanps** [comment]
> > VSuryaprasad-HCL Can you address the following failure?
> > sdn_tests/pins_ondatra/infrastructure/binding/pins_backend.go ❯❱ go.lang.security.audit.crypto.missing-ssl-minversion.missing-ssl-minversion `MinVersion` is missing from this TLS configuration. By default, TLS 1.2 is currently used as the minimum when acting as a client, and TLS 1.0 when acting as a server. General purpose web applications should default to TLS 1.3 with all other protocols disabled. Only where it is known that a web server must support legacy clients with unsupported an insecure browsers (such as Internet Explorer 10), it may be necessary to enable TLS 1.0 to provide support. Add `MinVersion: tls.VersionTLS13' to the TLS configuration to bump the minimum version to TLS 1.3. Details: https://sg.run/oxEN
> > ```
> >        ▶▶┆ Autofix ▶ tls.Config{ Certificates: []tls.Certificate{clientCert},RootCAs:      certPool,ServerName:
> >           serverName, MinVersion: tls.VersionTLS13 }                                                           
> >        [54](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:55)┆ b.configs[service] = &tls.Config{
> >        [55](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:56)┆    Certificates: []tls.Certificate{clientCert},
> >        [56](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:57)┆    RootCAs:      certPool,
> >        [57](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:58)┆    ServerName:   serverName,
> >        [58](https://github.com/sonic-net/sonic-mgmt/actions/runs/8983943613/job/24693677157?pr=12662#step:4:59)┆ }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > BLOCKING CODE RULES FIRED: go.lang.security.audit.crypto.missing-ssl-minversion.missing-ssl-minversion
> 
> @vamsipunati I've addressed the failure and tried resloving it by adding MinVersion: tls.VersionTLS13 to the TLS in pins_backend.go, Also attaching the build info here.
> 
> ```
>     $ bazel build ...
> 
>      INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//pathz:pathz_proto:
>      github.com/openconfig/gnsi/pathz/authorization.proto:43:1: 
>      warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
>      github.com/openconfig/gnsi/pathz/pathz.proto:25:1: 
>      warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
>      INFO: Elapsed time: 392.027s, Critical Path: 82.05s
>      INFO: 882 processes: 251 internal, 631 linux-sandbox.
>      INFO: Build completed successfully, 882 total actions
> ```

What is the current working dir of the bazel build cmd ? Can you make sure all targets are being built and tested where applicable. (check bazel build options here - https://bazel.build/run/build)
cc: @rkavitha-hcl

**Review by vamsipunati — APPROVED** [review]

**Review by vamsipunati — APPROVED** [review]

**Comment by VSuryaprasad-HCL** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/11771

**Pull request merged**
