### PR TITLE
Cisco: Fix the parameters to All-Port-Q-Watermark test.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
This PR:
1. Adds packet_size parameter that was missed out in qos.yml for topo-t2, and was not being used in the main code as well.
2. Changes the main script to consume all the qos.yml parameters for this test instead of doing them individually - to avoid the problems like point-1 in the future.

@abdosi : For review.

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@rraghav-cisco please fix the CLA signing part

**Comment by rraghav-cisco** [comment]
> * @akolamarvell .

Pls fix your CLA signing. It keeps blocking everybody else's commits.

**Comment by wangxin** [comment]
Hi @rraghav-cisco 
* To fix the easyCLA issue, can you squash all the commits of this PR to a single one, then force push the merged PR to the branch of this pull request (`rraghav-cisco:wm_q_wm_all_port-pkt-size`)? Otherwise, each author of the commits of this PR must have the easyCLA signed.
* Is this a backport of a master branch PR to 202205 branch? Can you mention the master branch PR ID in PR description?

**Comment by rraghav-cisco** [comment]
> Hi @rraghav-cisco
> 
> * To fix the easyCLA issue, can you squash all the commits of this PR to a single one, then force push the merged PR to the branch of this pull request (`rraghav-cisco:wm_q_wm_all_port-pkt-size`)? Otherwise, each author of the commits of this PR must have the easyCLA signed.
Hi @wangxin : There are only 5 commits for my PR, and all of them are mine. I have long ago signed the CLA. The CLA error comes from wrongly choosing master as the base. I have changed the base to 202205 afterwards. But the CLA error is still present.
> * Is this a backport of a master branch PR to 202205 branch? Can you mention the master branch PR ID in PR description?
No, this is a fresh PR on 202205. The master still doesn't have the required multi-asic code that is needed for my change.

**Comment by wangxin** [comment]
Hi @rraghav-cisco,

Change base branch is not able to fix the CLA issue. Need to squash the commits and force push to the branch of this PR to override the commits authored by others.

If master branch does not have multi-asic code, how to move on with future release to avoid duplicated work?

**Comment by rraghav-cisco** [comment]
> Hi @rraghav-cisco,
> 
> Change base branch is not able to fix the CLA issue. Need to squash the commits and force push to the branch of this PR to override the commits authored by others.
> 
> If master branch does not have multi-asic code, how to move on with future release to avoid duplicated work?

@wangxin , pls do squash if you have the permissions. I don't have any of the permissions.
Regarding the code to master, I am afraid we will have to redo all the PRs once the main multi-asic code is merged.

**Comment by wangxin** [comment]
@rraghav-cisco This PR is based on branch of your fork `rraghav-cisco:wm_q_wm_all_port-pkt-size`. You should have all the permissions.

The steps are to checkout this branch `rraghav-cisco:wm_q_wm_all_port-pkt-size` to your local machine, do the squash, then force push to `rraghav-cisco:wm_q_wm_all_port-pkt-size`.

**Comment by rraghav-cisco** [comment]
I have raised new PR, duplicate of the same: https://github.com/sonic-net/sonic-mgmt/pull/8958
I am closing this one.

**Pull request closed without merging**
