### PR TITLE
Configuring Community SNMP Credentials for SNMP TCs

### PR DESCRIPTION
**Pull request by agadia-cisco**
### Description of PR

Summary: The PR contains changes to `snmp/conftest.py` with logic to configure `snmp` credentials stored in `snmp.yml` for every host before running any test script. 

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR? 
If credentials in `snmp.yml` isn't configured, then the changes in PR configures them before running the tests and restores the original configuration after the TC execution.

#### How did you do it?
- `snmp/conftest.py` will now copy the `snmp.yml` from DUT to UCS (if DUT has `snmp.yml`) & then it will configure the SNMP credentials for every host via `sudo config snmp` command. The logic it configures is same as in `snmp_yml_to_configdb.py` script; where it checks whether the credentials in yml are configured in `config_db` or not, if the keys are configured but the values are different / the keys are not configured - then it will configure them. Before the test script execution, SNMP is configured, once the execution completes, it reverts the configuration that existed before.

#### How did you verify/test it?
- Run changes with `202405` image on a T0 setup without `snmp` credentials configured / with different credentials configured in image and `snmp` tests passed as expected in all scenarios.

### CODE REVIEW

**Comment by wsycqyz** [comment]
I believe this will go to 202405 branch?

**Comment by agadia-cisco** [comment]
> I believe this will go to 202405 branch?

This can go to `202405` & other branches too. Its more of a functionality than a TC.

**Comment by wsycqyz** [comment]
PR test stuck. Let me close and re-open the PR.

**Review by wsycqyz — APPROVED** [review]
lgtm

**Comment by agadia-cisco** [comment]
@yejianquan @wsycqyz Test Pipeline for `202405` Cherry Pick PR fails, because `create_checkpoint` & `rollback` are defined in different modules for `master` & `202405`. Have created a new PR with the change.

PR - https://github.com/sonic-net/sonic-mgmt/pull/15359

**Pull request merged**
