### PR TITLE
Fix portstat case

### PR DESCRIPTION
**Pull request by JibinBao**
There is a bug fix for "portstat -c -t filename" which changes the path of portstat status file, so  we need to update the relevant portstat test:
 https://github.com/sonic-net/sonic-utilities/pull/2232
 https://github.com/sonic-net/sonic-buildimage/pull/11244 
1. Orignal design: After running “portstat -c -t  filename”, status file will be created on the folder of /tmp/portstat-{uid}/{uid}-{filename}
2. New design: After running “portstat -c -t  filename”, status file will be created on the folder of /tmp/cache/portstat/{uid}-{filename}

Change-Id: Ia122a08b9a55a26fe6a299d74d2df1f1949c7ca3

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Fix test issue, because there is a relevant bug fix for the product.

#### How did you do it?
Change the test as the new desgin.
1. Orignal design: After running “portstat -c -t  filename”, status file will be created on the folder of /tmp/portstat-{uid}/{uid}-{filename}
2. New design: After running “portstat -c -t  filename”, status file will be created on the folder of /tmp/cache/portstat/{uid}-{filename}

#### How did you verify/test it?
Run the tests on the image with bug fix

#### Any platform specific information?
Any

#### Supported testbed topology if it's a new test case?
Any

### CODE REVIEW

**Review by roysr-nv — APPROVED** [review]

**Comment by JibinBao** [comment]
> Can we add backwards compatibility to this function? For example:
> 
> ```
> if int(re.search(r'20[0-9]{2}[0-1][0-9][0-3][0-9]', duthost.os_version)[0]) < 20220801:
>     path='/tmp/portstat-{uid}/{uid}-{filename}'
> else:
>     path='/tmp/cache/portstat/{uid}-{filename}'
> ```
The bug fixes: https://github.com/sonic-net/sonic-buildimage/pull/11244, https://github.com/sonic-net/sonic-utilities/pull/2232, which should be backported to branch 202205. Do we still to check the os version?

**Comment by romanvasylys** [comment]
> > Can we add backwards compatibility to this function? For example:
> > ```
> > if int(re.search(r'20[0-9]{2}[0-1][0-9][0-3][0-9]', duthost.os_version)[0]) < 20220801:
> >     path='/tmp/portstat-{uid}/{uid}-{filename}'
> > else:
> >     path='/tmp/cache/portstat/{uid}-{filename}'
> > ```
> 
> The bug fixes: [sonic-net/sonic-buildimage#11244](https://github.com/sonic-net/sonic-buildimage/pull/11244), [sonic-net/sonic-utilities#2232](https://github.com/sonic-net/sonic-utilities/pull/2232), which should be backported to branch 202205. For the master branch of sonic-mgmt, do we still check the os version?

Thank you for clarification. In case of fix being backported, OS version check is not needed.

**Review by arlakshm — APPROVED** [review]

**Comment by kbabujp** [comment]
Request for 202111 too.

**Pull request merged**
