### PR TITLE
Add QOS Params for Cisco 8111 Platform

### PR DESCRIPTION
**Pull request by mthatty**
### Description of PR

Add new qos config file for Cisco 8111 Platform - 400G / 300m
Add deep buffer option to Cisco qos config generator

Summary:

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
New platform support

#### How did you verify/test it?
Tested on Cisco 8111 T1

### CODE REVIEW

**Review by XuChen-MSFT — APPROVED** [review]
LGTM

**Comment by XuChen-MSFT** [comment]
@mthatty encounter pr-commit checking failure, as below:

```
$ pre-commit run flake8 --files tests/qos/files/cisco/qos_param_generator.py
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

tests/qos/files/cisco/qos_param_generator.py:125:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:126:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:127:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:128:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:129:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:130:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:132:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:133:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:134:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:135:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:136:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:137:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:140:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:141:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:142:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:143:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:144:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:145:41: E127 continuation line over-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:146:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:148:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:149:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:150:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:151:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:152:25: E128 continuation line under-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:153:41: E127 continuation line over-indented for visual indent
tests/qos/files/cisco/qos_param_generator.py:154:25: E128 continuation line under-indented for visual indent

flake8...............................................(no files to check)Skipped
```

Can you try to run "autopep8 --in-place --max-line-length=120 tests/qos/files/cisco/qos_param_generator.py" to resolve it?

**Review by XuChen-MSFT — APPROVED** [review]
pass manually 8111 test, looks good to me

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me

**Comment by StormLiangMS** [comment]
@XuChen-MSFT  do we need this on 202205?

**Pull request merged**
