### PR TITLE
[Mellanox] Update test_exceeding_headroom due to adding checker when enabling SHP

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Previously, when enabling SHP there is no checker even if  the accumulative headroom(shared headroom) of a port exceeds the maximum threshold. Currently, we have added the checker for mellanox device, so we update the existing case test_exceeding_headroom  to cover the scenarios enabling SHP.

The relevant PR: https://github.com/sonic-net/sonic-swss/pull/3272

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Add new case to cover new scenarios enabling SHP

#### How did you do it?
Update test_exceeding_headroom

#### How did you verify/test it?
Run test_exceeding_headroom on Mellanox device

#### Any platform specific information?
Mellanox

#### Supported testbed topology if it's a new test case?
Any

### CODE REVIEW

**Review by stephenxs — APPROVED** [review]

**Review by congh-nvidia — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
@kperumalbfn Can you help review?

**Comment by JibinBao** [comment]
Hi @kperumalbfn, Can you help review it?

**Pull request merged**
