### PR TITLE
limit parallel_run cct tasks number to avoid connection issue

### PR DESCRIPTION
**Pull request by jcaiMR**
Summary:
share same root cause as 
https://github.com/sonic-net/sonic-mgmt/pull/7897

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Description of PR
Fix test_bgp_gr_helper.py ansible connection issue during testing. 
On some T1 DUT, it has 24 neighbors, parallel run default has 24 ccts, and too many python process would has possibility cause ssh connection lost.
```
E Traceback:
E Traceback (most recent call last):
E File "/azp/_work/10/s/tests/common/helpers/parallel.py", line 31, in run
E Process.run(self)
E File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
E self._target(*self._args, **self._kwargs)
E File "/azp/_work/10/s/tests/common/helpers/parallel.py", line 243, in wrapper
E target(*args, **kwargs)
E File "/azp/_work/10/s/tests/bgp/conftest.py", line 102, in restore_nbr_gr
E node['host'].start_bgpd()
E File "/azp/_work/10/s/tests/common/devices/eos.py", line 178, in start_bgpd
E out = self.eos_config(lines=['no agent Rib shutdown'])
E File "/azp/_work/10/s/tests/common/devices/base.py", line 89, in _run
E raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E RunAnsibleModuleFail: run module eos_config failed, Ansible Results =>
E {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible-local-63098m7Qpg3/ansible-tmp-1681366820.21-63129-80728281144889/AnsiballZ_eos_config.py\", line 114, in <module>\n _ansiballz_main()\n File \"/tmp/ansible-local-63098m7Qpg3/ansible-tmp-1681366820.21-63129-80728281144889/AnsiballZ_eos_config.py\", line 106, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/tmp/ansible-local-63098m7Qpg3/ansible-tmp-1681366820.21-63129-80728281144889/AnsiballZ_eos_config.py\", line 49, in invoke_module\n imp.load_module('__main__', mod, module, MOD_DESC)\n File \"/tmp/ansible_eos_config_payload_5AxEWa/__main__.py\", line 518, in <module>\n File \"/tmp/ansible_eos_config_payload_5AxEWa/__main__.py\", line 397, in main\n File \"/tmp/ansible_eos_config_payload_5AxEWa/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py\", line 107, in get_connection\n File \"/tmp/ansible_eos_config_payload_5AxEWa/ansible_eos_config_payload.zip/ansible/module_utils/connection.py\", line 180, in __rpc__\n File \"/tmp/ansible_eos_config_payload_5AxEWa/ansible_eos_config_payload.zip/ansible/module_utils/connection.py\", line 139, in _exec_jsonrpc\nansible.module_utils.connection.ConnectionError: socket_path does not exist or cannot be found.\nSee the socket_path issue catergory in Network Debug and Troubleshooting Guide\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

#### How did you do it?
Limit parallel cct to 8.

#### How did you verify/test it?
Rerun script with multiple times

### CODE REVIEW

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by wangxin** [comment]
@jcaiMR Cherry-pick this PR to 202012 branch got conflicts. Can you create separate PR to 202012 branch to have this change?

**Pull request merged**
