### PR TITLE
Tests for VNET route precedence over BGP learnt route.

### PR DESCRIPTION
**Pull request by siqbal1986**
### Description of PR
These tests check the Vnet route precedence over bgp learnt route. 

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [X] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?

Currently if a route is learnt via BGP and added into the hardware, adding a VNET route results in failure. In addition due to a bug in VnetOrch, we start advertising the failed route, This prompts the BGP to remove the learnt route in favor of the local route. Since the Vnet Orch doesn't retry adding the Vnet route, This results in no route being present in the Hardware.

#### How I verified it
The fix is in PR https://github.com/sonic-net/sonic-swss/pull/3345
These tests cover various scenario in which VNET and BGP routes are added and removed in different order
#### Any platform specific information?
Cisco-8000 and mlnx.

### Documentation

There are 5 differnet scenarios which are checked. Each scenario is tested with with the following options.
Encap types [v4_inv4, v6_inV4]
Monitor Type [BFD, Custom]
Init NH state( BFD/monitor sessions for nexthops are initially up or not.)

1) test_vnet_route_after_bgp
        ADD BGP ROUTE on TOR
        Add VNET route
        Configure monitor (BFD or custom) with nexthop state (UP)
        Test with traffic
        Remove VNET route
        Remove BGP route
2) test_vnet_route_before_bgp_after_ep_up
        Add VNET route
        Configure monitor (BFD or custom) with nexthop state (UP)
        Add BGP ROUTE on TOR
        Test with traffic
        Remove VNET ROUTE
        Remove BGP route
3) test_vnet_route_bgp_removal_before_ep
        ADD BGP ROUTE on TOR
        Add VNET route
        Remove BGP route
        Configure monitor (BFD or custom) with nexthop state (UP)
        Test with traffic
        Remove VNET route
4) test_vnet_route_after_bgp_with_early_bgp_removal
        Add VNET route
        Add BGP ROUTE on TOR
        Configure monitor (BFD or custom) with nexthop state (UP)
        Test with traffic
        Remove BGP route
        Test with traffic
        Remove VNET route
5) test_vnet_route_after_bgp_multi_flap
         ADD BGP ROUTE on TOR
        Add VNET route
        Configure monitor (BFD or custom) with nexthop state (UP)
        Test with traffic
        flap the bfd/monitor sessions.
        Test with traffic
        Remove VNET route
        Remove BGP route

image

Note: Some scenarios are skipped because they are not valid.

### CODE REVIEW

**Review by prsunny — COMMENTED** [review]
Is the test covers for both IPv4 and IPv6 routes?

**Comment by siqbal1986** [comment]
These tests run for V4 in V4 and V6 in V4. I dont think we need this to run on Underlay V6. so both V4 and V6 routes are tested for all tests.

**Review by prsunny — APPROVED** [review]

**Comment by nhe-NV** [comment]
@siqbal1986 I see you provided the pass results.  which platfrom did you run the tests ?

**Comment by nhe-NV** [comment]
HI @siqbal1986 The test case could not pass when I run it, I check it, according to me looks like the vnet route added is not correct, I open a git hub issue for it, Can you help to check ? https://github.com/sonic-net/sonic-mgmt/issues/18594

**Pull request merged**
