### PR TITLE
Added missing changes of PR#7385 to fib_utils.py

### PR DESCRIPTION
**Pull request by mannytaheri**
### Description of PR
Added missing changes of PR #7385 to fib_utils.py

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Some changes of PR #7385 were missed in fib_utils.py.  We need to add the those changes for fib testcases to pass.

#### How did you do it?
Added the missed codes to fib_utils.py.

#### How did you verify/test it?
Tested fib testcases.

### CODE REVIEW

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/fixtures/fib_utils.py:136:121: E501 line too long (121 > 120 characters)<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by judyjoseph** [comment]
@mannytaheri do we need this fix still? I see the fib_tests passing atleast in 202205 branch

Could you check

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
This PR Fixes #8127

**Comment by arlakshm** [comment]
@mannytaheri, the precommit check is failing for the change in the PR. Can you please fix it.

**Comment by judyjoseph** [comment]
@mannytaheri please rebase this branch, the tests still fail

**Comment by mannytaheri** [comment]
> @mannytaheri, the precommit check is failing for the change in the PR. Can you please fix it.

Fixed

**Review by wangxin — APPROVED** [review]

**Pull request merged**
