### PR TITLE
cisco: qos-sai: Parameters for all_port_Q_watermark for t2 and move skip to common file

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Adding qos.yaml parameter (similar to topo-t1 using single flow) for topo-t2 for all port all Queue (0 to 6) Watermark Test. Also moving the skip condition to the common plugins location

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@XuChen-MSFT can you help merge this.

**Comment by abdosi** [comment]
@wangxin can you please help with merge of this.

**Comment by wangxin** [comment]
@rraghav-cisco Got conflicts after some other PRs are merged. Can you help resolve the new conflicts?

**Comment by rraghav-cisco** [comment]
@wangxin : Conflict resolved. Thanks.

**Comment by wangxin** [comment]
@rraghav-cisco Unfortunately, there are conflicts again. Can you help resolve?

**Comment by rraghav-cisco** [comment]
@wangxin : resolved conflicts.

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Pull request merged**
