### PR TITLE
Modify testbed-cli.sh related vm_topology.py to be compatible with both Python2/3

### PR DESCRIPTION
**Pull request by wsycqyz**
### Description of PR

Summary:
New sonic-mgmt-docker will come with Python3 as default.
testbed-cli.sh should modify to be compatible with both Python2 and Python3.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205

#### What is the motivation for this PR?
testbed-cli.sh should modify to be compatible with both Python2 and Python3.

#### How did you do it?
1. Use six package to deal with str/unicode error: 'str' object has no attribute 'decode'
2. Work around with a kernel issue: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1811241.html

#### How did you verify/test it?
With physical testbed, we can remove-topo, add-topo and deploy-mg.

### CODE REVIEW

**Review by lolyu — COMMENTED** [review]
Do we need to replace all the decode with `six.ensure_text`? There is a miss at https://github.com/sonic-net/sonic-mgmt/blob/faf092ccaaca18ac35a4c94e34aabce0dae9cb06/ansible/roles/vm_set/library/vm_topology.py#L1439

**Comment by wsycqyz** [comment]
@lolyu We don't need to replace all decode() with six.ensure_text(). Line 1439 is correct syntax both in Python2 and Python3.

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Review by wangxin — APPROVED** [review]

**Comment by wsycqyz** [comment]
202205 and 202012 branch will manually cherry-pick because obviously conflict.

**Pull request merged**
