### PR TITLE
sonic-mgmt: Assert if Arista Hwsku is not found in port_utils

### PR DESCRIPTION
**Pull request by aaronpayment**
### Description of PR
Assert to catch when a new hwsku is added so that the proper get_port_alias_to_name_map can be added.

This check will skip "FM" as Chassis Fabric cards.

### Type of change
- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### CODE REVIEW

**Comment by aaronpayment** [comment]
@StormLiangMS for review

**Comment by aaronpayment** [comment]
@r12f @StormLiangMS is is possible to get a review and merge this change. It does not change any test functionality.

**Review by yxieca — APPROVED** [review]

**Comment by StormLiangMS** [comment]
hi @aaronpayment  Merged, pls follow up the format of PR description for later PR.

**Comment by xwjiang-ms** [comment]
Get conn_graph_facts would loop all devices in inventory, once some Arista hwskus not included in the exception elif like Arista-7260CX3 with import error, read dut minigraph would always fail, so need to revert this PR

**Pull request merged**
