### PR TITLE
Skip test_syslog_protocol_filter_severity and test_syslog_config_work by bugs

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

1. Skip test_syslog_protocol_filter_severity by https://github.com/sonic-net/sonic-mgmt/issues/14493
2. Skip test_syslog_config_work by bugs by https://github.com/sonic-net/sonic-buildimage/issues/19638

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

### Approach
Skip test_syslog_protocol_filter_severity and test_syslog_config_work by bugs 

#### How did you do it?
Add skip conidtion

#### How did you verify/test it?
Run the two tests to check if they are skipped

#### Any platform specific information?
Any

### CODE REVIEW

**Comment by xwjiang-ms** [comment]
@JibinBao `syslog/test_syslog_source_ip.py::TestSSIP::test_basic_syslog_config` is failing with the fix, please check
run module wait_for failed, Ansible Results =>
{"changed": false, "elapsed": 30, "failed": true, "msg": "Timeout when waiting for 10.250.0.101:22 to stop."}
Traceback (most recent call last):
  File "/var/src/sonic-mgmt/tests/common/plugins/log_section_start/__init__.py", line 71, in _fixture_func_decorator
    return fixture_func(*args, **kargs)
  File "/var/src/sonic-mgmt/tests/syslog/test_syslog_source_ip.py", line 198, in setup_ssip_test_env
    self.configure_mgmt_vrf_test_data(localhost)
  File "/var/src/sonic-mgmt/tests/syslog/test_syslog_source_ip.py", line 255, in configure_mgmt_vrf_test_data
    localhost.wait_for(host=self.duthost.mgmt_ip, port=SONIC_SSH_PORT, search_regex=SONIC_SSH_REGEX,
  File "/var/src/sonic-mgmt/tests/common/devices/base.py", line 131, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module wait_for failed, Ansible Results =>
{"changed": false, "elapsed": 30, "failed": true, "msg": "Timeout when waiting for 10.250.0.101:22 to stop."}

**Comment by JibinBao** [comment]
@xwjiang-ms
The failed reason is when ceate mgmt vrf by "sudo config vrf add mgmt", the dut ssh port is not absent as expected.
Previously, we have a similar issue https://github.com/sonic-net/sonic-mgmt/issues/6479. The reason is that msft environemt has some issue when use domain name to check ssh port status. After replace it with duthost.mgmt_ip, it works well. I have verified it with @StormLiangMS .(This is the relevant fix: https://github.com/sonic-net/sonic-mgmt/pull/13280)
But now, we enounter the the similare issue, I want to konw the dut is a real switch or virtural switch? Can you help check it support creating the mgmt vrf? Can you help run the command "sudo config vrf add mgmt" on the simlar dut to check what  is the behavoir?
In our setup, the case has been working well. So, I doubt it is related to your setup.

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
need to get test result before cherry pick to 202405.

**Pull request merged**
