### PR TITLE
Fix the dst key error in qos-sai in cisco-8000

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Fixing the error from qos-sai runs for cisco-8000 platforms.
```
======================================================================
ERROR: sai_qos_tests.PFCtest
----------------------------------------------------------------------
Traceback (most recent call last):
  File \"saitests/py3/sai_qos_tests.py line 1057, in runTest
    pkt, int(self.test_params['pg']), asic_type))
  File \"saitests/py3/sai_qos_tests.py line 222, in fill_leakout_plus_one
    test_case.clients['dst'], "dst", dst_port_id)
KeyError: 'dst'
"----------------------------------------------------------------------"
```

This issue was introduced by multi-asic PR which introduces the src and dst asic values. These were not present in the pre-multiasic code. This affects T1 runs, and single-asic T2 runs with cisco-8000 platforms. The fill_leakout_plus_one functions used only for cisco-8000 platforms, and so we are hitting this issue.

### CODE REVIEW

**Comment by abdosi** [comment]
give more explantion why we are seeing this issue in PR description. Also target this change to master. validation can be done on 202205 branch

**Review by abdosi — CHANGES_REQUESTED** [review]
as comment

**Comment by rraghav-cisco** [comment]
> give more explantion why we are seeing this issue in PR description. Also target this change to master. validation can be done on 202205 branch

@abdosi : I can't merge this to master as of now - Master doesn't have this problem. It was introduced only after the multi-asic PR got merged in 202205. Below is the code snippet from master in the fill_leakout_plus_one function:
            queue_counters = sai_thrift_read_queue_occupancy(
                test_case.client, dst_port_id)

It has only one RPC client. The multi-asic PR introduces the src/dst client concept.

**Review by abdosi — APPROVED** [review]

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco  @abdosi ,  Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Pull request merged**
