### PR TITLE
Add fabric test data for 7800R3AK-36DM2-C36 cards

### PR DESCRIPTION
**Pull request by jfeng-arista**
### Description of PR

Summary: The test_fabric_reach test errored on 7800R3AK-36DM2-C36 cards due to missing expected fabric data file. This change adds the expected data for that type of cards. Also updated the test to fix some issue.
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/8383

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@arlakshm

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
Hi @wangxin , can you let us know how to kickoff the semgrep. It seems to be stuck

**Comment by kenneth-arista** [comment]
@arlakshm all checks passed! Please merge this when you get a chance

**Pull request merged**
