### PR TITLE
Add dualtor-64-breakout topology to support case test_cacl_application_dualtor

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Add dualtor-64-breakout topology to support case test_cacl_application_dualtor

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Case test_cacl_application_dualtor shall run on topology dualtor-64-breakout
#### How did you do it?
Update the skip condition
#### How did you verify/test it?
Run it locally

### CODE REVIEW

**Review by wsycqyz — APPROVED** [review]
lğtm

**Review by bingwang-ms — APPROVED** [review]

**Comment by echuawu** [comment]
> @echuawu PR conflicts with 202405 branch

The conflict handle https://github.com/sonic-net/sonic-mgmt/pull/15140

**Pull request merged**
