### PR TITLE
tuning timeout for test_turn_on_off_psu_and_check_psustatus

### PR DESCRIPTION
**Pull request by XuChen-MSFT**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305

#### What is the motivation for this PR?

timing issue caused test_copp/test_platform_info (psu test) /test_reload_config test failure in nightly

#### How did you do it?

refine timeout value for those cases

#### How did you verify/test it?

pass local test and nightly test

### CODE REVIEW

**Review by wsycqyz — APPROVED** [review]
LGTM

**Review by kevinskwang — APPROVED** [review]

**Comment by kevinskwang** [comment]
this PR also changes some timing issue for psu case, pls add those info in the commit message.

**Comment by XuChen-MSFT** [comment]
Removed change of test_reload_config and test_copp
Only track psustatus timeout changing in this PR.

**Review by wsycqyz — APPROVED** [review]
LGTM

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
