### PR TITLE
[Cherry-pick] Optimizing testQosSaiHeadroomPoolSize runtime #8775

### PR DESCRIPTION
**Pull request by ansrajpu-git**
### Description of PR

Cherry-pick from PR #8775 

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

### CODE REVIEW

**Comment by ansrajpu-git** [comment]
@vmittal-msft , please review
Please note, the master PR#8775 introduced an issue at line #2727 which is fixed in PR#11008 ( https://github.com/sonic-net/sonic-mgmt/pull/11008 ) yet to me merged in 202205 branch.

**Comment by vmittal-msft** [comment]
Can we combine changes for #11008 here ?

**Comment by ansrajpu-git** [comment]
> Can we combine changes for #11008 here ?

@vmittal-msft ,PR#11008 is merged to master and tagged for 202205 as well.This PR has this fix plus the tx_disable/enable for destination lag ports

**Comment by ansrajpu-git** [comment]
@vmittal-msft , this is being on hold for long time please help merge it to 202205 branch.

**Review by vmittal-msft — APPROVED** [review]

**Comment by vmittal-msft** [comment]
@yxieca @wangxin please help merge this to 202205 as this is cherry pick from master fix

**Pull request merged**
