### PR TITLE
T2 Chassis - BGP FIB Suppress Pending Testplan

### PR DESCRIPTION
**Pull request by sanjair-git**
**T2 Chassis - BGP FIB Suppress Pending Test Plan**

### Description of PR

Summary:
This T2 Chassis test plan for BGP FIB suppress pending feature is an extension of the BGP Suppress FIB Pending Test Plan added for T1 DUT at [plan](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/BGP-Suppress-FIB-Pending-test-plan.md)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
The test plan is created to verify the BGP suppress FIB pending feature functionality on a T2 Chassis line card that allows BGP not to advertise routes that haven't been installed into ASIC yet.

#### How did you do it?
Consistent to the existing T1 FIB suppress pending test cases, adapt the tests to verify the functionality on a T2 chassis.

### CODE REVIEW

**Comment by sanjair-git** [comment]
@arlakshm, please take a look at the test plan when you get a chance.

**Comment by abdosi** [comment]
@anamehra @vperumal @rajendrat : Please help review.
BGP Fib supress feature is critical and sesisitve for T2 considering route-scale of T2. We should think of enhancing the test plan (not just reuse T1 testplan) based on T2 specific scenario

**Comment by vperumal** [comment]
Sure @abdosi - will take a look and review it

**Comment by sanjair-git** [comment]
**Review comments from community:**

1. Verify the offloaded/queued flag check on the upstream line cards before the traffic flow ---> _Addressed, taken care._
2. For performance tests, may be snappi based tests have to be considered. ----> _Action item for IXIA team_
3. Scaling point of view - more number of route announcements ----> _For T2 alone on test case 5, 33k prefixes will be advertised._

**Comment by arlakshm** [comment]
@deepak-singhal0408 to sign off on this test plan

**Comment by sanjair-git** [comment]
Hi @deepak-singhal0408, I have taken care of the comments we discussed. Please take a look at the latest draft.

**Review by deepak-singhal0408 — APPROVED** [review]
Thanks @sanjair-git for taking care of all the review comments. The testplan looks good to me.

**Comment by deepak-singhal0408** [comment]
All Comments addressed. @rlhui please help merge the testplan. Thanks!

**Comment by rlhui** [comment]
@rlhui  to help merge

**Review by rlhui — APPROVED** [review]

**Pull request merged**
