### PR TITLE
[Nvidia] Enable vxlan_ecmp tests on Nvidia 4700 and 4280 platforms

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
Enable vxlan_ecmp tests on Nvidia 4700 and 4280 platforms

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
Enable vxlan_ecmp tests on Nvidia 4700 and 4280 platforms, these tests are supported by Nvidia 4700 and 4280 platforms.
#### How did you do it?
Update tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
#### How did you verify/test it?
Run the tests on 4700 and 4280 platforms, all passed.

### CODE REVIEW

**Review by wsycqyz — APPROVED** [review]
LGTM

**Review by nhe-NV — APPROVED** [review]

**Comment by congh-nvidia** [comment]
Hi @liat-grozovik , could you please review and merge this?

**Comment by bingwang-ms** [comment]
@siqbal1986 Can you please help review this PR?

**Review by siqbal1986 — APPROVED** [review]
Did you run these with include_long_tests . if yes then please go ahead and merge

**Comment by siqbal1986** [comment]
@congh-nvidia  Did you run these with include_long_tests . if yes then please go ahead and merge

**Comment by congh-nvidia** [comment]
Hi @siqbal1986, yes. We are running this in regression with include_long_tests. The test is passing. @bingwang-ms could you please help merge this?

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
