### PR TITLE
[test plan] Single switch reboot

### PR DESCRIPTION
**Pull request by parmarkj**
### Description of PR: 
This is a test plan to test single switch reboot and to ensure ports and routes 
comes back up post reboot.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
To add a new test case.
#### How did you do it?
Please refer to the readme file.
#### How did you verify/test it?
Verified on T2.
#### Supported testbed topology if it's a new test case?
T2

### CODE REVIEW

**Comment by yxieca** [comment]
@parmarkj what is this test adding on top of test_reboot.py under platform_test folder?

**Comment by parmarkj** [comment]
[yxieca](https://github.com/yxieca) I have moved the test from platform_tests to macsec as I have added the macsec check post reboot.

**Comment by rlhui** [comment]
@judyjoseph woudl you please check if our current tests already cover "macsec check after reboot" or not?

**Comment by parmarkj** [comment]
@judyjoseph could you please review?

**Comment by judyjoseph** [comment]
@parmarkj Could you check the macsec testplan : https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/MACsec-test-plan.md#macsec-enabled-on-all-interfaces-and-the-dut-is-rebooted. There is a scale session testcase for switch reboot.

so please merge your HDL (docs/testplan/Single-Switch-Reboot-test-plan.md) with the existing macsec testplan doc itself.

In addition, update the section "How did you verify/test it?" in the PR description with the test run/pass status

**Comment by parmarkj** [comment]
@judyjoseph I have updated the "How did you verify/test it?" section. This tests does not reboot the DUT with macsec interfaces, it reboots one of the neighbor. Should I still go ahead and merge the HDL with the existing macsec testplan doc. There is another test, Double Switch Reboot, which reboots both DUT and a neighbor with macsec interfaces ([PR-9260](https://github.com/sonic-net/sonic-mgmt/pull/9260). Would that be a better one to add in the macsec testplan doc.

**Comment by BYGX-wcr** [comment]
> @judyjoseph I have updated the "How did you verify/test it?" section. This tests does not reboot the DUT with macsec interfaces, it reboots one of the neighbor. Should I still go ahead and merge the HDL with the existing macsec testplan doc. There is another test, Double Switch Reboot, which reboots both DUT and a neighbor with macsec interfaces ([PR-9260])(#9260). Would that be a better one to add in the macsec testplan doc.

Your code is exactly rebooting the DUT. There is no reboot operation done on the neighbor.

If this is performing a reboot test for DUT, it seems to be duplicate to the PR: https://github.com/sonic-net/sonic-mgmt/pull/10504.

**Comment by parmarkj** [comment]
closing the PR as test is already covered

**Pull request closed without merging**
