### PR TITLE
Add x86_64-mlnx_msn2700-r0 A1 support

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**What I did?**

Add x86_64-mlnx_msn2700-r0 A1 support

**How I did?**

1. add sensor test for x86_64-mlnx_msn2700-r0 A1 version
2. make test framework load the A1 platform.json
3. make mock test load the A1 thermal profile

**How I test it?**

Run regression on Mellanox platforms: 4700/4600C/3700/3700C/2700/2700 A1

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Review by wangxin — DISMISSED** [review]

**Review by keboliu — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox can you please look for the pre check failures and handle them so we have clean file?

**Comment by Junchao-Mellanox** [comment]
Hi @wangxin , could you please help review and approve?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
