### PR TITLE
Fixing ecmp tests on 202305

### PR DESCRIPTION
**Pull request by alawing**
### Description of PR

Summary:
Fixes # fg_ecmp tests

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [x] 202205
- [x] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
fg_ecmp test failed because arp table not cleaned before main tests
#### How did you do it?
added sonic-clean arp on top of main tests
#### How did you verify/test it?
Tested the script

### CODE REVIEW

**Comment by wsycqyz** [comment]
Can we make sure this change goes to master branch?

**Comment by alawing** [comment]
> Can we make sure this change goes to master branch?

Yes we can.

**Review by wsycqyz — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
Can we check the status instead of sleeping?

**Comment by alawing** [comment]
Will create another PR on master

**Pull request closed without merging**
