### PR TITLE
sonic-mgmt/IXIA test to verify the PFC frame sent by DUT has a valid src_mac address

### PR DESCRIPTION
**Pull request by sreejithsreekumaran**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?

Add a IXIA testcase to capture the PFC frame sent by DUT and verify the src_mac is a valid address.

#### How did you do it?

- Injected lossless  traffic and PAUSE flows from the IXIA
- The resulting congestion caused the DUT to send XOFF frames
- Capture the XOFF frame on IXIA port and read and verify the validity of XOFF frame
- Compare the src_mac in XOFF frame against the peer DUT port mac address

#### How did you verify/test it?

Ran on m64/Compute AI

### CODE REVIEW

**Review by alpeshspatel — APPROVED** [review]
lgtm

**Comment by alpeshspatel** [comment]
@sreejithsreekumaran  fyi
@Anandaraj-Maharajan fyi

**Comment by wsycqyz** [comment]
re-trigger the PR test

**Comment by alpeshspatel** [comment]
@kevinwangsk fyi

**Review by bpar9 — APPROVED** [review]
lgtm

**Comment by sreejithsreekumaran** [comment]
> @sreejithsreekumaran PR conflicts with 202405 branch

@kevinskwang the conflict is due to #13533 missing in 202405 branch. Merging 13533 into 202405 could have avoided a conflict of current PR in the 202405 branch.

What is the suggested next step?

**Pull request merged**
