### PR TITLE
Adding the new function: sai_thrift_read_pg_occupancy.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Adding the definition of a new function to switch.py, to be used by sai_qos_tests.py.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : Any comments? This PR can be merged without any dependency on other PRs.

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT :  Pls port it to 202305 as well.

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me

**Comment by StormLiangMS** [comment]
@rraghav-cisco have you done test with 202305 image?

**Comment by rraghav-cisco** [comment]
> @rraghav-cisco have you done test with 202305 image?

@StormLiangMS : Yes, we have run with 202305 sonic-buildimage on DUT with 202305 sonic-mgmt base.

**Pull request merged**
