### PR TITLE
Exclude 0x0800 from the ethernet type range

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Exclude 0x0800 from the ethernet type range to enhance the test.
In lag hash test, when the hash field is INNER_ETHERTYPE, the packet with inner ether type as 0x0800 would be hashed to another portchannel in the same nexthop group.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Enhance the test.
#### How did you do it?
Exclude the 0x0800 from the ether type range.
#### How did you verify/test it?
Run it in internal regression.

### CODE REVIEW

**Comment by bingwang-ms** [comment]
Hi @echuawu, from what I see in the PR description, it looks like an image issue? Why the packet with ether type 0x0800 is hashed  to another port channel?

**Comment by echuawu** [comment]
> Hi @echuawu, from what I see in the PR description, it looks like an image issue? Why the packet with ether type 0x0800 is hashed to another port channel?

@dgsudharsan , could you please explain more detail to Bing?

**Comment by dgsudharsan** [comment]
> > Hi @echuawu, from what I see in the PR description, it looks like an image issue? Why the packet with ether type 0x0800 is hashed to another port channel?
> 
> @dgsudharsan , could you please explain more detail to Bing?

0x0800 in ethertype would classify the packet as IP packet and since the hash parameters are programmed to include IP parameters it would be hashed

**Review by dgsudharsan — APPROVED** [review]

**Comment by bingwang-ms** [comment]
> > > Hi @echuawu, from what I see in the PR description, it looks like an image issue? Why the packet with ether type 0x0800 is hashed to another port channel?
> > 
> > 
> > @dgsudharsan , could you please explain more detail to Bing?
> 
> 0x0800 in ethertype would classify the packet as IP packet and since the hash parameters are programmed to include IP parameters it would be hashed

Thanks for the clarification. @prsunny Could you please help check?

**Review by bingwang-ms — APPROVED** [review]

**Comment by prsunny** [comment]
> > > > Hi @echuawu, from what I see in the PR description, it looks like an image issue? Why the packet with ether type 0x0800 is hashed to another port channel?
> > > 
> > > 
> > > @dgsudharsan , could you please explain more detail to Bing?
> > 
> > 
> > 0x0800 in ethertype would classify the packet as IP packet and since the hash parameters are programmed to include IP parameters it would be hashed
> 
> Thanks for the clarification. @prsunny Could you please help check?

@bingwang-ms , lgtm

**Pull request merged**
