### PR TITLE
Fix fixture invocation order in qos/qos_sai_base.py

### PR DESCRIPTION
**Pull request by vivekverma-arista**
### Description of PR

Summary: Fix fixture invocation order in qos/qos_sai_base.py
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
qos/test_qos_sai.py fail with the following -
```
failed on setup with "Failed: Not all critical processes are healthy"
```

The fixture `dut_disable_ipv6` disables ipv6 due to which the following critical processes don't come up after swapping syncd ( fixture `swapSyncd_on_selected_duts ` ) -
1. program:snmpd
2. program:snmp-subagent

And this issue only hits if `swapSyncd_on_selected_duts` is executed after dut_disable_ipv6 and since there is no dependency between these fixtures, they can execute in any order.

#### How did you do it?
This change introduces a dependency between `dut_disable_ipv6` & `swapSyncd_on_selected_duts` such that former is always executed after latter.

#### How did you verify/test it?
Tested on Arista-7050CX3 platform with dualtor topology.

### CODE REVIEW

**Comment by StormLiangMS** [comment]
hi @neethajohn  @XuChen-MSFT  could you help to review?

**Review by neethajohn — APPROVED** [review]

**Comment by neethajohn** [comment]
@XuChen-MSFT , please take a look

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @vivekverma-arista  could you run test with 202311 image?

**Comment by vivekverma-arista** [comment]
> hi @vivekverma-arista could you run test with 202311 image?

I have testbed with 202311 image. The test passes and no new regression is seen because of this fix.

**Pull request merged**
