### PR TITLE
Fix for GCU Dhcp_Relay issue in KVM test failure 

### PR DESCRIPTION
**Pull request by ridahanif96**
**Why I did it**
This PR is created to resolve GCU DHCP_Relay issues in kvm test failure in [Update submodule sonic-utilities to the latest HEAD](https://github.com/sonic-net/sonic-buildimage/pull/16267)

Summary: Fixed PR issues in fixture/duthost_utilites.py to solve vlan addition changes on Port

Signed-off-by: Rida Hanif [rida.hanif@xflowresearch.com](mailto:rida.hanif@xflowresearch.com)

### CODE REVIEW

**Comment by ridahanif96** [comment]
[@mssonicbld](https://github.com/mssonicbld) [@liushilongbuaa](https://github.com/liushilongbuaa) I have created this PR to resolve the DHCP_Realy  failure  issue, but KVM tests are still failing here.
We have added a switchport mode command which needs to be checked always from now onward whenever VLAN members are configured in SONIC. We have updated sonic-utilities & sonic-mgmt earlier with HLD PR.
There was a recent change in DHCP_relay as well due to which this KVM test failure occurs.
What issue i am facing with this PR is that the current mgmt repo is not able to invoke the updated sonic-utilities repo, therefore it is showing following error:

{"changed": false, "cmds": ["config vlan add 108", "config interface ip add Vlan108 192.168.8.1/24", "config vlan add 109", "config interface ip add Vlan109 192.168.9.1/24", "config switchport mode trunk Ethernet4", "config vlan member add 108 Ethernet4", "config vlan member add 109 Ethernet4"], "delta": "0:00:04.600182", "end": "2023-09-02 12:27:53.114145", "failed": true, "failed_cmds": ["config switchport mode trunk Ethernet4"], "msg": "At least running one of the commands failed", "results": [{"cmd": "config vlan add 108", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0},
{"cmd": "config interface ip add Vlan108 192.168.8.1/24", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config vlan add 109", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config interface ip add Vlan109 192.168.9.1/24", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0},
**{"cmd": "config switchport mode trunk Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 2, "stderr": "Usage: config [OPTIONS] COMMAND [ARGS]...\nTry "config -h" for help.\n\nError: No such command "switchport".\n", "stderr_lines": ["Usage: config [OPTIONS] COMMAND [ARGS]...", "Try "config -h" for help.", "", "Error: No such command "switchport"."], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config vlan member add 108 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config vlan member add 109 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}], "start": "2023-09-02 12:27:48.513963"}**

These errors are different from [Update submodule sonic-utilities PR](https://github.com/sonic-net/sonic-buildimage/pull/16267) which can be verified as below:

{"cmd": "config vlan member add 108 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 2, "stderr": "Usage: config vlan member add [OPTIONS] port\nTry "config vlan member add -h" for help.\n\nError: Ethernet4 is in routed mode!\nUse switchport mode command to change port mode\n", "stderr_lines": ["Usage: config vlan member add [OPTIONS] port", "Try "config vlan member add -h" for help.", "", "Error: Ethernet4 is in routed mode!", "Use switchport mode command to change port mode"], "stdout": "", "stdout_lines": [], "timeout": 0},

**{"cmd": "config vlan member add 109 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 2, "stderr": "Usage: config vlan member add [OPTIONS] port\nTry "config vlan member add -h" for help.\n\nError: Ethernet4 is in routed mode!\nUse switchport mode command to change port mode\n", "stderr_lines": ["Usage: config vlan member add [OPTIONS] port", "Try "config vlan member add -h" for help.", "", "Error: Ethernet4 is in routed mode!", "Use switchport mode command to change port mode"], "stdout": "", "stdout_lines": [], "timeout": 0}], "start": "2023-08-31 16:11:31.354762"}**

Is there a way we can skip failing tests just for this PR to resolve kvm test failure? if this is possible we can do it to resolve this current issue. It might also be possible that you [@mssonicbld](https://github.com/mssonicbld) add these proposed changes in your PR to solve this failure or add me as collaborator in PR to help.

**Comment by liushilongbuaa** [comment]
@yejianquan , do you know who can help review this PR?

**Comment by liushilongbuaa** [comment]
@ridahanif96 , mssonicbld is automation account.

**Comment by ridahanif96** [comment]
> @ridahanif96 , mssonicbld is automation account.

Ok Thanks.

**Comment by yejianquan** [comment]
> [@mssonicbld](https://github.com/mssonicbld) [@liushilongbuaa](https://github.com/liushilongbuaa) [@gechiang ](https://github.com/gechiang) I have created this PR to resolve the DHCP_Realy failure issue, but KVM tests are still failing here. We have added a switchport mode command which needs to be checked always from now onward whenever VLAN members are configured in SONIC. We have updated sonic-utilities & sonic-mgmt earlier with HLD PR. There was a recent change in DHCP_relay as well due to which this KVM test failure occurs. What issue i am facing with this PR is that the current mgmt repo is not able to invoke the updated sonic-utilities repo, therefore it is showing following error:
> 
> {"changed": false, "cmds": ["config vlan add 108", "config interface ip add Vlan108 192.168.8.1/24", "config vlan add 109", "config interface ip add Vlan109 192.168.9.1/24", "config switchport mode trunk Ethernet4", "config vlan member add 108 Ethernet4", "config vlan member add 109 Ethernet4"], "delta": "0:00:04.600182", "end": "2023-09-02 12:27:53.114145", "failed": true, "failed_cmds": ["config switchport mode trunk Ethernet4"], "msg": "At least running one of the commands failed", "results": [{"cmd": "config vlan add 108", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config interface ip add Vlan108 192.168.8.1/24", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config vlan add 109", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config interface ip add Vlan109 192.168.9.1/24", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, **{"cmd": "config switchport mode trunk Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 2, "stderr": "Usage: config [OPTIONS] COMMAND [ARGS]...\nTry "config -h" for help.\n\nError: No such command "switchport".\n", "stderr_lines": ["Usage: config [OPTIONS] COMMAND [ARGS]...", "Try "config -h" for help.", "", "Error: No such command "switchport"."], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config vlan member add 108 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}, {"cmd": "config vlan member add 109 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "timeout": 0}], "start": "2023-09-02 12:27:48.513963"}**
> 
> These errors are different from [Update submodule sonic-utilities PR](https://github.com/sonic-net/sonic-buildimage/pull/16267) which can be verified as below:
> 
> {"cmd": "config vlan member add 108 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 2, "stderr": "Usage: config vlan member add [OPTIONS] port\nTry "config vlan member add -h" for help.\n\nError: Ethernet4 is in routed mode!\nUse switchport mode command to change port mode\n", "stderr_lines": ["Usage: config vlan member add [OPTIONS] port", "Try "config vlan member add -h" for help.", "", "Error: Ethernet4 is in routed mode!", "Use switchport mode command to change port mode"], "stdout": "", "stdout_lines": [], "timeout": 0},
> 
> **{"cmd": "config vlan member add 109 Ethernet4", "cmd_with_timeout": "", "err_msg": "", "rc": 2, "stderr": "Usage: config vlan member add [OPTIONS] port\nTry "config vlan member add -h" for help.\n\nError: Ethernet4 is in routed mode!\nUse switchport mode command to change port mode\n", "stderr_lines": ["Usage: config vlan member add [OPTIONS] port", "Try "config vlan member add -h" for help.", "", "Error: Ethernet4 is in routed mode!", "Use switchport mode command to change port mode"], "stdout": "", "stdout_lines": [], "timeout": 0}], "start": "2023-08-31 16:11:31.354762"}**
> 
> Is there a way we can skip failing tests just for this PR to resolve kvm test failure? if this is possible we can do it to resolve this current issue. It might also be possible that you [@mssonicbld](https://github.com/mssonicbld) add these proposed changes in your PR to solve this failure or add me as collaborator in PR to help.

@ridahanif96 Could you advance the sonic-utilities in the sonic-buildimage repo? sonic-mgmt's test will always use the newest built kvm image from sonic-buildimage repo.

**Comment by yejianquan** [comment]
I don't think it's a good approach to skip this DHCP case in only this PR, this will block all other PR tests.

**Comment by yejianquan** [comment]
+ @jcaiMR @kellyyeh as the DHCP owner

**Comment by jcaiMR** [comment]
@ridahanif96 Would you please change title to gcu dhcp_relay, since it may confuse with dhcp_relay/test_dhcp_relay.py.

**Comment by ridahanif96** [comment]
> @ridahanif96 Would you please change title to gcu dhcp_relay, since it may confuse with dhcp_relay/test_dhcp_relay.py.

Done

**Comment by ridahanif96** [comment]
All KVM failure resolved @liushilongbuaa @yejianquan please review this PR.
I have added a compatible logic to pass current KVM image along with passing [advance utilities PR (https://github.com/sonic-net/sonic-buildimage/pull/16267 
Thanks!

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
