### PR TITLE
Delete the files related to the customskipif

### PR DESCRIPTION
**Pull request by nhe-NV**
Since the condition marker is added and used to mark the test case skipped, the customskipif which has the duplicated functionality should be removed incase will introduce some confuse

### Description of PR

Summary: Delete the files related to the customskipif
Fixes # (issue) Delete the files related to the customskipif

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Delete the files related to the customskipif
#### How did you do it?
Delete the customskipif folder under the tests/common/plugins, and remove the refer to the custom_skipif
#### Any platform specific information?
No

### CODE REVIEW

**Review by ppikh — DISMISSED** [review]

**Comment by wangxin** [comment]
@nhe-NV Thanks for taking initiative to remove duplicated code. Can you do a `git rebase -i` to help resolve the merge conflicts?

**Comment by nhe-NV** [comment]
> done

**Comment by nhe-NV** [comment]
> @nhe-NV Thanks for taking initiative to remove duplicated code. Can you do a `git rebase -i` to help resolve the merge conflicts?

Done

**Comment by liat-grozovik** [comment]
@roysr-nv could u please help to review and approve?

**Review by roysr-nv — APPROVED** [review]

**Pull request merged**
