### PR TITLE
skipping test_route_flow_counter.py on Cisco 8122 platforms

### PR DESCRIPTION
**Pull request by CharudattaSChitale**
**What is the motivation for this PR?**

FLOW_COUNTER_CAPABILITY was enabled recently on ASIC/SDK side for Cisco 8122.

root@light-dut:/usr/share/sonic/device/x86_64-8122_64eh_o-r0/Cisco-8122-O64# sudo sonic-db-cli STATE_DB HGET "FLOW_COUNTER_CAPABILITY_TABLE|route" support
true

But 'enable_forwarding_route_counter' is not enabled on SONiC/asic_cfg.json because of scale limits (cannot scale more than 50k with the current LPM profile).

As the feature is not enabled for this platform, need to skip this testcase

**How did you do it?**
Added a skip condition for test test_route_flow_counter.py for Cisco 8122 platforms in file tests/common/plugins/conditional_mark/tests_mark_conditions.yaml

**Type of change** 
-Skip testcase

**Back port request** 
-202311
-202405

**How did you verify/test it?**
Ran test_route_flow_counter.py for 8122. Made sure it was skipped with 'Test not supported for cisco-8122 platform'

### CODE REVIEW

**Review by bpar9 — APPROVED** [review]
lgtm

**Review by wsycqyz — APPROVED** [review]
lğtm

**Comment by wsycqyz** [comment]
@CharudattaSChitale There is pre-commit error. Please help fix it.

**Comment by CharudattaSChitale** [comment]
> @CharudattaSChitale There is pre-commit error. Please help fix it.

I have fixed the pre-commit issue

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
