### PR TITLE
Fix the test_show_platform_fan test case statistically failure

### PR DESCRIPTION
**Pull request by nhe-NV**
Fix the test_show_platform_fan test case statistically failure and fix the pep8 failure at the same time

Fan having temporary status “NOT OK” is not a bug. It could happen in following case:
1.	Thermalctld/kernel changes the target speed. Hardware needs time to adjust the fan speed to target speed.
2.	Another thread of thermalctld reads the target speed and actual speed immediately. At this time point, there is a gap between fan target speed and actual speed which would cause “high speed warning” and fan status “NOT OK”.

Add retry in the test case to make the test case stable

### Description of PR

Summary: Fix the test_show_platform_fan test case statistically failure
Fixes # (issue) 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205

#### What is the motivation for this PR?
Fix the test_show_platform_fan test case statistically failure
#### How did you do it?
Add retry when validate the fan status
#### How did you verify/test it?
Run the test_show_platform.py for 10 times, and no failure.
#### Any platform specific information?
No

### CODE REVIEW

**Review by roysr-nv — APPROVED** [review]

**Review by roysr-nv — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]
great fixes for the pre-check :-)

**Pull request merged**
