### PR TITLE
[sonic-utilities] Add test case for show and sonic-installer not depends on database docker

### PR DESCRIPTION
**Pull request by liuh-80**
### Description of PR
Add new E2E test cases to  test show and sonic-installer not depends on database docker.

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Add new E2E test cases to  test show and sonic-installer not depends on database docker.

#### How did you do it?
Add new E2E test case to cover user scenarios.

#### How did you verify/test it?
Run new UT make sure they are all pass.
Make sure all current UT not break during merge validation.

#### Any platform specific information?
N/A

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Add E2E test case coverage for SSH login session limit.

#### How did you do it?
Add new E2E test case to cover user scenarios.

#### How did you verify/test it?
Run new UT make sure they are all pass.
Make sure all current UT not break during merge validation.

#### Any platform specific information?
N/A

#### Supported testbed topology if it's a new test case?

### CODE REVIEW

**Comment by liuh-80** [comment]
These new test case need can pass after this PR finish:
https://github.com/Azure/sonic-utilities/pull/2183

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
It this PR ready to merge?

**Comment by liuh-80** [comment]
Will complete this PR when validation passed.

**Comment by liuh-80** [comment]
The new UT failed after restart database docker, will fix it ASAP.

**Comment by liuh-80** [comment]
New UT keeps failed in following code, can't reproduce on local devbox, need investigation and fix:
        # reload config, because some critical process not work after database docker restart
        config_reload(duthost)
        time.sleep(CONFIG_RELOAD_WAIT_TIME)
>       wait_critical_processes(duthost) <== failed here

**Comment by liuh-80** [comment]
Close PR because EasyCLA issue, will create new PR later.

**Comment by liuh-80** [comment]
Create sonic-utilities UT here: https://github.com/sonic-net/sonic-utilities/pull/2401

**Pull request closed without merging**
