### PR TITLE
Updating J2C+ qos yaml  for 400G and 100G profile _egress_pkt count for lossy profile

### PR DESCRIPTION
**Pull request by ansrajpu-git**
### Description of PR

Since the dynamic_th-alpha changed from 0 to -4 (400g) & 100g port speed for egress lossy profile.
PR  #https://github.com/sonic-net/sonic-buildimage/pull/20132
Corresponding  changes made in J2C+ qos yaml for t2 -broadcom-dnx
Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [x] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### How did you do it?
Verified the qos test case execution with the new changes.

### CODE REVIEW

**Comment by ansrajpu-git** [comment]
@vmittal-msft , updated qos param change for Jr2 as well.

**Review by vmittal-msft — APPROVED** [review]

**Review by kenneth-arista — APPROVED** [review]

**Comment by rlhui** [comment]
@arlakshm  please help approve/merge

**Review by arlakshm — APPROVED** [review]

**Comment by rlhui** [comment]
@ansrajpu-git can we please help raise a 202405 PR at priority? Thanks.

**Comment by ansrajpu-git** [comment]
PR #https://github.com/sonic-net/sonic-mgmt/pull/15448 raised for  202405.

**Pull request merged**
