### PR TITLE
Improvements to vSONiC deployment

### LINKED ISSUE #8109: PR #7894 breaks vSonic based setup for T2 profile
**Description**

PR #7894 breaks vSonic based setup for T2 profile. The change expects all vSonic VMs to have Port Channels. In case of https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/vars/topo_t2_2lc_min_ports-masic.yml - Even numbered vSonic VM have PC so they work fine while odd numbered VM have issues

It also is missing leaf_asn_start in t2 yaml files.

TASK [sonic : create topo config] ********************************************************************************************************
Friday 21 April 2023  15:06:02 +0000 (0:00:01.459)       0:07:59.739 **********
fatal: [VM0100]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"}
fatal: [VM0101]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0102]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"}
fatal: [VM0103]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0104]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"}
fatal: [VM0105]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0106]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"} 

@saiarcot895 can you please take a look ?

@abdosi  for viz

### PR DESCRIPTION
**Pull request by saiarcot895**
### Description of PR

Summary:
Fixes #8109

### Type of change

- [x] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

There are two main issues currently with deployment with SONiC neighbors:

1. #8109 pointed out that there are topologies where the neighbor devices might not have a port channel, and that BGP is running directly on Ethernet interfaces. The current configdb template assumed that there is always a `Port-Channel1` interface that's used for BGP sessions. The purpose of this is so that the `local_addr` field can be populated, so that `show ip bgp summary` functions and has the full output. Fix this by getting all of the locally-configured addresses on the system and setting which address might be used for the BGP session with the peer based on the address and subnet. This should work in most cases.
2. The configdb template that is used is named based on the topology. However, all of the current templates for current topologies is the same, and hopefully continues to be the same in the future. To simplify things, remove the symlinks, and always use `configdb.j2`.

#### How did you verify/test it?

Did a `refresh-dut` on a t0-64-32 topo so that the config_db.json gets regenerated from the template, and verified that BGP sessions are up afterwards.

### CODE REVIEW

**Review by wangxin — DISMISSED** [review]

**Review by wangxin — APPROVED** [review]

**Comment by mannytaheri** [comment]
@saiarcot895 @wangxin  Please commit this PR to 2205 branch.

**Comment by mannytaheri** [comment]
@saiarcot895 @wangxin    I cherry-picked this PR to 2205 branch.  I see a new error.  swss container crashes on the VM which will prevent it from being rebooted. 
This occurs only on VMs that have portchannels.  It is ok on non-portchannel VMs.

fatal: [VM1506]: FAILED! => {
    "changed": true, 
    "cmd": [
        "config", 
        "reload", 
        "-y"
    ], 
    "delta": "0:00:00.729455", 
    "end": "2023-07-19 15:25:15.140806", 
    "invocation": {
        "module_args": {
            "_raw_params": "config reload -y", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2023-07-19 15:25:14.411351", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "SwSS container is not ready. Retry later or use -f to avoid system checks", 
    "stdout_lines": [
        "SwSS container is not ready. Retry later or use -f to avoid system checks"
    ]
}

PLAY RECAP *******************************************************************************************************
VM1500                     : ok=23   changed=8    unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   
VM1501                     : ok=24   changed=9    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0   
VM1502                     : ok=23   changed=8    unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   
VM1503                     : ok=24   changed=9    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0   
VM1504                     : ok=23   changed=8    unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   
VM1505                     : ok=24   changed=9    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0   
VM1506                     : ok=23   changed=8    unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   
VM1507                     : ok=30   changed=9    unreachable=0    failed=0    skipped=20   rescued=0    ignored=0   
sonic-tb15                 : ok=215  changed=13   unreachable=0    failed=0    skipped=316  rescued=0    ignored=0

**Comment by mannytaheri** [comment]
@saiarcot895 @wangxin This is breaking add-topo as I mentioned above.  Would you please address this issue?

**Comment by saiarcot895** [comment]
@mannytaheri Sorry for the delay, I just tested add-topo on 202205 branch, and on vms-kvm-t0-64-32, I don't see any swss crash. If this is still an issue, can you open a Github issue for this?

**Pull request merged**
