### PR TITLE
[py3 migration] [202205] fix incompatible py3 usage in copp_test.py in 202205 branch

### PR DESCRIPTION
**Pull request by wenyiz2021**
### Description of PR

This is to accommodate py3 to use `.items()` for dictionary iteration.
master branch PR https://github.com/sonic-net/sonic-mgmt/pull/9326 is fine as it was already using `items`, while 202205 branch has this difference.

Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/9574

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### How did you verify/test it?
run on T2 chassis

```
PASSED                                                                                                                                                                                       [ 12%]
copp/test_copp.py::TestCOPP::test_policer[lc-1-IP2ME]
```

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by arlakshm** [comment]
Hi @wangxin are we migrating to py3 for all test in 202205?

**Comment by wenyiz2021** [comment]
@wangxin coud you help to merge this PR? I have validated on T2

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
The same issue was also seen on non T2 platform.

**Review by wsycqyz — APPROVED** [review]
LGTM

**Review by yxieca — APPROVED** [review]

**Pull request merged**
