### PR TITLE
Add test plan for syslog source ip feature

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Add test plan for syslog source ip feature.
Syslog source IP HLD: https://github.com/JibinBao/sonic-mgmt/pull/new/syslog_test_plan

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Add test plan for syslog source ip feature

#### Any platform specific information?
Any
#### Supported testbed topology if it's a new test case?
Any

### CODE REVIEW

**Comment by JibinBao** [comment]
Move SSIP test plan from  sonic-net/SONiC to sonic-mgmt/docs/testplan/
Close https://github.com/sonic-net/SONiC/pull/1010

**Review by roysr-nv — COMMENTED** [review]
Jibin, there's a missing coverage for the port argument, all the test cases assume default port

**Comment by JibinBao** [comment]
> 
Hi Roy, in the test step we have a description for the different ports like below.
Repeat steps 1-6 by setting different port, and check the port of syslog message will be changed to the set one

**Review by nazariig — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
