### PR TITLE
[Everflow, Voq, chassis] Avoid need to configure IP address for Recycle port

### PR DESCRIPTION
**Pull request by judyjoseph**
Summary:
In VoQ chassis devices Avoid need to configure IP address for Recycle port. The Recycle port is added as a routed port via this PR https://github.com/sonic-net/sonic-buildimage/pull/13779

#### How did you do it?

Remove the Ip address being set on the Rec0/Rec1 interfaces based on signe;/multi-asic devices.

#### How did you verify/test it?

Run the Everflow sonic-mgmt tests with VoQ chassis without the need to configure an IP address on Ethernet-Rec0 interface. everflow_per_interface is a known failure - to be fixed.

```
--------------------------------------------------------------------------- generated xml file: /home/jujoseph/CHASSIS/CHASSIS/sonic-mgmt-int/tests/logs/tr.xml ----------------------------------------------------------------------------
========================================================================================================= short test summary info ==========================================================================================================
SKIPPED [4] /home/jujoseph/CHASSIS/CHASSIS/sonic-mgmt-int/tests/everflow/test_everflow_testbed.py:373: Skip test as is not supported on a VoQ chassis.
SKIPPED [10] /home/jujoseph/CHASSIS/CHASSIS/sonic-mgmt-int/tests/everflow/everflow_test_utilities.py:597: egress ACL w/ ingress Mirroring not supported, skipping
SKIPPED [4] /home/jujoseph/CHASSIS/CHASSIS/sonic-mgmt-int/tests/everflow/test_everflow_testbed.py:498: Skipping test since mirror policing is not supported on broadcom j2c+ platforms
SKIPPED [10] /home/jujoseph/CHASSIS/CHASSIS/sonic-mgmt-int/tests/everflow/everflow_test_utilities.py:597: ingress ACL w/ egress Mirroring not supported, skipping
FAILED everflow/test_everflow_per_interface.py::test_everflow_per_interface[ipv6] - AssertionError: Did not receive expected packet on any of ports [0, 1] for device 0.
===================================================================================== 1 failed, 33 passed, 28 skipped, 486 warnings in 2049.77
```

### CODE REVIEW

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/everflow/conftest.py:1:1: F401 'pytest' imported but unused<br/>tests/everflow/conftest.py:2:1: F401 'logging' imported but unused<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/everflow/conftest.py:1:1: F401 'pytest' imported but unused<br/>tests/everflow/conftest.py:2:1: F401 'logging' imported but unused<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/everflow/conftest.py:1:1: F401 'pytest' imported but unused<br/>tests/everflow/conftest.py:2:1: F401 'logging' imported but unused<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by judyjoseph** [comment]
@arlakshm to review again.

**Review by arlakshm — APPROVED** [review]

**Pull request merged**
