### PR TITLE
Enhance generic hash test cases

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR

Enhance Generic Hash test to cover 6 new supported fields and algorithm configuration.
Related test plan: https://github.com/sonic-net/sonic-mgmt/pull/11823

Summary:
1. Add support for 6 new fields
2. Update show parse function
3. Add algorithm configure and validate test
4. Adapt on dualtor setup
5. Skip cases on SPC1 due to hardware limitation
6. Add list support for option --algorithm and --hash_field according to community review request 
7. Update dynamic supported algorithm check

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
Enhance Generic Hash test to cover 6 new supported fields and algorithm configuration.
#### How did you do it?
Add related test functions.
#### How did you verify/test it?
Run it in internal regression.
#### Any platform specific information?
No
#### Supported testbed topology if it's a new test case?
T0 and T1 topology.

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@echuawu can you please check the missing checker EasyCLA?

**Review by liat-grozovik — APPROVED** [review]

**Comment by echuawu** [comment]
> @echuawu can you please check the missing checker EasyCLA?

Hi @liat-grozovik, when I was handling EasyCLA issue, the pre-commit check failed due to one unrelated line. So I handled the pre-commit failure, then pushed update. I don't know if it need you to approve again.

**Review by liat-grozovik — APPROVED** [review]

**Comment by xwjiang-ms** [comment]
@echuawu sonichost don't have the attribute is_interface_status_up, I'm gonna to create a issue and skip testcase test_nexthop_flap

**Comment by echuawu** [comment]
> @echuawu sonichost don't have the attribute is_interface_status_up, I'm gonna to create a issue and skip testcase test_nexthop_flap

@xwjiang-ms , the fix is in https://github.com/sonic-net/sonic-mgmt/pull/14065

**Pull request merged**
