### PR TITLE
[T2-ACL] Adding support for T2-profile in ACL script

### PR DESCRIPTION
**Pull request by vperumal**
### Description of PR
Currently t2 profile is not supported in acl script. Added support for the profile in the acl script.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Currently t2 profile is not supported in acl script. Added support for the profile in the acl script.

#### How did you do it?
Added a proc to get T2 related information for acl table. Made changes in script to check if it is t2 profile and add support for it.

#### How did you verify/test it?
Verified against cisco-8000 platform for T2 profile.

### CODE REVIEW

**Comment by vperumal** [comment]
FYI: @abdosi @SuvarnaMeenakshi

**Comment by sanmalho-git** [comment]
@abdosi @SuvarnaMeenakshi @judyjoseph @arlakshm  - with all the fixes from BRCM, ingress/egress IPv4/IPv6 ACL's are working fine for T2 chassis with DNX chipset. Can we get this PR merged please.

**Comment by judyjoseph** [comment]
@vperumal Could you resolve the conflicts

**Comment by vperumal** [comment]
Hi @judyjoseph, I have resolved the conflicts.

**Review by tjchadaga — APPROVED** [review]

**Pull request merged**
