### PR TITLE
qos.yml update for gb topo-t2 and longlink

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

qos.yml update for gb topo-t2 and longlink
Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### CODE REVIEW

**Review by wsycqyz — APPROVED** [review]
LGTM

**Comment by wangxin** [comment]
@zhixzhu Got conflicts after some other PRs are merged. Can you help resolve the new conflicts?

**Comment by zhixzhu** [comment]
> @zhixzhu Got conflicts after some other PRs are merged. Can you help resolve the new conflicts?

@wangxin conflicts resolved.

**Comment by XuChen-MSFT** [comment]
@zhixzhu , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Comment by zhixzhu** [comment]
> @zhixzhu , Can you help to cherry pick to master branch and 202305 branch?
> 
>     * @wangxin @StormLiangMS  for vis

@XuChen-MSFT 
master: https://github.com/sonic-net/sonic-mgmt/pull/9036
202305: https://github.com/sonic-net/sonic-mgmt/pull/9421

**Pull request merged**
