### PR TITLE
Add W-ECMP test plan

### PR DESCRIPTION
**Pull request by weiguo-nvidia**
### Description of PR

Summary: Add W-ECMP test plan re https://github.com/sonic-net/SONiC/blob/master/doc/wcmp/wcmp-design.md
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@nazariig can you please review it (as a feature leader)?
if no comments, this will be merged.

**Review by nazariig — APPROVED** [review]

**Comment by tjchadaga** [comment]
@weiguo-nvidia, @nazariig - Is there a PR with test code changes as well?

**Comment by weiguo-nvidia** [comment]
> @weiguo-nvidia, @nazariig - Is there a PR with test code changes as well?

No test code change, just add test plan

**Comment by nhe-NV** [comment]
@wangxin Can you help to merge the PR as we already did the on line review for it?

**Comment by bingwang-ms** [comment]
@wangxin Can you please help review?

**Review by nhe-NV — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
