### PR TITLE
[Mellanox] Stabilize test_crm_route 

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Fix test issue:https://github.com/sonic-net/sonic-mgmt/issues/12725
For mellanox device, the crm available counter is related to LPM tree. When shutdown all interfaces in vlan (e.g. vlan 1000), it will cause the route (e.g. 192.168.0.1/21 )for vlan to be removed, we have only one route for the prefix (21), after it is removed, the corresponding prefix in LPM tree will be removed too, which will lead to the LPM tree structure is changed. LPM tree change might cause available counter change dramatically, and we cannot estimate how long the change is ready. Therefore, it will lead the first case of test_crm_route fail occasionally because the expected available counter is not decreased. So, we add another route with the same prefix(21) as the vlan's so that the LPM tree is not changed.

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Stabilize test_crm_route

#### How did you do it?
Add another route with the same prefix(21) as the vlan's so that the LPM tree is not changed.

#### How did you verify/test it?
run test_crm_route tests

#### Any platform specific information?
Mellanox

#### Supported testbed topology if it's a new test case?
T0

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Hi @JibinBao, there is another PR https://github.com/sonic-net/sonic-mgmt/pull/12787 that is skipping `test_crm_route` as per the release note of Nvidia. Can you please double confirm? 
@prabhataravind FYI.

**Comment by JibinBao** [comment]
> Hi @JibinBao, there is another PR #12787 that is skipping `test_crm_route` as per the release note of Nvidia. Can you please double confirm? @prabhataravind FYI.

Yes. The fix can resolve the issue. After the fix is merged, I will revert https://github.com/sonic-net/sonic-mgmt/pull/12787

**Comment by prabhataravind** [comment]
Hi @JibinBao, @bingwang-ms 
This change seems to be a workaround for a specific case to keep the LPM tree structure as-is so the available counters check pass. I am concerned that any future change in the test  that can potentially change the LPM tree structure will again cause this test to fail intermittently.

**Comment by JibinBao** [comment]
> This change seems to be a workaround for a specific case to keep the LPM tree structure as-is so the available counters check pass. I

Yes. But it can keep the coverage currrently. I can not predict what test change will cause the LPM tree structure change In the future, but if there is not very special case, it will not cause the LPM structure change. If we meet the issue again in the future, we can change it accordingly. If you have a better solution, please let me know. Thanks.

**Comment by prabhataravind** [comment]
> > This change seems to be a workaround for a specific case to keep the LPM tree structure as-is so the available counters check pass. I
> 
> Yes. But it can keep the coverage currrently. I can not predict what test change will cause the LPM tree structure change In the future, but if there is not very special case, it will not cause the LPM structure change. If we meet the issue again in the future, we can change it accordingly. If you have a better solution, please let me know. Thanks.

I understand that this will help this testcase pass now, but my point is that if this is a known issue that is release-noted by Nvidia, can't we just accept it as a limitation and skip the available counters check to keep the test simple?

**Comment by JibinBao** [comment]
> > > This change seems to be a workaround for a specific case to keep the LPM tree structure as-is so the available counters check pass. I
> > 
> > 
> > Yes. But it can keep the coverage currrently. I can not predict what test change will cause the LPM tree structure change In the future, but if there is not very special case, it will not cause the LPM structure change. If we meet the issue again in the future, we can change it accordingly. If you have a better solution, please let me know. Thanks.
> 
> I understand that this will help this testcase pass now, but my point is that if this is a known issue that is release-noted by Nvidia, can't we just accept it as a limitation and skip the available counters check to keep the test simple?
Hi @prabhataravind 
1. We have verified the fix on mellanox platform for more than 1 month, all passed. So the change should be stable
2. We would like to keep the test coverage for emllanox platform
Thereforce, we hope the community can accecpt the fix.  If in the future, any change causing LMP tree change, we also can fix it accordingly.
Thanks

**Comment by JibinBao** [comment]
> > > > This change seems to be a workaround for a specific case to keep the LPM tree structure as-is so the available counters check pass. I
> > > 
> > > 
> > > Yes. But it can keep the coverage currrently. I can not predict what test change will cause the LPM tree structure change In the future, but if there is not very special case, it will not cause the LPM structure change. If we meet the issue again in the future, we can change it accordingly. If you have a better solution, please let me know. Thanks.
> > 
> > 
> > I understand that this will help this testcase pass now, but my point is that if this is a known issue that is release-noted by Nvidia, can't we just accept it as a limitation and skip the available counters check to keep the test simple?
> > Hi @prabhataravind
> 
> 1. We have verified the fix on mellanox platform for more than 1 month, all passed. So the change should be stable
> 2. We would like to keep the test coverage for emllanox platform
>    Thereforce, we hope the community can accecpt the fix.  If in the future, any change causing LMP tree change, we also can fix it accordingly.
>    Thanks

Hi @prabhataravind Could you approve it?

**Comment by prabhataravind** [comment]
@JibinBao, could you also please raise a PR to revert https://github.com/sonic-net/sonic-mgmt/pull/12787 after this is merged?

**Review by prabhataravind — APPROVED** [review]

**Comment by JibinBao** [comment]
> @JibinBao, could you also please raise a PR to revert #12787 after this is merged?

will do. Thanks

**Comment by JibinBao** [comment]
> > @JibinBao, could you also please raise a PR to revert #12787 after this is merged?
> > @prabhataravind
> > will do. Thanks

@prabhataravind , please review https://github.com/sonic-net/sonic-mgmt/pull/13354

**Review by bingwang-ms — APPROVED** [review]

**Comment by JibinBao** [comment]
> @JibinBao PR conflicts with 202311 branch

@mssonicbld new PR for 202311 is created:https://github.com/sonic-net/sonic-mgmt/pull/13762. Please review it. Thanks

**Pull request merged**
