### PR TITLE
Move the shared part in snappi to common place. 

### PR DESCRIPTION
**Pull request by yutongzhang-microsoft**
### Description of PR

Previously, there are some shared variables and scripts which were located in the feature-specific folder `snappi_tests` and were imported by the common scripts. To reduce cross-feature dependencies and improve modularity, I relocated them directly to the common path `tests/common/snappi_tests`. 

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
Previously, there are some shared variables and scripts which were located in the feature-specific folder `snappi_tests` and were imported by the common scripts. To reduce cross-feature dependencies and improve modularity, I relocated them directly to the common path `tests/common/snappi_tests`. 

#### How did you do it?
I relocated the shared part under folder `snappi` directly to the common path `tests/common/snappi_tests`.

### CODE REVIEW

**Review by sdszhang — APPROVED** [review]
LGTM

**Review by wangxin — APPROVED** [review]

**Comment by deepak-singhal0408** [comment]
@yatishkoul @vmittal-msft @wenyiz2021 for viz..

**Comment by deepak-singhal0408** [comment]
@bingwang-ms could you help approve this for 202405 branch? thanks,
This is causing conflicts while cherry-picking other PRs on top of it. Thanks,

**Comment by yutongzhang-microsoft** [comment]
Hi, @deepak-singhal0408, why do we need to cherry pick?

**Comment by deepak-singhal0408** [comment]
> Hi, @deepak-singhal0408, why do we need to cherry pick?

@yutongzhang-microsoft we are actively making changes to this file for convergence tests in 202405 branch. Since your change is present in Master but not in 202405, its causing conflict for every PR cherry-pick from master->202405.

**Comment by yutongzhang-microsoft** [comment]
> > Hi, @deepak-singhal0408, why do we need to cherry pick?
> 
> @yutongzhang-microsoft we are actively making changes to this file for convergence tests in 202405 branch. Since your change is present in Master but not in 202405, its causing conflict for every PR cherry-pick from master->202405.

@deepak-singhal0408 @bingwang-ms  Please help me review #16817

**Pull request merged**
