### PR TITLE
remove skip of bgp/test_bgp_queue.py on Mellanox platform

### PR DESCRIPTION
**Pull request by illia-kotvitskyi**
the issue is fixed by a new SDK 4000

Change-Id: I8644f90a887044df2ae7b5224103b973999fdaa9

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

### CODE REVIEW

**Comment by wsycqyz** [comment]
Re-trigger failed jobs.

**Comment by illia-kotvitskyi** [comment]
@roy-sror may I ask you to approve this change?

**Review by roy-sror — APPROVED** [review]

**Comment by SavchukRomanLv** [comment]
Hi @bingwang-ms, can you please help to merge?

**Review by bingwang-ms — APPROVED** [review]

**Comment by illia-kotvitskyi** [comment]
Hi @bingwang-ms,
Could we cherry-pick it to 202311 as well?

**Pull request merged**
