### PR TITLE
[chassis] [multi-asic] skip override_config_table test for multi-asic platforms

### PR DESCRIPTION
**Pull request by wenyiz2021**
### Description of PR

test `override_config_table/test_override_config_table.py` creates empty/partial/full configuration and tries to overwrite config_db.json partially or totally, on duthost, for multi-asic platforms.

There is coming change from ndm that golden config db is going to change, so that host config and asic configs are put in the same file, distinguished by keys `localhost` and `asic0` `asic1` ... and there comes PR https://github.com/sonic-net/sonic-utilities/pull/2825 to accommodate new ndm change.

with this new change, especially with https://github.com/sonic-net/sonic-utilities/pull/2825, this `override_config_table/test_override_config_table.py` no longer works for multi-asic scenarios, because test is providing incorrect format of `golden_config_db.json`. e.g. `localhost` and `asicx` is missing in the partial config. Thus we need to skip this test.

Summary:
Fixes # (issue)
https://github.com/sonic-net/sonic-mgmt/issues/8974

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### How did you verify/test it?
After:

```

override_config_table/test_override_config_table.py::test_load_minigraph_with_golden_config SKIPPED                                                                                          [100%]

-------------------------------------------------------------- generated xml file: /var/src/private/sonic-mgmt-int/tests/logs/tr.xml ---------------------------------------------------------------
===================================================================================== short test summary info ======================================================================================
SKIPPED [1] override_config_table/test_override_config_table.py: Skip override-config-table testing on multi-asic platforms, test provided golden config format is not compatible with multi-asics
==================================================================================== 1 skipped in 21.19 seconds ====================================================================================
```

### CODE REVIEW

**Review by wen587 — APPROVED** [review]

**Comment by wenyiz2021** [comment]
./EasyCLA

**Pull request merged**
