### PR TITLE
[ansible/testbed] Support overwriting the env vars defined in groups_vars/all

### PR DESCRIPTION
**Pull request by lizhijianrd**
### Summary:
Support overwriting the environment variables defined in `group_vars/all/env.yml` when add/remove topo.

Variables defined in `group_vars/all/env.yml` will be applied to all inventories when add/remove topo. If you want to provide some environment variables for a specific inventory, you can add it to `group_vars/{your-inventory-name}/env.yml` now. It'll overwrite the values in `group_vars/all/env.yml`.

BTW, you don't have to add an `env.yml` for every inventory directory, `ansible` will skip the overwrite task if file doesn't exist.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?

Support overwriting the environment variables defined in group_vars/all when add/remove topo

#### How did you do it?

Updated `ansible/testbed-cli.sh` and ansible playbooks for add/remove topo.

#### How did you verify/test it?

Verified on virtual testbeds and physical testbeds.

### CODE REVIEW

**Comment by lizhijianrd** [comment]
I don't think we need to back port this feature to any branch. Right?

**Comment by Blueve** [comment]
> I don't think we need to back port this feature to any branch. Right?

Will there env vars only be used when add/remove topo?

**Review by Blueve — APPROVED** [review]

**Comment by lizhijianrd** [comment]
> > I don't think we need to back port this feature to any branch. Right?
> 
> Will there env vars only be used when add/remove topo?

Yes.

**Comment by wangxin** [comment]
This extra behavior will be mixed with the existing ansible group var looking up behaviors. I am not sure if this is the best way to specify vars for hosts in different inventories.

**Review by wangxin — CHANGES_REQUESTED** [review]
As we discussed offline, it would be better to take advantage of how ansible discover and overwrite variables based on group of hosts.

**Comment by lizhijianrd** [comment]
> As we discussed offline, it would be better to take advantage of how ansible discover and overwrite variables based on group of hosts.

Thanks @wangxin, I'll try the method you suggested. Close this PR now.

**Pull request closed without merging**
