### PR TITLE
ipinip delay merge conflict 202205

### PR DESCRIPTION
**Pull request by anshuldubela**
### Description of PR
Port channel fails to come up after the above test. Port channel which
were UP, before the test. The script changes the minimum link from 2 to 1. Then performs
restarts the teamd and all is performed via a single command is likely causing this issue.
All the commands are issued via shell_cmds. Here it executes multiple commands
sequentially. However since multiple command were issued, the previous command may not have completed before
the new command could be executed. This is likely reason for the failure.
**Below is the original PR:**
https://github.com/sonic-net/sonic-mgmt/pull/8417

Summary:
I see this could be timing issue. Failure are seen sometime only. Could not repro the issues. But, looking at the PASS logs, I see messages for min link changes are still running while the next command of teamd restart is triggered. This could lead to failure, when the second command finishes ahead of first.
I could not get a FAIL even after running 20 runs, with all of them PASS.
hence based on analysis the conclusion is that,
It is a timing issue, where min link changes command failure to complete before the second
teamd restart command.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [ ] 202305

### CODE REVIEW

**Comment by wangxin** [comment]
@anshuldubela This looks like a PR for cherry-picking. Can you add the original PR ID in PR description?

**Comment by anshuldubela** [comment]
> @anshuldubela This looks like a PR for cherry-picking. Can you add the original PR ID in PR description?

**Below is the original PR:**
https://github.com/sonic-net/sonic-mgmt/pull/8417

**Review by wangxin — APPROVED** [review]

**Pull request merged**
