### PR TITLE
Adding support for PFCWD  cases for pfcQueueGroupSize of 4

### PR DESCRIPTION
**Pull request by selldinesh**
### Description of PR

Summary: Adding support for PFCWD  cases for pfcQueueGroupSize of 4
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
This PR supports pfcQueueGroupSize of 4 for pfcwd cases , currently the support is for 8

### CODE REVIEW

**Comment by sdszhang** [comment]
@amitpawar12 pls review, thanks.

**Review by sdszhang — APPROVED** [review]
LGTM

**Comment by amitpawar12** [comment]
No comments.

**Comment by amitpawar12** [comment]
Can you please also add the priority<->queue mapping support for the PFC oversubscription testcases as well?

tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py

Thanks,
-A

**Comment by abdosi** [comment]
> tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py

 
1.  Existing testcase do not have Queue Counter validation as checkmark. @selldinesh 
2.  Fix the Flow to Queue Mapping for below tests @amitpawar12

```
tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
```

**Comment by sdszhang** [comment]
1. Existing testcase do not have Queue Counter validation as checkmark.  
  -- Tracked in #13596 
  
2. Fix the Flow to Queue Mapping for below tests.
   @amitpawar12 Can you share the issue ID to track this item?

**Comment by yejianquan** [comment]
> 1. Existing testcase do not have Queue Counter validation as checkmark.
>    -- Tracked in [[PFC] DUT counter check missing in verification for oversubscription cases #13596](https://github.com/sonic-net/sonic-mgmt/issues/13596)
> 2. Fix the Flow to Queue Mapping for below tests.
>    @amitpawar12 Can you share the issue ID to track this item?

I can help to merge this PR, @sdszhang could you create an issue and assign to Amit?

**Comment by sdszhang** [comment]
> > 1. Existing testcase do not have Queue Counter validation as checkmark.
> >    -- Tracked in [[PFC] DUT counter check missing in verification for oversubscription cases #13596](https://github.com/sonic-net/sonic-mgmt/issues/13596)
> > 2. Fix the Flow to Queue Mapping for below tests.
> >    @amitpawar12 Can you share the issue ID to track this item?
> 
> I can help to merge this PR, @sdszhang could you create an issue and assign to Amit?

@yejianquan  #13737  Added.

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by amitpawar12** [comment]
> > > 1. Existing testcase do not have Queue Counter validation as checkmark.
> > >    -- Tracked in [[PFC] DUT counter check missing in verification for oversubscription cases #13596](https://github.com/sonic-net/sonic-mgmt/issues/13596)
> > > 2. Fix the Flow to Queue Mapping for below tests.
> > >    @amitpawar12 Can you share the issue ID to track this item?
> > 
> > 
> > I can help to merge this PR, @sdszhang could you create an issue and assign to Amit?
> 
> @yejianquan #13737 Added.

Hi @sdszhang , @yejianquan -
Raised - #13687 for the item (2).

Thanks,
-A

**Pull request merged**
