### PR TITLE
[Mellanox] Update qos sai tests for spc4 platform

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

1. update qos sai test for sn5400 refering to the two PRs below 

- https://github.com/sonic-net/sonic-mgmt/pull/9583
- https://github.com/sonic-net/sonic-mgmt/pull/12848

2. To stabilize testQosSaiQSharedWatermark[single_asic-wm_q_shared_lossy], update margin from 4 to 5 for spc4

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Update qos sai test for spc4 platform

#### How did you do it?
1. update qos sai test for sn5400
2. To stabilize testQosSaiQSharedWatermark[single_asic-wm_q_shared_lossy], update margin from 4 to 5 for spc4

#### How did you verify/test it?
Run qos tests on spc4 platform

#### Any platform specific information?
spc4

### CODE REVIEW

**Comment by wsycqyz** [comment]
@XuChen-MSFT FYI

**Comment by bingwang-ms** [comment]
@JibinBao Can you please paste or upload the test result for this change?

**Comment by JibinBao** [comment]
> @JibinBao Can you please paste or upload the test result for this change?
All cases passed on the platforms, please see the picture below:
image

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@Pterosaur , @Janetxxx Can you help review?

**Review by Janetxxx — APPROVED** [review]
Looks good to me

**Pull request merged**
