### PR TITLE
Add static-anycast-gateway(SAG) test plan

### PR DESCRIPTION
**Pull request by superchild**
### Description of PR

Summary:
Add new test cases HLD for static-anycast-gateway (SAG) 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### How did you do it?
Bases on the [SAG HLD](https://github.com/Azure/SONiC/pull/837), design needed test cases to verify its functionality.
#### How did you verify/test it?
Executing all SAG sonic-mgmt test cases using edge-core devices

#### Any platform specific information?
N/A
#### Supported testbed topology if it's a new test case?
ptf32, ptf64

### CODE REVIEW

**Comment by superchild** [comment]
@wangxin @yxieca 
Can you help to review the test plan? 
Thanks.

**Comment by zhangyanzhao** [comment]
added maintainers as reviewers. Can you please help to finish the review? Thanks.  @superchild  please sign-off the EasyCLA, that will block the merge.

**Comment by wangxin** [comment]
@superchild Can you add a reference to the design document in the test plan?

**Comment by yxieca** [comment]
@superchild can you sign the CLA?

**Pull request merged**
