### PR TITLE
Fix to use non RegionalHub T3 peers when selecting port. 

### LINKED ISSUE #9021: Voq chassis end to end Ping tests fail
**Description**

Few of the voq end to end tests fail. The tests are : voq/test_voq_ipfwd.py::TestVoqIPFwd::test_voq_end_to_end_ping,  voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut and few of test_voq_disrupts testcases.

The loopback route advt are getting filtered ( by RH route-maps) on the T2 chassis based on the BGP neighborship type as RegionalHub/AZNGHub  --  If the DEVICE_NEIGHBOR_METADATA type is  RegionalHub the loopback ip is filtered 

 This results in ping failure from T1 --> T3 as the reachability to loopback is not present in routing table for those "type" BGP neighbors. Mostly we should be able to fix this in tests - checking on that.

**Steps to reproduce the issue:**
1. Run voq/test_voq_ipfwd.py::TestVoqIPFwd::test_voq_end_to_end_ping,  voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut 
2.
3.

**Describe the results you received:**
End to End ping failure

**Describe the results you expected:**
ping should pass 

**Additional information you deem important:**

    **Output of `show version`:**

    ```
admin@svcstr-7250-lc1-1:~$ show version 

SONiC Software Version: SONiC.20220530.36
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: dfd7ce3082
Build date: Fri Jul 14 04:56:49 UTC 20
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

### PR DESCRIPTION
**Pull request by judyjoseph**
### Description of PR
When the minigraph/Config has T3 Peer is a "Regional Hub" type in DEVICE_NEIGHBOR_METADATA and if we select that T3 peer loopback IP for end to end ping -- the ping from T1 --> T3 loopback ip fails. This is because the the routemaps for that "Regional Hub" type filter the loopback routes advertised to SONiC T2.

Summary:
Fixes #9021

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)


### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### Approach
#### What is the motivation for this PR?
#### How did you do it?
Fix was to use T3 peer devices of this SONiC T2 which is of other types like AZNGHub. So filter the ethernet/portchannel interfaces based on which peer type it is connected to.

#### How did you verify/test it?
Ran the above tests which were failing earlier and it passes now.

```
collected 20 items                                                                                                                                                                                                                      

voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-4-portA-my_ip] PASSED                                                                                                                                              [  5%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-4-portA-my_lb_ip] PASSED                                                                                                                                           [ 10%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-4-portA-inband] PASSED                                                                                                                                             [ 15%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-4-portD-my_lb_ip] PASSED                                                                                                                                           [ 20%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-4-portD-inband] PASSED                                                                                                                                             [ 25%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-6-portA-my_ip] PASSED                                                                                                                                              [ 30%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-6-portA-my_lb_ip] PASSED                                                                                                                                           [ 35%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-6-portA-inband] PASSED                                                                                                                                             [ 40%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-6-portD-my_lb_ip] PASSED                                                                                                                                           [ 45%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[ethernet-6-portD-inband] PASSED                                                                                                                                             [ 50%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-4-portA-my_ip] PASSED                                                                                                                                           [ 55%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-4-portA-my_lb_ip] PASSED                                                                                                                                        [ 60%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-4-portA-inband] PASSED                                                                                                                                          [ 65%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-4-portD-my_lb_ip] PASSED                                                                                                                                        [ 70%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-4-portD-inband] PASSED                                                                                                                                          [ 75%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-6-portA-my_ip] PASSED                                                                                                                                           [ 80%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-6-portA-my_lb_ip] PASSED                                                                                                                                        [ 85%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-6-portA-inband] PASSED                                                                                                                                          [ 90%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-6-portD-my_lb_ip] PASSED                                                                                                                                        [ 95%]
voq/test_voq_ipfwd.py::test_ipforwarding_jumbo_to_dut[portchannel-6-portD-inband] PASSED                                                                                                                                          [100%]

------------------------------------------------------------------------------------- generated xml file: /var/src/sonic-mgmt-int/tests/logs/tr.xml -------------------------------------------------------------------------------------
====================================================================================================== 20 passed in 618.00 seconds ======================================================================================================
```

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]
lgtm

**Comment by wangxin** [comment]
This PR was merged before 202305 branch was created. Removing 202305 related labels.

**Comment by wangxin** [comment]
> @judyjoseph PR conflicts with 202305 branch

Already included in 202305 branch.

**Comment by wangxin** [comment]
> @judyjoseph PR conflicts with 202205 branch

Already cherry-picked to 202205 branch.

**Pull request merged**
