### PR TITLE
Add cEOS neighbor support for bgp/test_4-byte_asn_community.py

### PR DESCRIPTION
**Pull request by sdszhang**
### Description of PR

Summary:
Add cEOS neighbor support for test_4-byte_asn_community.py.  Current test case only support SONiC neighbors. this PR will improve coverage with more neighbor type.

Future works to improve, not in this PR:
-  implement SONiC specific BGP operations in class `SonicBGPRouter`. and change the current command check method to using class method for BGP configuration/verification.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Improve test coverage by adding cEOS support to the test case.

#### How did you do it?
Defined a base class for common BGP operations. `class BGPRouter(ABC):`, and implemented platfor specific BGP operations for cEOS neighbors.

#### How did you verify/test it?
```
bgp/test_4-byte_asn_community.py::test_4_byte_asn_community[vlab-01-None] PASSED [100%]
```

### CODE REVIEW

**Review by yejianquan — DISMISSED** [review]
LGTM

**Comment by sdszhang** [comment]
@Azarack can you help to review? Thanks.

**Review by Azarack — APPROVED** [review]

**Comment by sdszhang** [comment]
Results:

virtual testbed
```
bgp/test_4-byte_asn_community.py::test_4_byte_asn_community[vlab-01-None] PASSED [100%]
```

physical testbed:
```
bgp/test_4-byte_asn_community.py::test_4_byte_asn_community[str-a7060cx-acs-10-None] PASSED [100%]
```

T2 testbed:
```
bgp/test_4-byte_asn_community.py::test_4_byte_asn_community[xx-lc1-2-1] PASSED [ 50%]
bgp/test_4-byte_asn_community.py::test_4_byte_asn_community[xx-lc2-2-0] PASSED [100%]
```

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
