### PR TITLE
Add dpu-1 topo for dpu with only one single port

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Summary:
Add dpu-1 topo for dpu with single one port
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [X] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305

#### What is the motivation for this PR?
Add dpu-1 topo

#### How did you do it?
Add dpu-1 topo

#### How did you verify/test it?
Test i on dpu-1 topo

### CODE REVIEW

**Review by Pterosaur — COMMENTED** [review]
NIT: The file, dpu-1-tor.j2, looks totally the same as the file `dpu-tor.j2` Maybe create a symbol linker to dpu-tor.j2 is better.

**Comment by prsunny** [comment]
Is this meant for virtual smartswitch testbed? If not, whats the purpose of this topo?

**Comment by liat-grozovik** [comment]
yes, this is for the virtual switch.

**Comment by JibinBao** [comment]
> NIT: The file, dpu-1-tor.j2, looks totally the same as the file `dpu-tor.j2` Maybe create a symbol linker to dpu-tor.j2 is better.

Will update it

**Comment by JibinBao** [comment]
> NIT: The file, dpu-1-tor.j2, looks totally the same as the file `dpu-tor.j2` Maybe create a symbol linker to dpu-tor.j2 is better.
@Pterosaur 
Done. Can you help review it again?

**Review by Pterosaur — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
