### PR TITLE
Add an ansible-playbook to collect `show tech` result of a specific testbed

### PR DESCRIPTION
**Pull request by lizhijianrd**
### Description of PR

Summary:
Add an ansible-playbook to collect `show techsupport` results on all DUTs of a specific testbed.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205

#### What is the motivation for this PR?

Add an ansible-playbook to collect `show techsupport` results on all DUTs of a specific testbed.

#### How did you do it?

In the ansible-playbook:
1. Run `show techsupport` on all the DUTs of a specific testbed.
2. Fetch the dumped files to localhost.
3. Delete the dumped files on DUT (to release disk space).
I also integrated this utility to `testbed-cli.sh`.

#### How did you verify/test it?

Verified on physical testbeds.

### CODE REVIEW

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Failed<br/>- hook id: trailing-whitespace<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing ansible/collect_show_tech.yml<br/><br/>fix end of files.........................................................Passed<br/>check yaml...............................................................Passed<br/>check for added large files..............................................Passed<br/>check python ast.....................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
@lizhijianrd Merging this PR to 202205 branch has many conflicts. Can you help create a separate PR to 202205 branch?

**Comment by wangxin** [comment]
Cherry picking to 202012 branch has conflicts too.

**Comment by lizhijianrd** [comment]
> @lizhijianrd Merging this PR to 202205 branch has many conflicts. Can you help create a separate PR to 202205 branch?

Cherry-Pick to 202205 in #7577

**Comment by lizhijianrd** [comment]
> Cherry picking to 202012 branch has conflicts too.

Cherry-Pick to 202012 in #7578

**Pull request merged**
