### PR TITLE
Fix test_lag_2.py for multi-asic

### PR DESCRIPTION
**Pull request by ysmanman**
### Description of PR

Fix test_lag_2.py for multi-asic. 
The PR addresses issue https://github.com/sonic-net/sonic-mgmt/issues/7281.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### CODE REVIEW

**Comment by ysmanman** [comment]
Add @arlakshm for visibility.

**Comment by abdosi** [comment]
cc @vperumal for viz.

**Comment by anamehra** [comment]
> cc @anamehra this will help with some of failure we are seeing ?

Hi @abdosi , we were using a patch of https://github.com/sonic-net/sonic-mgmt/pull/6213 which I raised upstream but then closed because there is another old PR, still not merged, https://github.com/sonic-net/sonic-mgmt/pull/6055
for multi-asic support. We are using an internal fix for meanwhile while waiting for that to be merged.

@ysmanman , please check if https://github.com/sonic-net/sonic-mgmt/pull/6055 works for you.

**Comment by wenyiz2021** [comment]
@ysmanman think https://github.com/sonic-net/sonic-mgmt/pull/6055 has merged the support for masic, please check, thanks

**Comment by rlhui** [comment]
@ysmanman thanks a lot for fixing this. Should this one be closed?

**Pull request closed without merging**
