### PR TITLE
[QoS] J2C+ _qos_yaml  for 400 and 100G 

### PR DESCRIPTION
**Pull request by ansrajpu-git**
### Description of PR

Updated qos test params for 400g and 100g port speeds for the new vsq threshold introduced in PR#https://github.com/sonic-net/sonic-buildimage/pull/18239

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### How did you verify/test it?
Executed  Qos test for  j2C+  t2 topology

### CODE REVIEW

**Comment by ansrajpu-git** [comment]
@vmittal-msft .PR updated . Please review

**Comment by vmittal-msft** [comment]
@kenneth-arista we will need similar value for Arista HWSKUs for J2.

**Comment by arlakshm** [comment]
@kenneth-arista, to create another PR for J2

**Comment by ansrajpu-git** [comment]
This PR changes are reflected now in the master PR -https://github.com/sonic-net/sonic-mgmt/pull/13069.
Hence closing this PR.

**Pull request closed without merging**
