### PR TITLE
Added flow rules for OSPF and BFD

### PR DESCRIPTION
**Pull request by Ghulam-Bahoo**
### Description of PR

Summary:
This PR is intended to add flow rules for OSPF and BFD traffic from an external interface to a VM and a PTF container

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
To allow OSPF and BFD traffic between DUT and the neighboring devices in t0 or t1 topology by adding flow rules.
#### How did you do it?
By adding flow rules to sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file.

### CODE REVIEW

**Comment by Ghulam-Bahoo** [comment]
@yxieca can you help review and merge this PR? Initially, we were facing issues with OSPF configurations between DUT and neighboring devices so we added flow riles for OSPF traffic to the sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file and successfully built it locally.

Now after the changes, OSPF is successfully configured between DUT and neighboring devices in t0.

**Comment by yxieca** [comment]
> @yxieca can you help review and merge this PR? Initially, we were facing issues with OSPF configurations between DUT and neighboring devices so we added flow rules for OSPF traffic to the sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file and successfully built it locally.
> 
> Now after the changes, OSPF is successfully configured between DUT and neighboring devices in t0.

@Ghulam-Bahoo can you attach a summary snippet of test results?

**Comment by asraza07** [comment]
> > @yxieca can you help review and merge this PR? Initially, we were facing issues with OSPF configurations between DUT and neighboring devices so we added flow rules for OSPF traffic to the sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file and successfully built it locally.
> > Now after the changes, OSPF is successfully configured between DUT and neighboring devices in t0.
> 
> @Ghulam-Bahoo can you attach a summary snippet of test results?

Hi @yxieca , here are two screenshots showing OSPF and BFD configurations working properly after the addition of our new flows:
DUT OSPF Configuration
DUT OSPF BFD Config

**Comment by yxieca** [comment]
> > > @yxieca can you help review and merge this PR? Initially, we were facing issues with OSPF configurations between DUT and neighboring devices so we added flow rules for OSPF traffic to the sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file and successfully built it locally.
> > > Now after the changes, OSPF is successfully configured between DUT and neighboring devices in t0.
> > 
> > 
> > @Ghulam-Bahoo can you attach a summary snippet of test results?
> 
> Hi @yxieca , here are two screenshots showing OSPF and BFD configurations working properly after the addition of our new flows: DUT OSPF Configuration DUT OSPF BFD Config

@asraza07 this looks good. Did the test pass?

**Comment by ridahanif96** [comment]
> > > > @yxieca can you help review and merge this PR? Initially, we were facing issues with OSPF configurations between DUT and neighboring devices so we added flow rules for OSPF traffic to the sonic-mgmt/ansible/roles/vm_set/library/vm_topology.py file and successfully built it locally.
> > > > Now after the changes, OSPF is successfully configured between DUT and neighboring devices in t0.
> > > 
> > > 
> > > @Ghulam-Bahoo can you attach a summary snippet of test results?
> > 
> > Hi @yxieca , here are two screenshots showing OSPF and BFD configurations working properly after the addition of our new flows: DUT OSPF Configuration DUT OSPF BFD Config
> 
> @asraza07 this looks good. Did the test pass?

Hi @yxieca , 
 Yes the tests Passed.

**Pull request merged**
