### PR TITLE
Adding GRE ERSPAN type-2 for Marvell platform

### PR DESCRIPTION
**Pull request by rajneeshaec**
Summary:
Fixes # (issue)
Adding GRE ERSPAN type-2 for Marvell platform

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ X] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [X ] 202305
- [ X] 202311

#### What is the motivation for this PR?
Added GRE ERSPAN type-2 for Marvell platform 

#### How did you do it?
Added GRE ERSPAN type-2 for Marvell platform and changed the ethertype.

#### How did you verify/test it?
Verified on Marvell platform.

#### Any platform specific information?
Yes

### CODE REVIEW

**Comment by tudupa** [comment]
@rajneeshaec Can you please include "Nokia-7215-A1" HwSKU as well in this PR.

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
@rajneeshaec can you resolve all test failures? If you believe they are flaky, please re-run them.

**Comment by johnchiucc** [comment]
@Blueve  could you help merge this one?

**Review by wangxin — APPROVED** [review]

**Comment by Pavan-Nokia** [comment]
@mssonicbld @wangxin Could you please help backport to 2405 and 2311 branches

**Pull request merged**
