### PR TITLE
[dhcp_server_test] Enable autorestart before test dhcp server container autorestart

### PR DESCRIPTION
**Pull request by w1nda**
### Description of PR

Summary:
Fixes # (issue)
 test_pretest.py disables autorestart for all features, so if we want to test dhcp server autorestart we need to enable it.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
test_pretest.py disables autorestart for all features, so if we want to test dhcp server autorestart we need to enable it.

#### How did you do it?
Enable autorestart before test

### CODE REVIEW

**Review by yaqiangz — APPROVED** [review]

**Comment by w1nda** [comment]
Hi @wangxin, cloud you help merge this PR? thanks.

**Review by yaqiangz — APPROVED** [review]

**Comment by w1nda** [comment]
Hi @wangxin , cloud you merge this PR? thanks

**Comment by w1nda** [comment]
Hi @yejianquan, thanks for trggering the pipeline, the validation passed.
Cloud you help merge this PR?

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
