### PR TITLE
cisco: multi-asic topo t2 addition to qos.yaml

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Adding topo-t2 for cisco-8000 in qos.yml file for gb asic. This will be needed to run the multi-asic code in qos-sai on t2 platforms

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
let's have the PR directed for master. we can do testing on 202205 branch. Point is we don;t want to miss some changes in master.

**Review by abdosi — CHANGES_REQUESTED** [review]
as comment

**Review by abdosi — APPROVED** [review]
for master separate PR will be there once multi-asic comes in master. Tracked by Cisco.

**Comment by abdosi** [comment]
Please rebase with latest 202205.

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco @abdosi
Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Pull request merged**
