### PR TITLE
Increase the ready timeout for fast reboot test

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Increase the ready timeout from 180 to 540.
This is due to the flow was modified so that counter initialization happens approximately 5 minutes after the boot, which is introduced in PR - 
https://github.com/sonic-net/sonic-sairedis/pull/1362

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Due to PR https://github.com/sonic-net/sonic-sairedis/pull/1362, the ready timeout in continuous fast reboot test should be increased.
#### How did you do it?
Increase the ready timeout from 180 to 540.
#### How did you verify/test it?
Run it in internal regression

### CODE REVIEW

**Comment by echuawu** [comment]
> Are we still using this Ansible playbook?

Yes, we are using this playbook as well.

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
It's surprising to me that the Ansible playbook is still being used. What's the justification to backport the change to 202405?

**Comment by echuawu** [comment]
Hi @bingwang-ms , so you have not run this case in 202405?

**Comment by bingwang-ms** [comment]
We are not using Ansible playbook to run test. I'm not sure if I understand the question.

**Pull request merged**
