### PR TITLE
Cisco: Fixing get_multiple_flows for T0.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
Addressing the following issues:
1. In T0 topology, since the packet can take any port in a Vlan, the get_multiple_flows function runs in to infinite loop. To avoid this, we set a limit on the loop to 20, and if it runs out, we use the port that packet is actually taking instead of the user-provided one. 
2. addressing the keyerror in BufferPoolWatermark testcase.
3. Addressed the assert error in AllPortQWatermark for T0.

@XuChen-MSFT : Pls review.

### CODE REVIEW

**Review by XuChen-MSFT — CHANGES_REQUESTED** [review]
@rraghav-cisco , please commit to master first to make sure pass the PR test

**Comment by rraghav-cisco** [comment]
> @rraghav-cisco , please commit to master first to make sure pass the PR test

@XuChen-MSFT : master doesn't have get_multiple_flows yet.

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco , directly commit to 202205 is not allowed now, except urgent fix approved by Storm, Xin, Ying and Guohan. And this not new rule, it run for long time, just break by some chassis PRs about one or two month ago. Now we need to re-enable this rule to make sure PR qulity.
And we had leaved message in previous PR only committed in 202205, and ask for cherry pick them back to master branch.

please help commit those previous PRs to resolve dependency.

+ @wangxin @StormLiangMS for vis

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT / @StormLiangMS : This is one of the critical bug fixes - since it fixes the get_multiple_flows in 202205. As such, I request this to be approved for merger to 202205. Thanks!

**Comment by neethajohn** [comment]
@XuChen-MSFT , will this PR fix the issues that were seen in t0-backend and t1-backend runs after commit of #8399? The failing cases are Xon, PgSharedWm, Dwrr and LossyQueue

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco 
As Neetha metioned above, need you help to double commit this PR to 202012 branch, to resolve the failure of Xon, PgSharedWm, Dwrr and LossyQueue.

and for this PR, we still need you to commit master first, and then cherry pick to 202205.

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco ,
backend qos test were broken for long time, we try to revert get_multple_flow() part in PR https://github.com/sonic-net/sonic-mgmt/pull/9748 .

**Comment by yxieca** [comment]
> @rraghav-cisco As Neetha metioned above, need you help to double commit this PR to 202012 branch, to resolve the failure of Xon, PgSharedWm, Dwrr and LossyQueue.
> 
> and for this PR, we still need you to commit master first, and then cherry pick to 202205.

How about leaving this PR for 202205 but merge with master PR when the other PR is ready?

**Review by XuChen-MSFT — APPROVED** [review]
as Ying's suggestion, commit it to 202205 branch . But need to double commit to master/202012/202305 branch soon later.

**Comment by XuChen-MSFT** [comment]
@wangxin 
can you help to merge to 202205?

**Pull request merged**
