### PR TITLE
Add ERR log ignore for ECMP/LAG hash not supported

### PR DESCRIPTION
**Pull request by justin-wong-ce**
### Description of PR

Summary: 
On Broadcom platforms, ECMP/LAG hash is not supported. Adding ERR log ignore as it is expected for this error log to print.

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
On Broadcom platforms, ECMP/LAG hash is not supported. Adding ERR log ignore as it is expected for this error log to print.

#### How did you do it?
Added log regex to `loganalyzer_common_ignore.txt`

#### How did you verify/test it?
`snmp/test_snmp_queue_counters.py` no longer fails on loganalyzer error on Broadcom platform.

#### Any platform specific information?
Only applies to Broadcom platform.

### CODE REVIEW

**Review by StormLiangMS — DISMISSED** [review]
LGTM

**Comment by justin-wong-ce** [comment]
^Fixed merge conflict

**Review by Gfrom2016 — APPROVED** [review]
LGTM

**Comment by justin-wong-ce** [comment]
This log ignore causes one of the tests that are expected to fail in the CI check to pass, will be moving this logignore to manual extend in the individual test files with `loganalyzer[dutIndex].ignore_regex.extend`

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by justin-wong-ce** [comment]
> @justin-wong-ce PR conflicts with 202405 branch

202405 PR with conflict solved:
https://github.com/sonic-net/sonic-mgmt/pull/16165

**Pull request merged**
