### PR TITLE
Disable loganalyzer for voq_disrupts test

### LINKED ISSUE #15916: [Bug]: VOQ disrupts test log analyzer failures
### Issue Description

When an LC or a supervisor is rebooted it produces a lot of logs irrelevant to the individual testcases. This is one of the drawbacks faced by the voq disrupts tests that reboots the device and fails because of these unaccounted error logs. The errors can be reproduced by running `test_reboot_supervisor` in a T2 topology.

In testcases the involve a reboot the loganalyzer is usually disabled. This can be seen in testcases like:

- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/pfcwd/test_pfcwd_warm_reboot.py#L37
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/platform_tests/test_power_off_reboot.py#L12
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/platform_tests/test_cont_warm_reboot.py#L23

### Results you see

A number of log analyzer errors that are unrelated to VOQs

### Results you expected to see

I expect the runs to catch/check voq related errors

### Is it platform specific

generic

### Relevant log output

```
	 E               Failed: Processes "['analyze_logs--<MultiAsicSonicHost cmp214>', 'analyze_logs--<MultiAsicSonicHost cmp214-6>', 'analyze_logs--<MultiAsicSonicHost cmp214-5>']" failed with exit code "1"
	 E               Exception:
	 E               match: 17
	 E               expected_match: 0
	 E               expected_missing_match: 0
	 E
	 E               Match Messages:
	 E               2024 Sep 23 07:13:24.492029 cmp214 ERR kernel: [18641.674628] pcieport 0000:68:02.0: Unable to change power state from D3hot to D0, device inaccessible
	 E
	 E               2024 Sep 23 07:14:49.234564 cmp214 ERR kernel: [    1.130366] tpm tpm0: [Firmware Bug]: TPM interrupt not working, polling instead
	 E
	 E               2024 Sep 23 07:14:49.235332 cmp214 WARNING kernel: [   18.724950] EXT4-fs (loop1): warning: mounting fs with errors, running e2fsck is recommended
	 E
	 E               2024 Sep 23 07:15:37.268005 cmp214 ERR CCmisApi: system_servicetoo many values to unpack (expected 2)
	 E
	 E               2024 Sep 23 07:15:39.982507 cmp214 ERR eventd#eventd: :- deserialize: deserialize Failed: input stream errorstr[0:64]:(#001) data type: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&
	 E
	 E               2024 Sep 23 07:20:20.055070 cmp214 ERR syncd10#syncd: [3b:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.224719 cmp214 ERR syncd1#syncd: [10:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.394472 cmp214 ERR syncd7#syncd: [2e:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.402920 cmp214 ERR syncd9#syncd: [38:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.786212 cmp214 ERR syncd2#syncd: [13:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.856832 cmp214 ERR syncd8#syncd: [31:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.102896 cmp214 ERR syncd11#syncd: [42:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.433288 cmp214 ERR syncd3#syncd: [1a:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.607603 cmp214 ERR syncd0#syncd: [09:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.623071 cmp214 ERR syncd6#syncd: [27:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.780340 cmp214 ERR syncd5#syncd: [24:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.815145 cmp214 ERR syncd4#syncd: [1d:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               Traceback:
	 E               Traceback (most recent call last):
	 E                 File "/data/tests/common/helpers/parallel.py", line 35, in run
	 E                   Process.run(self)
	 E                 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
	 E                   self._target(*self._args, **self._kwargs)
	 E                 File "/data/tests/common/helpers/parallel.py", line 245, in wrapper
	 E                   target(*args, **kwargs)
	 E                 File "/data/tests/common/plugins/loganalyzer/__init__.py", line 45, in analyze_logs
	 E                   dut_analyzer.analyze(markers[node.hostname], fail_test, store_la_logs=store_la_logs)
	 E                 File "/data/tests/common/plugins/loganalyzer/loganalyzer.py", line 409, in analyze
	 E                   self._verify_log(analyzer_summary)
	 E                 File "/data/tests/common/plugins/loganalyzer/loganalyzer.py", line 140, in _verify_log
	 E                   raise LogAnalyzerError(result_str)
	 E               tests.common.plugins.loganalyzer.loganalyzer.LogAnalyzerError: match: 17
	 E               expected_match: 0
	 E               expected_missing_match: 0
	 E
	 E               Match Messages:
	 E               2024 Sep 23 07:13:24.492029 cmp214 ERR kernel: [18641.674628] pcieport 0000:68:02.0: Unable to change power state from D3hot to D0, device inaccessible
	 E
	 E               2024 Sep 23 07:14:49.234564 cmp214 ERR kernel: [    1.130366] tpm tpm0: [Firmware Bug]: TPM interrupt not working, polling instead
	 E
	 E               2024 Sep 23 07:14:49.235332 cmp214 WARNING kernel: [   18.724950] EXT4-fs (loop1): warning: mounting fs with errors, running e2fsck is recommended
	 E
	 E               2024 Sep 23 07:15:37.268005 cmp214 ERR CCmisApi: system_servicetoo many values to unpack (expected 2)
	 E
	 E               2024 Sep 23 07:15:39.982507 cmp214 ERR eventd#eventd: :- deserialize: deserialize Failed: input stream errorstr[0:64]:(#001) data type: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&
	 E
	 E               2024 Sep 23 07:20:20.055070 cmp214 ERR syncd10#syncd: [3b:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.224719 cmp214 ERR syncd1#syncd: [10:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.394472 cmp214 ERR syncd7#syncd: [2e:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.402920 cmp214 ERR syncd9#syncd: [38:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.786212 cmp214 ERR syncd2#syncd: [13:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:20.856832 cmp214 ERR syncd8#syncd: [31:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.102896 cmp214 ERR syncd11#syncd: [42:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.433288 cmp214 ERR syncd3#syncd: [1a:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.607603 cmp214 ERR syncd0#syncd: [09:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.623071 cmp214 ERR syncd6#syncd: [27:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.780340 cmp214 ERR syncd5#syncd: [24:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
	 E
	 E               2024 Sep 23 07:20:21.815145 cmp214 ERR syncd4#syncd: [1d:00.0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:6654 Get switch attrib 37 failed with error Feature unavailable (0xfffffff0).
```

### Output of `show version`

```shell
SONiC Software Version: SONiC.branch.202405-ars.bdc49266-buildimage.origin.202405-nightly-dbg-2024.11.28.22.44
SONiC OS Version: 12
Distribution: Debian 12.8
Kernel: 6.1.0-22-2-amd64
Build commit: 3c6372b8e
Build date: Fri Nov 29 08:41:16 UTC 2024

Platform: x86_64-arista_7800_sup
HwSKU: Arista-7804R3-FM
ASIC: broadcom
ASIC Count: 12
Serial Number: SSN20290119
Model Number: DCS-7800-SUP1A
Hardware Revision: 01.0a
Uptime: 18:55:31 up 2 days,  3:06,  1 user,  load average: 5.89, 6.11, 6.34
Date: Thu 05 Dec 2024 18:55:31
```

### Attach files (if any)

_No response_

### PR DESCRIPTION
**Pull request by arista-hpandya**
### Description of PR

Summary:
Fixes #15916 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
When an LC or a supervisor is rebooted it produces a lot of logs irrelevant to the individual testcases. This is one of the drawbacks faced by the voq disrupts tests that reboots the device and fails because of these unaccounted error logs. Following the theme seen in the below tests that call reboots, I have disabled the log analyzer in voq disrupt to make sure the test focuses more on catching the voq related failures.

- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/pfcwd/test_pfcwd_warm_reboot.py#L37
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/platform_tests/test_power_off_reboot.py#L12
- https://github.com/sonic-net/sonic-mgmt/blob/7e7dded7e51fa08e4fcff2efe1e0b0d412a3c230/tests/platform_tests/test_cont_warm_reboot.py#L23

#### How did you do it?
By adding the `pytest.mark.disable_loganalyzer` pytest mark

#### How did you verify/test it?
I have run the test on a T2 topology and verified that we no longer hit the loganalyzer errors

#### Any platform specific information?
NA

#### Supported testbed topology if it's a new test case?
NA

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@arlakshm for awareness

**Comment by arista-hpandya** [comment]
Looks like the pipeline failed with an Azure authentication error:

```
##[error]Error Code: [1]
##[error]Error: Azure login failed
##[error]Script failed with error: ERROR: AADSTS500031: Cannot find signing certificate configured. Trace ID: b11efad7-3c3b-4607-9c3f-d81b4ce04500 Correlation ID: e76892ba-b02e-4a05-acb9-1a03c19be3b7 Timestamp: 2024-12-05 22:00:55Z
Interactive authentication is needed. Please run:
az login
```

Can someone from MSFT rerun the pipeline? @arlakshm @wenyiz2021

**Comment by arista-hpandya** [comment]
@arlakshm @wenyiz2021 It seems like I don't have the permission to kickstart the pipeline run. Since the failure seems unrelated to the change can you please help me re-run the checks?

**Review by wenyiz2021 — APPROVED** [review]

**Comment by yxieca** [comment]
@arista-hpandya @wenyiz2021 I suggest add the offending error logs to the issue and assess if we should white-list them instead? disabling the log analyzer will generally ignore all issues could be caught by log analyzer therefore leaving windows for regression.

**Comment by wenyiz2021** [comment]
> @arista-hpandya @wenyiz2021 I suggest add the offending error logs to the issue and assess if we should white-list them instead? disabling the log analyzer will generally ignore all issues could be caught by log analyzer therefore leaving windows for regression.

@yxieca , here the error logs happened due to reboot, since the other reboot cases are disabling loganalyzer, and this test are all reboot tests except 1 config reload test.

I think it would be hard to whitelist all errors due to reboot.
If we really want to do whitelist, then it should be applicable for other reboot tests?

**Comment by arista-hpandya** [comment]
If you wish I can open an issue for these untracked loganalyzer errors which would ensure that they don't slide away while giving the voq reboot tests the ability to run and verify reboot related checks

**Comment by yxieca** [comment]
> > @arista-hpandya @wenyiz2021 I suggest add the offending error logs to the issue and assess if we should white-list them instead? disabling the log analyzer will generally ignore all issues could be caught by log analyzer therefore leaving windows for regression.
> 
> Hi @yxieca and @wenyiz2021 , thank you for reviewing the change. To my knowledge the current process of ignoring logs is via adding them to `ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt`. The issue with this approach is that it is not test specific. As you rightly mentioned many of these issues raised by loganalyzer are valid issues/regressions to look at. In fact many of them are reproducible in other tests and are being actively worked upon. Adding these logs in the ignore file will hide these errors from all tests and not just the voq_disrupts tests.

The log analyzer infrastructure support adding whitelist to a single test case.

With that said, reboot related error logs is long and Wenyi is right, other tests currently also choose to disable log analyzer.

**Comment by wenyiz2021** [comment]
there is a way to ignore certain syslog on the testcase 
https://github.com/sonic-net/sonic-mgmt/blob/4aa835e441f6c35a7c35f8f7ba62ae09971e3f76/tests/autorestart/test_container_autorestart.py#L82C5-L82C42

**Comment by arista-hpandya** [comment]
Thank you @wenyiz2021 and @yxieca for the prompt response. Based on the discussion can we go ahead and merge this change for consistency across all reboot test cases.

**Review by rlhui — APPROVED** [review]

**Pull request merged**
