### PR TITLE
Skip broadcast test for dual TOR

### PR DESCRIPTION
**Pull request by ganglyu**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
VLAN tests failed on dual TOR.

#### How did you do it?
Skip broadcast test for dual TOR.

#### How did you verify/test it?
Run VLAN tests on dual TOR.

### CODE REVIEW

**Review by lolyu — COMMENTED** [review]
LGTM

**Comment by prsunny** [comment]
I thought, some of these tests on dualtor explicitly sets one side to "all" active and execute the tests in which case these tests should pass. @theasianpianist , could you review?

**Comment by ganglyu** [comment]
> I thought, some of these tests on dualtor explicitly sets one side to "all" active and execute the tests in which case these tests should pass. @theasianpianist , could you review?

The same test failed on dual tor and passed on single tor.

**Review by prsunny — APPROVED** [review]

**Comment by ganglyu** [comment]
@theasianpianist 
Would you please confirm?

**Pull request merged**
