### PR TITLE
Enable pre-commit code check

### PR DESCRIPTION
**Pull request by wangxin**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
The pre-commit framework is an easy to use and powerful framework that can
be used in git hooks.

This PR enables the pre-commit code check to ensure better code quality.

#### How did you do it?
* Added pre-commit configuration
* Updated the azure pipeline yaml to run pre-commit check.

### CODE REVIEW

**Comment by wangxin** [comment]
Comment injected through API

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check failed for this pull request.
Please install pre-commit, run pre-commit check to find out what failed, then fix the issues.

Steps:
1. Ensure that the `pre-commit` package is installed
```
sudo pip install pre-commit
```
2. Go to repository root folder and run below commands to do a local pre-commit check.
```
pre-commit install     # Install the pre-commit git hooks
pre-commit             # Check staged files
pre-commit run --from-ref <commit_id> --to-ref HEAD     # Check touched files from <commit_id> to HEAD.
```
3. Fix the issues, then commit and push to update your pull request.

**Comment by yejianquan** [comment]
LGTM

**Review by yejianquan — APPROVED** [review]

**Pull request merged**
