### PR TITLE
cisco: qos-sai: Update all-port-q-wm to use the dscp->Q mapping from the DUT itself.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
The test testQosSaiQWatermarkAllPorts has a hardcoded dscp->queue mapping data. This PR updates it to read the mapping data from the DUT and use that for testing. Changes:
1. Update the test_qos_sai.py::testQosSaiQWatermarkAllPorts to read the dscp->queue mapping from DUT.
2. Pass the new parameter to the PTF script.
3. Change the PTF script to use the CLI argument for the mapping instead of the hard-coded value.

@XuChen-MSFT  and @abdosi  for review.

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
================================================================================================================= short test summary info ==================================================================================================================
SKIPPED [1] /data/tests/qos/qos_sai_base.py:511: Did not find any frontend node that is multi-asic - so can't run single_dut_multi_asic tests
SKIPPED [1] /data/tests/qos/qos_sai_base.py:517: multi-dut is not supported on T1 topologies
========================================================================================================== 1 passed, 2 skipped in 914.59 seconds ===========================================================================================================
AzDevOps@99027110b121:/data/tests$ less /run_logs/logs/qos/tr_2023-07-12-16-27-21.xml

**Review by abdosi — APPROVED** [review]

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT : Pls let me know if you have any comments.

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me.
and pass qos sai test on 8101 after apply this script changes

**Comment by XuChen-MSFT** [comment]
@rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?

+ @wangxin @StormLiangMS  for vis

**Comment by rlhui** [comment]
> @rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?
> 
> * @wangxin @StormLiangMS  for vis

Shouldn't the PR be created in master branch first, and then cherry-pick to 202205 and 202305?

**Comment by XuChen-MSFT** [comment]
Because of PR https://github.com/sonic-net/sonic-mgmt/pull/8266,
This pr had became the dependency of many qos PRs. Before it was committed to the master, most of qos PRs could not be committed to the master.

**Comment by StormLiangMS** [comment]
> > @rraghav-cisco @abdosi , Can you help to cherry pick to master branch and 202305 branch?
> > 
> > * @wangxin @StormLiangMS  for vis
> 
> Shouldn't the PR be created in master branch first, and then cherry-pick to 202205 and 202305?

#8266, which went to 202205, many followed PRs went to 202205 only also, since infra code changed in #8266, which was not in master. As we discussed, after cherry-pick #8266 to master, all new PRs must go into master, then cherry-pick to 202205 and 202305. And only bug fix is allowed to be cherry-picked to previous branches. If some fixes is only applicable to 202205 or older branches, it is fine, but need to be sponsored by the owner of QoS test cases.

For those PRs which only went to 202205, now Xu is helping to identify them and ask PR submitter to have them cherry-picked to master. Before this finished, all PRs to 202205/202305 or older branches QoS would be blocked to avoid more duplicate work. @XuChen-MSFT @wsycqyz  @neethajohn @rlhui  @rraghav-cisco  @vmittal-msft

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT , @StormLiangMS : This is one of the critical bug fixes - since it fixes the get_multiple_flows in 202205. As such, I request this to be approved for merger to 202205. Thanks!

**Pull request merged**
