### PR TITLE
fix auto-negotiation test unstable issue

### PR DESCRIPTION
**Pull request by nhe-NV**
For Nvidia device, only support to raise link Force<->Force or Auto-negotiation<->Auto-negotiation flows

For other scenario the port may not come up in timeout, but could come up in longer time, for example may need 120s.

### Description of PR

Summary: 
Fixes # (issue) The auto-nego test not stable, sometimes the port could not come up in the 90s timeout

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205

#### What is the motivation for this PR?
fix the test unstable issue
#### How did you do it?
Shutdown the dut port before change the interface type on both the dut port and the fanout port, startup the dut port after the config finished. with this method we can make sure the interface type can be same (both force or both auto-nego) when the 2 ports are both in up state. 
#### How did you verify/test it?
run the autonego test on Nvidia platform, and it could pass stablly

### CODE REVIEW

**Review by roy-sror — COMMENTED** [review]
The PR description is a bit confusing, since it mentions that only frc-frc or autoneg-autoneg are supported, however the fix is to shitdown both end before applying the configuration, please make it more clear.

**Comment by nhe-NV** [comment]
> 

Updated, and in my fix, I only shutdown the dut port, not need to shutdown the port fanout, shutdown port on one side is enough.

**Comment by liat-grozovik** [comment]
@roy-sror could you please help to review following provided feedback?
@prgeor any comments?

**Review by prgeor — APPROVED** [review]

**Comment by nhe-NV** [comment]
> @nhe-NV PR conflicts with 202205 branch

@wangxin  I opened a seperate PR for 202205, can you please help to review and merge？
https://github.com/sonic-net/sonic-mgmt/pull/10511

Thanks
Nana

**Pull request merged**
