### PR TITLE
enable cisco 8800-LC-48H-C48 platform

### PR DESCRIPTION
**Pull request by alpeshspatel**
### Description of PR

enable qos-sai scripts for cisco 8800-LC-48H-C48 platform

#### What is the motivation for this PR?

enable qos-sai scripts for cisco 8800-LC-48H-C48 platform

### CODE REVIEW

**Comment by alpeshspatel** [comment]
@abdosi Please review to enable to run the tests for the pac asic on distributed system

**Comment by XuChen-MSFT** [comment]
@alpeshspatel  can you commit this PR to master first, then cherry pick to 202205

**Comment by alpeshspatel** [comment]
@XuChen-MSFT : created  https://github.com/sonic-net/sonic-mgmt/pull/9713 with request to merge to 202205 as well

**Comment by alpeshspatel** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/9713 - master pr. will be double committed to 202205

**Comment by XuChen-MSFT** [comment]
@alpeshspatel 
since cherry pick https://github.com/sonic-net/sonic-mgmt/pull/9713 conflict , re-open this PR for double commit to 202205 branch

**Review by XuChen-MSFT — APPROVED** [review]
since cherry pick #9713 conflict, merge this PR for 202205 branch

**Comment by XuChen-MSFT** [comment]
@wangxin  @StormLiangMS 
can you help to merge this double commit for #9713 ?

**Pull request closed without merging**
