### PR TITLE
Skip system health test on kvm testbed. 

### PR DESCRIPTION
**Pull request by yutongzhang-microsoft**
### Description of PR

In script `system_health/test_system_health.py`, it will check use the table `SYSTEM_HEALTH_INFO` of DB `STATE_DB` to verify if the system is healthy. But for kvm testbed, there is no table `SYSTEM_HEALTH_INFO` in DB `STATE_DB`. Thus skip this script on kvm testbed. 
```
admin@vlab-01:~$ redis-cli --raw -n 6 EXISTS "SYSTEM_HEALTH_INFO"
0
```

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
In script `system_health/test_system_health.py`, it will check use the table `SYSTEM_HEALTH_INFO` of DB `STATE_DB` to verify if the system is healthy. But for kvm testbed, there is no table `SYSTEM_HEALTH_INFO` in DB `STATE_DB`. Thus skip this script on kvm testbed. 
```
admin@vlab-01:~$ redis-cli --raw -n 6 EXISTS "SYSTEM_HEALTH_INFO"
0
```

#### How did you do it?
Add the mark `pytest.mark.device_type('physical')` at the beginning of this scipt to verify this script can only be executed on physical testbed, and add it to the `pr_test_skip_scripts.yaml` for our calculation.

### CODE REVIEW

**Review by xwjiang-ms — APPROVED** [review]
LGTM

**Comment by wangxin** [comment]
This test has been included in PR testing for quite some time. And it also has some mocks. Why simply skip it?

**Comment by yutongzhang-microsoft** [comment]
> n PR testing for quite some time.

Hi, @wangxin , I think this test is added in `onboarding T0` PR checker not T0 PR checker.  Although it has some mocks, it will use table `SYSTEM_HEALTH_INFO`, which doesn't exist on kvm testbed.

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
There are some conflicts. Can you help resolve? @yutongzhang-microsoft

**Review by wangxin — APPROVED** [review]

**Pull request merged**
