### PR TITLE
Add ASIC DB validation to ACL tests

### PR DESCRIPTION
**Pull request by opcoder0**
### Description of PR
This PR extends `AsicDbCli`, `SonicDbCli` and adds fixtures for tests to be able to perform ASIC DB validation. The PR includes the following changes -

* Extend AsicDbCli with ACL, Next hop and route entry methods
* Extend SonicDbCli with hget_all
* Add ASIC DB fixtures for tests
* Add ASIC DB validation tests to ACL tests
* Fix port numbers to match configured range for tests `test_l4_dport_range_match_dropped` and `test_l4_sport_range_match_dropped` ACL test cases.
* Add README

Summary:
Fixes # Not Applicable

### Type of change

- [x] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?

Performing ASIC DB validation for test cases improves the depth of the coverage of tests.

#### How did you do it?

By extending `AsicDbCli` and `SonicDbCli`. Added methods to access ASIC DB entries for route entry table, next hop table, ACL entries. Added ASIC DB validation to ACL tests.

#### How did you verify/test it?

Ran ACL tests on s6100 and 8111 DUTs.

#### Any platform specific information?

None

#### Supported testbed topology if it's a new test case?

Not applicable

### Documentation

Not applicable

### CODE REVIEW

**Comment by wsycqyz** [comment]
Re-trigger PR test

**Comment by wsycqyz** [comment]
Do we need this PR in 2024 or 2023 branch?

**Comment by opcoder0** [comment]
> Do we need this PR in 2024 or 2023 branch?

I think so. @wangxin can you please confirm?

**Review by xwjiang-ms — APPROVED** [review]
LGTM

**Comment by yutongzhang-microsoft** [comment]
Hi, @opcoder0, do you think we should add some unit tests for `sonic_db.py`

**Comment by opcoder0** [comment]
> Hi, @opcoder0, do you think we should add some unit tests for `sonic_db.py`

Thanks for the suggestion @yutongzhang-microsoft I have added a task for this and will implement that in a separate PR.

**Review by wangxin — DISMISSED** [review]

**Comment by wangxin** [comment]
> > Do we need this PR in 2024 or 2023 branch?
> 
> I think so. @wangxin can you please confirm?

The guideline is to only backport bug fixes to release branches.This is something new for PR testing. We'd better keep it in master branch.

**Comment by yejianquan** [comment]
I'm enhancing test_acl with multi-thread on master and 202405, 
since this PR is causing much difference between master and 202405, I will cherry-pick it to 202405
FYI @wangxin

**Comment by yejianquan** [comment]
> I'm enhancing test_acl with multi-thread on master and 202405, But a key block is this PR causes much difference between master and 202405, it's hard and unsafe to write different version of multi-thread codes for master and 202405. I will cherry-pick it to 202405 FYI @wangxin

NVM, too much conflict if we want to cherry-pick this one, aborting the cherry-pick

**Comment by bingwang-ms** [comment]
> > I'm enhancing test_acl with multi-thread on master and 202405, But a key block is this PR causes much difference between master and 202405, it's hard and unsafe to write different version of multi-thread codes for master and 202405. I will cherry-pick it to 202405 FYI @wangxin
> 
> NVM, too much conflict if we want to cherry-pick this one, aborting the cherry-pick

@yejianquan Please don't cherry-pick the PR to 202405.  We are only taking BUG fix now.

**Pull request merged**
