### PR TITLE
[Mellanox] enable dynamic ecmp on Mellanox switches and updated test nhop_group per vendor

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Summary:
Updated test nhop_group according to Nvidia ASICs behavior
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Updated test nhop_group according to Nvidia ASICs behavior

#### How did you do it?
Created dict with expected traffic redistribution for Nvidia-related ASICs
Removed test ignore for Mellanox/Nvidia platforms

#### How did you verify/test it?
Executed tests from file test_nhop_group.py

#### Any platform specific information?
Nvidia

### CODE REVIEW

**Comment by JibinBao** [comment]
Resolve conflict of https://github.com/sonic-net/sonic-mgmt/pull/8987.
And open one new.

**Review by roy-sror — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@prsunny could you please help to review or assign someone ?

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@abdosi to sign-off

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@yxieca @prsunny we need to backport this to 202205

**Comment by JibinBao** [comment]
> @JibinBao PR conflicts with 202205 branch

@mssonicbld ,I have opened one new PR https://github.com/sonic-net/sonic-mgmt/pull/10153 . Can you help review it?

**Pull request merged**
