### PR TITLE
Updating LossyQueueVoq test for Cisco-8111 platform

### PR DESCRIPTION
**Pull request by jsanghra**
### Description of PR
Updating LossyQueueVoq test for Cisco-8111 platform

#### What is the motivation for this PR?
Updating LossyQueueVoq test for Cisco-8111 platform

#### How did you verify/test it?
Verified the changes in local Cisco-8111 setup and the testcase passes .

### CODE REVIEW

**Comment by XuChen-MSFT** [comment]
@jsanghra 
can you help to resolve PR test failure?

**Comment by wsycqyz** [comment]
The pre-commit check is a mandatory check, please fix detected issues.

**Comment by jsanghra** [comment]
Sure will take a look .

**Comment by XuChen-MSFT** [comment]
@jsanghra , still have pre-commit issue. can you fix it?

```
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
check python ast.........................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

tests/saitests/py3/sai_qos_tests.py:3276:13: E128 continuation line under-indented for visual indent
tests/saitests/py3/sai_qos_tests.py:3277:13: E128 continuation line under-indented for visual indent
tests/saitests/py3/sai_qos_tests.py:3279:20: F821 undefined name 'get_multiple_flows'
tests/saitests/py3/sai_qos_tests.py:3282:57: E231 missing whitespace after ','

flake8...............................................(no files to check)Skipped
check conditional mark sort..........................(no files to check)Skipped
##[error]Bash exited with code '1'.
···

**Comment by jsanghra** [comment]
Hi Xu , 
This PR change has some dependency with changes present only on 202205 branch . 
Will Sync up with @rraghav-cisco to see how that dependencies can be resolved as the change made by me is using Raghav's changes present only in 202205 branch .

**Comment by XuChen-MSFT** [comment]
@jsanghra  pass manually test,  can you help fix conflict? then we can approve and merge.

**Review by XuChen-MSFT — DISMISSED** [review]
looks good to me, and pass in 202305 branch

**Comment by XuChen-MSFT** [comment]
@jsanghra 
```
tests/saitests/py3/sai_qos_tests.py:15:1: F401 'ptf.testutils.simple_udp_packet' imported but unused
```
can you help to fix above pre-commit failur?

**Comment by jsanghra** [comment]
Hi Xu , 
Fixed the pre-commit issue .

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me

**Pull request merged**
