### PR TITLE
mgmt|202311: Skip some route tests for standalone topos.

### PR DESCRIPTION
**Pull request by ccroy-arista**
### Description of PR
Summary:

Some route tests do not apply to standalone
topologies and should be skipped. This patch skips such tests.

Corresponding PR was opened, approved, and merged for master and 202405: https://github.com/sonic-net/sonic-mgmt/pull/13889

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [ ] 202405

#### What is the motivation for this PR?
Some route tests are not applicable to t0 topos and should be skipped rather than failing unecessarily, negatively impacting pass rate.

#### How did you do it?
Applied skip conditions to the applicable tests in the tests mark conditions yaml file in sonic-mgmt.

#### How did you verify/test it?
Ran the route test suite and confirmed that the desired tests are now skipped.

#### Any platform specific information?
Verified on Arista-7060X6-64PE-256x200G.

### CODE REVIEW

**Comment by Janetxxx** [comment]
LGTM

**Review by Janetxxx — APPROVED** [review]
LGTM

**Review by Janetxxx — APPROVED** [review]
LGTM

**Comment by Janetxxx** [comment]
@wangxin Please help to merge this PR, thanks

**Review by r12f — APPROVED** [review]

**Pull request merged**
