### PR TITLE
[Python3 migration]sonic-mgmt repo first batch Python3 migration

### PR DESCRIPTION
**Pull request by wsycqyz**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Python2 to Python3 migration

#### How did you do it?
Step1: Use 2to3 tool to make change.
Step2: Run nightly test and manually make change.
Step3: Rebase the code with master branch.
Step4: Use 2to3 tool again to make change.

#### How did you verify/test it?
N/A

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by nhe-NV** [comment]
HI @wsycqyz  
after this PR merged, when we run the test case from the sonic-mgmt docker, it there any change comaring to the previous method?

Thanks

**Comment by wsycqyz** [comment]
Hi @nhe-NV 
Generally speaking, there is no change when running test case.
All test cases listed in "tests/python3_test_files.txt" will run in Python3 environment.
If you remove the test case file name from "tests/python3_test_files.txt", the test case will run in Python2 environment.

it's possible that you may come across some test case failures due to this PR. I want to acknowledge that the Python 2 to 3 migration process can be a challenging and arduous one, and it's not uncommon to encounter unexpected issues along the way.

Please know that I am available to address any concerns you may have. Please don't hesitate to reach out to me if you need any assistance or have any questions.

**Comment by nhe-NV** [comment]
> 

Thanks @wsycqyz 
Currently I know that for the test cases listed in the python3_test_files.txt need to run with "/var/AzDevOps/env-python3/bin/py.test", and for other test cases it will run with py.test directly.

So in your scenario, you will check if the test case is in the python3_test_files.txt, and then decide which py.test will be used to run the test, is it correct?

and finally we will move all the test cases from python2 to python3, right?

Thanks

**Comment by wsycqyz** [comment]
Hi @nhe-NV 
Your understanding is correct. Now when you run run_test.sh, it will check if the test case is in the python3_test_files.txt, and then decide which Python will be used to run the test.

And yes, finally we will move all the test cases from Py2 to Py3, and remove Python2 from the sonic-mgmt docker totally.

**Pull request merged**
