### PR TITLE
OSPF Test Cases

### PR DESCRIPTION
**Pull request by asraza07**
### Summary
Add test case code for OSPF functionality according to [OSPF test plan](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/OSPF-test-plan.md)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### Motivation for this PR
To add PyTest test case code in accordance with previously contributed [OSPF test plan](https://github.com/sonic-net/sonic-mgmt/blob/master/docs/testplan/OSPF-test-plan.md)

#### How I did it
Added a new folder directory 'sonic-mgmt/tests/ospf/' containing the following files:
- conftest.py containing setup/teardown plugins
- test_ospf.py containing 2 test cases:
  - Test OSPF Neighborship
  - Test OSPF Dynamic Routing

#### Platform specific information
These test cases have been written to run on testing topologies with SONiC-type neighbors. Once the code is tested and verified, code to support Arista-type neighbors will be developed as well.

#### Supported testbed topologies
These test cases support the following topologies:
- T0
- T1

### CODE REVIEW

**Comment by ridahanif96** [comment]
@StormLiangMS Hi, Can you please help review this test case. Target is 202405 release. Thanks alot in advance for help!

**Comment by asraza07** [comment]
## Sanity Testing for Test Case 1 - test_ospf_neighborship
I have manually performed the steps outlined in test_ospf_neighborship() on T0 which can be seen in the screenshots below. It can be seen that OSPF neighborship is successfully established and redistributed routes are available to the DUT shared from neighboring devices.
DUT OSPF Configuration
Neighbor OSPF Configuration
DUT OSPF Routes

## Sanity Testing for Test Case 2 - test_ospf_dynamic_routing
I have manually performed the steps outlined in test_ospf_dynamic_routing() on T0 where after configuring OSPF neighborship, a Loopback interface was created on ARISTA01T1 and the route shared to the DUT. It can be seen in the screenshots below that the Loopback route is available to the DUT, and then link failure was simulated by removing the Loopback interface, after which the route is not seen by the DUT anymore.
Test OSPF Dynamic Routing DUT
Test OSPF Dynamic Routing Neighbor

**Comment by asraza07** [comment]
Hi @yxieca , kindly help review this PR

**Comment by ridahanif96** [comment]
@yxieca Hi Ying, we have added sanity testing for this testcase. Can you please help review this PR. Thanks in advance.

**Comment by ridahanif96** [comment]
@yxieca Hey Ying,

Can you pls, look into this PR. Target is 202045 release. All sanity test passed as expected by each testcase.

**Pull request merged**
