### PR TITLE
[iface_namingmode]Update the iface naming mode test to get real speed of the ports

### PR DESCRIPTION
**Pull request by nhe-NV**
In the fixture, the test will save all the speed of the up port, in the original implement, it could not get the real speed of the port,update it to use the speed in the running config.

### Description of PR

Summary:
Fixes # (issue) https://github.com/sonic-net/sonic-mgmt/issues/11358

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
In the cleanup of the TestConfigInterface, the fixture will reset the port speed to the orignal speed, but in the original fixture implement, the speed of the port is not correct, if the speed is not supported on this port, then the port will be changed to down status.
#### How did you do it?
Get the correct speed for each up port in the fixture of the test
#### How did you verify/test it?
run all the iface_namingmode test, all could pass.
#### Any platform specific information?
No

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@yxieca please help to review or assign someone to review

**Review by liat-grozovik — DISMISSED** [review]

**Review by roy-sror — APPROVED** [review]

**Comment by nhe-NV** [comment]
tests/common/plugins/loganalyzer/bug_handler_helper.py

**Comment by nhe-NV** [comment]
Close it before the check pass

**Pull request closed without merging**
