### PR TITLE
[wol_test] Add udp related tests into wol test plan

### PR DESCRIPTION
**Pull request by w1nda**
### Description of PR

Summary:
Fixes # (issue)
We extended wol tool to support sending magic pattern in udp paylod, and we need to add related tests into test plan.
Related PRs: https://github.com/sonic-net/SONiC/pull/1827, https://github.com/sonic-net/sonic-buildimage/pull/20523

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
We extended wol tool to support sending magic pattern in udp paylod, and we need to add related tests into test plan.

#### How did you do it?
Add udp related tests and give some demo commands.

### CODE REVIEW

**Comment by lizhijianrd** [comment]
Hi @w1nda, below are my suggestions:
1. For testcases 1~6, they are focusing on specific scenario, so add a L3 test would be enough. No need to test both ipv4 and ipv6.
2. Add a group of testcases for newly introduced L3 parameters, like,
    1. Verify ip address can be both v4 and v6.
    2. Verify dest UDP port can be set properly.
    3. ...

**Comment by w1nda** [comment]
> Hi @w1nda, below are my suggestions:
> 
> 1. For testcases 1~6, they are focusing on specific scenario, so add a L3 test would be enough. No need to test both ipv4 and ipv6.
> 2. Add a group of testcases for newly introduced L3 parameters, like,
>    
>    1. Verify ip address can be both v4 and v6.
>    2. Verify dest UDP port can be set properly.
>    3. ...

Thanks for suggestions.
For 1, we need to verify if wol works with both address family ipv4 and ipv6, so we can't just verify one of them.
For 2.*, these scenarios were covered by our testcases, because when we verify packet content, we will check those parameters indirectly. I think we can add a new standalone testcases to verify those parameters, i will add it.

**Review by lizhijianrd — APPROVED** [review]

**Comment by lizhijianrd** [comment]
>  For 1, we need to verify if wol works with both address family ipv4 and ipv6, so we can't just verify one of them.

Thanks, this make sense. One more question, when implementing testcase, which IP address will you verify? unicast, broadcast or both? Can you update the testplan to clarify this?

**Comment by w1nda** [comment]
> > For 1, we need to verify if wol works with both address family ipv4 and ipv6, so we can't just verify one of them.
> 
> Thanks, this make sense. One more question, when implementing testcase, which IP address will you verify? unicast, broadcast or both? Can you update the testplan to clarify this?

Good point, I think both are needed, I will add it.

**Review by lizhijianrd — APPROVED** [review]

**Pull request merged**
