### PR TITLE
[pfcwd] Adding innovium to the list of platforms for forward action

### PR DESCRIPTION
**Pull request by meinh**
### Description of PR

Modify the testcase to check for ingress traffic getting forwarded in innovium platform.
Related to [PR#2304](https://github.com/sonic-net/sonic-swss/pull/2304)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### How did you verify/test it?
Run test with PTF/T0 topology in innovium platform and it passed

### CODE REVIEW

**Comment by puffc** [comment]
@kbabujp @rck-innovium Marvell please take a look at this PR.

**Review by neethajohn — APPROVED** [review]

**Comment by kbabujp** [comment]
@neethajohn, Please hold this merge. I will ask submitter to share pass logs.

**Comment by kbabujp** [comment]
@meinh, Could you please run the modified tests and share the pass logs.

**Review by rck-innovium — CHANGES_REQUESTED** [review]
Please provide the full logs of the test script run with this change.

**Comment by meinh** [comment]
@kbabujp @rck-innovium 

test run in ptf topology, the result is
pfcwd/test_pfc_config.py::TestPfcConfig::test_forward_action_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_invalid_action_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_invalid_detect_time_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_low_detect_time_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_high_detect_time_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_invalid_restore_time_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_low_restore_time_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestPfcConfig::test_high_restore_time_cfg[lab-inno-01-None] PASSED
pfcwd/test_pfc_config.py::TestDefaultPfcConfig::test_default_cfg_after_load_mg[lab-inno-01] PASSED
pfcwd/test_pfcwd_all_port_storm.py::TestPfcwdAllPortStorm::test_all_port_storm_restore[lab-inno-01-None] PASSED
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_actions[lab-inno-01-None] PASSED
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_mmu_change[lab-inno-01-None] PASSED
pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_port_toggle[lab-inno-01-None] PASSED
pfcwd/test_pfcwd_timer_accuracy.py::TestPfcwdAllTimer::test_pfcwd_timer_accuracy[lab-inno-01-None] PASSED

Here is full log
[ptf_pfcwd.log](https://github.com/sonic-net/sonic-mgmt/files/12237566/ptf_pfcwd.log)

**Comment by puffc** [comment]
@kbabujp @rck-innovium Please share your opinion. Thank you.

**Comment by meinh** [comment]
Marvell will handle it. close this PR.

**Pull request closed without merging**
