### PR TITLE
sonic-mgmt: Fix test_memory_checker.py test for low memory skus

### LINKED ISSUE #8642: memory_checker related cases need enhance for the devices which has a small disk and low memory
**Description**
Several memory_checker.test_memory_checker related cases failed on the devices which have a small disk and low memory.
Need to enhance the cases.

**Steps to reproduce the issue:**
1. Run cases on Arista 7050qx devices
memory_checker.test_memory_checker.test_memory_checker
memory_checker.test_memory_checker.test_memory_checker_without_container_created
memory_checker.test_memory_checker.test_monit_new_syntax
memory_checker.test_memory_checker.test_monit_reset_counter_failure
2.
3.

**Describe the results you received:**
case failed or setup failure

**Describe the results you expected:**
case pass

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

### PR DESCRIPTION
**Pull request by aaronpayment**
### Description of PR
The test_memory_checker.py test tries to consume >400MB of RAM in the telemetry container using 'stress -m 6' which by default mallocs 6*256MB.

With docker in ram on a system with 4GB of RAM there is limited available memory and we can no longer malloc 6*256MB.

Instead, modify the test to use 2 vm_workers which results in 'stress -m 2' which gets us over the 400MB limit that is being checked by monit and the config is in /etc/monit/conf.d/monit_telemetry. The test also does not wait long enough before checking that the expected log messages are available in syslog. Increase the time before checking syslog from 130sec to 360sec. In testing it can take ~3min30sec for the logs to appear.

Summary:
Fixes #8642

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Fix test_memory_checker.py that is failing on 7050QX platform with docker in ram.

#### How did you do it?
As per description, modify the test to consume memory within the bounds of the available memory on a 4GB RAM system using docker in ram.

#### How did you verify/test it?
Verify that the test test_memory_checker.py is passing on 202205 sonic mgmt + 202205 swi.

### CODE REVIEW

**Comment by wangxin** [comment]
@aaronpayment Is this PR a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description?

**Comment by lipxu** [comment]
@aaronpayment  Please create the PR based on the master branch first, and add a label to cherry-pick to 202205 branch, thanks a lot.

**Comment by aaronpayment** [comment]
@lipxu @wangxin I can open a PR on master. Setting up and running sonic mgmt master + master swi to validate will take extra time as this may expose a different issues  as this case is not yet running. We were validating 202205 which was why this PR was opened first.

**Comment by wangxin** [comment]
@aaronpayment If master branch does not have the fix, then in the future, duplicated work fixing this same issue would be required for master and later releases.

**Comment by aaronpayment** [comment]
Going to close the PR. We are going to re-write the test to make it more robust and open the PR on master.

**Pull request closed without merging**
