### PR TITLE
fix the issue which timeout is too short for bgp shut

### PR DESCRIPTION
**Pull request by StormLiangMS**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
flaky failure for platform test on 2700 platforms

#### How did you do it?
2 changes:
1. To extend the timeout from 30 seconds to 60, and increase the delay from 0 to 5 seconds.
2. To add some debug log

#### How did you verify/test it?
Run local test.

### CODE REVIEW

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/fixtures/duthost_utils.py:170:121: E501 line too long (121 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:201:121: E501 line too long (138 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:204:121: E501 line too long (138 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:472:121: E501 line too long (122 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:474:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:476:121: E501 line too long (128 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:478:121: E501 line too long (146 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:480:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:481:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:520:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:544:5: E722 do not use bare 'except'<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/fixtures/duthost_utils.py:170:121: E501 line too long (121 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:474:121: E501 line too long (122 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:476:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:478:121: E501 line too long (128 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:480:121: E501 line too long (146 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:482:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:483:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:522:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:546:5: E722 do not use bare 'except'<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Review by jcaiMR — APPROVED** [review]

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/fixtures/duthost_utils.py:170:121: E501 line too long (121 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:474:121: E501 line too long (122 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:476:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:478:121: E501 line too long (128 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:480:121: E501 line too long (146 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:482:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:483:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:522:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:546:5: E722 do not use bare 'except'<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/fixtures/duthost_utils.py:170:121: E501 line too long (121 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:474:121: E501 line too long (122 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:476:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:478:121: E501 line too long (128 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:480:121: E501 line too long (146 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:482:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:483:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:522:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:546:5: E722 do not use bare 'except'<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/common/fixtures/duthost_utils.py:170:121: E501 line too long (121 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:474:121: E501 line too long (122 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:476:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:478:121: E501 line too long (128 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:480:121: E501 line too long (146 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:482:121: E501 line too long (126 > 120 characters)<br/>tests/common/fixtures/duthost_utils.py:483:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:522:5: E722 do not use bare 'except'<br/>tests/common/fixtures/duthost_utils.py:546:5: E722 do not use bare 'except'<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Pull request merged**
