### PR TITLE
Fix route/test_route_consistency.py

### PR DESCRIPTION
**Pull request by vkjammala-arista**
### Description of PR

Summary: Fix flaky test route/test_route_consistency.py
Fixes # [aristanetworks/sonic-qual.msft#99](https://github.com/aristanetworks/sonic-qual.msft/issues/99)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
After announcing the routes, it is taking some time for kernel routes (IP-in-IP tunnel routes from standby ToR to active ToR) to be populated in ASIC_DB. And current sleep_interval is not enough for kernel routes to be populated in some of the runs and thus test is failing because of mismatch in pre_test_route_snapshot and post_test_route_snapshot (lead to `AssertionError`.

#### How did you do it?
Increased the sleep_interval (to ~100 secs) for time.sleep after announcing the routes (announce or withdraw) to give more time for kernel routes to be populated in ASIC_DB.

#### How did you verify/test it?
Test is consistently passing with the fix (verified on Arista-7260CX3-C64).

### CODE REVIEW

**Comment by StormLiangMS** [comment]
hi @prsunny  could you help to review?

**Review by deepak-singhal0408 — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by StormLiangMS** [comment]
hi @vkjammala-arista could you help to update result with 202305 / 202311 for cherry pick?

**Comment by vkjammala-arista** [comment]
> hi @vkjammala-arista could you help to update result with 202305 / 202311 for cherry pick?

Thanks @StormLiangMS. We have verifed the fix on 202305 and 202311 branches. Test has been passing consistenly with the fix (no flakiness).

**Comment by StormLiangMS** [comment]
hi @yxieca for 202311 cherry pick.

**Pull request merged**
