### PR TITLE
Adding reboot test case scripts

### PR DESCRIPTION
**Pull request by albertovillarreal-keys**
### Description of PR

Summary: Downtime convergence script for various reboot scenarios
Test case # 1 - Downtime convergence measurement for warm-reboot while sending traffic
 [test_warm_reboot.py]
Test case # 2 – Downtime Convergence measurement for fast-reboot while sending traffic
 [test_fast_reboot.py]
Test case # 3 – Downtime Convergence measurement for cold-reboot while sending traffic
 [test_cold_reboot.py]
Test case # 4 – Downtime Convergence measurement for soft-reboot while sending traffic
 [test_soft_reboot.py]

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

### Documentation

https://github.com/Azure/sonic-mgmt/blob/9a503927d620cf978641af5424062f9961ba15ee/docs/testplan/Downtime%20Convergence%20for%20various%20reboot%20scenarios.md

### CODE REVIEW

**Comment by wangxin** [comment]
PR test failed with below error:
```
==================================== ERRORS ====================================
______________ ERROR collecting snappi/reboot/test_cold_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_cold_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_cold_reboot.py:1: in <module>
    from tests.common.snappi.snappi_fixtures import cvg_api
E   ImportError: cannot import name cvg_api
______________ ERROR collecting snappi/reboot/test_fast_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_fast_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_fast_reboot.py:1: in <module>
    from tests.common.snappi.snappi_fixtures import cvg_api
E   ImportError: cannot import name cvg_api
______________ ERROR collecting snappi/reboot/test_soft_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_soft_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_soft_reboot.py:1: in <module>
    from tests.common.snappi.snappi_fixtures import cvg_api
E   ImportError: cannot import name cvg_api
______________ ERROR collecting snappi/reboot/test_warm_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_warm_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_warm_reboot.py:3: in <module>
    from tests.common.snappi.snappi_fixtures import cvg_api
E   ImportError: cannot import name cvg_api

```
@albertovillarreal-keys Can you check and fix?

**Comment by albertovillarreal-keys** [comment]
@wangxin

The ImportErrors are because those fixtures have been checked in another PR but have not yet been merged.  Thanks.

**Comment by wangxin** [comment]
@albertovillarreal-keys Do you have link to the other PR that contains the dependent fixture `cvg_api`? We need to get that PR merged first to have your PR pass testing.

BTW, can you also fix the LGTM alerts?

**Comment by albertovillarreal-keys** [comment]
@wangxin I fixed the LGTM alerts.  The link to the PR is the following:
https://github.com/Azure/sonic-mgmt/pull/3715

**Comment by selldinesh** [comment]
@wangxin  waiting for the PR 3715 to be merged, for the reboot cases to work

**Comment by wangxin** [comment]
I think log analyzer needs to be disabled for the reboot tests. Currently lots of error logs are generated during reboot. These is no way to address all those error logs in near future. The feasible way is to simply disable loganalyzer for reboot test cases.

**Comment by yxieca** [comment]
@albertovillarreal-keys , this test case cannot be executed on regular PTF testbeds, can you add a topology marker to make to clear that these test cases require hardware tester supports SNAPPI API?

**Comment by wangxin** [comment]
Seeing similar import error in PR testing log:

```
==================================== ERRORS ====================================
______________ ERROR collecting snappi/reboot/test_cold_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_cold_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_cold_reboot.py:4: in <module>
    from files.reboot_helper import run_reboot_test
E   ImportError: No module named reboot_helper
______________ ERROR collecting snappi/reboot/test_fast_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_fast_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_fast_reboot.py:4: in <module>
    from files.reboot_helper import run_reboot_test
E   ImportError: No module named reboot_helper
______________ ERROR collecting snappi/reboot/test_soft_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_soft_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_soft_reboot.py:4: in <module>
    from files.reboot_helper import run_reboot_test
E   ImportError: No module named reboot_helper
______________ ERROR collecting snappi/reboot/test_warm_reboot.py ______________
ImportError while importing test module '/var/src/s/tests/snappi/reboot/test_warm_reboot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
snappi/reboot/test_warm_reboot.py:6: in <module>
    from files.reboot_helper import run_reboot_test
E   ImportError: No module named reboot_helper

```

**Comment by wangxin** [comment]
Can you also sign the EasyCLA?

**Comment by albertovillarreal-keys** [comment]
Fixing remainder of errors

**Comment by albertovillarreal-keys** [comment]
commented out unused variable in reboot_helper.py

**Comment by albertovillarreal-keys** [comment]
@wangxin i think the blocks have been resolved.  Can you check please, thanks!

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
@developfast This PR adds new test cases. Generally, we should only cherry-pick bug fixes to older releases. Can you elaborate why this PR is required for these branches?

**Comment by vaibhavhd** [comment]
@wangxin we need this on other feature branches as we have discovered cases where PTF based IO is not sufficient (or has issues) for evaluating feature.

Hence, IXIA generated IO will further strengthen the qualification confidence on older branches.

**Comment by developfast** [comment]
Just realised this PR is still based on the old `snappi` dir, which has now been renamed to 'snappi_tests`. This PR may cause merge conflicts, and all imports have to be fixed to the correct path. Please continue the cherry-pick and I will create a new PR for the 202012 and 202205 branch.

**Comment by wangxin** [comment]
@developfast All the auto cherry-picked PRs cannot pass basic PR testing. I am going to close them. 
Can you help manually backport these scripts? Thanks!

**Pull request merged**
