### PR TITLE
Fix definitions of active-active dualtor fixtures

### PR DESCRIPTION
**Pull request by vivekverma-arista**
### Description of PR

Summary: Fix the definitions of dualtor-aa fixtures.
Fixes [#135](https://github.com/aristanetworks/sonic-qual.msft/issues/135)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Regression due to: [#10079](https://github.com/sonic-net/sonic-mgmt/pull/10079)

This has broken the following testcases for non dualtor-aa in 202305, 202311 and master -

```
1. qos/test_tunnel_qos_remap.py::test_encap_dscp_rewrite[active-standby]
2. qos/test_tunnel_qos_remap.py::test_bounced_back_traffic_in_expected_queue[active-standby]
3. qos/test_tunnel_qos_remap.py::test_tunnel_decap_dscp_to_queue_mapping

```

```
    @pytest.fixture
    def toggle_all_aa_ports_to_lower_tor(config_active_active_dualtor_active_standby,
                                         lower_tor_host, upper_tor_host, active_active_ports):  # noqa F811
&gt;       config_active_active_dualtor_active_standby(lower_tor_host, upper_tor_host, active_active_ports)
E       TypeError: 'NoneType' object is not callable
```

```
    @pytest.fixture
    def toggle_all_aa_ports_to_rand_selected_tor(config_active_active_dualtor_active_standby,
                                                 rand_selected_dut, rand_unselected_dut, active_active_ports):  # noqa F811
&gt;       config_active_active_dualtor_active_standby(rand_selected_dut, rand_unselected_dut, active_active_ports)
E       TypeError: 'NoneType' object is not callable

```
This is because the check for active-active ports is missing similar to this: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/dualtor/dual_tor_utils.py#L1807.

#### How did you do it?
Proposed fix is to introduce a check for the existence of active-active ports so that the following fixtures don't end up running in active-standby dualtor.
1. `toggle_all_aa_ports_to_lower_tor`
2. `toggle_all_aa_ports_to_rand_unselected_tor`
3. `toggle_all_aa_ports_to_rand_selected_tor`

#### How did you verify/test it?
Tested on Arista-7260 platform with active-standby dualtor topology with 202305 and 202311 SONiC images.

### CODE REVIEW

**Comment by vivekverma-arista** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/13001 raised for this issue.

**Review by lolyu — COMMENTED** [review]
could you please fix the pre-commit failure?

**Comment by vivekverma-arista** [comment]
> could you please fix the pre-commit failure?

Hi @lolyu I have already addressed pre-commit failure in this commit: https://github.com/sonic-net/sonic-mgmt/pull/13001/commits/397a84cc07f6d5c88974fc87f37fd2bccf6fe12b

**Review by lolyu — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @yxieca 202311 cherry pick.

**Pull request merged**
