### PR TITLE
Add multi-asic support for syslog rate limit test

### PR DESCRIPTION
**Pull request by wumiaont**
### Description of PR
Summary:
syslog rate limit test failed on multi asic chasssis. The reason is that test code does not have support for multi asic. In multi asic scenario the container can be either global (pmon, snmp etc) or per asic scope (macsec0, macsec1, swss0 etc). In multi asic scenario for all per asci scope features the service name is different with container name.
Fixes # (issue)
Add check for each feature, get the running config facts for feature. If has_per_asic_scope is true will randomly choose one container (macsec0 for example) to test rate limit. Add code to handle container name in this scenario.
### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [X] 202405

#### What is the motivation for this PR?
Test failed
#### How did you do it?
Add check for each feature, get the running config facts for feature. If has_per_asic_scope is true will randomly choose one container (macsec0 for example) to test rate limit. Add code to handle container name in this scenario.
#### How did you verify/test it?
Run test with change. test_syslog_rate_limit test passes.

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@yejianquan for viz.

**Comment by wumiaont** [comment]
/azpw run Azure.sonic-mgmt (Test kvmtest-dpu by Elastictest)

**Comment by wumiaont** [comment]
/azpw run Azure.sonic-mgmt(Test onboarding testcases by Elastictest)

**Comment by wumiaont** [comment]
/azpw run "Azure.sonic-mgmt (Test onboarding testcases by Elastictest)"

**Comment by wumiaont** [comment]
@abdosi Cannot make that (Test onboarding testcases by Elastictest) check to pass. Can you help to check what can we do? I don't believe it has anything to do with the code change here. Rerun Azure.sonic-mgmt many times and it did not help.

**Comment by rlhui** [comment]
@yejianquan would you be able to help? thanks

**Comment by yejianquan** [comment]
> @abdosi Cannot make that (Test onboarding testcases by Elastictest) check to pass. Can you help to check what can we do? I don't believe it has anything to do with the code change here. Rerun Azure.sonic-mgmt many times and it did not help.

onboarding is the rehearsal of forthcoming PR tests, we can ignore the failure of it

**Comment by wumiaont** [comment]
@abdosi Can you help to merge this PR? Azure.sonic-mgmt (Test onboarding testcases by Elastictest) is failing always so you maybe able to ignore this one.

**Comment by yejianquan** [comment]
> @abdosi Can you help to merge this PR? Azure.sonic-mgmt (Test onboarding testcases by Elastictest) is failing always so you maybe able to ignore this one.

@wumiaont There's required test job failed besides onboarding on the newest run
image

Let's rerun until all required test jobs pass.
And then I will help to merge and cherry-pick to 202405

**Comment by wumiaont** [comment]
@abdosi This run only Azure.sonic-mgmt (Test onboarding testcases by Elastictest) is still failing. Others passed. This failed one seems to be there always. Cannot make it pass.

**Comment by yejianquan** [comment]
> @abdosi This run only Azure.sonic-mgmt (Test onboarding testcases by Elastictest) is still failing. Others passed. This failed one seems to be there always. Cannot make it pass.

In my capture, it failed on t1-lag, after the newest retry, only onboarding failed, we're good to merge it.

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
