### PR TITLE
Revert "Added temporary skip to system_health TC for MLX platfroms "

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Revert "Added temporary skip to system_health TC for MLX platfroms " https://github.com/sonic-net/sonic-mgmt/pull/12798, because there is a fix: https://github.com/sonic-net/sonic-mgmt/pull/12895

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
Remove the skip condition

#### How did you do it?
Remove it

#### How did you verify/test it?
Run test_device_checker 

#### Any platform specific information?
Mellanox

### CODE REVIEW

**Comment by bingwang-ms** [comment]
Re-triggered PR test.

**Review by SavchukRomanLv — APPROVED** [review]

**Review by roy-sror — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Merge is on-hold because PR #12895 is not merged into 202311 and 202405 yet.

**Comment by JibinBao** [comment]
> Merge is on-hold because PR #12895 is not merged into 202311 and 202405 yet.

cherry-pick to 202311, please help review :https://github.com/sonic-net/sonic-mgmt/pull/13760

**Comment by bingwang-ms** [comment]
@JibinBao Please check if the PR is required for 202405 branch. Thanks

**Comment by JibinBao** [comment]
> @JibinBao Please check if the PR is required for 202405 branch. Thanks

Yes. 202405 also need it.

**Pull request merged**
