### PR TITLE
Put back #11934, fix qos/test_qos_sai.py teardown for dualtor.

### PR DESCRIPTION
**Pull request by vivekverma-arista**
This reverts commit 616df5ff5ca315e426f1260509b9fa368fb3ab4e.

### Description of PR

Summary: Fix qos/tes_qos_sai.py teardown failure for dualtor.
Fixes [#78](https://github.com/aristanetworks/sonic-qual.msft/issues/78)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
qos/test_qos_sai.py fails at teardown 

```
failed on setup with "Failed: All critical services should be fully started!
```

Regression introduced by https://github.com/sonic-net/sonic-mgmt/pull/10651 for dualtor.

#### How did you do it?
The config_reload in the fixture `dut_disable_ipv6` waits until all critical processes are up after issuing config reload command and it timeouts in case of dualtor because mux container doesn't come up. Mux container is disabled by another fixture `stopServices` in the same file. These two fixtures have no dependency on each other hence the execution can happen in any order, so if the teardown of `dut_disable_ipv6` happens before `stopServices` then this issue is seen.

This change ensures that the teardown of `stopServices` happens before `dut_disable_ipv6` so that mux is no longer disabled at the time of config_reload.

#### How did you verify/test it?
Ran qos/test_qos_sai.py on Arista-7260CX3 platform with dualtor topology with 202305 and 202311 images.

### CODE REVIEW

**Comment by neethajohn** [comment]
@vivekverma-arista, this change was reverted in https://github.com/sonic-net/sonic-mgmt/commit/616df5ff5ca315e426f1260509b9fa368fb3ab4e due to snmp crash observed in qos sai test. Has that been addressed?

**Comment by vivekverma-arista** [comment]
> @vivekverma-arista, this change was reverted in [616df5f](https://github.com/sonic-net/sonic-mgmt/commit/616df5ff5ca315e426f1260509b9fa368fb3ab4e) due to snmp crash observed in qos sai test. Has that been addressed?

@neethajohn, this was addressed in https://github.com/sonic-net/sonic-mgmt/pull/12152

**Review by XuChen-MSFT — APPROVED** [review]
looks good to me

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by vivekverma-arista** [comment]
Hi @StormLiangMS and @XuChen-MSFT, let's cherry pick this to 202305 and 202311 as well.

**Comment by bingwang-ms** [comment]
Hi @vivekverma-arista, I'm sorry I have to revert this change as it caused regression. The error message is as below.
```
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_tbtk5-t1-2700-2_65a9f3c0abd5cba890cf2065/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "/var/src/sonic-mgmt_tbtk5-t1-2700-2_65a9f3c0abd5cba890cf2065/tests/qos/qos_sai_base.py", line 948, in dutConfig
    portIpMap = {'peer_addr': addr["peer_ipv4"], 'peer_addr_ipv6': addr["peer_ipv6"]}
KeyError: 'peer_ipv6'
```
The error is because IPv6 is disabled earlier than before, which caused `get_active_ip_interfaces` can't retrieve the IPv6 address from interface.

**Pull request merged**
