### PR TITLE
Skip error messages for https://github.com/sonic-net/sonic-buildimage…

### PR DESCRIPTION
**Pull request by roy-sror**
Skip error messages related to the following issue:
https://github.com/sonic-net/sonic-buildimage/issues/7895

Summary:
Fixes # https://github.com/sonic-net/sonic-mgmt/issues/10272

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305

### CODE REVIEW

**Comment by ZhaohuiS** [comment]
@roy-sror which case is failed due to these error log? I suggest don't put the real error log into `ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt,` which we used to put non-harm or not real error logs needs to be ignored usually.
For your case, it's a real issue, could you please skip or xfail the impacted cases in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. Please also add the conditions like platform,hwsku, or os version to limit the scope of skip or xfail.

**Comment by roy-sror** [comment]
> @roy-sror which case is failed due to these error log? I suggest don't put the real error log into `ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt,` which we used to put non-harm or not real error logs needs to be ignored usually. For your case, it's a real issue, could you please skip or xfail the impacted cases in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. Please also add the conditions like platform,hwsku, or os version to limit the scope of skip or xfail.

@ZhaohuiS - the error messages are discussed in https://github.com/sonic-net/sonic-buildimage/issues/7895 and could happen on any boot. This is why `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml` is less suitable in this case.

**Comment by bingwang-ms** [comment]
> > @roy-sror which case is failed due to these error log? I suggest don't put the real error log into `ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt,` which we used to put non-harm or not real error logs needs to be ignored usually. For your case, it's a real issue, could you please skip or xfail the impacted cases in `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml`. Please also add the conditions like platform,hwsku, or os version to limit the scope of skip or xfail.
> 
> @ZhaohuiS - the error messages are discussed in [sonic-net/sonic-buildimage#7895](https://github.com/sonic-net/sonic-buildimage/issues/7895) and could happen on any boot. This is why `tests/common/plugins/conditional_mark/tests_mark_conditions.yaml` is less suitable in this case.

Hi @roy-sror, issue https://github.com/sonic-net/sonic-buildimage/issues/7895 is a quite old issue. Why didn't we see the same error log in other branch, like 202205?

**Comment by ZhaohuiS** [comment]
@roy-sror I don't know which case has these kinds of error log. bgp fib suppress? If there are some specific cases hit these error log during log analyzer, we can ignore these error log in script level or case level, please take the following one for reference.

https://github.com/sonic-net/sonic-mgmt/pull/10211/files

**Comment by bingwang-ms** [comment]
@roy-sror Can you please check and address the comments?

**Comment by roy-sror** [comment]
@bingwang-ms , @ZhaohuiS - Based on https://github.com/sonic-net/sonic-buildimage/issues/7895, this might happen during any test that involves a reboot or configuration reload. To prevent having to add a skip statement for every test that involves a reload, I suggest keeping this globally skipped.

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@roy-sror  Can you please address the pre_test static analysis failure?

**Review by bingwang-ms — DISMISSED** [review]

**Comment by bingwang-ms** [comment]
I'm not aware of any known blocker in sonic-mgmt PR checker. Just retriggered the testing.

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
MFST ADO: 25581299
@StormLiangMS Can you please help cherry-pick to 202305 branch? Thanks!

**Comment by bingwang-ms** [comment]
@roy-sror  Can you please create another PR for 202305? Thanks!

**Comment by nhe-NV** [comment]
@bingwang-ms new PR added for 202305 branch: https://github.com/sonic-net/sonic-mgmt/pull/11334

**Comment by wangxin** [comment]
This PR was merged before 202311 branch was created from master branch. No need to cherry-pick for 202311 branch.

**Pull request merged**
