### PR TITLE
separated VXLAN IPv4/6 tunnel configuration for VXLAN tests

### PR DESCRIPTION
**Pull request by antonptashnik**
### Description of PR

Summary: separated VXLAN IPv4/6 tunnel configuration for VXLAN tests
Fixes # (issue)
- separated VXLAN IPv4/6 tunnel configuration 

There are separate VXLAN Encap tests on IPv4/6 tunnels with v4/v6 payload, but both tunnels are setup at once before all tests. It is redundant configuration and it may cause setup conflicts. The PR separates configs for testing ('v4_in_v4', 'v4_in_v6', 'v6_in_v4', 'v6_in_v6') and organizes tests execution by applying each config separately and running tests for the applied config, with cleaning up before next test set run.
Collectonly output demonstrates the order tests will run:
```
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_single_endpoint[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_modify_route_different_endpoint[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_remove_all_route[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_a[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_b[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route2_ecmp_group_b[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_route2[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_single_nh[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_nh[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_different_nh[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_ecmp_route2[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_random_hash::test_vxlan_random_hash[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v4_in_v4-1]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v4_in_v4-2]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_remove_add_underlay_default[v4_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_single_endpoint[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_modify_route_different_endpoint[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_remove_all_route[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_a[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_b[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route2_ecmp_group_b[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_route2[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_single_nh[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_nh[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_different_nh[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_ecmp_route2[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_random_hash::test_vxlan_random_hash[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v4_in_v6-1]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v4_in_v6-2]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_remove_add_underlay_default[v4_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_single_endpoint[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_modify_route_different_endpoint[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_remove_all_route[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_a[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_b[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route2_ecmp_group_b[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_route2[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_single_nh[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_nh[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_different_nh[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_ecmp_route2[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_random_hash::test_vxlan_random_hash[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v6_in_v4-1]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v6_in_v4-2]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_remove_add_underlay_default[v6_in_v4]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_single_endpoint[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_modify_route_different_endpoint[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_route_tests::test_vxlan_remove_all_route[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_a[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route1_ecmp_group_b[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_create::test_vxlan_configure_route2_ecmp_group_b[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_route2[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_single_nh[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_nh[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_route2_shared_different_nh[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_NHG_Modify::test_vxlan_remove_ecmp_route2[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_ecmp_random_hash::test_vxlan_random_hash[v6_in_v6]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v6_in_v6-1]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_modify_underlay_default[v6_in_v6-2]
vxlan/test_vxlan_ecmp.py::Test_VxLAN_underlay_ecmp::test_vxlan_remove_add_underlay_default[v6_in_v6]
```
- made tunnel config file vxlan_configs.json to be written to PTF only once per tunnel config instead of being written before each test

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Keep DUT configuration closer to the test needing it

#### How did you do it?
Separated IPv4/6 VXLAN test on 2 subsets (per tunnel) and setup the corresponding tunnel before a given test set

#### How did you verify/test it?
py.test --inventory=../ansible/lab,../ansible/veos --testbed_file=../ansible/testbed.csv --module-path=../ansible/library -v -rA --topology=t1,any vxlan/test_vxlan_ecmp.py

### CODE REVIEW

**Comment by SavchukRomanLv** [comment]
@wangxin @yxieca could you please take a look?

**Review by yxieca — APPROVED** [review]

**Comment by prsunny** [comment]
this will break the current PR in review - https://github.com/Azure/sonic-mgmt/pull/5059. I suggest, you can revisit this change, once PR 5059  is merged and take it as a wholistic change.

**Comment by prsunny** [comment]
@rraghav-cisco to review/sign-off

**Comment by ihorchekh** [comment]
@prsunny, @rraghav-cisco on the Nvidia side we're using a slightly different workaround for this issue. I've created a draft PR: https://github.com/Azure/sonic-mgmt/pull/5858. 
Please take a look and comment if you find that solution reasonable.

**Comment by antonptashnik** [comment]
closing as another similar PR was accepted instead - https://github.com/sonic-net/sonic-mgmt/pull/5858

**Pull request closed without merging**
