### PR TITLE
[snappi] Fix helper config_wred to config RED for Broadcom ASIC

### PR DESCRIPTION
**Pull request by ysmanman**
### Description of PR

Broadcom ASICs only supports RED threshold.  Fix helper config_wred to config RED for Broadcom ASIC.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### CODE REVIEW

**Comment by sdszhang** [comment]
@amitpawar12 pls review. thanks.

**Comment by amitpawar12** [comment]
Looks good.

Thanks,
-A

**Review by sdszhang — APPROVED** [review]
LGTM

**Comment by sdszhang** [comment]
> @yejianquan @sdszhang seeing regression on T0/T1 testbeds for this issue
> 
> ```
> kmax_arg = '-{}max' % color[0]
> E       TypeError: not all arguments converted during string formatting
> 
> asic_type  = 'broadcom'
> asic_value = None
> color      = 'red'
> host_ans   = <MultiAsicSonicHost 7050CX3>
> kmax       = 51000
> kmin       = 50000
> pmax       = 100
> profile    = None
> ```
> 
> can you pls help rectify?

@ysmanman Seems the string formatting is wrong. Can you get this fixed? Thanks.

**Pull request merged**
