### PR TITLE
Skip override config multi-asic testing for single-asic platforms

### PR DESCRIPTION
**Pull request by wenyiz2021**
### Description of PR

This testcase test_override_config_table_masic.py is designed for multi-asic only. While even this testcase has skipped for single-asic specifically in `test` function, there are fixtures run before test, especially fixture setup is backing up config files with multi-asic names.
Add skip in conditional_marker to specifically skip whole testcase for single-asic.

```
06/10/2023 12:10:17 __init__._fixture_generator_decorator    L0081 INFO   | -------------------- fixture setup_env setup starts --------------------
06/10/2023 12:10:17 utilities.backup_config                  L0010 INFO   | Backup /etc/sonic/config_dbNone.json to /etc/sonic/config_dbNone.json_before_override on str-7260cx3-acs-7
06/10/2023 12:10:17 base._run                                L0067 DEBUG  | /var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/common/devices/multi_asic.py::_run_on_asics#118: [str-7260cx3-acs-7] AnsibleModule::shell, args=["cp /etc/sonic/config_dbNone.json /etc/sonic/config_dbNone.json_before_override"], kwargs={}
06/10/2023 12:10:17 base._run                                L0104 DEBUG  | /var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/common/devices/multi_asic.py::_run_on_asics#118: [str-7260cx3-acs-7] AnsibleModule::shell Result => {"failed": true, "msg": "non-zero return code", "cmd": "cp /etc/sonic/config_dbNone.json /etc/sonic/config_dbNone.json_before_override", "stdout": "", "stderr": "cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory", "rc": 1, "start": "2023-10-06 12:13:06.064153", "end": "2023-10-06 12:13:06.068836", "delta": "0:00:00.004683", "changed": true, "invocation": {"module_args": {"_raw_params": "cp /etc/sonic/config_dbNone.json /etc/sonic/config_dbNone.json_before_override", "_uses_shell": true, "warn": true, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}, "stdout_lines": [], "stderr_lines": ["cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory"], "_ansible_no_log": false}
06/10/2023 12:10:17 __init__._fixture_generator_decorator    L0088 ERROR  | 
run module shell failed, Ansible Results =>
{"changed": true, "cmd": "cp /etc/sonic/config_dbNone.json /etc/sonic/config_dbNone.json_before_override", "delta": "0:00:00.004683", "end": "2023-10-06 12:13:06.068836", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-10-06 12:13:06.064153", "stderr": "cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory", "stderr_lines": ["cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory"], "stdout": "", "stdout_lines": []}
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/override_config_table/test_override_config_table_masic.py", line 53, in setup_env
    backup_config(duthost, config, config_backup)
  File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/override_config_table/utilities.py", line 12, in backup_config
    duthost.shell("cp {} {}".format(config, config_backup))
  File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/common/devices/multi_asic.py", line 118, in _run_on_asics
    return getattr(self.sonichost, self.multi_asic_attr)(*module_args, **complex_args)
  File "/var/src/sonic-mgmt_vms2-t1-7260-7_646f1406735219c3e54440f7/tests/common/devices/base.py", line 127, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "cp /etc/sonic/config_dbNone.json /etc/sonic/config_dbNone.json_before_override", "delta": "0:00:00.004683", "end": "2023-10-06 12:13:06.068836", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-10-06 12:13:06.064153", "stderr": "cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory", "stderr_lines": ["cp: cannot stat '/etc/sonic/config_dbNone.json': No such file or directory"], "stdout": "", "stdout_lines": []}
```
Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305

### CODE REVIEW

**Review by ZhaohuiS — APPROVED** [review]

**Comment by judyjoseph** [comment]
@wenyiz2021 do we need to add this to 202205, 202305  branches also ?

**Comment by wenyiz2021** [comment]
> @wenyiz2021 do we need to add this to 202205, 202305 branches also ?

@judyjoseph this testcase is introduced in https://github.com/sonic-net/sonic-mgmt/pull/9923, origianl PR has not yet ported to 202205 branch. do we need chassis testcase on 202305?

**Comment by judyjoseph** [comment]
Thanks @wenyiz2021 -- yes I did remember that. We could cherry-pick that PR to 202205 and 202305 branch then

**Comment by wenyiz2021** [comment]
@judyjoseph sure, I was waiting for origianl PR to port to 202205 first before adding label for this PR. Added request for 202305 as well on the other PR

**Pull request merged**
