### PR TITLE
Adjust test case for PSU power threshold checking

### PR DESCRIPTION
**Pull request by stephenxs**
### Description of PR

Summary:
Fixes # (issue)

Adjust test case for PSU power threshold checking

1. The slope should be per PSU value instead of global
2. Cosmetic change: power_warning_threshold => power_warning_suppress_threshold
3. Fix pre-commit check failures

Signed-off-by: Stephen Sun <stephens@nvidia.com>

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

Adjust test case for PSU power threshold checking.

#### How did you verify/test it?

Manual and regression test.

### CODE REVIEW

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Failed<br/>- hook id: trailing-whitespace<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing tests/platform_tests/mellanox/test_psu_power_threshold.py<br/><br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Passed<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by liat-grozovik** [comment]
@stephenxs could u please check the pre check commit failure and ensure it is not related to this PR?

**Comment by stephenxs** [comment]
> @stephenxs could u please check the pre check commit failure and ensure it is not related to this PR?

Hi @liat-grozovik 
Thanks
I did and fixed all precheck failures except the left one - it complains about the trailing whitespace but I didn't find it in the PR.
So I do not think it is relevant to the change in the PR.

**Comment by stephenxs** [comment]
> > @stephenxs could u please check the pre check commit failure and ensure it is not related to this PR?
> 
> Hi @liat-grozovik Thanks I did and fixed all precheck failures except the left one - it complains about the trailing whitespace but I didn't find it in the PR. So I do not think it is relevant to the change in the PR.

Hi,
Eventually, I found out and fixed the trailing whitespace which had been introduced form the very beginning.

**Review by nhe-NV — APPROVED** [review]

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
