### PR TITLE
Cisco: Fix the parameters to All-Port-Q-Watermark test. 

### PR DESCRIPTION
**Pull request by rraghav-cisco**
This PR:

1. Adds packet_size parameter that was missed out in qos.yml for topo-t2, and was not being used in the main code as well.
2. Changes the main script to consume all the qos.yml parameters for this test instead of doing them individually - to avoid the problems like point-1 in the future.

@abdosi : For review.
@wangxin : This is duplicate of PR:8818.

### CODE REVIEW

**Review by abdosi — APPROVED** [review]

**Review by wsycqyz — APPROVED** [review]
LGTM

**Comment by abdosi** [comment]
please resolve the conflict.

**Comment by abdosi** [comment]
@rraghav-cisco please resolve the conflict

**Comment by rraghav-cisco** [comment]
> 

@abdosi : Resolved conflicts.

**Review by abdosi — APPROVED** [review]

**Comment by abdosi** [comment]
@wangxin please help to merge this

**Pull request merged**
