### PR TITLE
Porting PR:15099 to 202405: Move the common code from testcases to the fixtures.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
### Description of PR

Summary:
Snappi reboot testcases don't save the config before rebooting the DUT. This causes the DUT to loose all the config, and the test fails with "ARP is not resolved" errors.

This PR addresses this issue by saving the config before any reboot. Also this PR moves the code that is reused in multiple tests to a common code.

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [X] 202405

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@sdszhang , The above error is due to the fact that the PR:https://github.com/sonic-net/sonic-mgmt/pull/14527 is not ported to 202405. I have added a note in this PR to port it to 202405.

**Comment by sdszhang** [comment]
> @sdszhang , The above error is due to the fact that the PR:#14527 is not ported to 202405. I have added a note in this PR to port it to 202405.

Hi @rraghav-cisco , can you modify the code to import get_running_config from the current location  
 tests/override_config_table/utilities.py? in this case, we don't need to port # 14527.

**Comment by rraghav-cisco** [comment]
> > @sdszhang , The above error is due to the fact that the PR:#14527 is not ported to 202405. I have added a note in this PR to port it to 202405.
> 
> Hi @rraghav-cisco , can you modify the code to import get_running_config from the current location tests/override_config_table/utilities.py? in this case, we don't need to port # 14527.

@sdszhang : Yes, implemented this change.

**Comment by sdszhang** [comment]
@rraghav-cisco  there are some conflicts needs to be resolved. can you resolve it?

**Comment by rraghav-cisco** [comment]
> @rraghav-cisco there are some conflicts needs to be resolved. can you resolve it?

@sdszhang : Done.

**Review by sdszhang — APPROVED** [review]
LGTM

**Pull request merged**
