### PR TITLE
[Mellanox] Fix testQosSaiDwrr issue

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Fix issue: https://github.com/sonic-net/sonic-mgmt/issues/10299
Because the method to generate congestion for Mellanox device is changed from disabling the whole port to disabling the queue one by one, and when we recover the port, we also enable the queue one by one. So, it will cause testQosSaiDwrr to fail. testQosSaiDwrr is to test the function of scheduling queue to send packets, the pre-condition is that all queues should be at the same enabled state, but currently, they are enabled back one by one, so the order to send packets is the same as the order to enable the queue not depending on the scheduling algorithm. So, for this case, we still use the original method to generate congestion.

Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/10299

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### What is the motivation for this PR?
Fix issue : https://github.com/sonic-net/sonic-mgmt/issues/10299

#### How did you do it?
For this case, we still use the original method to generate congestion.

#### How did you verify/test it?
Run testQosSaiDwrr  on Mellanox device

#### Any platform specific information?
Mellonax device

#### Supported testbed topology if it's a new test case?
T0

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
MSFT ADO 25238997

**Comment by JibinBao** [comment]
> @JibinBao PR conflicts with 202205 branch

I will open one new PR for 202205 branch

**Comment by JibinBao** [comment]
> @JibinBao Can you file another PR for 202205 branch?

Will file one new for 202205

**Comment by JibinBao** [comment]
Add PR for 202205: https://github.com/sonic-net/sonic-mgmt/pull/10764

**Pull request merged**
