### PR TITLE
[chassis]: Fix bgp session check in container_checker and critical_process_mon tests

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
https://github.com/sonic-net/sonic-mgmt/pull/5478 Added new functions to get bgp neighbors and check bgp sessions for each asic. This was done because bgp session neighbor IP can be same for asics in a Linecard as the neighbor IP will be loopback IP of neighbor LC's ASIC. 
container_checker and process monitoring should use the new functions to get bgp neighbors and check bgp sessions.

#### How did you do it?
Modify container_checker and process monitoring to use get_bgp_neighbors_per_asic() and check_bgp_session_state_all_asics()

#### How did you verify/test it?
Verified on chassis.

Verified on multi-asic VS:
```
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-radv] SKIPPED                                                                               [ 60%]
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-mgmt-framework] PASSED                                                                      [ 66%]
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-nat] SKIPPED                                                                                [ 73%]
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-teamd] PASSED                                                                               [ 80%]
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-dhcp_relay] SKIPPED                                                                         [ 86%]
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-swss] PASSED                                                                                [ 93%]
container_checker/test_container_checker.py::test_container_checker[vlab-08-1-syncd] PASSED                                                                               [100%]

------------------------------- generated xml file: /var/src/sonic-mgmt/tests/logs/multi_asic_t1_lag/container_checker/test_container_checker.xml -------------------------------
============================================================================ short test summary info ============================================================================
SKIPPED [1] /var/src/sonic-mgmt/tests/common/helpers/assertions.py:13: Container 'macsec' is skipped for testing.
SKIPPED [1] /var/src/sonic-mgmt/tests/common/helpers/assertions.py:13: Container 'radv' is skipped for testing.
SKIPPED [1] /var/src/sonic-mgmt/tests/common/helpers/assertions.py:13: Container 'nat' is skipped for testing.
SKIPPED [1] /var/src/sonic-mgmt/tests/common/helpers/assertions.py:13: Container 'dhcp_relay' is skipped for testing.
SKIPPED [1] /var/src/sonic-mgmt/tests/common/helpers/assertions.py:13: Container 'sflow' is skipped for testing.
SKIPPED [1] /var/src/sonic-mgmt/tests/common/helpers/assertions.py:13: Container 'mux' is skipped for testing.
==================================================================== 9 passed, 6 skipped in 1126.06 seconds =====================================================================
INFO:root:Can not get Allure report URL. Please check logs
sumeenak@d38f5615ba78:/var/src/sonic-mgmt/tests$
sumeenak@d38f5615ba78:/var/src/sonic-mgmt/tests$ ./run_tests.sh -i ../ansible/veos_vtb -d vlab-08 -n vms-kvm-four-asic-t1-lag -f vtestbed.yaml -k debug -l warning -m individual -q 1 -a False -O -r -e --allow_recover -E -c 'process_monitoring/test_critical_process_monitoring.py' -p logs/multi_asic_t1_lag -e --disable_loganalyzer -e --skip_sanity -u
=== Running tests individually ===
Running: pytest process_monitoring/test_critical_process_monitoring.py --inventory ../ansible/veos_vtb --host-pattern vlab-08 --testbed vms-kvm-four-asic-t1-lag --testbed_file vtestbed.yaml --log-cli-level warning --log-file-level debug --kube_master unset --showlocals --assert plain --show-capture no -rav --ignore=ptftests --ignore=acstests --ignore=saitests --ignore=scripts --ignore=k8s --ignore=sai_qualify --maxfail=1 --log-file logs/multi_asic_t1_lag/process_monitoring/test_critical_process_monitoring.log --junitxml=logs/multi_asic_t1_lag/process_monitoring/test_critical_process_monitoring.xml --allow_recover --disable_loganalyzer --skip_sanity
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
============================================================================== test session starts ==============================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.11.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /var/src/sonic-mgmt/tests, inifile: pytest.ini
plugins: allure-pytest-2.8.22, forked-1.3.0, metadata-1.11.0, html-1.22.1, repeat-0.9.1, xdist-1.28.0, ansible-2.2.2
collected 1 item                                                                                                                                                                

process_monitoring/test_critical_process_monitoring.py::test_monitoring_critical_processes PASSED                                                                         [100%]

------------------------- generated xml file: /var/src/sonic-mgmt/tests/logs/multi_asic_t1_lag/process_monitoring/test_critical_process_monitoring.xml --------------------------
========================================================================== 1 passed in 760.62 seconds ===========================================================================
INFO:root:Can not get Allure report URL. Please check logs
sumeenak@d38f5615ba78:/var/src/sonic-mgmt/tests$ ./run_tests.sh -i ../ansible/veos_vtb -d vlab-08 -n vms-kvm-four-asic-t1-lag -f vtestbed.yaml -k debug -l warning -m individual -q 1 -a False -O -r -e --allow_recover -E -c 'process_monitoring/test_critical_process_monitoring.py' -p logs/multi_asic_t1_lag -e --disable_loganalyzer -e --skip_sanity -u
=== Running tests individually ===
Running: pytest process_monitoring/test_critical_process_monitoring.py --inventory ../ansible/veos_vtb --host-pattern vlab-08 --testbed vms-kvm-four-asic-t1-lag --testbed_file vtestbed.yaml --log-cli-level warning --log-file-level debug --kube_master unset --showlocals --assert plain --show-capture no -rav --ignore=ptftests --ignore=acstests --ignore=saitests --ignore=scripts --ignore=k8s --ignore=sai_qualify --maxfail=1 --log-file logs/multi_asic_t1_lag/process_monitoring/test_critical_process_monitoring.log --junitxml=logs/multi_asic_t1_lag/process_monitoring/test_critical_process_monitoring.xml --allow_recover --disable_loganalyzer --skip_sanity
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
======================================================================== test session starts ========================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.11.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /var/src/sonic-mgmt/tests, inifile: pytest.ini
plugins: allure-pytest-2.8.22, forked-1.3.0, metadata-1.11.0, html-1.22.1, repeat-0.9.1, xdist-1.28.0, ansible-2.2.2
collected 1 item                                                                                                                                                    

process_monitoring/test_critical_process_monitoring.py::test_monitoring_critical_processes PASSED                                                             [100%]

------------------- generated xml file: /var/src/sonic-mgmt/tests/logs/multi_asic_t1_lag/process_monitoring/test_critical_process_monitoring.xml --------------------
==================================================================== 1 passed in 742.79 seconds =====================================================================
INFO:root:Can not get Allure report URL. Please check logs
```

### CODE REVIEW

**Comment by SuvarnaMeenakshi** [comment]
@anamehra please check

**Review by abdosi — DISMISSED** [review]
LGTM. Can you update description section with the need to increase the timeout value

**Comment by SuvarnaMeenakshi** [comment]
> @anamehra please check

@anamehra in PR 5097 you have mentioned about 'Added a sleep to wait for bgp list to be populated post container restart.'
I did not find a case where this is required, can you check with latest changes if the additional sleep is required.

**Comment by SuvarnaMeenakshi** [comment]
> LGTM. Can you update description section with the need to increase the timeout value

removed the additional sleep as it is not required.

**Review by abdosi — APPROVED** [review]

**Pull request merged**
