### PR TITLE
fix ip_inip testcase ignore ttl condition

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Fix ip_in_ip test case ignore ttl condition. We are using outer ipv4 and inner ipv6 so we need to use ipv4 as ip header for setting up ignore ttl/checksum condition.

How I verify:
After fix test case passes for multi-asic platforms.

### CODE REVIEW

**Comment by abdosi** [comment]
@vperumal/ for reference.

**Comment by abdosi** [comment]
@wangxin can you please help with review/merge of this

**Comment by vperumal** [comment]
Thanks @abdosi , the fix works, I was able to try out and confirm it

fib/test_fib.py::test_basic_fib[True-True-1514] PASSED                   [ 14%]
fib/test_fib.py::test_hash[ipv4] PASSED                                  [ 28%]
fib/test_fib.py::test_hash[ipv6] PASSED                                  [ 42%]
fib/test_fib.py::test_ipinip_hash[ipv4] SKIPPED                          [ 57%]
fib/test_fib.py::test_ipinip_hash[ipv6] SKIPPED                          [ 71%]
fib/test_fib.py::test_ipinip_hash_negative[ipv4] PASSED                  [ 85%]
fib/test_fib.py::test_ipinip_hash_negative[ipv6] PASSED                  [100%]

**Review by vperumal — APPROVED** [review]

**Review by xwjiang-ms — APPROVED** [review]
@abdosi LGTM, do we need to cherry-pick to other release branches?

**Comment by wangxin** [comment]
Cherry-pick PR to 202305: https://github.com/sonic-net/sonic-mgmt/pull/10791

**Pull request merged**
