### PR TITLE
[Mellanox] Update generic hash INNER_IP_PROTOCOL skip condition 

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Update generic hash INNER_IP_PROTOCOL skip condition due to hw capabilities

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Update skip condition for hash field INNER_IP_PROTOCOL
#### How did you do it?
Add skips
#### How did you verify/test it?
Run it in internal regression

### CODE REVIEW

**Review by liat-grozovik — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@echuawu can you please handle conflict so i can merge?

**Comment by echuawu** [comment]
> @echuawu can you please handle conflict so i can merge?

Hi @liat-grozovik , the conflict has been fixed.

**Review by nhe-NV — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by echuawu** [comment]
Hi @bingwang-ms , could you please merge it into branch 202411?

**Comment by echuawu** [comment]
Hi, @bingwang-ms, the conflict had been handled in https://github.com/sonic-net/sonic-mgmt/pull/17562

**Pull request merged**
