### PR TITLE
Get estimated pkts_num_egr_mem in run time for cisco-8000 multi-dut

### PR DESCRIPTION
**Pull request by zhixzhu**
### Description of PR

1. Improve fill_egress_plus_one to support unknown pkts_num_egr_mem and multi streams.
  - If pkts_num_egr_mem is 0, call overflow_egress to get estimated pkts_num_egr_mem
  - In multi-asic scenario, multiple streams could take the same or different BP port as egress port in ingress asic.
  -- Send 1 pkt first, stop if pg occupancy increase, --> This is the case when 2nd stream goes to the same BP port as 1st stream
  -- else continue with original steps. --> This is the case when 2nd stream goes to different BP port
 
2. Updated xoff case, use fill_egress_plus_one at the beginning of the case. Updated qos.yml data accordingly. Previous the pkts num of fill egress is included in pkts_num_trig_pfc and pkts_num_trig_ingr_drp.

3. For 3 cases(xoff, xon, wm_pg_shared_lossless) which use fill_egress for multi-asic, add multi-dut check, if multi-dut, set pkts_num_egr_mem to 0 and get estimated pkts_num_egr_mem at run time. Because in multi-dut scenario, the egress asic and ingress asic will be in different rdma config, one is long-link with hbm, the other is short-link with sms. pkts_num_egr_mem in qos.yml is only accurate when ingress port and egress port are in same rdma config.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### CODE REVIEW

**Comment by wangxin** [comment]
@zhixzhu Is this a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description?

**Comment by rraghav-cisco** [comment]
> @zhixzhu Is this a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description?

Hi @wangxin : No this is a new PR off 202205. The master branch doesn't have the multi-asic code needed for this PR.

**Comment by wangxin** [comment]
> > @zhixzhu Is this a backport of master branch PR to 202205 branch? Can you mention the master branch PR ID here in PR description?
> 
> Hi @wangxin : No this is a new PR off 202205. The master branch doesn't have the multi-asic code needed for this PR.

OK. Can you resolve the conflicts? @XuChen-MSFT @wsycqyz Can you help review this PR? After the PR is approved, then we can merge it.

If the master branch doesn't have multi-asic code, how to move on with future releases? For example, when create 202305 branch from master, then the 202305 branch would not have the multi-asic code. All of the current work to the 202205 branch would need to be done again for 202305 branch. 

How do we move on?

**Comment by rraghav-cisco** [comment]
> 

@wangxin , The master needs the PR:https://github.com/sonic-net/sonic-mgmt/pull/8149 before adding all the fixes from our end.

**Comment by wangxin** [comment]
Thanks @rraghav-cisco for the info. Let's try to get 8149 merged. Then close this PR and submit it to master branch instead.

**Comment by zhixzhu** [comment]
L-S and S-L scenarios have the same pkts number to fill egress, no need to fill it dynamically.

**Pull request closed without merging**
