### PR TITLE
[tacacs]Fix directory not correct issue in test_ro_disk.py

### PR DESCRIPTION
**Pull request by nhe-NV**
test_ro_disk.py is failed when "os.mkdir(DATA_DIR)", change the value of DATA_DIR
With 'DATA_DIR = "logs/tacacs"' it will throw errs, [Errno 2] No such file or directory: 'logs/tacacs', change it to '/logs/tacacs'

Change-Id: I57d75229b54e50bda83a5c71b1ba3068db0ad277

### Description of PR

Summary: test_ro_disk.py is failed when "os.mkdir(DATA_DIR)", change the value of DATA_DIR
 With 'DATA_DIR = "logs/tacacs"' it will throw errs, [Errno 2] No such file or directory: 'logs/tacacs', change it to '/logs/tacacs'
Fixes # (issue) With 'DATA_DIR = "logs/tacacs"' it will throw errs, [Errno 2] No such file or directory: 'logs/tacacs', change it to '/logs/tacacs'

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Fix test_ro_disk.py is failure
#### How did you do it?
change DATA_DIR value to '/logs/tacacs'

### CODE REVIEW

**Comment by wangxin** [comment]
@nhe-NV It looks like the PR test failure is related with your change. Below is the error message in detailed test log:
```
03/11/2022 13:36:25 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/var/src/sonic-mgmt/tests/tacacs/test_ro_disk.py", line 200, in test_ro_disk
    os.mkdir(DATA_DIR)
OSError: [Errno 2] No such file or directory: '/logs/tacacs'
```
The above error is in log of running tacacs/test_ro_disk.py on KVM t0 testbed.

**Comment by nhe-NV** [comment]
> 

Thanks @wangxin , it is my fault, I will abandon this PR.

**Pull request closed without merging**
