### PR TITLE
Update pfc_gen_t2.py

### PR DESCRIPTION
**Pull request by harsgoll**
While running PFCWD test cases, encountered concatenation issue on sonic fanout.

root@xx37-root-fanout:/tmp# sudo nice --20 python pfc_gen_t2.py -p 16 -t 65535 -s 8 -n 1000000 -i Ethernet152 -r 1.76.0.62 Traceback (most recent call last):
File "/tmp/pfc_gen_t2.py", line 340, in
main()
File "/tmp/pfc_gen_t2.py", line 264, in main
fo_logger.debug(fo_str + ' sendmmsg got errno ' + str(errno) + ' for socket ' + s.getsockname()) TypeError: can only concatenate str (not "tuple") to str

We converted s.getsockname() into str and able to proceed further.

Cc: sanjair-git, @rraghav-cisco

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@sanjair-git : Pls review.

**Review by auspham — APPROVED** [review]

**Comment by auspham** [comment]
@yejianquan  Could you help rebuild azp run

**Comment by auspham** [comment]
@abdosi this needs to be merged in

**Comment by auspham** [comment]
Hi @harsgoll i'm raising a new PR as this one has stiling issue. I'll cherry pick your comment there.

**Comment by auspham** [comment]
Closing as raised in #15527

**Pull request closed without merging**
