### PR TITLE
Revert adding 'any' topology to pre/post tests

### PR DESCRIPTION
**Pull request by patrickmacarthur**
### Description of PR

The pre/post tests are intended to be run before and after the entire body of tests run, respectively. They were marked with the 'util' topology as such, so that they would not be considered for being run in the middle of the test run. However, a change was made which added the 'any' topology, which caused the pre- and post-tests to run twice: once at the start and end, and once in the middle of the test run in the lexicographical sequence.

Removing 'any' means it will only be run at the start and end of the test run as intended.

Summary:

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
This PR removes the redundant execution of pre- and post-tests in the middle of the test run.

#### How did you do it?
I removed the 'any' topology from these tests.

#### How did you verify/test it?
The changes were verified manually by doing a test run and verifying through manual inspection that the pre- and post-tests executed at the start and end, respectively, but not in the middle of the test run in the lexicographical sequence.

#### Any platform specific information?
N/A

#### Supported testbed topology if it's a new test case?
N/A

### CODE REVIEW

**Review by wenyiz2021 — APPROVED** [review]
LGTM

**Comment by wenyiz2021** [comment]
@yejianquan for review

**Comment by yejianquan** [comment]
Offline discussed with @wangxin , he will explicitly exclude pretest and posttest in the run_test.sh to avoid the duplicate run.
So that it will no affect Elastcitest

**Comment by yejianquan** [comment]
> Offline discussed with @wangxin , he will explicitly exclude pretest and posttest in the run_test.sh to avoid the duplicate run. So that it will no affect Elastcitest

Please don't merge this PR, and close it after Xin's change is created and merged

**Comment by wenyiz2021** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/11497 can address such issue by skipping pre/post checks in run_test.sh, the label was added to port to 202205 branch.
closing current PR

**Pull request closed without merging**
