### PR TITLE
Fix gnmi test to support t1 topo

### LINKED ISSUE #7462: test_gnmi_configdb.py fails and block sanity check
**Description**

The failed reason is as below:
```
2023-01-23T21:48:43.3970447Z gnmi/test_gnmi_configdb.py::test_gnmi_configdb_incremental_01 
2023-01-23T21:48:43.3977200Z -------------------------------- live log call ---------------------------------
2023-01-23T21:48:43.3979950Z 21:48:43 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
2023-01-23T21:48:43.3983142Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
2023-01-23T21:48:43.3985333Z     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
2023-01-23T21:48:43.3988037Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
2023-01-23T21:48:43.3990294Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2023-01-23T21:48:43.3993103Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
2023-01-23T21:48:43.3995348Z     return self._inner_hookexec(hook, methods, kwargs)
2023-01-23T21:48:43.3998695Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
2023-01-23T21:48:43.4001087Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2023-01-23T21:48:43.4004049Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
2023-01-23T21:48:43.4006044Z     return outcome.get_result()
2023-01-23T21:48:43.4008469Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
2023-01-23T21:48:43.4011422Z     _reraise(*ex)  # noqa
2023-01-23T21:48:43.4014629Z   File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
2023-01-23T21:48:43.4016602Z     res = hook_impl.function(*args)
2023-01-23T21:48:43.4019354Z   File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
2023-01-23T21:48:43.4021717Z     testfunction(**testargs)
2023-01-23T21:48:43.4023924Z   File "/azp/_work/19/s/tests/gnmi/test_gnmi_configdb.py", line 63, in test_gnmi_configdb_incremental_01
2023-01-23T21:48:43.4026152Z     assert interface is not None, "Invalid interface"
2023-01-23T21:48:43.4027828Z AssertionError: Invalid interface
2023-01-23T21:48:43.4028523Z 
```

**Steps to reproduce the issue:**
1. run gnmi/test_gnmi_configdb.py
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

### PR DESCRIPTION
**Pull request by ganglyu**
### Description of PR

Summary:
Fixes #7462

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
test_gnmi_configdb.py fails and block sanity check

#### How did you do it?
Port vlan type should be trunk or portchannel, and portchannel vlan type should be routed.

#### How did you verify/test it?
Run gNMI end2end test.

### CODE REVIEW

**Comment by ZhaohuiS** [comment]
@ganglyu If test case fails or some other reason to cause traceback, will the case mess up config db? Just curious why sanity check failed behind this case, not sure if it messes up config_db or just it's coincident to happen after this case.

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Passed<br/>fix end of files.........................................................Passed<br/>check yaml...............................................................Passed<br/>check for added large files..............................................Passed<br/>check python ast.........................................................Passed<br/>flake8...................................................................Failed<br/>- hook id: flake8<br/>- exit code: 1<br/><br/>tests/gnmi/helper.py:43:1: E302 expected 2 blank lines, found 1<br/>tests/gnmi/helper.py:50:1: E302 expected 2 blank lines, found 1<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by ganglyu** [comment]
> @ganglyu If test case fails or some other reason to cause traceback, will the case mess up config db? Just curious why sanity check failed behind this case, not sure if it messes up config_db or just it's coincident to happen after this case.

I find that telemetry service failed to start, and now sanity check can pass after gnmi test.

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Pull request merged**
