### PR TITLE
Enhance qos tests to support single-asic, multi-asic, and multi-dut testing

### PR DESCRIPTION
**Pull request by vmittal-msft**
### Description of PR

Summary:
Fixes # (issue)
The existing QoS (test_qos_sai.py) is written to accomodata a single asic on a single Dut. But, we require the same tests to be executed against a T2 chassis (with single/multi-asic linecards) and multi-asic pizza boxes.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
All the test cases create a list of src and dst ports. For the different modes, here is the distribution of the src and dst ports:
- single_asic: The src and dst ports are on the same asic on the same linecard.
- single_dut_multi_asic: On a multi-asic DUT/linecard, the src port is on an asic, while the dst ports are on another asic on the same DUT/linecard
- multi_dut: The src port is on an asic on one of the DUT/linecards, and the dst port is on another asic on another DUT/linecard. This is currently only required for T2 topology

#### How did you do it?
Approach to accomplish this is the following:
- All the tests have to parameterized for the 3 modes defined above.
  - This is done using the 'select_src_and_dst_dut_and_asic' fixture that is parameterized for 'single_asic', 'single_dut_multi_asic', 'multi_dut' - Based on the mode, it sets the src_dut_index, dst_dut_index, src_asic_index and dst_asic_index
  - Added fixture 'get_src_dst_asic_and_duts' that returns dictionary of the src_dut_index, dst_dut_index, src_asic_index, and dst_asic_index, and the src_dut and dst_dut (instances of MultiAsicSonicHost), src_asic and dst_asic (instances of Asic), and also a list of all DUTs and all Asics
- dutConfig is modified such that testPortIds and testPortIps are collecting from all the duts and asics involved and stored in a dictionary with key being the dutIndex and value being a dictionary per asic index.
   - __buildTestPorts then sets the src and dst ports based on the src_dut_index, dst_dut_index, src_asic_index and dst_asic_index
- All the other fixtures and tests, we use 'get_src_dst_asci_and_duts' fixture instead of enum_rand_one_frontend_hostname and enum_frontend_index.
  - The code instead the fixtures and tests is modified to the actions on the correct src/dst dut or asic. For example: - swap_syncd fixture would swap syncd docker on all DUT's (both src and dst) instead of just one DUT as before. - stopServices - do it all_duts (src and dst duts)

- Similarly, changes to saitests involved dealing with multiple DUTs (and thus multiple sai clients) and modifying other data structure like 'interface_to_front_mapping' in sai_base_test.py and port_list, sai_port_list, front_port_list in switch.py to deal with multiple duts (modified to be dictionary with keys being 'src' and 'dst')
  - default_interface_to_front_map.ini file in ptf modified to have syntax: ptf_port@dut_port:dut_index - Done by using new fixture 'ptf_portmap_file_all_frontend_nodes' in ptfhost_utils.py
  - tests in sai_qos_tests.py pass src_dut_index and dst_dut_index in the testParams.
     - The saitests classes then use this to do the actions on the right client and ports.

- Assumptions:
  - For multi-dut, we are assuming that hwsku for all the cards are same.

#### How did you verify/test it?
Ran the tests against T2 J2C+ chassis.

### CODE REVIEW

**Comment by vmittal-msft** [comment]
Porting changes from following PR to master branch - 
https://github.com/sonic-net/sonic-mgmt/pull/6946

Same changes has been pushed to 202205 branch recently using -
https://github.com/sonic-net/sonic-mgmt/pull/8059

**Comment by vmittal-msft** [comment]
202205 PR - https://github.com/sonic-net/sonic-mgmt/pull/8213

**Comment by xwjiang-ms** [comment]
The pre-commit check is a mandatory check, please fix detected issues

**Comment by wsycqyz** [comment]
The pre-commit check is a mandatory check, please fix.

**Comment by XuChen-MSFT** [comment]
@vmittal-msft did you run qos test on single box device?  and can you resolve conflict?

**Comment by wangxin** [comment]
@vmittal-msft This is a critical PR to master branch to include all the multi-asic related code to unblock lots of fixes required for 202205 branch. Can you handle the comments and conflicts with priority?

**Comment by vmittal-msft** [comment]
Sure. Will work on this.

**Comment by wsycqyz** [comment]
The pre-commit check is mandatory. Please fix according to the output.

**Review by XuChen-MSFT — APPROVED** [review]
validated fix on t1 , t0, dualtor , and cover broadcom and mellanox platform. only a few failure in test, and these failure are known issue,, not related to this changes.
ready for merge.

**Comment by vmittal-msft** [comment]
@XuChen-MSFT after pre-commit fixes, i am seeing some failures. Fixing them. not ready to merge yet.

**Review by XuChen-MSFT — APPROVED** [review]
LGTM

**Pull request merged**
