### PR TITLE
[doc] fix link to README.testbed.Setup.md in spytest/Doc/install.md

### PR DESCRIPTION
**Pull request by andriidovhan**
### Description of PR

Summary:
Fixes # (This PR fixes link to `README.testbed.Setup.md` in `spytest/Doc/install.md`)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)
- [x] Doc (fix link in documentation)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
just want the documentation up to date

#### How did you do it?
find the file by the 'find' command and replace obsolete URL

#### How did you verify/test it?
It was checked manually that the new link is not broken and it is redirected to correct file.

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
@andriidovhan Thanks for your contribution! Can you sign the EasyCLA? Then we can have this PR merged.

**Comment by andriidovhan** [comment]
@wangxin done, thx.

**Pull request merged**
