### PR TITLE
[202205] Fixing auto_techsupport

### PR DESCRIPTION
**Pull request by davidm-arista**
sonic-mgmt bug Fix: Fix regex parser for show auto-techsupport global command

### CODE REVIEW

**Comment by xwjiang-ms** [comment]
@davidm-arista  LGTM, could you also cherry-pick this file to master branch?

**Review by xwjiang-ms — APPROVED** [review]
@davidm-arista  LGTM, could you also cherry-pick this file to master branch? Suggest go master first in future.

**Comment by davidm-arista** [comment]
This patch doesn't apply to master.  The file is quite different in master.

**Comment by Blueve** [comment]
> This patch doesn't apply to master. The file is quite different in master.

@davidm-arista Do we have same issue in master branch image now?

**Comment by davidm-arista** [comment]
> 

I haven't looked at master test results, but the code is different enough, that I doubt the same issue exists.  We can look later once the 202205 results are looking good.

**Pull request merged**
