### PR TITLE
[test_bgp_update_timer] Increase update time when suppress feature is enabled on device

### PR DESCRIPTION
**Pull request by stepanblyschak**
### Description of PR

Summary: Increase update time when suppress feature is enabled on device
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

On image with suppress-fib-pending know set it is expected to get BGP update later due to additional messages need to be sent between bgpd/zebra/fpmsyncd.

E.g:

```
Mar 29 14:19:20.949852 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:20 BGP: [W0R38-AAD36] 20.0.0.1 rcvd 10.10.100.128/27 IPv4 unicast

Mar 29 14:19:21.010574 r-tigon-11 INFO bgp#fpmsyncd: :- isRawProcessing: Rx MsgType:24 Encap:0
Mar 29 14:19:21.010722 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [YXCJP-0WZWV] netlink_nexthop_msg_encode: ID (713): 20.0.0.1, via PortChannel1015(1194) vrf default(0)
Mar 29 14:19:21.010722 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [R43C6-KYHWT] netlink_nexthop_msg_encode: RTM_NEWNEXTHOP, id=713
Mar 29 14:19:21.010722 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [YXPF5-B2CE0] netlink_route_multipath_msg_encode: RTM_NEWROUTE 10.10.100.128/27 vrf 0(254)
Mar 29 14:19:21.010722 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [J87BH-XW5PP] netlink_route_multipath_msg_encode: 10.10.100.128/27 nhg_id is 713
Mar 29 14:19:21.010777 r-tigon-11 DEBUG bgp#fpmsyncd: :> sendOffloadReply: enter
Mar 29 14:19:21.010777 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [HYEHE-CQZ9G] nl_batch_send: netlink-dp (NS 0), batch size=108, msg cnt=2
Mar 29 14:19:21.010915 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [YXPF5-B2CE0] netlink_route_multipath_msg_encode: RTM_NEWROUTE 10.10.100.128/27 vrf 0(254)
Mar 29 14:19:21.010915 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [TVM3E-A8ZAG] _netlink_route_build_singlepath: (single-path): 10.10.100.128/27 nexthop via 20.0.0.1  if 1194 vrf default(0)
Mar 29 14:19:21.010915 r-tigon-11 DEBUG bgp#fpmsyncd: :> sendOffloadReply: enter
Mar 29 14:19:21.010915 r-tigon-11 DEBUG bgp#fpmsyncd: :< sendOffloadReply: exit
Mar 29 14:19:21.011049 r-tigon-11 DEBUG bgp#fpmsyncd: :< sendOffloadReply: exit
Mar 29 14:19:21.011049 r-tigon-11 DEBUG bgp#fpmsyncd: :- onRouteMsg: RouteTable set msg: 10.10.100.128/27 20.0.0.1 PortChannel1015

Mar 29 14:19:21.011049 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [TS3SH-1276M] default(0:254):10.10.100.128/27 update_from_ctx(): no fib nhg
Mar 29 14:19:21.011188 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [HKQXC-4STSK] default(0:254):10.10.100.128/27 update_from_ctx(): rib nhg matched, changed 'true'
Mar 29 14:19:21.011188 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [Z1MP1-RFGJA] (0:254):10.10.100.128/27(0): Redist update re 0x564c62d6ef90 (bgp), old 0x0 (None)
Mar 29 14:19:21.011188 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [K2A4T-TS83H] RTM_NEWROUTE 10.10.100.128/27 vrf default(0) table_id: 254 metric: 20 Admin Distance: 0
Mar 29 14:19:21.011188 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [TJXPZ-RC5XQ] default(0:254):10.10.100.128/27 Processing dplane notif ctx 0x7f585cca5e60
Mar 29 14:19:21.011258 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [TS3SH-1276M] default(0:254):10.10.100.128/27 update_from_ctx(): no fib nhg
Mar 29 14:19:21.011310 r-tigon-11 INFO bgp#supervisord: zebra 2023/03/29 14:19:21 ZEBRA: [P37HH-D4J54] default(0:254):10.10.100.128/27 update_from_ctx(): changed true, adding new fib nhg (empty)
Mar 29 14:19:21.012001 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MQ4TN-P2T15] route 10.10.100.128/27 : INSTALLED

Mar 29 14:19:21.173660 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [TN0HX-6G1RR] u2:s2 send UPDATE w/ attr: nexthop 0.0.0.0, origin i, community 5060:12345, path 61000
Mar 29 14:19:21.173775 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [HVRWP-5R9NQ] u2:s2 send UPDATE 10.10.100.128/27 IPv4 unicast
Mar 29 14:19:21.173775 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [WEV7K-2GAQ5] u2:s2 send UPDATE len 60 (max message len: 4096) numpfx 1
Mar 29 14:19:21.173815 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.43 send UPDATE w/ nexthop 10.0.0.42
Mar 29 14:19:21.173815 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.49 send UPDATE w/ nexthop 10.0.0.48
Mar 29 14:19:21.173836 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.1 send UPDATE w/ nexthop 10.0.0.0
Mar 29 14:19:21.295692 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.69 send UPDATE w/ nexthop 10.0.0.68
Mar 29 14:19:21.295692 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.9 send UPDATE w/ nexthop 10.0.0.8
Mar 29 14:19:21.748081 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.51 send UPDATE w/ nexthop 10.0.0.50
Mar 29 14:19:21.938562 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.67 send UPDATE w/ nexthop 10.0.0.66
Mar 29 14:19:21.938562 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.59 send UPDATE w/ nexthop 10.0.0.58
Mar 29 14:19:21.939013 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.71 send UPDATE w/ nexthop 10.0.0.70
Mar 29 14:19:21.939013 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.39 send UPDATE w/ nexthop 10.0.0.38
Mar 29 14:19:21.939086 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:21 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.35 send UPDATE w/ nexthop 10.0.0.34
Mar 29 14:19:22.011515 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [TN0HX-6G1RR] u3:s9 send UPDATE w/ attr: nexthop 0.0.0.0, origin i, community 5060:12345, path 61000
Mar 29 14:19:22.011515 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [HVRWP-5R9NQ] u3:s9 send UPDATE 10.10.100.128/27 IPv4 unicast
Mar 29 14:19:22.011620 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [WEV7K-2GAQ5] u3:s9 send UPDATE len 60 (max message len: 4096) numpfx 1
Mar 29 14:19:22.011620 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u3:s9 20.0.0.3 send UPDATE w/ nexthop 20.0.0.2
Mar 29 14:19:22.011620 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u3:s9 20.0.0.1 send UPDATE w/ nexthop 20.0.0.0
Mar 29 14:19:22.012261 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.57 send UPDATE w/ nexthop 10.0.0.56
Mar 29 14:19:22.012261 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.55 send UPDATE w/ nexthop 10.0.0.54
Mar 29 14:19:22.012455 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.5 send UPDATE w/ nexthop 10.0.0.4
Mar 29 14:19:22.012455 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.45 send UPDATE w/ nexthop 10.0.0.44
Mar 29 14:19:22.012455 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.65 send UPDATE w/ nexthop 10.0.0.64
Mar 29 14:19:22.012487 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.63 send UPDATE w/ nexthop 10.0.0.62
Mar 29 14:19:22.012519 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.41 send UPDATE w/ nexthop 10.0.0.40
Mar 29 14:19:22.012519 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.47 send UPDATE w/ nexthop 10.0.0.46
Mar 29 14:19:22.012519 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.13 send UPDATE w/ nexthop 10.0.0.12
Mar 29 14:19:22.012566 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.37 send UPDATE w/ nexthop 10.0.0.36
Mar 29 14:19:22.012566 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.33 send UPDATE w/ nexthop 10.0.0.32
Mar 29 14:19:22.012661 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.61 send UPDATE w/ nexthop 10.0.0.60
Mar 29 14:19:22.012661 r-tigon-11 INFO bgp#supervisord: bgpd 2023/03/29 14:19:22 BGP: [MBFVT-8GSC6] u2:s2 10.0.0.53 send UPDATE w/ nexthop 10.0.0.52
```

Shows that more then 1 sec is sometimes required.

#### How did you do it?

Check if ```suppress-fib-pending``` knob is set and then double the interval.

#### How did you verify/test it?

Run on the image with ```suppress-fib-pending``` knob set.

### CODE REVIEW

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Review by jcaiMR — APPROVED** [review]

**Comment by stepanblyschak** [comment]
@jcaiMR @StormLiangMS These warnings raised by pre-commit check aren't for the code that is being added in this PR. Can we please merge?

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@stepanblyschak can this be merged even if the feature is not enabled? we currently using the same branch for both 202211 and master

**Comment by stepanblyschak** [comment]
@liat-grozovik Yes, the code checks if feature is enabled

**Pull request merged**
