### PR TITLE
Fix test_events instability

### PR DESCRIPTION
**Pull request by zbud-msft**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?

test_events success is flaky. Refactoring to help consistency

#### How did you do it?

Code change

#### How did you verify/test it?

Starlab test environment

### CODE REVIEW

**Comment by yejianquan** [comment]
Since the test_events.py still fails on this PR, I have merged https://github.com/sonic-net/sonic-mgmt/pull/8295

**Comment by yejianquan** [comment]
> > Since the test_events.py still fails on this PR, I have merged #8295
> 
> @yejianquan Earlier test failed due to issue with docker exec command

@lerry-lee , can you help to verify the stability? Please run 50 rounds.

**Comment by lerry-lee** [comment]
@zbud-msft 
I ran test_events.py on T0-topo fifty times, but it still failed more than half. Can you please check the fix again?
image
image

**Comment by zbud-msft** [comment]
@lerry-lee Thanks, I will revise fix.

**Comment by zbud-msft** [comment]
Closing PR, opened new PR: https://github.com/sonic-net/sonic-mgmt/pull/8819

**Pull request closed without merging**
