### PR TITLE
Fix test_check_show_lpmode case

### PR DESCRIPTION
**Pull request by weiguo-nvidia**
### Description of PR

Summary: Fix test_check_show_lpmode case
Fixes # PR #15062 fix the test_check_show_lpmode case and merge in **master** branch, but conflicts with **202405** branch. So create this PR to submit the code to **202405** branch

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

### CODE REVIEW

**Comment by weiguo-nvidia** [comment]
Hi @mihirpat1 ,

The PR #15062 had merge to master branch, but it cherry-pick conflicts with 202405 branch. So I submit this PR to 202405 branch. Could you help review it? Thanks

**Comment by weiguo-nvidia** [comment]
Hi @mihirpat1 , could you help review the merged PR

**Review by Blueve — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Pull request merged**
