### PR TITLE
[202205] Backport auto-techsupport related PR#7365 into 202205 branch

### PR DESCRIPTION
**Pull request by ppikh**
### Description of PR
Backport auto-techsupport related PR# 7365 into 202205 branch

Summary: Backport auto-techsupport related PR# 7365 into 202205 branch
Fixes # (issue)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Backport auto-techsupport related PR# 7365 into 202205 branch

#### How did you do it?
cherry-pick PR#7365

#### How did you verify/test it?
Run test

### CODE REVIEW

**Comment by yxieca** [comment]
@ppikh  can you sign the CLA?

**Comment by ppikh** [comment]
@yxieca How to do it? I did sign for easycla 5 times, but it still shows that it's not signed.

**Comment by yxieca** [comment]
> @yxieca How to do it? I did sign for easycla 5 times, but it still shows that it's not signed.

@zhangyanzhao we still have challenge with easycla, can you share the instructions again?

**Comment by ppikh** [comment]
Another similar PR opened. https://github.com/sonic-net/sonic-mgmt/pull/8181 it passed EasyCLA check.

**Pull request closed without merging**
