### PR TITLE
skip test_bgp_suppress_fib in 202405 release

### PR DESCRIPTION
**Pull request by AnantKishorSharma**
### Description of PR
As the required SW changes are not available in 202405 we should skip test_bgp_suppress_fib for 202405

"We should not be taking this change in 202405 as we don't have the required memory enhancements that are part of master only. From 202411 we will have fib suppression feature"([Revert "Remove suppress-fib-pending CLI and make route_check.py check suppress-fib in BGP configuration" by dgsudharsan · Pull Request #3477 · sonic-net/sonic-utilities](https://github.com/sonic-net/sonic-utilities/pull/3477#issuecomment-2353123101) ).

Summary:
Fixes #https://github.com/sonic-net/sonic-mgmt/issues/14381

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Skip the test as the functionality is not available in the release 202405
#### How did you do it?
Skip the test for 202405 release
#### How did you verify/test it?
Test skipped
```
------ generated xml file: /run_logs/ananshar/bgp/test_bgp_suppress_fib_2024-09-18-06-43-54.xml ------

--------------------------------------- live log sessionfinish ---------------------------------------
06:44:05 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
====================================== short test summary info =======================================
SKIPPED [2] bgp/test_bgp_suppress_fib.py:717: Not supported before release 202411.
SKIPPED [5] bgp/test_bgp_suppress_fib.py: Not supported before release 202411.
=================================== 7 skipped, 1 warning in 9.53s ====================================
```
#### Any platform specific information?
Generic issue
#### Supported testbed topology if it's a new test case?
NA
### Documentation
NA

### CODE REVIEW

**Comment by AnantKishorSharma** [comment]
Hi @kevinskwang , please review.

**Review by bpar9 — CHANGES_REQUESTED** [review]
can you change this line <<As the required SW changes are not available in 202411 we should skip test_bgp_suppress_fib for 202411>> to have 202405 and not 202411 because the required changes will be available in 202411, isnt it? which is why you had put the skip for 202405 and not 202411

**Comment by AnantKishorSharma** [comment]
> can you change this line <<As the required SW changes are not available in 202411 we should skip test_bgp_suppress_fib for 202411>> to have 202405 and not 202411 because the required changes will be available in 202411, isnt it? which is why you had put the skip for 202405 and not 202411

My bad. Corrected the PR description.

**Review by bpar9 — APPROVED** [review]
lgtm

**Comment by AnantKishorSharma** [comment]
Hi @kevinskwang, pls review this change.

**Review by wsycqyz — APPROVED** [review]
lğtm

**Pull request merged**
