### PR TITLE
Update report uploader upgrade and reboot JSON logs regex

### PR DESCRIPTION
**Pull request by dayouliu1**
### Description of PR

Summary:
Modified the regex to upload upgrade and reboot JSON logs to a more general case to better match the logs being uploaded.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Certain generated upgrade and reboot JSON logs were not being matched by the current regex.

#### How did you do it?
Modified the regex.

#### How did you verify/test it?
Tested uploads manually.

### CODE REVIEW

**Review by vaibhavhd — APPROVED** [review]

**Comment by wsycqyz** [comment]
Any previous branch needs this PR?

**Comment by dayouliu1** [comment]
202311 and 202405 should be sufficient

**Comment by dayouliu1** [comment]
@vaibhavhd can you help me merge this?

**Comment by vaibhavhd** [comment]
@StormLiangMS , @wangxin can any one of you help to merge this?

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
