### PR TITLE
Ignore other FRR error messages on 202311 branch

### PR DESCRIPTION
**Pull request by lipxu**
### Description of PR

Summary:
Fixes # (issue)
28150848

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
Test cases failed due to FRR error messages output into syslog.

#### How did you do it?

1. ignore these error messages at this moment to make nightly run stable
2. create a new task to add FRR related logs into loganalyzer system
3. Check these error messages and fix them with test case owners

This PR is for step 1, ignore the error message
task 28212392 is for step 2

#### How did you verify/test it?
Run nightly pipeline

### CODE REVIEW

**Comment by wsycqyz** [comment]
Do we need the fix in master branch?

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by lipxu** [comment]
> Do we need the fix in master branch?

thanks for reviewing the PR.
This PR is for 202311 branch only, no need for master branch.
We do not expect any error message output during the test. The ignore error message in this PR is just a workaround to make the nightly build result more stable since the error messages are the known issue and had been tracked in another ADO.
thanks

**Review by wsycqyz — APPROVED** [review]
LGTM

**Review by StormLiangMS — APPROVED** [review]

**Pull request merged**
