### PR TITLE
[Snappi] change duthost/port mapping for multidut PFC test cases.

### PR DESCRIPTION
**Pull request by sdszhang**
### Description of PR

Summary:
Fixes duthost port mapping issue in multidut PFC test cases. 
PFCWD and ECN test cases were fixed in #13541 . This PR is to finish the change for PFC test cases too.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Fixes duthost port mapping issue in multidut PFC test cases. 

#### How did you do it?
Same method as #13541

#### How did you verify/test it?
manually tested it locally.

### CODE REVIEW

**Comment by sdszhang** [comment]
@selldinesh @amitpawar12 Can you help to review this one? This is the same change as #13541.   
#13541 fixed the mapping for PFCWD and ECN test cases.
This PR is to fix the remaining part which PFC test cases.

**Comment by amitpawar12** [comment]
Reviewed. No comments.

**Comment by sdszhang** [comment]
@rraghav-cisco for review.

**Comment by sdszhang** [comment]
@rraghav-cisco Thanks for the comment. I have updated the code to avoid duplication. can you help to review it again? Thanks.

**Review by rraghav-cisco — APPROVED** [review]

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
