### PR TITLE
[cherry-pick PR8843 (master PR7953)] missing change for 202205 branch

### PR DESCRIPTION
**Pull request by ansrajpu-git**
### Description of PR

This is cherry-pick (missed change) of https://github.com/sonic-net/sonic-mgmt/pull/7953 to 202205 
Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

### CODE REVIEW

**Review by judyjoseph — APPROVED** [review]

**Comment by judyjoseph** [comment]
@wangxin could you merge this please

**Comment by wangxin** [comment]
@judyjoseph What does "cherry-pick PR8844" mean in PR title?
I noticed that there is already a PR cherry-picking 7953 to 202205 branch. The PR number is 8843.
I am confused with the purpose of this PR.

**Comment by judyjoseph** [comment]
This PR has a few fixes missed during cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/7953 into 202205 earlier via PR 8843

**Comment by judyjoseph** [comment]
@wangxin .. to give more clarity without this fix in 202205 it errors out with this 
```

Error message
NameError: global name 'rand_one_dut_hostname' is not defined

```

**Pull request merged**
