### PR TITLE
fix for test_snmp_numpsu failure

### PR DESCRIPTION
**Pull request by agadia-cisco**
### Description of PR

Summary: `test_snmp_numpsu` TC fails because of change in `stdout` output, observed in `202405` & `202311`.

Fixes # (issue)
`stdout_lines` will be use to fetch the `numpsus` value, if the `stdout_lines` is empty / the value can't be typecasted; then in all scenarios TC wouldn't break, instead it will Error out gracefully. Sample `stdout_lines` considered -
```
1. ["PSU0: Topology teardown completed successfully upon PSU removal", "2"]
2. ["2"]
3. []
```

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Observed `test_snmp_psu` failing in `202405` & `202311` images due to change in the `stdout` structure.

#### How did you do it?
Earlier `stdout` output was simply getting typecasted, instead now it will use `stdout_lines` & check its length, if it has a non-zero length, then it will pick the last element & try typecasting it; `numpsus` count if exists, will always be the last element in the output.

#### How did you verify/test it?
Run changes with `202405` & `202311` images on a `T0` setup and all of them passed.

### CODE REVIEW

**Review by bpar9 — CHANGES_REQUESTED** [review]
Can you please fill the Approach Section of the PR and how/where it was verified? rest lgtm

**Comment by agadia-cisco** [comment]
@bpar9 have updated the PR with approach section.

**Review by bpar9 — APPROVED** [review]
lgtm

**Review by wsycqyz — APPROVED** [review]
lğtm

**Comment by wsycqyz** [comment]
PR test stuck. Let me close and re-open the PR.

**Comment by agadia-cisco** [comment]
@kevinskwang @wsycqyz Could you please trigger cherry pick PR for `202311` too.

**Comment by agadia-cisco** [comment]
> @kevinskwang @wsycqyz Could you please trigger cherry pick PR for `202311` too.

@kevinskwang @wsycqyz Could you please trigger cherry pick PR for `202305` too.

**Pull request merged**
