### PR TITLE
Fixing the syntax error from pkt_gen show cpu output.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
The current code has a bug:
-------------------------------- live log call ---------------------------------
13:03:35 init.pytest_runtest_call L0040 ERROR | Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
self.ihook.pytest_pyfunc_call(pyfuncitem=self)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in call
return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 115, in _hookexec
return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 113, in _multicall
raise exception.with_traceback(exception.traceback)
File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 77, in _multicall
res = hook_impl.function(*args)
File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
result = testfunction(**testargs)
File "/var/src/sonic-mgmt_vms20-t0-7050cx3-2_646f1402735219c3e544409d/tests/test_pktgen.py", line 87, in test_pktgen
pytest_assert(cpu_before > cpu_threshold, "Cpu util was above threshold {} for atleast 1 process
TypeError: '>' not supported between instances of 'list' and 'int'

FAILED

cpu_before is a list of numbers from the output of **show cpu** command. we need to handle it accordingly.

### CODE REVIEW

**Comment by kevinskwang** [comment]
pls fix the commit message format issue

**Comment by rraghav-cisco** [comment]
> pls fix the commit message format issue

@kevinskwang : I apologize, I don't understand the comment. What issue is this?

**Comment by wsycqyz** [comment]
@rraghav-cisco There is merge conflict, please help resolve.

**Comment by rraghav-cisco** [comment]
> @rraghav-cisco There is merge conflict, please help resolve.

@wsycqyz : Fixed the conflicts. Thanks.

**Comment by wsycqyz** [comment]
@rraghav-cisco What Kevin was saying is that please make sure your PR commit message uses the template format, not current starting with "The current code has a bug......".

**Review by kevinskwang — APPROVED** [review]

**Comment by kevinskwang** [comment]
> > pls fix the commit message format issue
> 
> @kevinskwang : I apologize, I don't understand the comment. What issue is this?

pls follow this: @rraghav-cisco 
What is the motivation for this PR?
How did you do it?
How did you verify/test it?

**Comment by rraghav-cisco** [comment]
> > > pls fix the commit message format issue
> > 
> > 
> > @kevinskwang : I apologize, I don't understand the comment. What issue is this?
> 
> pls follow this: @rraghav-cisco What is the motivation for this PR? How did you do it? How did you verify/test it?

@kevinskwang : Done.

**Pull request merged**
