### PR TITLE
[Snappi] Infra changes to make snappi multidut work for T0/T1 testbed

### PR DESCRIPTION
**Pull request by sdszhang**
### Description of PR

Summary:
Infra change for #14144 #14220
This change is to add initial infra changes for current tests/snappi_tests/multidut test cases to be able to run on T0/T1 testbed.

Main changes are the following:
1. `get_snappi_ports_single_dut`:  generate port lists for T0/T1 testbed without the need to add port definition in variables.py.
2. `get_snappi_ports`: unified function to return snappi port lists for both T0/T1 and T2 testbed.
3. Add vlan and port-channel support into `snappi_dut_base_config`: make it consistent for T0/T1 testbed.
4. sample change in two test case `test_multidut_global_pause_with_snappi.py` and `test_multidut_pfc_pause_lossless_with_snappi.py`

After this change, following function can work for both T0/T1 and T2, and test case can adopt the same method to support T0/T1.
1. `get_snappi_ports`
2. `cleanup_config`
3. `snappi_dut_base_config`
4. existing helper files are unchanged.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
support T0/T1 testbed for T2.

#### How did you do it?
use `get_snappi_ports` for both T0/T1 testbed and T2 testbed. For T0/T1 testbed, return all the available ports, for T2 testbed, return the ports defined in MULTIDUT_PORT_INFO.

#### How did you verify/test it?
Tested in local T0/T1 testbed.

```
snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py::test_global_pause[multidut_port_info0] PASSED                                                                   [100%]
```
```
snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py::test_pfc_pause_single_lossless_prio[xxx|3-multidut_port_info0]  PASSED                                                                   [ 50%]
snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py::test_pfc_pause_single_lossless_prio[xxx|4-multidut_port_info0] PASSED [100%]

```

### CODE REVIEW

**Comment by sdszhang** [comment]
@selldinesh @amitpawar12 @developfast can you help to review this change? Thanks.

**Comment by amitpawar12** [comment]
@sdszhang  - Existing helper files might also need change to remove/modify to enable/disable credit-watchdog.

**Comment by sdszhang** [comment]
> @sdszhang - Existing helper files might also need change to remove/modify to enable/disable credit-watchdog.
@amitpawar12  can you open a github issue to track this. Thanks.

**Comment by sdszhang** [comment]
Discussed in the community meeting, no further comments on this one. Okay to merge.

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
