### PR TITLE
Generalizing GCU test suite to verify both ip types (IPV4, IPV6) for BGP Neighbors

### PR DESCRIPTION
**Pull request by okaravasi**
Currently, under generic config update there is a test suite verifying only IPV6 BGP Neighbors' changes. This PR extends the existing test suite and adds support for verifying IPV4 BGP NEighbors also. This is achieved by generalizing the test code with adding dynamic variable for neighbor ip type and with test mark parameters. Also, renamed the test suite to a generic name.

### Description of PR

Summary:
This is an improvement on existing test suite generic_config_updater/test_ipv6.py
Currently, under generic config update there is a test suite verifying only IPV6 BGP Neighbors' changes. This PR extends the existing test suite and adds support for verifying IPV4 BGP NEighbors also. This is achieved by generalizing the test code with adding dynamic variable for neighbor ip type and with test mark parameters. Also, renamed the test suite to a generic name.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Currently, there are no test cases for IPv4 BGP Neighbors in the verification of generic config updates functionality. This PR extends the existing test suite, which verifies IPv6 BGP Peers, to add support for IPv4 BGP Neighbors verification.

#### How did you do it?
Added argument for ip_version in test functions to dynamically verify the relevant peer IP type.
Added test mark parameters to run the same test case for both IP types.
Renamed the test suite to a generic name that reflects new test cases content.

#### How did you verify/test it?
Ran the newly created test suite and verified that the test cases pass for both IP types.

image

#### Any platform specific information?
N/A

#### Supported testbed topology if it's a new test case?
N/A

### CODE REVIEW

**Comment by okaravasi** [comment]
Hello @judyjoseph @arlakshm , Could you please help on reviewing this?
Thank you.

**Comment by judyjoseph** [comment]
LGTM, @okaravasi  could you resolve the conflicts. Also do add a snapshot of the test run for ipv4 and ipv6 under the section "How did you verify/test it?"

**Review by judyjoseph — APPROVED** [review]

**Comment by judyjoseph** [comment]
@okaravasi Arvind had a comment earlier -- that we need to add support for multi-asic as well. Do you plan to do it in this PR ?

**Comment by okaravasi** [comment]
> ad a comment earlier -- that we need to add support for multi-asic as well. Do you plan to do it in this PR ?

@judyjoseph Support to multi-asic will be handled by different PRs. 
1) Adding support to existing test scope shall  be handled via :  https://github.com/sonic-net/sonic-mgmt/pull/14070
2) Adding new test for t2/chassis GCU shall be handled via separate ticket: https://github.com/sonic-net/sonic-mgmt/pull/14887. I will comment soon when it  is opened as non-draft.

**Comment by bingwang-ms** [comment]
@wen587 Can you please check if this change is required for 202405?

**Comment by wen587** [comment]
> @wen587 Can you please check if this change is required for 202405?

Hi @bingwang-ms , this is an improvement from ipv6 only test to ipv4+ipv6 test. It is good to have in 202405 but not bug fix related.

**Pull request merged**
