### PR TITLE
Enable designating build id of KVM image

### PR DESCRIPTION
**Pull request by yejianquan**
### Description of PR

Summary:
Enable designating build id of KVM image to avoid image issue keep affecting sonic-mgmt repo pull requests.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Enable designating build id of KVM image to avoid image issue keep affecting sonic-mgmt repo pull requests.
#### How did you do it?
Enable designating build id of KVM image to avoid image issue keep affecting sonic-mgmt repo pull requests.
#### How did you verify/test it?
Pipeline tests it.

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Comment by Blueve** [comment]
Since this is not related to any testcases and it is fixing the test failures itself, can we force merge it?

**Comment by yejianquan** [comment]
> Since this is not related to any testcases and it is fixing the test failures itself, can we force merge it?

Likely the dhcp test in t0_2vlan keeps failing, not sure whether it's because I pick the kvm image that too old, checking

**Review by wangxin — APPROVED** [review]

**Pull request merged**
