### PR TITLE
Backported test case test_sai_sdk_dump from master branch to 202205

### PR DESCRIPTION
**Pull request by ppikh**
### Description of PR
Backported test case test_sai_sdk_dump from master branch to 202205
It's backport of PRs to branch 202205:
https://github.com/sonic-net/sonic-mgmt/pull/7365
https://github.com/sonic-net/sonic-mgmt/pull/7465

Summary: Backported test case test_sai_sdk_dump from master branch to 202205
Fixes # (issue)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Backported test case test_sai_sdk_dump from master branch to 202205

#### How did you do it?
Backported test case test_sai_sdk_dump from master branch to 202205

#### How did you verify/test it?
Executed test

#### Any platform specific information?
Mellanox/Nvidia

### CODE REVIEW

**Comment by ppikh** [comment]
@yxieca, @liat-grozovik can you please merge this PR?

**Comment by ppikh** [comment]
@yxieca can you please merge this changes?

**Review by nhe-NV — APPROVED** [review]

**Comment by ppikh** [comment]
Can anyone merge this change?

**Comment by liat-grozovik** [comment]
@ppikh why having 2 PRs backport in one PR against 202205?
can you please have backport per PR? they also seems to me 2 different things.

**Comment by ppikh** [comment]
Will do 2 separate PRs for each commit.

**Pull request closed without merging**
