### PR TITLE
[QoS]qos_yaml j2C+ changes for new _vsq thresholds

### PR DESCRIPTION
**Pull request by ansrajpu-git**
### Description of PR

Updated qos test params for 400g and 100g port speeds for the new vsq threshold introduced in   PR #https://github.com/sonic-net/sonic-buildimage/pull/18239
Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
The new   MMU settings to enhance performance for RDMA traffic in production.
Hence the qos_params needs to be tweaked according to the set buffer profiles.

However, the existing sonic-mgmt LossyQueueTest  doesn't fairly verify the buffer threshold for headroom for Lossy traffic. As per the new vsq profile setting the XOFF FADT threshold/PG is way lesser than the Nominal headroom, which limits it to not utilize the headroom buffer completely and send pause frames before reaching the MAX headroom limit.
Either the test case needs to be improvised by adding more source ports or a new test case should be added to verify the Lossy queue traffic at PG level 
#### How did you verify/test it?
Executed the qos test cases   and verify the results

### CODE REVIEW

**Comment by wsycqyz** [comment]
I can see you request for 202205 branch. How about 202311 branch?

**Comment by ansrajpu-git** [comment]
@vmittal-msft , could you please review and comment on above request.

**Comment by vmittal-msft** [comment]
@ansrajpu-git Can you please confirm if this PR has all the latest changes ?

**Comment by ansrajpu-git** [comment]
> @ansrajpu-git Can you please confirm if this PR has all the latest changes?

@vmittal-msft, the latest changes on PR #18239 are tested with ' libsaibcm_7.1.78.4_amd64.deb' for 202205 branch, for which the PR raised #13319. Kindly confirm for master which version should be used.
This PR (for master) is based on the previous commit of PR #18239+ BRCM SAI ver: [10.1.21.0]

**Comment by arlakshm** [comment]
@ansrajpu-git to update the PR with the new values to match the values in 202205.

**Comment by ansrajpu-git** [comment]
@vmittal-msft , updated the qos_params aligning with 202205. Please review.  Also closing the PR #https://github.com/sonic-net/sonic-mgmt/pull/13319 raised separately for 202205 to keep changes at one place.

**Review by kenneth-arista — APPROVED** [review]
Looks okay to me

**Review by vmittal-msft — APPROVED** [review]

**Comment by ansrajpu-git** [comment]
@vmittal-msft , Updated this PR with the latest buffer profile changes #[19653] (https://github.com/sonic-net/sonic-buildimage/pull/19653).

**Comment by vmittal-msft** [comment]
@yxieca @wangxin please help merge this.

**Comment by rlhui** [comment]
@vmittal-msft , @ansrajpu-git , I'm removing the request cherry label as there's separate PR merged to 202405 already. Please review/clarify if any. thanks.

**Pull request merged**
