### PR TITLE
Add `platform_tests/sfp/test_show_intf_xcvr.py` into T0 PR checker.

### PR DESCRIPTION
**Pull request by yutongzhang-microsoft**
### Description of PR

In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/sfp/test_show_intf_xcvr.py` and let it run successfully in T0 PR checker. 

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
In PR [#13220](https://github.com/sonic-net/sonic-mgmt/pull/13220), we add a batch of control plane test scripts into onboarding T0 PR checker, but some of them failed. In this PR, we fix the failed test script `platform_tests/sfp/test_show_intf_xcvr.py` and let it run successfully in T0 PR checker. 

#### How did you verify/test it?
```
------------------------------------------------------------------ live log sessionfinish ------------------------------------------------------------------
08:22:25 __init__.pytest_terminal_summary         L0067 INFO   | Can not get Allure report URL. Please check logs
============================================================== 3 passed, 1 warning in 26.13s ===============================================================
```

### CODE REVIEW

**Review by opcoder0 — APPROVED** [review]
LGTM.

**Comment by wsycqyz** [comment]
Have triggered to rerun failed jobs.

**Review by wangxin — APPROVED** [review]

**Comment by weiguo-nvidia** [comment]
Hi @yutongzhang-microsoft @wangxin ,

Is there any plan to merge this PR to 202405 branch?

**Comment by yutongzhang-microsoft** [comment]
> Hi @yutongzhang-microsoft @wangxin ,
> 
> Is there any plan to merge this PR to 202405 branch?

This change is aimed at adding this case into PR checker. So we don't have to merge it into 202405 temporarily

**Pull request merged**
