### PR TITLE
Use list to fix wrong population type error

### PR DESCRIPTION
**Pull request by Gfrom2016**
### Description of PR

Summary:
Fixes # (issue)
Testcase test_memory_exhaustion failed on dualtor due to:
```
        if isinstance(population, _Set):
            population = tuple(population)
        if not isinstance(population, _Sequence):
>           raise TypeError("Population must be a sequence or set.  For dicts, use list(d).")
E           TypeError: Population must be a sequence or set.  For dicts, use list(d).
```

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Fix the testcase issue on dualtor when it need to select one host to run test.
#### How did you do it?
Pass list type parameters in random.sample().
#### How did you verify/test it?
Run test case locally with the change and it passed.

### CODE REVIEW

**Comment by Gfrom2016** [comment]
@wenyiz2021 Please help review this PR. I was wondering why this case only failed on the master/internal and succeeded on 202205, even though they both use random.sample() to select a dut host.

**Review by wenyiz2021 — APPROVED** [review]

**Comment by wenyiz2021** [comment]
@Gfrom2016 I have approved your change.
1. why it fail in master but pass on 202205?
Answer: we mostly use 202205 to test chassis, so it'll early return and will not call radom.sample
2. the other question I had was: this function is similar to `def generate_params_supervisor_hostname` in conftest.py, why it fail?
Answer:  `def generate_params_supervisor_hostname` uses `duts = get_specified_duts(request)` which returns a list, while this function `get_sup_node_or_random_node` uses fixture `duthosts` while it is encapsulated `DutHosts` object:  https://github.com/sonic-net/sonic-mgmt/blob/8918907eb5a29aaf2b494617c9d672282cefbea3/tests/conftest.py#L300

**Comment by wenyiz2021** [comment]
another pointer is for  single-duts `duthosts[0]` will also work even it is DutHosts object.

**Comment by wenyiz2021** [comment]
@Gfrom2016 could you raise separate PR to 202205 branch?

**Pull request merged**
