### PR TITLE
Verify no tx_drop counter increment on egress DUT port in oper down state

### PR DESCRIPTION
**Pull request by sreejithsreekumaran**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?

Egress DUT port in oper down state shouldn't increase the tx drop counter of the egress port.

#### How did you do it?

Used Ixia snappi framework to inject traffic and verify the data path.
Bring down the Ixia port to get the egress DUT port to go to Oper down state.
Check for no tx_drop counter increment after 90 seconds.

#### How did you verify/test it?

On a Ixia connected DUT

### CODE REVIEW

**Review by alpeshspatel — APPROVED** [review]

**Comment by alpeshspatel** [comment]
FYI: @kevinwangsk @wsycqyz for the test

**Review by bpar9 — DISMISSED** [review]
lgtm

**Comment by kevinskwang** [comment]
@sreejithsreekumaran  @alpeshspatel  can we address this without ixia?

**Comment by alpeshspatel** [comment]
> @sreejithsreekumaran @alpeshspatel can we address this without ixia?

@kevinskwang  we will need a separate PR for that. We can track it separately.

**Review by kevinskwang — APPROVED** [review]
LGTM

**Comment by alpeshspatel** [comment]
@kevinskwang  Need 202411 label as well.

**Pull request merged**
