### PR TITLE
[sonic-mgmt] Fix "enum_dut_lossy_prio_with_completeness_level" collection failure

### PR DESCRIPTION
**Pull request by vkjammala-arista**
### Description of PR

Summary: Fix "enum_dut_lossy_prio_with_completeness_level" fixture collection failure
Fixes # https://github.com/aristanetworks/sonic-qual.msft/issues/324

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?

https://github.com/sonic-net/sonic-mgmt/pull/15057/ has introduced logic to select dut queue priority list based on the completeness_level. If completeness_level is "debug", we are selecting one queue priority randomly from the dut priority list which can be empty also, and this is causing `ValueError: Sample larger than population or is negative`.

(Reason for dut priority list can be empty: In `tests/pretest.py` we have `collect_dut_all_prio` method which is generating `tests/priority/<testbed>-all.json` see https://github.com/sonic-net/sonic-mgmt/blob/202405/tests/test_pretest.py#L220, where we are not populating dut priority list if there are multiple `DSCP_TO_TC_MAP`s, a bug?)

#### How did you do it?
Enhancing condition to randomly select a value from dut priority collection only if it's non-empty.

#### How did you verify/test it?
Ran the test and verified it's not complaining about `ValueError` with the fix.

### CODE REVIEW

**Comment by vkjammala-arista** [comment]
@sdszhang @yejianquan please review

**Review by lolyu — APPROVED** [review]

**Review by sdszhang — APPROVED** [review]
LGTM

**Comment by sdszhang** [comment]
What's the scenario for multiple `DSCP_TO_TC_MAP` in config_db.json?

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
> What's the scenario for multiple `DSCP_TO_TC_MAP` in config_db.json?

There can be multiple `DSCP_TO_TC_MAP` in dualtor and T1-in-dualtor scenario

**Pull request merged**
