### PR TITLE
Add IPV6 default route test

### PR DESCRIPTION
**Pull request by liuh-80**
Add IPV6 default route test.

### Description of PR
Add IPV6 default route test.

##### Work item tracking
- Microsoft ADO: 25798732

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Add IPV6 default route test.

#### How did you do it?
Add IPV6 default route test.

#### How did you verify/test it?
Pass all UT

### CODE REVIEW

**Comment by liuh-80** [comment]
This PR depends on this PR merge first:
https://github.com/sonic-net/sonic-buildimage/pull/17281

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
