### PR TITLE
BFD test fixes and improvements

### PR DESCRIPTION
**Pull request by ihorchekh**
### Description of PR

Summary: Improved BFD test. Fixed test issues.
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012

#### What is the motivation for this PR?
To improve the test

#### How did you verify/test it?
Ran on 202012 and 202205 images

#### Supported testbed topology if it's a new test case?
't1', 't1-lag', 't1-64-lag'

### CODE REVIEW

**Comment by prsunny** [comment]
@siqbal1986  to review

**Comment by liat-grozovik** [comment]
@siqbal1986 kindly reminder to review.

**Review by siqbal1986 — APPROVED** [review]
looks good

**Pull request merged**
