### PR TITLE
[CRM] Implemented DASH CRM test case

### PR DESCRIPTION
**Pull request by ppikh**
Summary: Add new test to cover CRM DASH (for DPU only)
Fixes # (issue)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Add DASH CRM coverage

#### How did you do it?
Implement new dash CRM test cases based on test plan https://github.com/sonic-net/sonic-mgmt/pull/7796

#### How did you verify/test it?
Executed regular CRM test and new tests on DASH/DPU devices

#### Any platform specific information?
DASH/DPU

#### Supported testbed topology if it's a new test case?
Appliance

### Documentation
Test plan https://github.com/sonic-net/sonic-mgmt/pull/7796

### CODE REVIEW

**Comment by ppikh** [comment]
@prsunny , @yxieca can you please merge this PR?

**Review by AntonHryshchuk — APPROVED** [review]

**Comment by oleksandrivantsiv** [comment]
@prsunny kindly reminder to review the PR.

**Review by prsunny — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@ppikh please solve conflicts and ensure the test can run only on DPU and ignored by switch

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
