### PR TITLE
Enhance pfc_gen script to support multi-processing

### PR DESCRIPTION
**Pull request by bingwang-ms**
### Description of PR

Summary:
This PR is to enhance pfc_gen script to support multi-processing to generate more PFC pause frames.
The current pfc_gen script is single thread. We saw some PFCWD test is flay because it can't generate enough PFC pause frames to trigger PFC srorm on DUT.

This PR enhanced the script to support multi-processing to reduce flakiness in test. 
Change list
1. Enhance pfc_gen.py to support multi-processing
2. Update [pfc_storm_stop_eos.j2](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:pfc_gen_mp?expand=1#diff-454591a1010b66cbe0da38fa9cf1d25bb084e9445802d74ec6cc6035f17c5e2f) to support the multi-processing script (remove sudo in the command pattern as subprocess doesn't have sudo)
3. Send more back ground traffic.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
This PR is to enhance pfc_gen script to support multi-processing to generate more PFC pause frames.

#### How did you do it?
1. Enhance pfc_gen.py to support multi-processing
2. Update [pfc_storm_stop_eos.j2](https://github.com/sonic-net/sonic-mgmt/compare/master...bingwang-ms:pfc_gen_mp?expand=1#diff-454591a1010b66cbe0da38fa9cf1d25bb084e9445802d74ec6cc6035f17c5e2f) to support the multi-processing script (remove sudo in the command pattern as subprocess doesn't have sudo)
3. Send more back ground traffic.

#### How did you verify/test it?
The change is verified on a Physical testbed.
```
collected 1 item                                                                                                                                                                                      

pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_port_toggle[str-msn2700-22]  ^H ^HPASSED                                                                                                      [100%]
```

#### Any platform specific information?
No.

#### Supported testbed topology if it's a new test case?
Not a new test case.

### CODE REVIEW

**Review by nhe-NV — COMMENTED** [review]
As I know this pfc_gen.py file is also used by the tests/qos/test_pfc_counters.py, did you test and make sure the change will not affect the pfc counter test?

**Comment by bingwang-ms** [comment]
> qos/test_pfc_counters.py

Good point! Let me run some test to confirm. Thanks

**Comment by wsycqyz** [comment]
Let me try on Cisco testbed and reply later.

**Comment by bingwang-ms** [comment]
> Let me try on Cisco testbed and reply later.

Thanks!

**Comment by bingwang-ms** [comment]
@wsycqyz Are we good to merge this PR?

**Comment by wsycqyz** [comment]
> pfcwd/test_pfcwd_function.py::TestPfcwdFunc::test_pfcwd_port_toggle

Good to merge. No issue is found during test with Cisco platform.

**Review by wsycqyz — APPROVED** [review]
lğtm

**Pull request merged**
