### PR TITLE
Loganalyzer regex correction for test_po_update

### PR DESCRIPTION
**Pull request by sanjair-git**
### Description of PR

Summary:
Fixes # (issue)

- For PC tests '_test_po_update.py_', seen the following LogAnalyzer mismatch related messages being reported as errors.
- Issues seen in PC tests running on chassis with topo t2 multi-asic.
`
E               Match Messages:
E               Nov 11 20:41:16.136440 ixre-egl-board3 ERR syncd0#syncd: :- process_on_fdb_event: invalid OIDs in fdb notifications, NOT translating and NOT storing in ASIC DB
E               
E               Nov 11 20:41:16.136471 ixre-egl-board3 ERR syncd0#syncd: :- process_on_fdb_event: FDB notification was not sent since it contain invalid OIDs, bug?
`

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### What is the motivation for this PR?

-  Loganalyzer mismatch errors seen during PC test suites for test_po_update.py tests w.r.t syncd container messages per asic as shown above.

#### How did you do it?

-  Fix the existing regex to support syncd container syslog messages per asic.

#### How did you verify/test it?

- Ran the PC test cases against a multi-asic line card in a T2 chassis.

### Documentation

image

### CODE REVIEW

**Comment by judyjoseph** [comment]
@sanjair-git We have a brodcom CSP opened to fix this ? Do we really need this to be added here

**Comment by sanjair-git** [comment]
> @sanjair-git We have a brodcom CSP opened to fix this ? Do we really need this to be added here

Hi @judyjoseph , Looks like Broadcom already pushed the fix to DMZ and it will be available in the next SAI. If you are planning to take next SAI soon, we can ignore this PR.

Otherwise, we can keep this PR till we take the next SAI.

**Review by SuvarnaMeenakshi — APPROVED** [review]
lgtm, @judyjoseph  please approve if this is ok to be merged.

**Review by judyjoseph — APPROVED** [review]

**Pull request merged**
