### PR TITLE
Update watchdog.yml

### PR DESCRIPTION
**Pull request by gollarharsha**
### Description of PR
Adding watchdog timeout values for Cisco Churchil Mono Platform.
**Dependencies**: tests/platform_tests/api/test_watchdog.py

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205

#### What is the motivation for this PR?
Adding watchdog timeout values for Cisco Churchil Mono Platform.

#### How did you verify/test it?
Verified this on Cisco Churchil Mono platform (T1 profile)

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@kevinskwang , pls look into this change.

**Review by kevinskwang — DISMISSED** [review]

**Comment by kevinskwang** [comment]
@rraghav-cisco please rebase and resolve the conflicts.

**Comment by rraghav-cisco** [comment]
@gollarharsha , pls rebase and resolve conflicts.

**Comment by gollarharsha** [comment]
@kevinskwang - I have resolved conflicts. Can you pls check if it looks good?

**Review by kevinskwang — APPROVED** [review]

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
