### PR TITLE
Enhancement of test_sensors.py to address several issues

### PR DESCRIPTION
**Pull request by mhen1**
### Description of PR

Summary:
Fixes # (issue)
Enhancement of test_sensors.py to address several issues:
1. Updated PSU mapping of msn4600-r0 platform.
2. Updated test to support both Forward (PSF) and Reversed (PSR) versions of each PSU Model.
3. Added support to PSU Model MTEF-AC-G.
### Type of change

- [ ] Bug fix
- [] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Address several issues with the sensor test case.
#### How did you do it?
Updated the Dynamic PSU mapping process to address the issues.
#### How did you verify/test it?
Run test_sensors.py on several Systems (each of the PSU Models listed in psu_data.yaml).

### CODE REVIEW

**Comment by wsycqyz** [comment]
Do we need this PR in 202311 or 202405 branch?

**Comment by mhen1** [comment]
Hey,
The PR is needed in 202311/202405, but please wait with merging it as the issues mentioned might not be resolved yet, I’ll let you know once they are.
Thanks,
Mor Hen

**Comment by bingwang-ms** [comment]
I confirmed this PR will fix the test_sensor failure on SN4600. But the failure on SN2700A1 is not fixed. Need some update.

**Comment by mhen1** [comment]
> I confirmed this PR will fix the test_sensor failure on SN4600. But the failure on SN2700A1 is not fixed. Need some update.

Hey, I believe the following PR to sonic-buildimage should resolve the issue - https://github.com/sonic-net/sonic-buildimage/pull/19515
Please verify it does and if so, This PR is ready from my part (and needs to be backported to 202311/202405 as well).

**Comment by bingwang-ms** [comment]
LGTM.

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
