### PR TITLE
Skip CRC algorithm test on INNER_IP_PROTOCOL field

### PR DESCRIPTION
**Pull request by echuawu**
### Description of PR
Skip CRC algorithm test on INNER_IP_PROTOCOL field
Skip the test combination due to hw limitation

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
HW limitation
#### How did you do it?
Skip specific cases
#### How did you verify/test it?
Run the script in internal regression
#### Any platform specific information?
No

### CODE REVIEW

**Review by nhe-NV — APPROVED** [review]

**Comment by echuawu** [comment]
Hi @wangxin , could you help check the pre checker failure? The skip shall not lead to the failure.

**Comment by bingwang-ms** [comment]
@prsunny , @siqbal1986 Can you please help review?

**Comment by prsunny** [comment]
Is it applicable to all spectrum platforms or specific variants?

**Comment by echuawu** [comment]
> Is it applicable to all spectrum platforms or specific variants?

All spectrum platforms.

**Review by prsunny — APPROVED** [review]

**Comment by echuawu** [comment]
> @echuawu PR conflicts with 202405 branch

Handled in PR - https://github.com/sonic-net/sonic-mgmt/pull/14941

**Pull request merged**
