### PR TITLE
added testplan for syslog protocol, filter, trap severity level

### PR DESCRIPTION
**Pull request by SvyatDemn**
### Description of PR
- Adding a new test plan and test for syslog protocol, filter, trap severity level

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
Adding a new test plan document and tests.

#### How did you do it?
Created an MD file with the test plan information.

#### How did you verify/test it?
N/A

#### Any platform specific information?
N/A

#### Supported testbed topology if it's a new test case?
N/A

### Documentation
N/A

### CODE REVIEW

**Comment by yxieca** [comment]
@SvyatDemn please sign the EasyCLA.

**Comment by SvyatDemn** [comment]
> @SvyatDemn please sign the EasyCLA.

Hi, did it many times, doesn't work for me, created a ticket for that
https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-25419

**Comment by SvyatDemn** [comment]
> @SvyatDemn please sign the EasyCLA.

Done with Easy CLA, please review

**Review by qiluo-msft — APPROVED** [review]

**Comment by JibinBao** [comment]
Hi @SvyatDemn , does the branch 202311 support the test?

**Pull request merged**
