### PR TITLE
Make oscillation fix persistent across reboots and config reload

### PR DESCRIPTION
**Pull request by vivekverma-arista**
### Description of PR

Summary: Make oscillation fix persistent across reboots.
Fixes [#226](https://github.com/aristanetworks/sonic-qual.msft/issues/226)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
https://github.com/sonic-net/sonic-mgmt/pull/13004, introduces a fix to disable oscillations at the session level for dualtor.

The fix however is not persistent across reboots and config reload.

During the sanity checks that run in the beginning of the tests, https://github.com/sonic-net/sonic-mgmt/blob/master/tests/conftest.py#L77, if it is found that any interfaces or BGP sessions is/are down (which could be due to a test that run before the current test and contaminated the testbed), a config_reload and then further a reboot is issued, which clears off this config to disable oscillation, resulting in a flakiness when the test runs or a sanity check failure again.

#### How did you do it?
The proposed fix is to do a config save -y of this config so as to make it persistent across reboots and config reload.

#### How did you verify/test it?
Ran the tests that were flaky due to oscillations.
a) `acl/test_acl.py`
b) `drop_packets/drop_packets.py`
c) `fib/test_fib.py`

### CODE REVIEW

**Review by lolyu — COMMENTED** [review]
can we also put this into the golden config?
I believe most of the config reloads are using the golden config.

**Comment by zjswhhh** [comment]
> can we also put this into the golden config? I believe most of the config reloads are using the golden config.c

**Comment by zjswhhh** [comment]
Hi @vivekverma-arista - sorry I mis-clicked and closed the PR.

**Comment by zjswhhh** [comment]
> can we also put this into the golden config? I believe most of the config reloads are using the golden config.

Why do we need golden config? `config save` should be enough in this case?

**Comment by lolyu** [comment]
> > can we also put this into the golden config? I believe most of the config reloads are using the golden config.
> 
> Why do we need golden config? `config save` should be enough in this case?

Most of the config reloads now are using the golden config.

**Comment by StormLiangMS** [comment]
hi @zjswhhh  @lolyu any concern to approve?

**Review by lolyu — APPROVED** [review]

**Comment by lolyu** [comment]
@StormLiangMS, approved, please help merge, thanks!

**Pull request merged**
