### PR TITLE
[SNMP E2E Testing]  Select the right PDU controller in Dual-TOR testbed

### PR DESCRIPTION
**Pull request by isabelmsft**
### Description of PR

ADO 25860723

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### What is the motivation for this PR?
In Dual-TOR testbed, the test test_turn_off_psu_and_check_psu_info()

Randomly selects a DUT
Randomly selects the PDU controller for one of the DUT
The PDU controller selected at Step2 may not match with the DUT randomly selected at Step1.
This can result in the test case failing intermittently on multiple runs.
#### How did you do it?
Explicitly select the PDU controller for the randomly selected DUT in dual-TOR testbed

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by wenyiz2021** [comment]
seems https://github.com/sonic-net/sonic-mgmt/pull/11145 was merged yesterday for the same fix, we just need to port that PR to needed branches?

**Comment by isabelmsft** [comment]
> seems #11145 was merged yesterday for the same fix, we just need to port that PR to needed branches?

PR #11145 fixes a different file with the same issue

**Review by wenyiz2021 — APPROVED** [review]
LGTM

**Pull request merged**
