### PR TITLE
Fix QoS test failure: brcm_sai_set_switch_attribute/updating switch mac addr failed

### PR DESCRIPTION
**Pull request by wsycqyz**
### Description of PR

Summary:
Fix test failure in qos/test_qos_sai.py
SAI_API_SWITCH:brcm_sai_set_switch_attribute:3852 updating switch mac addr failed with error -2

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012
- [x] 202205

#### What is the motivation for this PR?
During test_qos_sai.py, following error is seen:
Apr 21 11:15:31.453298 str2-7260cx3-acs-11 ERR syncd#syncd: message repeated 3 times: [ [none] SAI_API_SWITCH:brcm_sai_set_switch_attribute:3852 updating switch mac addr failed with error -2.]

#### How did you do it?
Remove old brcm_sai_set_switch_attribute code.

#### How did you verify/test it?
Manually run test case: qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit

### CODE REVIEW

**Review by XuChen-MSFT — DISMISSED** [review]

**Review by XuChen-MSFT — APPROVED** [review]

**Comment by wsycqyz** [comment]
@wangxin Will do

**Comment by wsycqyz** [comment]
#8250 and #8251 cherry pick this PR to 202205 and 202012

**Comment by wangxin** [comment]
Thanks @wsycqyz !

**Pull request merged**
