### PR TITLE
Test plan for feature Generic Hash

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
Test plan for the new feature Generic Hash.
The HLD of Generic Hash: https://github.com/sonic-net/SONiC/pull/1101
The test implementation is not included in this PR, will open another PR. 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305

#### What is the motivation for this PR?
Adding the test plan for the new feature Generic Hash.
#### How did you verify/test it?
The test plan has already been reviewed internally.

### CODE REVIEW

**Comment by wangxin** [comment]
The [pre-commit](http://pre-commit.com/) check detected issues in the files touched by this pull request.
The detected issues may be old or new. For new issues, please try to fix them.

For old issues, it is not mandatory to fix them because they were not caused by this change. It is unfair to blame
author of this pull request. But if you can take extra effort to fix the old issues as well, that would be great!

Detailed pre-commit check results:
<samp>trim trailing whitespace.................................................Failed<br/>- hook id: trailing-whitespace<br/>- exit code: 1<br/>- files were modified by this hook<br/><br/>Fixing docs/testplan/Generic-Hash-test-plan.md<br/><br/>fix end of files.........................................................Passed<br/>check yaml...........................................(no files to check)Skipped<br/>check for added large files..............................................Passed<br/>check python ast.....................................(no files to check)Skipped<br/>flake8...............................................(no files to check)Skipped<br/></samp>

To run the pre-commit checks locally, you can follow below steps:
1. Ensure that default python is python3. In sonic-mgmt docker container, default python is python2. You can run
   the check by activating the python3 virtual environment in sonic-mgmt docker container or outside of sonic-mgmt
   docker container.
2. Ensure that the `pre-commit` package is installed:
```
sudo pip install pre-commit
```
3. Go to repository root folder
4. Install the pre-commit hooks:
```
pre-commit install
```
5. Use pre-commit to check staged file:
```
pre-commit
```
6. Alternatively, you can check committed files using:
```
pre-commit run --from-ref <commit_id> --to-ref <commit_id>
```

**Comment by liat-grozovik** [comment]
@yxieca could you please help to review or assign?

**Comment by yxieca** [comment]
@congh-nvidia can you present this test plan in test subgroup meeting?

**Comment by congh-nvidia** [comment]
> 
Hi @yxieca, could you send me the time of the next test subgroup meeting?

**Comment by congh-nvidia** [comment]
I will update the test plan for the review comments in the Aug 16th sonic-test-workgroup meeting.

**Comment by liat-grozovik** [comment]
@nazariig please review

**Review by roy-sror — APPROVED** [review]

**Comment by congh-nvidia** [comment]
The test plan is updated according to the comments in the Aug 16th review meeting:
1. Removed the "doesn't support dualtor" expression.
2. Added clear steps for the lag hash cases when the tested hash field is DST_MAC, ETHERTYPE or VLAN_ID.
3. Added a new test case the cover the lag member remove/add scenario.
4. Removed the test case "test_invalid_hash_fields" for it has been covered in the sonic-utilities UT. (https://github.com/sonic-net/sonic-utilities/blob/c7c4831baf2f60c7f63166244eb07c6ab7fe8b8a/tests/hash_test.py)

**Comment by congh-nvidia** [comment]
Hi @yxieca, the pre-commit keeps complaining about the trailing whitespace, but I can't find where it is. Is it auto-fixed by the pre-commit? How can I make the checker pass?
Thanks!

**Comment by congh-nvidia** [comment]
> @nazariig please review

@nazariig Please review and approve the test plan, it is updated after the review meeting. Thanks.

**Comment by yxieca** [comment]
> Hi @yxieca, the pre-commit keeps complaining about the trailing whitespace, but I can't find where it is. Is it auto-fixed by the pre-commit? How can I make the checker pass? Thanks!

@congh-nvidia this is a standalone file, have you search for " $" or "\t$" with vim? Or similar use similar method with other editors?

**Review by nazariig — APPROVED** [review]

**Comment by liat-grozovik** [comment]
As no feedback for sonic test group community and feature owner has approved, moving a head with merging the test plan.

**Pull request merged**
