### PR TITLE
[advanced-reboot] IO path verification fixes for dualtor

### PR DESCRIPTION
**Pull request by vaibhavhd**
### Description of PR

Summary: Update checks for vlan and dut MAC in the bidirectional IO.
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Three improvements:
1. Present test_advanced_reboot crashes in `examine_flow`. This is due to packets are incorrectly matched in the code.
2. Additionally, added icmp_responder in the test, so that mux state is healthy during the duration of test.
3. Change mux config on both TORs to manual during the duration of test.

Fixes:
1. Identifying received packet in dualtor case --  `t1->server` rcvd pkt will have src MAC as vlan_mac, and `server->t1` rcvd pkt will have src MAC as dut_mac
2. Identifying sent packet --  `t1->server` sent pkt will have dst MAC as dut_mac, and `server->t1` sent pkt will have dst MAC as vlan_mac

#### How did you do it?

Added checks for vlan_mac
execute `config mux mode manuall all` during test, and revert to `auto` after the test.

#### How did you verify/test it?
Tested on physical testbed. The test does not crash anymore.
However, there are still some packet drops which points towards an image issue.

```
2022-12-01 23:32:22 : **************** Packet received summary: ********************
2022-12-01 23:32:22 : *********** Sent packets captured - 45000
2022-12-01 23:32:22 : *********** received packets captured - t1-to-vlan - 35919
2022-12-01 23:32:22 : *********** received packets captured - vlan-to-t1 - 8284
2022-12-01 23:32:22 : *********** Missed received packets - t1-to-vlan - 81
2022-12-01 23:32:22 : *********** Missed received packets - vlan-to-t1 - 716
2022-12-01 23:32:22 : **************************************************************
2022-12-01 23:32:22 : Disruptions happen between 0:00:08.393471 and 0:03:51.360718 after the reboot.
2022-12-01 23:32:22 : Total incoming packets captured 44203

2022-12-01 23:33:21 : The longest disruption lasted 0.045 seconds. 8 packet(s) lost.
2022-12-01 23:33:21 : Total disruptions count is 756. All disruptions lasted 4.434 seconds. Total 797 packet(s) lost

2022-12-01 23:33:37 : --------------------------------------------------
2022-12-01 23:33:37 : Fails:
2022-12-01 23:33:37 : --------------------------------------------------
2022-12-01 23:33:37 : FAILED:dut:Total downtime period must be less then 0:00:00 seconds. It was 4.43433070183
```

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@vaibhavhd can you update the PR comments, it should be dst mac instead of src mac in your 'fixes' section.

**Review by yxieca — APPROVED** [review]

**Review by kellyyeh — APPROVED** [review]

**Review by kellyyeh — APPROVED** [review]

**Comment by wangxin** [comment]
@vaibhavhd Merging this PR to 202012 branch has conflicts. The signature of AdvancedReboot fixture is changed. This script `tests/platform_tests/test_cont_warm_reboot.py` could be broken by cherry-pick. Can you create separate PR to 202012 branch to have this change?

**Comment by wangxin** [comment]
@vaibhavhd Cherry-picking this PR to 202205 branch hit similar issue.

**Pull request merged**
