### PR TITLE
Crm total routes change

### PR DESCRIPTION
**Pull request by CharudattaSChitale**
Description: 
Cisco platforms need an upward of 10 routes for 'crm_stats_ipv4_route_available' to decrement
It was observed that even with 10 routes, test_crm_route[str2-8102-02-None-ipv4] tescase was failing because "crm_stats_ipv4_route_available" counter was not getting decremented.

Changes:
It was decided that its better to increase the ipv4 routes added from 10 to 64 to make sure that the crm_stats_ipv4_route_available counter is decremented consistently.

Verification:
The test was run multiple times after changing the routes from 10 to 64. No failures were seen.

### CODE REVIEW

**Comment by CharudattaSChitale** [comment]
I have fixed the pre-commit issues related to my changes. Rest of the issues are for the pre-existing code.

**Comment by kevinskwang** [comment]
Please follow the SONiC PR guidance to add some more description info for the PR.

What is the motivation for this PR?
How did you do it?
How did you verify/test it?

**Comment by kevinskwang** [comment]
Please also remove the redundant space changes.

**Comment by CharudattaSChitale** [comment]
I have updated the PR description and also fixed some of the pre-commit issues related to redundant spaces.

**Comment by CharudattaSChitale** [comment]
Pre-commit errors are not because of my changes. Still, fixed few of the pre commit errors.
Can you please approve this change?

**Comment by kevinskwang** [comment]
@CharudattaSChitale Now I understood the purpose of this PR, but please remove all the redundant spaces/lines, just keep the required changes aligned with your description.

**Comment by CharudattaSChitale** [comment]
I have kept my changes and also fixed all the pre-commit errors in this file.
Please approve this PR

**Comment by kevinskwang** [comment]
> I have kept my changes and also fixed all the pre-commit errors in this file. Please approve this PR

I still can see lots of space/new lines. Could you remove that?

**Pull request closed without merging**
