### PR TITLE
BFD with OSPF testplan

### PR DESCRIPTION
**Pull request by Ghulam-Bahoo**
### Description of PR
This PR contains a test plan for BFD with OSPF. The test plan comprises 3 test cases:

1. Test OSPF Neighborship Status
2. Test BFD Neighborship Status
3. Test BFD Dynamic Switching of Network Traffic

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311

#### What is the motivation for this PR?
Currently, there is no existing test plan for running BFD in conjunction with OSPF in SONiC. This test plan helps users configure BFD with OSPF in the existing testbed and framework.
#### How did you do it?
The test cases disable the existing BGP configurations, enable the FRR container's OSPF and BFD feature, and establish OSPF and BFD neighborship using existing neighbor IP and DUT port IP configurations. Once these initial configurations are done, the planned tests and checks are carried out. 
#### How did you verify/test it?
Run the test case on any topology
#### Any platform specific information?
It will run on all topologies where neighboring devices are SONiC devices.
#### Supported testbed topology if it's a new test case?
- [x] T0 (all versions)
- [x] T1 (all variations)

### CODE REVIEW

**Comment by Ghulam-Bahoo** [comment]
@yxieca  can you please review this PR.

**Comment by yxieca** [comment]
@Ghulam-Bahoo please resolve the merge conflicts.

**Comment by Ghulam-Bahoo** [comment]
> @Ghulam-Bahoo please resolve the merge conflicts.
I have resolved the merge conflicts, kindly help merge the test plan.

**Comment by ridahanif96** [comment]
@yxieca Hi Ying, can you please help merge this testplan. It has been reviewed and changes have being made as per suggestion, thanks!

**Comment by ridahanif96** [comment]
@yxieca Hi Ying, a reminder to pls review and merge this PR.

**Pull request merged**
