### PR TITLE
Updated skip reasons on Mellanox platforms

### PR DESCRIPTION
**Pull request by mhen1**
### Description of PR

Summary:
Updated skip reasons to skips that were added in https://github.com/sonic-net/sonic-mgmt/pull/12183.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Update skip reasons in .yaml file.

### CODE REVIEW

**Comment by wsycqyz** [comment]
Please re-run to make sure all PR test passed.

**Comment by mhen1** [comment]
> Please re-run to make sure all PR test passed.

Hey, all checks have passed

**Review by wsycqyz — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Pull request merged**
