### PR TITLE
RDMA case modification to support Multi-ASIC Feature

### PR DESCRIPTION
**Pull request by selldinesh**
### Description of PR

Summary:
Summary:RDMA case modification to support Multi-ASIC Feature 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

### CODE REVIEW

**Comment by vmittal-msft** [comment]
@baiwei0427 for your review.

**Review by baiwei0427 — CHANGES_REQUESTED** [review]
It seems that you upload too many test cases. Can you please start with a easy test case? Note that we have a very basic snappi test [test_snappi.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/snappi/test_snappi.py). Maybe you can have one called test_snappi_multidut.py?

**Comment by selldinesh** [comment]
> It seems that you upload too many test cases. Can you please start with a easy test case? Note that we have a very basic snappi test [test_snappi.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/snappi/test_snappi.py). Maybe you can have one called test_snappi_multidut.py?

added tests/snappi/test_multidut_snappi.py

**Comment by vmittal-msft** [comment]
1. Please open different PRs for Infra, PFC, PFCWD, ECN. Usually one PR for one test case.
2. Need update for test plan for IXIA test cases supporting multi dut.

**Comment by vmittal-msft** [comment]
@selldinesh @kamalsahu0001 As discussed, Can you please start raising PRs for individual test cases so we can review/merge soon ?

**Comment by kamalsahu0001** [comment]
Please find the PR for multi-dut/multi-asic infrastructure changes. 
https://github.com/sonic-net/sonic-mgmt/pull/7849

**Comment by selldinesh** [comment]
Multidut Infrastructure and Global pause test case PR: https://github.com/sonic-net/sonic-mgmt/pull/7849
PFC Lossless: https://github.com/sonic-net/sonic-mgmt/pull/7912
PFC Lossy: https://github.com/sonic-net/sonic-mgmt/pull/7913
ECN dequeue: https://github.com/sonic-net/sonic-mgmt/pull/7914
ECN red accuracy: https://github.com/sonic-net/sonic-mgmt/pull/7915
PFCWD basic: https://github.com/sonic-net/sonic-mgmt/pull/7917
PFCWD burst storm: https://github.com/sonic-net/sonic-mgmt/pull/7918
PFCWD a2a: https://github.com/sonic-net/sonic-mgmt/pull/7916
PFCWD m2o: https://github.com/sonic-net/sonic-mgmt/pull/7919
PFCWD runtime traffic: https://github.com/sonic-net/sonic-mgmt/pull/7920

**Comment by developfast** [comment]
Can you please close this PR as we have separate PRs for each test case?

**Comment by selldinesh** [comment]
Closing this PR as we have raised separate PR's for each test case and infrastructure PR

**Pull request closed without merging**
