### PR TITLE
[Dash] Relaxed match support

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
This PR contains the test plan and test implementation of the feature "Relaxed match support" for DPU.
The feature is to support dynamic change of VXLAN UDP port on the DPU.
The purpose of this test is to verify the functionality of dynamic VXLAN UDP port changing on DPU.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
Provide the test plan and test implementation of the feature "Relaxed match support" for DPU.
#### How did you do it?
1. Integrate the functionality test into the existing dash vnet test(https://github.com/sonic-net/sonic-mgmt/blob/master/tests/dash/test_dash_vnet.py).
2. Add a new test file for the negative test case.
#### How did you verify/test it?
Run the tests on DPU setups, all passed.
#### Any platform specific information?
Only for DPU.
#### Supported testbed topology if it's a new test case?
dpu, dpu-1
### Documentation
Test plan: docs/testplan/dash/Dash-Relaxed-Match-Support.md

### CODE REVIEW

**Comment by congh-nvidia** [comment]
Currently, configuring an invalid vxlan port will cause orchagent crash. The behavior is inherited from the switch and has not been decided whether it will be changed on DPU. If finally, it is decided to keep the same behavior with switch, the test case test_relaxed_match_invalid_port should be removed.
I will move this draft to "ready for review" after the decision is made.

**Comment by congh-nvidia** [comment]
> Currently, configuring an invalid vxlan port will cause orchagent crash. The behavior is inherited from the switch, and it has not been decided whether it should be changed on DPU or not. If finally, it is decided to keep the same behavior with switch, the test case test_relaxed_match_invalid_port should be removed. I will move this draft to "ready for review" after the decision is made.

It is decided not to change the behavior of changing the vxlan port to a invalid value. The negative test cases for invalid port is removed from test plan and test file.

**Comment by congh-nvidia** [comment]
@nhe-NV @Yakiv-Huryk Please review, thanks.

**Review by nhe-NV — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Yakiv-Huryk OK to merge?

**Review by Yakiv-Huryk — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@congh-nvidia can you handle the conflict so i can merge it?

**Review by kperumalbfn — APPROVED** [review]

**Comment by congh-nvidia** [comment]
Hi @liat-grozovik, could you please merge this? Thanks.

**Comment by congh-nvidia** [comment]
@nhe-NV please add 202405 label.
Hi @liat-grozovik, could you please merge this? Thanks

**Comment by congh-nvidia** [comment]
Hi @liat-grozovik , could you please merge this? Thanks.

**Comment by congh-nvidia** [comment]
Hi @wangxin could you please review and merge this?

**Comment by bingwang-ms** [comment]
@congh-nvidia Please fix the conflict.

**Comment by congh-nvidia** [comment]
Will manually cherry-pick to 202405.

**Comment by congh-nvidia** [comment]
Cherry-pick to 202405: https://github.com/sonic-net/sonic-mgmt/pull/14059. @bingwang-ms please review.

**Pull request merged**
