### PR TITLE
Add skip for test_service_warm_restart test by github issue

### PR DESCRIPTION
**Pull request by nhe-NV**
### Description of PR

Summary: Add skip for test_service_warm_restart test by github issue:  https://github.com/sonic-net/sonic-mgmt/issues/10362
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

### CODE REVIEW

**Review by roy-sror — COMMENTED** [review]
@nhe-NV  - what is the probability of this issue? do we really want to permanently skip the test on that?

**Review by roy-sror — APPROVED** [review]

**Comment by bingwang-ms** [comment]
There is already a skip statement in `tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml`.

**Comment by nhe-NV** [comment]
> There is already a skip statement in `tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml`. Can you update the existing one?

I see, but you have a PR to revert it right? @bingwang-ms  https://github.com/sonic-net/sonic-mgmt/pull/13512

**Comment by bingwang-ms** [comment]
> > There is already a skip statement in `tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml`. Can you update the existing one?
> 
> I see, but you have a PR to revert it right? @bingwang-ms #13512

I have closed #13512. Please update your PR. Thanks!

**Comment by nhe-NV** [comment]
> > > There is already a skip statement in `tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml`. Can you update the existing one?
> > 
> > 
> > I see, but you have a PR to revert it right? @bingwang-ms #13512
> 
> I have closed #13512. Please update your PR. Thanks!

Updated

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
The change is not required for 202305 as we don't have the skip statement in 202305 branch.

**Pull request merged**
