### PR TITLE
fix test failures caused due to PR 6519

### PR DESCRIPTION
**Pull request by rraguraj**
Description of PR

Removed the duplicate entry for skip conditions for the following tests caused by https://github.com/sonic-net/sonic-mgmt/pull/6519 

platform_tests/api/test_fan_drawer_fans.py::TestFanDrawerFans::test_set_fans_speed:
platform_tests/api/test_chassis_fans.py::TestChassisFans::test_set_fans_speed:
platform_tests/api/test_chassis_fans.py::TestChassisFans::test_set_fans_led:

Summary:
Fixes # (6811)

### Type of change

- [ x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ x] 202205

#### What is the motivation for this PR?
  tests failures caused by https://github.com/sonic-net/sonic-mgmt/pull/6519 

#### How did you do it?
Removed the duplicate entry for skip conditions

### CODE REVIEW

**Comment by abdosi** [comment]
please resolve the conflict.

**Comment by abdosi** [comment]
add more description as what is the issue here.

**Comment by abdosi** [comment]
@assrinivasan for viz.

**Comment by abdosi** [comment]
please resolve the conflict.

**Comment by abdosi** [comment]
please resolve the conflict

**Comment by abdosi** [comment]
cc @gechiang for viz

**Comment by abdosi** [comment]
@vperumal please help in resolving the conflict at earliest.

**Comment by gechiang** [comment]
azp/run

**Review by gechiang — APPROVED** [review]
Changes looks good to me.  Not sure about the test pre-commit-check failure...

**Comment by shivuv** [comment]
@abdosi : Appreciate if you can expedite the double commit of this PR into 202205.

**Pull request merged**
