### PR TITLE
Always run postboot_setup in runRebootTest

### PR DESCRIPTION
**Pull request by andywongarista**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
In event of an exception in runRebootTest, postboot_setup may not run. 

#### How did you do it?
Move the call to the finally block to ensure it is always run.

#### How did you verify/test it?
Verified running test_upgrade_path on Arista device.

### CODE REVIEW

**Comment by andywongarista** [comment]
@saiarcot895 can you please review?

**Review by ryanzhu706 — APPROVED** [review]

**Comment by Ryangwaite** [comment]
I don't think it's the best approach for `postboot_setup` to always run. For our internal use of `postboot_setup` we copy and run additional scripts as well as patch various things that are only relevant after a successful reboot into the next version has occurred. If we put the `postboot_setup` in the finally block, then we'd always run these unless there was some flag that we set on error and pass into postboot_setup to selectively run pieces of the implementation. This sounds messy.

I'm interested in your use case here. I get the sense that your `postboot_setup` implementation does some sort of additional log capture which would make sense to run in all cases. If so, we could introduce another hook like `preboot_setup` and `postboot_setup` that is called in the finally block.

**Review by saiarcot895 — APPROVED** [review]

**Comment by andywongarista** [comment]
> I don't think it's the best approach for `postboot_setup` to always run. For our internal use of `postboot_setup` we copy and run additional scripts as well as patch various things that are only relevant after a successful reboot into the next version has occurred. If we put the `postboot_setup` in the finally block, then we'd always run these unless there was some flag that we set on error and pass into postboot_setup to selectively run pieces of the implementation. This sounds messy.
> 
> I'm interested in your use case here. I get the sense that your `postboot_setup` implementation does some sort of additional log capture which would make sense to run in all cases. If so, we could introduce another hook like `preboot_setup` and `postboot_setup` that is called in the finally block.

Internally we use postboot_setup to restore DNS-related config that gets lost during the upgrade process, so for us it seems necessary to always run - otherwise subsequent attempts to run the test fail because the SONiC image cannot be installed.

**Comment by saiarcot895** [comment]
Vaibhav and I believe that the `postboot_setup` should always run, whether or not the upgrade was successful. For our use case, we'll need to refactor our code so that it works properly.

**Review by Ryangwaite — APPROVED** [review]

**Comment by StormLiangMS** [comment]
hi @yxieca  @bingwang-ms need cherry pick.

**Pull request merged**
