### PR TITLE
[python3_migration]Fix python3 migration issue for qos_sai and test_sub_port_l2_forwarding

### PR DESCRIPTION
**Pull request by nhe-NV**
### Description of PR

Summary: Fix python3 migration issue for qos_sai and test_sub_port_l2_forwarding
Fixes # (issue) Fix the issues: https://github.com/sonic-net/sonic-mgmt/issues/7866 and https://github.com/sonic-net/sonic-mgmt/issues/7884

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
Fix the test failure caused by python3 migration

#### How did you verify/test it?
Run qos sai and test_sub_port_l2_forwarding, and it could pass

### CODE REVIEW

**Review by neethajohn — APPROVED** [review]

**Review by wangxin — DISMISSED** [review]

**Comment by neethajohn** [comment]
@nhe-NV , please resolve merge conflicts

**Comment by wsycqyz** [comment]
@nhe-NV I am waiting for this PR to be merged. Then I can merge #8010

**Comment by liat-grozovik** [comment]
@nhe-NV could you please help to resolve conflict?

**Comment by liat-grozovik** [comment]
@wangxin could you please help to approve?

**Review by wangxin — APPROVED** [review]

**Pull request merged**
