### PR TITLE
Add debuggability for reboot function

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

1. Add function to collect console log from starting reboot to dut up
2. When dut is not up, check if dut is pingable and collect the mgmt interface config

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Enhance the debugability for reboot fucntion

#### How did you do it?
1. Add function to collect console log from starting reboot to dut up
2. When dut is not up, check if dut is pingable and collect the mgmt interface config

#### How did you verify/test it?
Run reboot cases

#### Any platform specific information?
Any

### CODE REVIEW

**Comment by JibinBao** [comment]
The PR of https://github.com/sonic-net/sonic-mgmt/pull/14341 is hung  when push the new fix. It is githhug issue, so open the PR same as https://github.com/sonic-net/sonic-mgmt/pull/14341.
For the previous review comments, please see https://github.com/sonic-net/sonic-mgmt/pull/14341

**Review by nhe-NV — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
LGTM. great addition for debug cases. @yxieca  @bingwang-ms are you ok to merge?

**Comment by bingwang-ms** [comment]
Hi @JibinBao, @liat-grozovik, we have discussed a similar enhancement in another PR. I do have concern to add console access to reboot function. It can add flakiness to any tests that require reboot as console access is not always available and stable.

**Comment by yxieca** [comment]
> Hi @JibinBao, @liat-grozovik, we have discussed a similar enhancement in another PR. I do have concern to add console access to reboot function. It can add flakiness to any tests that require reboot as console access is not always available and stable.

I agree with Bing, this PR is adding console access as a must-have. Can we make it optional, if the console access is there, then we take extra inputs, otherwise, fallback to original test behavior?

**Comment by liat-grozovik** [comment]
optional based on availability sound ok to me. @JibinBao  can you please align the code based on that?

**Comment by yutongzhang-microsoft** [comment]
> Hi @JibinBao, @liat-grozovik, we have discussed a similar enhancement in another PR. I do have concern to add console access to reboot function. It can add flakiness to any tests that require reboot as console access is not always available and stable.

I also worry about this, as console connection is not stable enough, and sometimes fails because of the console server issues. This will add uncertainty of the test script.

**Comment by JibinBao** [comment]
> > Hi @JibinBao, @liat-grozovik, we have discussed a similar enhancement in another PR. I do have concern to add console access to reboot function. It can add flakiness to any tests that require reboot as console access is not always available and stable.
> 
> I also worry about this, as console connection is not stable enough, and sometimes fails because of the console server issues. This will add uncertainty of the test script.

Hi @yxieca @bingwang-ms @liat-grozovik @yutongzhang-microsoft ,
The current design has considered the case, we use 'try mechanism' to create a console, and when failing to create the console, we will not use console collecting logs.  
I have tested the following scenarios, and they all do not affect the original reboot logic.

- 1 No console config
- 2 Wrong console config
- 3 correct console config and console works

Anyway, If you still have the concerns, I can add one env variable to control it.
for example **CONSOLE_IS_READY**
when os.getenv("CONSOLE_IS_READY") is Ture, we can collect the logs by console, otherwise keep the old logic.
By default, we don't have the env variable, so collecting logs by console will not be enabled.

Is it ok? If yes, I will change it accordingly.
Thanks.

**Comment by yxieca** [comment]
@yutongzhang-microsoft please review the change. I don't have other concerns.

**Comment by yutongzhang-microsoft** [comment]
> > > Hi @JibinBao, @liat-grozovik, we have discussed a similar enhancement in another PR. I do have concern to add console access to reboot function. It can add flakiness to any tests that require reboot as console access is not always available and stable.
> > 
> > 
> > I also worry about this, as console connection is not stable enough, and sometimes fails because of the console server issues. This will add uncertainty of the test script.
> 
> Hi @yxieca @bingwang-ms @liat-grozovik @yutongzhang-microsoft , The current design has considered the case, we use 'try mechanism' to create a console, and when failing to create the console, we will not use console collecting logs. I have tested the following scenarios, and they all do not affect the original reboot logic.
> 
> * 1 No console config
> * 2 Wrong console config
> * 3 correct console config and console works
> 
> Anyway, If you still have the concerns, I can add one env variable to control it. for example **CONSOLE_IS_READY** when os.getenv("CONSOLE_IS_READY") is Ture, we can collect the logs by console, otherwise keep the old logic. By default, we don't have the env variable, so collecting logs by console will not be enabled.
> 
> Is it ok? If yes, I will change it accordingly. Thanks.

Will the "try mechanism" takes too much time if console session is unreachable?

**Comment by JibinBao** [comment]
> > > > Hi @JibinBao, @liat-grozovik, we have discussed a similar enhancement in another PR. I do have concern to add console access to reboot function. It can add flakiness to any tests that require reboot as console access is not always available and stable.
> > > 
> > > 
> > > I also worry about this, as console connection is not stable enough, and sometimes fails because of the console server issues. This will add uncertainty of the test script.
> > 
> > 
> > Hi @yxieca @bingwang-ms @liat-grozovik @yutongzhang-microsoft , The current design has considered the case, we use 'try mechanism' to create a console, and when failing to create the console, we will not use console collecting logs. I have tested the following scenarios, and they all do not affect the original reboot logic.
> > 
> > * 1 No console config
> > * 2 Wrong console config
> > * 3 correct console config and console works
> > 
> > Anyway, If you still have the concerns, I can add one env variable to control it. for example **CONSOLE_IS_READY** when os.getenv("CONSOLE_IS_READY") is Ture, we can collect the logs by console, otherwise keep the old logic. By default, we don't have the env variable, so collecting logs by console will not be enabled.
> > Is it ok? If yes, I will change it accordingly. Thanks.
> 
> Will the "try mechanism" takes too much time if console session is unreachable?

I tested it with a wrong console config, it took about 1 second to try.  it seems not to introduce execution time increasing obviously.

**Review by yutongzhang-microsoft — COMMENTED** [review]
LGTM

**Review by yutongzhang-microsoft — APPROVED** [review]

**Comment by kperumalbfn** [comment]
202411 PR - https://github.com/sonic-net/sonic-mgmt/pull/16845

**Pull request merged**
