### PR TITLE
DEFAULT_ASIC_SERVICES list based on Feature Table status on device

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

Updated the SonicHost List DEFAULT_ASIC_SERVICES based on Feature Table `has_per_asic_scope` and `state`  field.

Why I did:
In Chassis environment supervisor and LC's can have different set of feature running and can not have static asic service list.

How I verify:
Verified by running `test_pretest.py` in Chassis environment both for supervisor and LC's

### CODE REVIEW

**Comment by rlhui** [comment]
There are 34 commits in this PR?

**Comment by abdosi** [comment]
> There are 34 commits in this PR?

@rlhui i am using same branch for all my PR' so it shows all the commit history. merging PR with squash will show only relevant commit)

**Review by SuvarnaMeenakshi — APPROVED** [review]
lgtm

**Pull request merged**
