### PR TITLE
Stabilize test_cacl cases

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

After rollback_or_reload the config,  the case check if the current iptable rules equal to the original iptale rules directly. Sometimes, the iptable rules are not ready completely, so case will fail due to missing some iptable rules. Therefore, update the code to use retry mechanism to check if the current iptable rules are equal to the original ones.

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Stabilize test_cacl cases

#### How did you do it?
Update the code to use retry mechanism to check if the current iptable rules are equal to the original ones.

#### How did you verify/test it?
Run test_cacl  20 times

#### Any platform specific information?
Any

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@wen587 Can you help review?
@JibinBao What's the error or failure without this change? The test is passing consistently in the history.

**Comment by JibinBao** [comment]
hi @bingwang-ms , please see below:
Failed: iptable rules are not suppose to change after test. diff: ['- -A INPUT -d 10.0.0.32/32 -j DROP', '- -A INPUT -d 10.0.0.34/32 -j DROP', '- -A INPUT -d 10.0.0.36/32 -j DROP', '- -A INPUT -d 10.0.0.38/32 -j DROP', '- -A INPUT -d 10.0.0.40/32 -j DROP', '- -A INPUT -p icmp -m ttl --ttl-lt 2 -j ACCEPT', '- -A INPUT -p udp -m ttl --ttl-lt 2 -m udp --dport 1025:65535 -j ACCEPT', '- -A INPUT -p tcp -m ttl --ttl-lt 2 -m tcp --dport 1025:65535 -j ACCEPT']

**Comment by wen587** [comment]
@JibinBao , what is the platform or OSversion that fail in this case?
I don't think we need to add a wait_until for this case. There are forced 1 sec wait embeded in to GCU utilities for CACL rule refresh. https://github.com/sonic-net/sonic-utilities/blob/master/generic_config_updater/services_validator.py#L100

**Comment by JibinBao** [comment]
> @JibinBao , what is the platform or OSversion that fail in this case? I don't think we need to add a wait_until for this case. The caclmgrd should be refreshed within 0.5 sec if cacl change. And there are already forced 1 sec wait embeded in to GCU utilities for CACL rule refresh. https://github.com/sonic-net/sonic-utilities/blob/master/generic_config_updater/services_validator.py#L100

Hi @wen587 ,
The platform is sn4280, and the os is 202405. The issue happened from time to time.
The reproduced steps are as follows:
In the teardown,  
- config rollback test
- iptables -S.

From the end of "config rollback test" to the start of "iptables -S", it takes 0.5006 seconds. I am not sure what time the caclmgrd start refreshing when doing config rollback.  Do we have a way to make sure get the iptable in 0.5s after the caclmgrd start refresh?or after ""config rollback test"", can we sleep(0.5) before getting iptable rules?

 {"cmd": "config rollback test", "start": "2024-10-13 07:03:45.040295", "end": "2024-10-13 07:03:49.415466", "delta": "0:00:04.375171"}
{ cmd": "iptables -S", "start": "2024-10-13 07:03:49.916084", "end": "2024-10-13 07:03:49.929695", "delta": "0:00:00.013611"}

**Comment by wen587** [comment]
> > @JibinBao , what is the platform or OSversion that fail in this case? I don't think we need to add a wait_until for this case. The caclmgrd should be refreshed within 0.5 sec if cacl change. And there are already forced 1 sec wait embeded in to GCU utilities for CACL rule refresh. https://github.com/sonic-net/sonic-utilities/blob/master/generic_config_updater/services_validator.py#L100
> 
> Hi @wen587 , The platform is sn4280, and the os is 202405. The issue happened from time to time. The reproduced steps are as follows: In the teardown,
> 
> * config rollback test
> * iptables -S.
> 
> From the end of "config rollback test" to the start of "iptables -S", it takes 0.5006 seconds. I am not sure what time the caclmgrd start refreshing when doing config rollback. Do we have a way to make sure get the iptable in 0.5s after the caclmgrd start refresh?or after ""config rollback test"", can we sleep(0.5) before getting iptable rules?
> 
> {"cmd": "config rollback test", "start": "2024-10-13 07:03:45.040295", "end": "2024-10-13 07:03:49.415466", "delta": "0:00:04.375171"} { cmd": "iptables -S", "start": "2024-10-13 07:03:49.916084", "end": "2024-10-13 07:03:49.929695", "delta": "0:00:00.013611"}

Hi @JibinBao , I got your point. Though the sleep 1 sec in GCU make sure this change is applied successfully, but in mgmt test we are checking `iptables` too early. 

Let's restrict it to `wait_until(5, 1, 0,` I think this should be updated within 1 sec.

**Comment by JibinBao** [comment]
> > > @JibinBao , what is the platform or OSversion that fail in this case? I don't think we need to add a wait_until for this case. The caclmgrd should be refreshed within 0.5 sec if cacl change. And there are already forced 1 sec wait embeded in to GCU utilities for CACL rule refresh. https://github.com/sonic-net/sonic-utilities/blob/master/generic_config_updater/services_validator.py#L100
> > 
> > 
> > Hi @wen587 , The platform is sn4280, and the os is 202405. The issue happened from time to time. The reproduced steps are as follows: In the teardown,
> > 
> > * config rollback test
> > * iptables -S.
> > 
> > From the end of "config rollback test" to the start of "iptables -S", it takes 0.5006 seconds. I am not sure what time the caclmgrd start refreshing when doing config rollback. Do we have a way to make sure get the iptable in 0.5s after the caclmgrd start refresh?or after ""config rollback test"", can we sleep(0.5) before getting iptable rules?
> > {"cmd": "config rollback test", "start": "2024-10-13 07:03:45.040295", "end": "2024-10-13 07:03:49.415466", "delta": "0:00:04.375171"} { cmd": "iptables -S", "start": "2024-10-13 07:03:49.916084", "end": "2024-10-13 07:03:49.929695", "delta": "0:00:00.013611"}
> 
> Hi @JibinBao , I got your point. Though the sleep 1 sec in GCU make sure this change is applied successfully, but in mgmt test we are checking `iptables` too early.
> 
> Let's restrict it to `wait_until(5, 1, 0,` by my understanding this should be updated within 1 sec.

@wen587 , Thanks . So, I will update the code from wait_until(60, 5, 0, to wait_until(5, 1, 0

**Comment by JibinBao** [comment]
Hi @wen587 ,
Fixed is done, can you help review it?

**Review by wen587 — APPROVED** [review]
lgtm

**Comment by JibinBao** [comment]
> @JibinBao PR conflicts with 202405 branch

@bingwang-ms conficts are fixed
https://github.com/sonic-net/sonic-mgmt/pull/15299

**Pull request merged**
