### PR TITLE
[drop_packets] Skip drop_packets on MGFX

### PR DESCRIPTION
**Pull request by yaqiangz**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
drop_packtes tests were skipped for MGFX by folder previously. Now it is broken by this change https://github.com/sonic-net/sonic-mgmt/pull/14395
Hence update condition mark

#### How did you do it?
Update condition mark

#### How did you verify/test it?
Run tests

### CODE REVIEW

**Review by yutongzhang-microsoft — APPROVED** [review]

**Comment by yaqiangz** [comment]
Hi @wangxin could you please help to merge this PR?

**Comment by yaqiangz** [comment]
Hi @wangxin could you please help to merge this PR?

**Review by wangxin — APPROVED** [review]

**Comment by yaqiangz** [comment]
Hi @bingwang-ms could you please help to approve the backport request?

**Comment by bingwang-ms** [comment]
Hi @yaqiangz, is the test passing in 202311 branch?

**Comment by yaqiangz** [comment]
> Hi @yaqiangz, is the test passing in 202311 branch?

Hi @bingwang-ms no, all drop_packets test on m0/mx has been skipped in 202311 https://github.com/sonic-net/sonic-mgmt/blob/202311/tests/common/plugins/conditional_mark/tests_mark_conditions.yaml#L346

But in master and 202405, new change in current PR description caused that folder level condition mark would be override by case level, hence I updated the case level skip with current PR

**Comment by yaqiangz** [comment]
Found code conflict with 202405, I will create manually backport

**Pull request merged**
