### PR TITLE
[Fanout] Update Arista-7260CX3 leaf fanout template for breakout 4x 10G interface

### PR DESCRIPTION
**Pull request by lizhijianrd**
### Description of PR

Summary:
Update Arista-7260CX3 leaf fanout configuration template for breakout 4x 10G interface.
Fix the template for situation that not all the 4 breakout interface are being used.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405

#### What is the motivation for this PR?
Update Arista-7260CX3 leaf fanout configuration template for breakout 4x 10G interface.
Fix the template for situation that not all the 4 breakout interface are being used.

#### How did you do it?
Update the j2 template file.

#### How did you verify/test it?
Verified on physical Arista-7260CX3 fanout switch.
Snippet of generated configuration:

```
...
interface Ethernet9/1
   description DUT-1-Ethernet51
   speed forced 10000full
   switchport access vlan 668
   switchport mode dot1q-tunnel
   spanning-tree portfast
!
interface Ethernet9/2
   shutdown
!
interface Ethernet9/3
   description DUT-2-Ethernet51
   speed forced 10000full
   switchport access vlan 772
   switchport mode dot1q-tunnel
   spanning-tree portfast
!
interface Ethernet9/4
   shutdown
!
...
```

### CODE REVIEW

**Comment by wsycqyz** [comment]
Do we need this PR in 2024 or 2023 branch?

**Comment by wsycqyz** [comment]
PR test re-triggered.

**Comment by lizhijianrd** [comment]
> Do we need this PR in 2024 or 2023 branch?

No, we only use master branch for fanout switch deployment.

**Review by yutongzhang-microsoft — APPROVED** [review]
LGTM

**Review by wsycqyz — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Pull request merged**
