### PR TITLE
Add new topology t0-56-d48c8

### PR DESCRIPTION
**Pull request by wangxin**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205

#### What is the motivation for this PR?
On some devices using topology t0-56, upstream portchannels are not using 100G interfaces due to their own port breakout schema.

#### How did you do it?
This change added new topology t0-56-d48c8 so that on these devices the upstream portchannels are using the 100G interfaces.

#### How did you verify/test it?
Update a testbed to use topology t0-56-d48c8, deploy the topology, run tests like bgp_facts, link_flap.

### CODE REVIEW

**Review by yutongzhang-microsoft — APPROVED** [review]

**Review by yejianquan — APPROVED** [review]
LGTM

**Comment by bingwang-ms** [comment]
Do we need this change for `202205` and `202012` branches?

**Pull request merged**
