### PR TITLE
Add Marvell new hwsku port alias mapping

### PR DESCRIPTION
**Pull request by rajneeshaec**
Summary:
Add Marvell new hwsku port alias mapping

### Type of change
- [ ] Bug fix
- [X ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ X] 202305
- [X ] 202311

#### What is the motivation for this PR?
Adding new product support

### CODE REVIEW

**Comment by tudupa** [comment]
@rajneeshaec Can you please include "Nokia-7215-A1" HwSKU as well in this PR.

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
@wangxin can you help merge this PR?

**Comment by johnchiucc** [comment]
@wangxin   ping to have your help to merge this one.

**Review by wangxin — APPROVED** [review]

**Comment by Pavan-Nokia** [comment]
@mssonicbld @wangxin Could you please help backport to 2405 and 2311 branches

**Pull request merged**
