### PR TITLE
T2 Snappi Based route convergence: Code changes to support multiple platforms

### PR DESCRIPTION
**Pull request by deepak-singhal0408**
### Description of PR

Summary:
Code changes to support multiple platforms for T2 Snappi Based route convergence tests

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Currently the Snappi based T2 route convergence tests can only be used with single set of duts (hardcoded in variables.py). 
Enhanced the testcases/Infra to provide support for more than one platforms. The platform is fetched at runtime based on testbed parameters.

#### How did you do it?
Fetch the platform info first by comparing the DUTs passed in testcase and duts defined in variables.py.
Use this platform info through out the tests to fetch various other parameters

#### How did you verify/test it?
Ran the T2 snappi route convergance tests

#### Any platform specific information?
None
#### Supported testbed topology if it's a new test case?
NA

### CODE REVIEW

**Comment by deepak-singhal0408** [comment]
@selldinesh for viz.

**Review by arlakshm — APPROVED** [review]

**Review by YatishSVC — APPROVED** [review]
LGTM

**Comment by deepak-singhal0408** [comment]
@arlakshm @rlhui can you please help merge this PR?
MSFT ADO: 30460218

**Comment by deepak-singhal0408** [comment]
@yejianquan could you help approve this PR for 202405? This is needed to run T2 snappi convergence tests on multiple platforms on 202405 branch.

**Comment by deepak-singhal0408** [comment]
@bingwang-ms could you help approve for 202405 branch? Thanks,

**Pull request merged**
