### PR TITLE
[sdn_tests]: Adding LACP testhelper to pins_ondatra.

### PR DESCRIPTION
**Pull request by VSuryaprasad-HCL**
### Description of PR
- [sdn_tests]: Adding LACP testhelper to pins_ondatra.

Summary:
- Adding LACP testhelper to pins_ondatra.

Build result:

                   $ bazel build ...

                   INFO: From Generating Descriptor Set proto_library @com_github_openconfig_gnsi//pathz:pathz_proto:
                   github.com/openconfig/gnsi/pathz/authorization.proto:43:1:
                   warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
                   github.com/openconfig/gnsi/pathz/pathz.proto:25:1: 
                   warning: Import github.com/openconfig/gnsi/version/version.proto is unused.
                   INFO: Elapsed time: 543.745s, Critical Path: 154.16s
                   INFO: 975 processes: 251 internal, 724 linux-sandbox.
                   INFO: Build completed successfully, 975 total actions

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [-] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

### CODE REVIEW

**Review by parth-opensrc — APPROVED** [review]

**Review by rkavitha-hcl — APPROVED** [review]

**Review by vamsipunati — APPROVED** [review]

**Comment by VSuryaprasad-HCL** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/11771

**Pull request merged**
