### PR TITLE
Dynamic threshold test for Cisco-8000

### PR DESCRIPTION
**Pull request by rbpittman**
### Description of PR

Add a new test for the traditional buffer model for lossless profiles. Verifies traffic is being paused at the correct threshold given the alpha computed from the dynamic threshold. This verification is only performed for Cisco-8000 platform.

Includes some additional changes to utilities to query, set, and reset buffer profiles and dynamic thresholds:
- OnExit utility in conftest.py to ensure the test cleans up dynamic threshold setting to avoid side-effects on other tests in either failure or success cases.
- Getter for ingress pool size.
- find_buffer_profile
- get_buffer_alpha

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [X] Test case(new/improvement)

### Back port request
- [ ] 201911
- [X] 202012

#### What is the motivation for this PR?
Improve test coverage of ingress alpha functionality for the traditional buffer model. 

#### How did you verify/test it?
Verified on local cisco-8000 platform.

### CODE REVIEW

**Comment by sachinv-msft** [comment]
@wangxin can you please help on this?

**Comment by wangxin** [comment]
@rbpittman Can you click the link "Please click here to be authorized" in the EasyCLA comment to sign EasyCLA? You'll need to select "Individual Contributor" on the popup window.

**Comment by alpeshspatel** [comment]
@kevinskwang @wangxin Can you please help?

**Comment by rbpittman** [comment]
Thanks @developfast, I haven't seen this pre-commit check before, so installed locally, but am noticing some of these files have a large number of old formatting problems. 
I'm doing a pass over my commits to ensure I'm not *adding* any new formatting problems, and I might fix a few old ones to simplify the output.

**Comment by rbpittman** [comment]
@developfast Done, the pre-commit checks look much better and only relate to old parts of conftest.py. 
The changes did involve some tweaks to code (lambda -> def), so it'd be good to run again to verify.

**Review by kevinskwang — APPROVED** [review]

**Pull request merged**
