### PR TITLE
[202205] Fix iface_namingmode alias check (cherry-pick)

### PR DESCRIPTION
**Pull request by kenneth-arista**
### Description of PR
This is a cherry-pick of https://github.com/sonic-net/sonic-mgmt/pull/10892 as requested to 202205. 

The `iface_namingmode` test attempts to verify that the original interface name is not present in counters output when alias mode is requested, but it winds up matching if the original interface name is a substring of an alias name (e.g., Ethernet1 would match Ethernet12 in the output and cause the test to fail).

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311

#### What is the motivation for this PR?
This is a requested cherry-pick to 202205 to resolve conflicts.

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@judyjoseph @arlakshm @patrickmacarthur for awareness

**Review by wangxin — APPROVED** [review]

**Comment by ysmanman** [comment]
Add @arlakshm for help merge the PR.

**Comment by arlakshm** [comment]
@wangxin, can you help merge this PR

**Review by wenyiz2021 — APPROVED** [review]
LGTM

**Pull request merged**
