### PR TITLE
[T2]:Change the dst ports to a sequential order.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
When running multi-dst tests, in case of switch-packet platforms, it is possible to encounter dst ports that use the same static route. This causes the tests to fail, which assume there is seperate static route for each dst port. We can reduce the possibility of this happening by picking the dst ports sequencially instead of the current list:[0,2,3].

### CODE REVIEW

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT , @abdosi : pls review.

**Comment by rraghav-cisco** [comment]
@XuChen-MSFT , @abdosi : Any comments? Should I move this change to be only for chassis-packet ?

**Comment by abdosi** [comment]
can you please rebase and only keep the relevant changes under cisco specific change.

**Comment by rraghav-cisco** [comment]
Verified on T2:
```
=========================================================================================================== PASSES ===========================================================================================================
_____________________________________________________________________________________ TestQosSai.testQosSaiPfcXonLimit[multi_dut-xon_1] ______________________________________________________________________________________
_____________________________________________________________________________________ TestQosSai.testQosSaiPfcXonLimit[multi_dut-xon_2] ______________________________________________________________________________________
------------------------------ generated xml file: /run_logs/verify-10319/2024-03-08-18-44-06/AJ-100g-SS-gb-pac/qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit_2024-03-08-18-44-06.xml -------------------------------
INFO:root:Can not get Allure report URL. Please check logs
--------------------------------------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------------------------------------
19:11:29 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
================================================================================================== short test summary info ===================================================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[multi_dut-xon_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[multi_dut-xon_2]
SKIPPED [2] qos/test_qos_sai.py:600: Additional DSCPs are not supported on non-dual ToR ports
==================================================================================== 2 passed, 2 skipped, 1 warning in 1641.62s (0:27:21) ====================================================================================
sonic@prod-qos-sonic-mgmt-DNT:/data/tests$ 

```

Verified on T1:
```
=========================================================================================================== PASSES ===========================================================================================================
____________________________________________________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_1] _____________________________________________________________________________________
____________________________________________________________________________________ TestQosSai.testQosSaiPfcXonLimit[single_asic-xon_2] _____________________________________________________________________________________
----------------------------------------------------------------------------- generated xml file: /run_logs/logs/qos/tr_2024-03-08-20-04-43.xml ------------------------------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
--------------------------------------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------------------------------------
20:10:56 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
================================================================================================== short test summary info ===================================================================================================
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_1]
PASSED qos/test_qos_sai.py::TestQosSai::testQosSaiPfcXonLimit[single_asic-xon_2]
SKIPPED [2] qos/test_qos_sai.py:599: Additional DSCPs are not supported on non-dual ToR ports
SKIPPED [4] qos/qos_sai_base.py:603: Did not find any frontend node that is multi-asic - so can't run single_dut_multi_asic tests
SKIPPED [4] qos/qos_sai_base.py:613: Don't have 2 frontend nodes - so can't run multi_dut tests
==================================================================================== 2 passed, 10 skipped, 1 warning in 371.92s (0:06:11) ====================================================================================
sonic@447c4c4ec6fc:/data/tests$ 
```

**Comment by rraghav-cisco** [comment]
> can you please rebase and only keep the relevant changes under cisco specific change.

@abdosi : Simplified, and verified on both T2 and T1.

**Comment by rraghav-cisco** [comment]
@abdosi : Verified the diff is passing for T1:
====================================================================================================== warnings summary ======================================================================================================
../../usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18
  /usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18: DeprecationWarning: The _yaml extension module is now located at yaml._yaml and its location is subject to change.  To use the LibYAML-based parser and emitter, import from `yaml`: `from yaml import CLoader as Loader, CDumper as Dumper`.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
----------------------------------------------------------------------- generated xml file: /data/tests/logs/qos/test_qos_sai_2024-04-10-19-31-49.xml ------------------------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
--------------------------------------------------------------------------------------------------- live log sessionfinish ---------------------------------------------------------------------------------------------------
20:17:40 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
================================================================================================== short test summary info ===================================================================================================
SKIPPED [2] qos/test_qos_sai.py:351: Additional DSCPs are not supported on non-dual ToR ports
SKIPPED [2] qos/test_qos_sai.py:436: This Test Case is only meant for Mellanox ASIC
SKIPPED [2] qos/test_qos_sai.py:432: Additional DSCPs are not supported on non-dual ToR ports
SKIPPED [2] qos/test_qos_sai.py:610: Additional DSCPs are not supported on non-dual ToR ports
SKIPPED [3] qos/test_qos_sai.py: Headroom pool size not supported.
SKIPPED [1] qos/test_qos_sai.py:968: Headroom pool size is not enabled on this DUT
SKIPPED [2] qos/test_qos_sai.py:1358: Skip this test since separated DSCP_TO_TC_MAP is not applied
SKIPPED [3] qos/test_qos_sai.py: Dot1p-queue mapping is only supported on backend.
SKIPPED [3] qos/test_qos_sai.py: Dot1p-PG mapping is only supported on backend.
SKIPPED [3] qos/test_qos_sai.py: Priority Group Headroom Watermark is not supported on cisco asic. PG drop counter stat is covered as a part of testQosSaiPfcXoffLimit
SKIPPED [1] qos/qos_sai_base.py:2162: PGDrop test is not supported for 400G port speed.
SKIPPED [2] qos/test_qos_sai.py:1972: Skip this test since separated DSCP_TO_TC_MAP is not applied
SKIPPED [40] qos/qos_sai_base.py:628: Did not find any frontend node that is multi-asic - so can't run single_dut_multi_asic tests
SKIPPED [40] qos/qos_sai_base.py:635: multi-dut is not supported on T1 topologies
FAILED qos/test_qos_sai.py::TestQosSai::testIPIPQosSaiDscpToPgMapping[single_asic-uniform] - Failed: Test Failed: [['Expected packet with DSCP 3 was not received on any of the ports: [24', ' 25', ' 26', ' 27', ' 28', ' ...
FAILED qos/test_qos_sai.py::TestQosSai::testIPIPQosSaiDscpToPgMapping[single_asic-pipe] - TypeError: config_reload() got an unexpected keyword argument 'wait_for_bgp'
============================================================================= 2 failed, 24 passed, 106 skipped, 1 warning in 2749.33s (0:45:49) ==============================================================================
AzDevOps@nonprod-sonic-mgmt-202311:/data/tests$

**Review by abdosi — APPROVED** [review]

**Pull request merged**
