### PR TITLE
Add IPv6 TC to queue mapping test

### LINKED ISSUE #10939: Missing coverage for IPv6 TC to queue mapping
**Description**
There is currently a test gap for IPv6 traffic for TC to queue mapping.

### PR DESCRIPTION
**Pull request by bktsim-arista**
Summary:
This change introduces an IPv6 test for TC to queue mapping in the QoS suite alongside the infrastructure needed to construct this test. Resolves #10939

### Type of change
- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [x] 202205
- [x] 202305

#### What is the motivation for this PR?
There is a missing test gap for IPv6 DSCP to TC queue mapping. This change introduces a test to fill this test gap by modifying an existing test DscpToQueueMapping which previously tested DSCP to TC queue mapping on IPv4 to also test it for IPv6.

#### How did you do it?
Modified existing `testQosSaiDscpQueueMapping` to also test for IPv6, and added changes to `active_ip_interfaces` to also fetch IPv6 addresses to be used in this test. 

#### How did you verify/test it?
Ran the test manually and it passed.

### CODE REVIEW

**Comment by rlhui** [comment]
@vmittal-msft will review

**Comment by abdosi** [comment]
@alpeshspatel / @rraghav-cisco  for viz

**Review by abdosi — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@bktsim-arista The change caused some regression for other test cases in test_qos_sai. Can you please fix it or revert this change?
```
14:44:01 __init__._fixture_generator_decorator    L0088 ERROR  | 
KeyError('peer_addr_ipv6')
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/qos/qos_sai_base.py", line 1089, in dutConfig
    testPorts = self.__buildTestPorts(request, testPortIds, testPortIps,
  File "/var/src/sonic-mgmt_vms21-t0-2700_646f1402735219c3e5444094/tests/qos/qos_sai_base.py", line 766, in __buildTestPorts
    "dst_port_ipv6": dst_test_port_ips[dstPort]['peer_addr_ipv6'],
KeyError: 'peer_addr_ipv6'
```

**Comment by vivekverma-arista** [comment]
Hi @bingwang-ms, this was fixed in https://github.com/sonic-net/sonic-mgmt/pull/12334.

**Comment by rraghav-cisco** [comment]
@vivekverma-arista :
The qos-sai explicitly disables IPv6 as shown by below code in qos/qos_sai_base.py:
```
1738     @pytest.fixture(scope='class', autouse=True)
1739     def dut_disable_ipv6(self, duthosts, get_src_dst_asic_and_duts, tbinfo, lower_tor_host, # noqa F811
1740                          swapSyncd_on_selected_duts):
1741         for duthost in get_src_dst_asic_and_duts['all_duts']:
1742             docker0_ipv6_addr = \
1743                 duthost.shell("sudo ip -6  addr show dev docker0 | grep global" + " | awk '{print $2}'")[
1744                     "stdout_lines"][0]
1745             duthost.shell("sysctl -w net.ipv6.conf.all.disable_ipv6=1")
1746 
1747         yield
1748 
1749         for duthost in get_src_dst_asic_and_duts['all_duts']:
1750             duthost.shell("sysctl -w net.ipv6.conf.all.disable_ipv6=0")
1751             logger.info("Adding docker0's IPv6 address since it was removed when disabing IPv6")
1752             duthost.shell("ip -6 addr add {} dev docker0".format(docker0_ipv6_addr))
1753             config_reload(duthost, config_source='config_db', safe_reload=True, check_intf_up_ports=True)
```

So even if minigraph has ipv6 addresses, the new test will fail.  Can you pls attach a passing log for this ?

**Comment by vivekverma-arista** [comment]
> @vivekverma-arista : The qos-sai explicitly disables IPv6 as shown by below code in qos/qos_sai_base.py:
> 
> ```
> 1738     @pytest.fixture(scope='class', autouse=True)
> 1739     def dut_disable_ipv6(self, duthosts, get_src_dst_asic_and_duts, tbinfo, lower_tor_host, # noqa F811
> 1740                          swapSyncd_on_selected_duts):
> 1741         for duthost in get_src_dst_asic_and_duts['all_duts']:
> 1742             docker0_ipv6_addr = \
> 1743                 duthost.shell("sudo ip -6  addr show dev docker0 | grep global" + " | awk '{print $2}'")[
> 1744                     "stdout_lines"][0]
> 1745             duthost.shell("sysctl -w net.ipv6.conf.all.disable_ipv6=1")
> 1746 
> 1747         yield
> 1748 
> 1749         for duthost in get_src_dst_asic_and_duts['all_duts']:
> 1750             duthost.shell("sysctl -w net.ipv6.conf.all.disable_ipv6=0")
> 1751             logger.info("Adding docker0's IPv6 address since it was removed when disabing IPv6")
> 1752             duthost.shell("ip -6 addr add {} dev docker0".format(docker0_ipv6_addr))
> 1753             config_reload(duthost, config_source='config_db', safe_reload=True, check_intf_up_ports=True)
> ```
> 
> So even if minigraph has ipv6 addresses, the new test will fail. Can you pls attach a passing log for this ?

Hi @rraghav-cisco, we are skipping the test in master and 202311 [#12834](https://github.com/sonic-net/sonic-mgmt/pull/12834)

**Pull request merged**
