### PR TITLE
sonic-mgmt: reduce fdb test time for large topos

### PR DESCRIPTION
**Pull request by ccroy-arista**
Summary: reduce fdb test time for large topos

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [x] 202311
- [x] 202405

#### What is the motivation for this PR?
Standalone topos with many interfaces, such as
64 or more, may result in individual test runs
from test_dfb.py that are longer in duration
than comparatively smaller topos by orders of
magnitude, making the tests in test_fdb.py
impractical to run in such cases.

#### How did you do it?
This patch reduces the mac count for larger 
standalone topos from 10 to 2, similar to what
has been done in the past for other topos that
otherwise do not scale well for this test.

#### How did you verify/test it?
Ran snmp_lopoback test on t0-standalone-64 topo and observed that the run time of the tests was well under 2 hours.

#### Any platform specific information?
Verified on Arista-7060X6-64DE-128x400G.

### CODE REVIEW

**Comment by ccroy-arista** [comment]
@r12f FYI.

**Review by r12f — APPROVED** [review]
lgtm!

**Comment by ccroy-arista** [comment]
@r12f it looks like merging it still blocked even though you approved. Do we need approval from someone with elevated privileges?

**Comment by ccroy-arista** [comment]
> @r12f it looks like merging it still blocked even though you approved. Do we need approval from someone with elevated privileges?

bump

**Review by r12f — APPROVED** [review]
lgtm!

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
LGTM

**Comment by ccroy-arista** [comment]
Removed request to backport to 202311 per: https://github.com/aristanetworks/sonic-qual.msft/issues/201#issuecomment-2375240395

Can also remove the [Request for 202311 branch](https://github.com/sonic-net/sonic-mgmt/labels/Request%20for%20202311%20branch) tag from this PR now.

**Pull request merged**
