### PR TITLE
Fix testQosSaiDwrr issue

### PR DESCRIPTION
**Pull request by JibinBao**
### Description of PR

Fix issue:https://github.com/sonic-net/sonic-mgmt/issues/11156
1. When sending a burst packet, sometimes packets will lost on the server side, which will cause a test fail, so change the port speed to decrease the burst rate
2. When the previous test case just sends a large of packets only by one queue such as queue1, then Dwrr test might fail, because queue1 has got much chance to send packets before, so it will get less chance to send packets than expected. Therefore add one first run as a dry run, and it will not check Dwrr function. After the dry run, all tested queues can be scheduled so that all queues are at the same start.

Summary:
Fixes # (issue)https://github.com/sonic-net/sonic-mgmt/issues/11156

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [ ] 202305

#### What is the motivation for this PR?
Fix testQosSaiDwrr issue: https://github.com/sonic-net/sonic-mgmt/issues/11156

#### How did you do it?
1. Add one parameter port_target_speed. when port_target_speed is set, change the port speed to the specified one.
2. Dry run before real test

#### How did you verify/test it?
Run testQosSaiDwrr

#### Any platform specific information?
Any

### CODE REVIEW

**Comment by JibinBao** [comment]
Hi @bingwang-ms,
Can you help review it? it is cherry-picked from https://github.com/sonic-net/sonic-mgmt/pull/11154

**Comment by liat-grozovik** [comment]
@stephenxs @bingwang-ms please help to review
@JibinBao please handle conflicts.

**Review by bingwang-ms — DISMISSED** [review]

**Review by stephenxs — APPROVED** [review]
LGTM.

**Comment by liat-grozovik** [comment]
@yxieca please help to merge

**Pull request merged**
