### PR TITLE
Enhance advance reboot test 

### PR DESCRIPTION
**Pull request by nhe-NV**
### Description of PR

Summary: 
Add more debug information to the advance reboot
    
    1. Add more debug information
    2. When get the dut time has exception, need to not break the get teamd state function
    3. When get the finalizer_state, if the state is set to empty should not return.

Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [x] 202405

#### What is the motivation for this PR?
Add one debug information
and fix an issue for finalizer_state
#### How did you verify/test it?
Run the warm reboot and fast reboot and upgrade test, it works fine

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca  @vaibhavhd   this is a kind reminder for the review. no point to handle conflicts till you review as it will pop up again.

**Comment by bingwang-ms** [comment]
@saiarcot895 , @Ryangwaite Can you help review?

**Review by bingwang-ms — APPROVED** [review]

**Comment by nhe-NV** [comment]
Here is the PR for 202405: https://github.com/sonic-net/sonic-mgmt/pull/16160

**Pull request merged**
