### PR TITLE
Fix route/test_forced_mgmt_route.py

### PR DESCRIPTION
**Pull request by vkjammala-arista**
### Description of PR

Summary: Fix route/test_forced_mgmt_route.py failures during teardown
Fixes # [aristanetworks/sonic-qual.msft#113](https://github.com/aristanetworks/sonic-qual.msft/issues/113)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012
- [ ] 202205
- [x] 202305
- [x] 202311

#### What is the motivation for this PR?
Test is tampering the running config of the duthost and leaving the config in this state. This is causing failures during teardown `core_dump_and_config_check` is failing during `config_db_check`. 

Also seeing loganalyzer failures with symptom similar to ` ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:449 Invalid sai_api_t 50 passed to sai_api_query ...` (mostly due to config changes)

#### How did you do it?
Perform "config_reload" with the backup config as part of fixture teardown (`backup_restore_config`).

#### How did you verify/test it?
Test is passing consistently with the fix (verified on Arista-7260CX3-C64), verified on 202305 and 202311 branches.

### CODE REVIEW

**Comment by wsycqyz** [comment]
The pre-commit check is mandatory. Please check.

**Comment by vkjammala-arista** [comment]
> The pre-commit check is mandatory. Please check.

Somehow missed this. Updated the diff, Thanks!

**Review by wsycqyz — APPROVED** [review]
LGTM

**Comment by wsycqyz** [comment]
Do you need backport to 202305 and 202311 branch?

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by StormLiangMS** [comment]
hi @yxieca for 202311 cherry pick.

**Pull request merged**
